### ISSUE TITLE
Support for non-gradient <def>s and references

### ISSUE THREAD

**Issue by dnfield** [dnfield/flutter_svg#10]

**Comment by gmlewis** [comment]
In https://github.com/dnfield/flutter_svg/pull/41#issuecomment-410750274 you suggested that we discuss supporting `<defs>` and `<use...>` in a separate issue and this seemed like a good location.

I agree that the `XmlElement`s should not be held onto any longer than necessary.

But if I understand the SVG spec correctly, an element defined within a `<defs>` block can be referred to any time later within a `<use...>` block... note that this is all happening during XML parsing.

The `<use...>` takes on all the styling of its current parent, which was not in scope during the time of the `<defs>` and acts as if the original XML element was copy/pasted within the scope of the `<use...>`. Here is a simple example for discussion: https://github.com/gmlewis/flutter_svg/commit/531ed5a03df3aea73446ad05f40f8d8b48a1158a#diff-55d723a79da3c9e707509cc3329983ea

Therefore, I think it is a requirement that we retain the original XML element defined within `<defs>` for the duration of *parsing* after which references to all XML elements can be safely discarded.

I believe my second solution does just this:
https://github.com/gmlewis/flutter_svg/commit/2c51d0afe1c05b35796f2223a1403aec9ff5c011
but we can discuss it here before I put together a PR to this repo.

**Comment by dnfield** [comment]
Ok.  My basic opposition here is not to holding the data the `XmlElement` contains, so much as to holding the `XmlElement` itself (which will also contain references that will require holding the entirely Xml document tree in memory, e.g. it's `parent`, it's `children`, etc.).

Instead, the stored element should be further parsed into a class (probably a `DrawableShape`), and hold a stored reference to the `DrawableShape`.

So instead of seeing the `defs` child and just storing the `XmlElement`, we should try to parse that out into some other object (which should be some subclass of `Drawable`, even if not a `DrawableShape`). Does that make more sense?

**Comment by gmlewis** [comment]
Just so I understand correctly... aren't there intrinsically two distinct phases for this plugin... parsing and later rendering?

Isn't the parsing done just once and you end up with a tree of `DrawableShape` and all `XmlElements` are freed from memory and all that is left is the `Drawable` tree?

In other words, during parsing, your XML tree is already in memory, isn't it?  So holding on to an `XmlElement` during parsing isn't taking up any more memory than is already being used, right? We just have a reference to the existing `XmlElement` until parsing is done.

Or am I missing something?

**Comment by dnfield** [comment]
That's the basic idea.  Your proposal was pulling XML into the rendering phase though.  The definitions are retained for that portion.

**Comment by dnfield** [comment]
I've implemented quite a bit of this on the shape_ref branch, which, after I have a little more time to think on it, I'll merge in to master (and probably include in the eventual 0.7.0 release once I'm settled on the new width/height handling).

It has some limitations that I know of right now:

- Not supporting `viewBox` on a `<use>` element.
- Not following the spec exactly in that I'm not creating a new `DrawableRoot` for certain cases (somewhat related to the viewBox part).

I also haven't exhaustively tested the style things - but I think for a lot of simple/normal cases it should work.

**Comment by dnfield** [comment]
This is at least initially supported as of v0.7.0. Will open additional issues if/as necessary.
