### ISSUE TITLE
SVG theme

### ISSUE THREAD

**Issue by bensonarafat** [dnfield/flutter_svg#1009]
How can i apply dark and light mode theme to SVGPicture.asset

**Comment by 3kdeveloper** [comment]
Create a global widget for Svg Icon and controller the theme inside this one widget.
CODE: 
SvgPicture.asset('svg path',
                        colorFilter: const ColorFilter.mode(
                        isdark?Colors.black:   Colors.white, BlendMode.srcIn)),

**Comment by bensonarafat** [comment]
yeah, i finally did it. 
thanks
