### ISSUE TITLE
When I color the svg, its width becomes smaller?

### ISSUE THREAD

**Issue by mrasityilmaz** [dnfield/flutter_svg#1010]
<img width="82" alt="Ekran Resmi 2023-11-13 13 09 26" src="https://github.com/dnfield/flutter_svg/assets/81583706/ba461edb-b133-46c2-a590-b43c7b718727"> Normal 

<img width="90" alt="Ekran Resmi 2023-11-13 13 09 10" src="https://github.com/dnfield/flutter_svg/assets/81583706/575c50b2-3008-49ec-b059-dadef7d798ca"> Colorized 

**Did you see right side of icon ?**

**Comment by duykhanhhs1** [comment]
Same issue, flutter 3.13.8

**Comment by Minhalattek** [comment]
Facing same issue

**Comment by chinghoi** [comment]
Same issue, Flutter channel stable: 3.16.0, Strangely enough, merely iPhone 12 had problem.

<img width="132" alt="image" src="https://github.com/dnfield/flutter_svg/assets/20352401/d8d2b0d6-3996-431d-a8d5-804df3cb5662">
<img width="126" alt="image" src="https://github.com/dnfield/flutter_svg/assets/20352401/ae4ad82a-1e12-46d4-9d81-5bff74df978a">

**Comment by dnfield** [comment]
See https://github.com/dnfield/flutter_svg/issues/985 - I don't have a good way to reproduce this, and it's not clear to me whether this is fixed on master. I think it's an Impeller issue if it is one.
