### ISSUE TITLE
SVG <foreignObject></foreignObject> support

### ISSUE THREAD

**Issue by samorian** [dnfield/flutter_svg#1020]
Used `<foreignObject></foreignObject>` elements are not displayed by Flutter SVG. The elements are visualized correctly within the browser.

The following code was used in the SVG:

```
<foreignObject x="232" y="276.969" width="300" height="100" >
        <div xmlns="http://www.w3.org/1999/xhtml" style="font-size: 16px; font-weight: 500; letter-spacing: 0px; text-align: left">
            Hello World
        </div>
</foreignObject>
```
The string "Hello World" is not displayed within the app.

Is this an incorrect use or are foreignObject elements not supported?

**Comment by dnfield** [comment]
This will never be supported in this package. It would require implementing a full HTML renderer.
