### ISSUE TITLE
Always Crash when show many SvgPicture.asset

### ISSUE THREAD

**Issue by HuyNguyen1590** [dnfield/flutter_svg#1022]
I made an app that use a lot of SvgPicture.asset to make a Card Maker Template. They always crash when svg.cache.cacheCount = 10.

Flutter version 3.7.10
flutter_svg: ^2.0.5

Log:
I/libc    (26246): Requested dump for pid 26246 (ugioh.cardmaker)
F/crash_dump64(30859): crash_dump.cpp:515] failed to attach to thread 653: Permission denied

Screenshoot:
I cannot capture the screenshot because my phone show the "Not response" system dialog.

Device:
Xiaomi redmi Note 11S
MiUI14
Android 13
And some samsung phones

**Comment by dnfield** [comment]
There should be a tombstone. Without that I'm not sure how much help I can be. 

Also you should try a more recent version of flutter

**Comment by HuyNguyen1590** [comment]
I just want to ask some question here:
- How many SvgPicture.asset this package can show in a single screen
- Does it depend on how complex the SVG is
- May it crash if i show 10, 20 or 50 SVG picture in a list

**Comment by dnfield** [comment]
It should not crash unless you're running out of memory, but it shouldn't run out of memory easily unless you have lots of raster images in your svgs.

**Comment by HuyNguyen1590** [comment]
Thanks for your answer. I will close this issue!
