### ISSUE TITLE
How to have SvgPicture with a full screen width and scrollable height

### ISSUE THREAD

**Issue by Abu-Abdullah** [dnfield/flutter_svg#1027]
Hi,

I'm trying to have SvgPicture to take the full width of the screen without any height overflow i.e. scrollable height. while it is working for a simple png image, it is not with svg. i tried many things without success. any hint is appreciated

```
Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: SvgPicture.asset(
        width: double.infinity,
        fit: BoxFit.cover,
        'assets/3.svg',
      ),
    );
  }
```
it is throwing:
```
BoxConstraints forces an infinite height.
```
the file can be downloaded from:
https://maknoon.com/quran/hafs/3.svg

**Comment by dnfield** [comment]
There are a bunch of ways to do this - use a media query, use a layout builder, use intrinsics. It depends.

A SingleChildScrollView doesn't have a "scrollable height" notion - I suspect what you want here is a width that's the width of the available screen from the media query?

**Comment by Abu-Abdullah** [comment]
thanks for quick reply

> A SingleChildScrollView doesn't have a "scrollable height" notion - I suspect what you want here is a width that's the width of the available screen from the media query?

yes, i can get the width to cover the view area with 'width: double.infinity' but in this case we will have an overflow in the height and I'm not able to make it scroll down. the svg in the example has a height greater than screen height so it needs to be scrollable. I'm facing issue here.

**Comment by Abu-Abdullah** [comment]
one way of doing it if we know the height/width of the svg viewBox. for the same file '3.svg' the viewBox="0 0 293.23 484.99"

the below code will work but again i do not know the h/w for the files that the app will use. it needs manual fetch. not sure if there is easy way to fetch this info.

this code is workable:
```
Widget build(BuildContext context) {
    double factor = MediaQuery.of(context).size.width / 293.23;
    return SingleChildScrollView(
      child: SvgPicture.asset(
        width: 293.23 * factor,
        height: 484.99 * factor,
        'assets/3.svg',
      ),
    );
  }
```

**Comment by Abu-Abdullah** [comment]
it seems specifying the width only was enough to get the required behavior.
```
Widget build(BuildContext context) {
    double w = MediaQuery.of(context).size.width;
    return SingleChildScrollView(
      child: SvgPicture.asset(
        width: w,
        'assets/3.svg',
      ),
    );
  }
```
thank you
