### ISSUE TITLE
Hit test of a coordinate inside SVG-file?

### ISSUE THREAD

**Issue by large** [dnfield/flutter_svg#1028]
Thank you for this great implementation of SVG in flutter!
I have tested the widget using this SVG, a map over Europe: https://upload.wikimedia.org/wikipedia/commons/6/66/Blank_map_of_Europe_cropped.svg

I figured out that using the "Colormapper" I could set the color to each "path" of the SVG and it works pretty well!

But are there any functions to make a "hit test" of an coordinate path?
Like this example here: http://dahlström.net/svg/interactivity/intersection/sandbox_hover.svg
(Example from this question: https://stackoverflow.com/questions/2174640/hit-testing-svg-shapes )

My goal is to click on a country in the SVG-file and highlight it with color.

Edit:
I found this great article that shows a technique to get this done right: https://medium.com/@alvaro.armijoss/implementing-interactive-svgs-in-flutter-a-comprehensive-guide-835863f42886

Since the flutter_svg package already have the paths available, is it possible to extract directly? (Without using the xml parser...)

**Comment by dnfield** [comment]
No - hit testing with paths gets pretty expensive, and the package intentionally doesn't expose a lot of these details to avoid leaking out optimizations it may do to users.

You could use vector_graphics_compiler directly for this, or path_parser
