### ISSUE TITLE
svgz support

### ISSUE THREAD

**Issue by Abu-Abdullah** [dnfield/flutter_svg#1030]
Hi,

This ticket is to raise a request to support svgz.

in addition, I would appreciate any hint to provide any workaround to support svgz manually now.

**Comment by dnfield** [comment]
Isn't that just gzipped SVG?

You shoul dbe able to run the data through The gzip codec first and then use it as normal.

**Comment by Abu-Abdullah** [comment]
yes, but it is more handy to have it out of the box, just want to raise this point here
thanks
