### ISSUE TITLE
Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [dnfield/flutter_svg#1037]
The short version:
- Migrate usage of dart:html to package:web
- Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

**Comment by dnfield** [comment]
Yes, thanks

**Comment by dnfield** [comment]
(the real solution for web here should still be to let the browser do it, but that patch hasn't made it in here and there are other good reasons to just use package:http at this point)
