### ISSUE TITLE
Plugin not displaying this SVG (No errors)

### ISSUE THREAD

**Issue by yekta** [dnfield/flutter_svg#104]
I couldn't get the following svg to display, and I didn't get any errors either: https://banano.fun/svg/bboss.svg

Can you help me to understand if I'm using something that is not supported?

**Comment by dnfield** [comment]
I'm curious about why you're not seeing errors as well - testing this locally results in errors for me on the console.

**Comment by yekta** [comment]
Thanks for the fast response, I have no idea why it's not showing up error 😅 A fix would be really helpful btw, because this is a very common illustrator export. Also, we're dynamically producing trillions of these monkeys basically, so we can't really change them 1 by 1.

**Comment by yekta** [comment]
Thanks a lot again, we'll be heavily relying on your plugin in our app so a fix would be very much appreciated. Currently we are using 4 different size of pngs but we would love to use svgs and make that just a single file.

**Comment by dnfield** [comment]
33c8e39  fixes this - not entirely sure yet if this is the right way to do it, but should get you by.

Ideally this should support the numeric postfixes better...

**Comment by yekta** [comment]
Thanks a lot, I’ll test it

**Comment by yekta** [comment]
Thanks a lot, I’ll test it in an hour or so and report back

**Comment by yekta** [comment]
Updated to flutter_svg: ^0.10.2 and tried again, it is still not displaying. I tried the same svg but exported from Sketch instead of Illustrator, that one worked (but that's 143 kb, while this one is 85). I also tried to compressed the Sketch export with https://vecta.io/nano, that did not work either.

These are the export options I picked for Illustrator:
<img width="300" alt="screenshot 2019-01-21 15 47 01" src="https://user-images.githubusercontent.com/40706601/51475574-d1470000-1d93-11e9-9406-5e848948cb59.png">

**Comment by dnfield** [comment]
You'd have to pull directly from master.

Maybe try usvg?

**Comment by yekta** [comment]
Yea it's forget, I edited the message later 😅 We are now uploading the to the server that generates them, and try it on the app. But as far as plugin is concerned, there is no problem now, it's fixed.

Thanks a lot again, keep up the good work!
