### ISSUE TITLE
SVG rendering issues after flutter upgrade from 3.7

### ISSUE THREAD

**Issue by ristiisa** [dnfield/flutter_svg#1056]
After updating flutter from 3.7 to 3.19 stroke seems to be behaving in an weird way:
before:
<img width="124" alt="image" src="https://github.com/dnfield/flutter_svg/assets/514571/48a7b6f8-bbc1-4861-b70e-e5a5b1adf1db">
after:
<img width="139" alt="image" src="https://github.com/dnfield/flutter_svg/assets/514571/5a1d6f81-119f-46ba-909a-893f55706c9e">

original svg:
![image](https://github.com/dnfield/flutter_svg/assets/514571/05bc418f-1770-4b54-b3fd-3d14e3697f85)

flutter_svg: 2.0.10+1

**Comment by GIfatahTH** [comment]
Is this packages still maintained.

**Comment by jonahwilliams** [comment]
Hi, Flutter team member here. If you're hitting Impeller specific rendering bugs you need to file them on the main flutter repo. We do not triage this repo, so these will be missed.

**Comment by ristiisa** [comment]
> Hi, Flutter team member here. If you're hitting Impeller specific rendering bugs you need to file them on the main flutter repo. We do not triage this repo, so these will be missed.

Oh did not realize it was a flutter issue...

**Comment by ristiisa** [comment]
https://github.com/flutter/flutter/issues/147139

**Comment by nateshmbhat** [comment]
Since they fixed this issue in flutter , we can close this issue
