### ISSUE TITLE
Grid problems in gradients

### ISSUE THREAD

**Issue by AlexisArcs** [dnfield/flutter_svg#1063]
Hi, I'm experiencing artifacts on iOS when using gradients. When using a viewbox different from the final image size (e.g. a viewbox at 0, 0, 2048, 2048 and an image rendered at 350x350) a "grid" appears in the gradients.

### Viewbox of 2048

![Simulator Screenshot - iPhone 15 Pro - 2024-05-17 at 13 15 03](https://github.com/dnfield/flutter_svg/assets/165772004/4aaa8942-ce8e-482e-ae95-cf22fac2056b)

### Viewbox of 350 (equals to the render size)

![Simulator Screenshot - iPhone 15 Pro - 2024-05-17 at 13 16 09](https://github.com/dnfield/flutter_svg/assets/165772004/bef63da6-f5d8-4ece-b80a-a230a63a7258)

#### Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.3 23D56 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.0)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!
```

#### flutter_svg
Version : 2.0.10+1

**Comment by jonahwilliams** [comment]
You need to file rendering bugs on the Flutter repo and not here. This is likely the same as https://github.com/flutter/flutter/issues/145481
