### ISSUE TITLE
[PERFORMANCE] ColorFilter introduces jank

### ISSUE THREAD

**Issue by tofylion** [dnfield/flutter_svg#1071]
When working with SVGs, even pre-compiled ones, ColorFilter introduces a lot of jank. Especially when used multiple times in a list. 

Here's how my color filter is configured:
```dart
colorFilter: ColorFilter.mode(
              !widget.bookmarked ? _secondaryColor : _primaryColor,
              BlendMode.srcIn),
```

This is especially a problem when needing to switch between light/dark modes, etc...

**Comment by jonahwilliams** [comment]
If you use a filter you have to pay the cost. The flutter repo has an issue template for perfomance problems. If you fill it out and include an example application, we could benchmark and determine if there is anything that can be done.
 
 This isn't directly related to flutter_svg
