### ISSUE TITLE
SVG not showing at all

### ISSUE THREAD

**Issue by fisforfaheem** [dnfield/flutter_svg#1072]
Getting Following Error:

`E/flutter (31233): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/images/img_mailicon_2.svg".
E/flutter (31233): #1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)
E/flutter (31233): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/images/img_mailicon_2.svg".
E/flutter (31233): #1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)
E/flutter (31233): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/images/img_mailicon_2.svg".
E/flutter (31233): #1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)
E/flutter (31233): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/images/img_lockicon_1.svg".
E/flutter (31233): #1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)
E/flutter (31233): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/images/img_lockicon_1.svg".
E/flutter (31233): #1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)
E/flutter (31233): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/images/img_lockicon_1.svg".
E/flutter (31233): #1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)`

**Comment by fisforfaheem** [comment]
I am using like this...:
///main code:

` switch (widget.imagePath!.imageType) {
        case ImageType.svg:
          return SizedBox(
            height: widget.height,
            width: widget.width,
            child: SvgPicture.asset(
              widget.imagePath!,
              height: widget.height,
              width: widget.width,
              fit: widget.fit ?? BoxFit.contain,
              color: Colors.red,
            ),
          );`


`CustomImageView(
                                  imagePath: ImageConstant.loginPpageLogo,
                                  fit: BoxFit.contain,
                                  height: 60.v,
                                  // width: 360.h,
                                )`

**Comment by jonahwilliams** [comment]
The exception you're getting indicates your asset path is malformed. That doesn't have anything to do with flutter_svg specifically, I would recommending looking for a help forum for assistance on fixing that.
