### ISSUE TITLE
Would it improve performance if `ByteLoaders` could reuse a pool of Isolates instead of creating a new one every time with `compute`?

### ISSUE THREAD

**Issue by escamoteur** [dnfield/flutter_svg#1081]

**Comment by jonahwilliams** [comment]
in AOT builds with lightweight isolates, launching an isolate is nearly free. Keeping around an isolate means that we can use the isolate.exit trick to send the data back with no copy.

**Comment by escamoteur** [comment]
You mean if you don't keep the isolate around? So you can call Isolate.exit?
Am 17. Juni 2024, 19:31 +0100 schrieb Jonah Williams ***@***.***>:

**Comment by jonahwilliams** [comment]
oops yeah, we *Can't* use isolate exit. meaning we'd need to copy for every decode.
