### ISSUE TITLE
Error found in FirebaseCrashlytics

### ISSUE THREAD

**Issue by suhailpatel49** [dnfield/flutter_svg#1085]
I am facing this similar issue [660](https://github.com/dnfield/flutter_svg/issues/660). We are using a third party api and displaying svgs from there so there is no way for us to fix the svgs. Is there any way we can catch the exceptions from the library itself or tell the library to ignore the errors?

**Comment by jonahwilliams** [comment]
I think the underlying problem with out of order defs has been fixed, but the errorBuilder property should be sufficient to catch exceptions.
