### ISSUE TITLE
Certain SVGs cause iOS crash since flutter 3.22

### ISSUE THREAD

**Issue by davestimpert** [dnfield/flutter_svg#1090]
We noticed a few of our SVGs started causing a app crash (iOS-only, not android or web) with a small percentage of our svg files.

Here's an example:
![sleep](https://github.com/user-attachments/assets/6fb29ba4-7b14-46b6-ac99-fa80dc251535)

**Comment by zanderso** [comment]
@davestimpert Would you mind filing this in the Flutter issue tracker? https://github.com/flutter/flutter/issues

**Comment by jonahwilliams** [comment]
This is fixed in the 3.22 hotfixes and the 3.24 stable
