### ISSUE TITLE
The method 'getBounds' isn't defined for the class 'Path'.

### ISSUE THREAD

**Issue by robinthomas** [dnfield/flutter_svg#11]
The method 'getBounds' isn't defined for the class 'Path'.

file "\flutter_svg\src\svg_parser.dart"
Line 55, 56
final stroke = parseStroke(el, path.getBounds(), paintServers);
final fill = parseFill(el, path.getBounds(), paintServers);

file "\flutter_svg\src\vector_painter.dart"
Line 174 
Rect get bounds => path?.getBounds();

**Comment by dnfield** [comment]
One other possibility I've run into - make sure you don't have anything checked out/locked up in your FLUTTER_ROOT directory that would be preventing Git from getting all the relevant updates.

**Comment by robinthomas** [comment]
Yes i'm using Flutter 0.3.2

Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (3 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
