### ISSUE TITLE
Andorid Impeller, SVGs completely freeze the app

### ISSUE THREAD

**Issue by PetrKubes97** [dnfield/flutter_svg#1103]
Hi, when I have impeller enabled, some android devices completely free when using this SVG library.

The following error is in logs:
```
E/flutter (25434): [ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not wait for fence.
E/flutter (25434): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(66)] No surface available.
```
I've tested it with Flutter versions 3.24.1 - 3.24.3 (happens in all) and Google Pixel 8 and OnePlus 7 Pro, only happening on the OnePlus phone.

**Comment by jonahwilliams** [comment]
You have to file bugs on flutter/flutter along with complete details (flutter doctor, example svg, phone et cetera). This is a rendering bug in flutter and not related to this library.
