### ISSUE TITLE
Crashed on iOS

### ISSUE THREAD

**Issue by ProFive** [dnfield/flutter_svg#1107]
![thumb_up](https://github.com/user-attachments/assets/3de9f53a-9029-4f95-98ea-1dd1ea34200f)
The app crashed  when loading this svg 

`
return Container(
      padding: EdgeInsets.symmetric(vertical: 40),
      child: SvgPicture.asset(
        "Assets/icons/thumb_up.svg"
         width: 100,
        height: 120,
      ),
    );
`
Using the version 2.0.10+1 and fluter SDK. 3.22.3

**Comment by congwa** [comment]
https://github.com/dnfield/flutter_svg/issues/1106#issuecomment-2446323899

**Comment by jonahwilliams** [comment]
You need to file a bug on the main flutter issue tracker, along with your version of flutter and examples to reproduce the problem. As noted in the README, this library has been moved to flutter/packages and this issue tracker isn't maintained.
