### ISSUE TITLE
iOS consistently slow/choppy compared to Android

### ISSUE THREAD

**Issue by corepuncher** [dnfield/flutter_svg#1109]
I use flutter map and plot svg image assets as markers. Typically 50-100 on screen at once. 

Each marker is a very small SVG. Like a circle plus a rotated line.

In Android, the map pans smoothly. 

In iOS, even on a new iPhone, it's jittery/choppy. The choppiness is directly proportional to the number of markers visible.  

Is this normal? What can be done? I've optimized all these icons, the marker widgets are cached. These are like 500 to 2000 byte svgs. Is iOS just bad at rendering? My Android device is older too.

**Comment by Kam5678** [comment]
I am encountering this issue as well. Simply just having a Column widget wrapped with SingleChildScrollView, that simply has a list of buttons, each with a SvgPicture.asset.

On Android seems to run fine, no jittering when scrolling, but on IOS its very choppy!

It also depends on the svg asset I use. A less complicated SVG (less paths) it runs fine on IOS. But once I start using SVGs with more paths that are more complicated, I keep running into this issue.

**Comment by jonahwilliams** [comment]
You need to file a bug on the main flutter issue tracker, along with your version of flutter and examples to reproduce the problem. As noted in the README, this library has been moved to flutter/packages and this issue tracker isn't maintained.
