### ISSUE TITLE
unable to load svg resource

### ISSUE THREAD

**Issue by mojtabaparvar** [dnfield/flutter_svg#116]
I am using the flutter_svg (version 0.10.3)package to load svg in my app. but it shows me an error saying that it is unable to load the resource.(I am following this tutorial: https://medium.com/flutter-community/bmi-calculator-in-flutter-part-1-gender-b75f263bdff1 .  here is my code

```
static final Map<Gender, String> _genderImage = {
Gender.female: 'assets/images/gender_female.svg',
Gender.other: 'assets/images/gender_other.svg',
Gender.male: 'assets/images/gender_male.svg'
};
Widget icon = Padding(
    padding: EdgeInsets.only(left: _leftPadding(context)),
    child: SvgPicture.asset(
      _assetName,
      height: _iconSize(context),
      width: _iconSize(context),
    ));
```
this is the error: `Another exception was thrown: Unable to load asset: assets/images/gender_male.svg`

**Comment by berosoboy** [comment]
Did you registered your assets?
This guide can help
https://flutter.io/docs/development/ui/assets-and-images

**Comment by dnfield** [comment]
Can you share your pubspec.yaml?

**Comment by dnfield** [comment]
Without any more information I'm not sure what else can be done here - this doesn't seem like a bug in the library unfortunately.

**Comment by jarrrgh** [comment]
I just ran into this issue. For me, having the svg files in a subfolder did not work with the following in pubspec.yaml:

assets:
  - assets/
  - assets/images/

Instead, not sure why, I had to either move the files up one level to assets folder, or list them separately like this:

assets:
  - assets/
  - assets/images/file1.svg
  - assets/images/file2.svg

**Comment by atilkan** [comment]
I also experience this issue. It was working when i first put them. Now i get black screen and error saying 
"Unable to load asset: assets/icons/brands/windows.svg"

**Comment by jogendra-zokudo** [comment]
I'm also facing the same Problem . unable to see some SVG part in flutter 
[top left logo missing while rendering on flutter app]
SVG File Attached
![zokudo_card_front_gc](https://github.com/dnfield/flutter_svg/assets/139207864/42b3f2fa-7781-4930-a7d8-f5cd551e6a73)
