### ISSUE TITLE
SvgPicture.asset should consider the DefaultAssetBundle

### ISSUE THREAD

**Issue by dballesteros7** [dnfield/flutter_svg#117]
For developer ergonomics, similarly to how it is passed for [Image.asset](https://docs.flutter.io/flutter/widgets/Image/Image.asset.html)

Right it now if no bundle is passed, it defaults to the rootBundle instead.

Happy to contribute a PR if this sounds like a reasonable change.

**Comment by dnfield** [comment]
Sure, a PR would be great!
