### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by gedw99** [dnfield/flutter_svg#12]
This is really great work. I just want to say it.

Looking forward to trying out and seeing the interesting possibilities and use cases this offers. I think there are many !

**Comment by gedw99** [comment]
Actually Lottie and this have a relationship maybe ?
Lottie is animation and svg is static. But there is potential overlap.

The reason at a high level I ask is because all of this provides a entry point for designers ( as opposed todevelopers ) to be involved in the application development process.
If you have time I would love to hear your thoughts ....

**Comment by dnfield** [comment]
Thanks for the feedback.  I'm also working on Lottie over at https://github.com/dnfield/lottie-flutter
