### ISSUE TITLE
svg not rendering correctly

### ISSUE THREAD

**Issue by szotp** [dnfield/flutter_svg#122]
![screenshot 2019-02-25 at 09 02 50](https://user-images.githubusercontent.com/19707261/53326517-15bf4180-38e6-11e9-829f-42c8a37b2547.png)

[example.svg.zip](https://github.com/dnfield/flutter_svg/files/2899404/example.svg.zip)

It looks like pen is not centered in the circle. Checked problem with current master.

**Comment by szotp** [comment]
![screenshot 2019-02-25 at 09 02 50](https://user-images.githubusercontent.com/19707261/53326517-15bf4180-38e6-11e9-829f-42c8a37b2547.png)

I managed to fix this by changing translate(4.338) into translate(4.338 0)

**Comment by dnfield** [comment]
This is a bug in the parsing.  I have it set up right now to assume `x` should be repated if `y` is not specified, which is not accurate for this case - `y` defaults to 0.

**Comment by dnfield** [comment]
This should be fixed on master, will be released as v0.10.4 once CI passes.  Thanks for the clear reproduction!

**Comment by dnfield** [comment]
This should be fixed now, please feel free to re-open if it's not working for you.
