### ISSUE TITLE
There are black background on svg in 0.10.3(0.10.4 version)

### ISSUE THREAD

**Issue by wonderful89** [dnfield/flutter_svg#126]
![image](https://user-images.githubusercontent.com/44089389/53471752-a93c7200-3aa0-11e9-8369-1554faffbe7b.png)

There are black background on svg in 0.10.3 flutter_svg version . But it is OK in 0.8.3 flutter_svg version.

➜  examples git:(master) ✗ flutter --version
Flutter 1.0.0 • channel unknown • unknown source
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

 [reproduct project:](https://github.com/qqzhao/flutterDemos/tree/master/examples/svg_check )

It should be flutter_svg issue. Did Someone have the problem ?

**Comment by dnfield** [comment]
Can you try on 0.10.4?  I just tried it on that and it seems to work ok.

**Comment by wonderful89** [comment]
> Can you try on 0.10.4? I just tried it on that and it seems to work ok.

@dnfield , I try 0.10.4 version and it does not work , too. 

Only the two svgs resources don't work and others are OK. But I try the two svgs resources in 0.8.3  and they are OK.

![image](https://user-images.githubusercontent.com/44089389/53476238-d8f17700-3aac-11e9-9f49-18e6ce3996da.png)

We can solve it by replacing svg resouces, but it is good that flutter_svg plugin can support the feature.

**Comment by dnfield** [comment]
Hmm.  It appears to be because of the `<mask>` elements, which aren't supported.  I'm not entirely sure why that's happening but it is a bug.

For now if you can remove the mask element, you should be good.  I'll try to look at why this regressed this way.

**Comment by dnfield** [comment]
Ahhh - it's because of that `<use>` element in the mask.

So while parsing, if an unsupported element is encountered we try to be tolerant and parse children it has. We end up finding a `use` element and try to apply it to the parent group since we didn't know what to do with the mask.

**Comment by dnfield** [comment]
(and in v0.8.3, we didn't support use elements)

**Comment by dnfield** [comment]
This is fixed on master, and will be published as v0.11.0 once CI passes...

**Comment by wonderful89** [comment]
Thanks for your response. I will try it again when v0.11.0 is released.
