### ISSUE TITLE
[Suggestion] Add a precache function

### ISSUE THREAD

**Issue by Skyost** [dnfield/flutter_svg#128]
In my app, I need to quickly display SVG pictures. As I have a loading screen, it would be great to be able to load my pictures using a `precacheImage` function (a bit like [in flutter images](https://docs.flutter.io/flutter/widgets/precacheImage.html) function).

Something like :

```dart
precacheImage(SvgPicture.asset(
      'asset.svg'
      width: 512,
      fit: BoxFit.cover,
      semanticsLabel: 'My picture',
));
```

Which returns a `Future<void>` for when it's loaded.

**Comment by dnfield** [comment]
The problem is the return value of `SvgPicture.asset` is a Widget.  I think this would actually take the PictureProvider, which could make more sense.  Something like

```dart
precachePicture(ExactAssetPicture(
  svgStringDecoder,
  assetName,
   ...,
));
```

shouldn't be too hard to add though, and then if you used that asset it would be in the cache.

**Comment by Skyost** [comment]
Your pull request is exactly what I was searching for ! Do you have an estimated release date for this build ?

**Comment by graux** [comment]
Is there any example about how to use the precachePicture within a StatefulWidget?
I cannot load the Svg string within the initState as it cannot be async. Should I use didChangeDependencies? 
Some pointers about the steps to follow would be really helpful.
Thanks!
