### ISSUE TITLE
Framedrops/Performance problems using SvgPicture.file() in ListView

### ISSUE THREAD

**Issue by bbedward** [dnfield/flutter_svg#133]
Hi,

Now that we were able to get SVGs working in our app, we noticed some pretty significant frame drops/performance issues (Especially on lower end devices, e.g. iPhone 5s) when scrolling and entering a list.

This is basically what we're doing:

1) We have a list, for that list we fetch images (SVG or PNG) from a web service (which are unique to that persons address). We cache these images in device storage.

2) Use these images when showing a list of contacts

Here's ListView.builder code, using `SvgPicture.file`:

```
  Widget buildSingleContact(BuildContext context, Contact contact) {
    return FlatButton(
      highlightColor: StateContainer.of(context).curTheme.text15,
      splashColor: StateContainer.of(context).curTheme.text15,
      onPressed: () {
        ContactDetailsSheet(contact, documentsDirectory)
            .mainBottomSheet(context);
      },
      padding: EdgeInsets.all(0.0),
      child: Column(children: <Widget>[
        Divider(
          height: 2,
          color: StateContainer.of(context).curTheme.text15,
        ),
        // Main Container
        Container(
          padding: EdgeInsets.symmetric(vertical: 5.0),
          margin: new EdgeInsets.only(left: 20.0),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              //Container for monKey
              contact.monkeyPath != null && _contactsOpen
                  ? SvgPicture.file(
                    File("$documentsDirectory/${contact.monkeyPath}"),
                    width: smallScreen(context) ? 55 : 70,
                    height: smallScreen(context) ? 55 : 70,
                  )
                  : SizedBox(
                      width: smallScreen(context) ? 55 : 70,
                      height: smallScreen(context) ? 55 : 70),
              //Contact info
              Container(
                margin: EdgeInsets.only(left: 5),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    //Contact name
                    Text(contact.name,
                        style: AppStyles.textStyleSettingItemHeader(context)),
                    //Contact address
                    Text(
                      Address(contact.address).getShortString(),
                      style: AppStyles.textStyleTransactionAddress(context),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ]),
    );
  }
```

Here's ListView:

```
// Contacts list
ListView.builder(
  physics: const AlwaysScrollableScrollPhysics(),
  padding: EdgeInsets.only(top: 15.0),
  itemCount: _contacts.length,
  itemBuilder: (context, index) {
    // Some disaster recovery if monKey is in DB, but doesnt exist in filesystem
    if (_contacts[index].monkeyPath != null) {
      File("$documentsDirectory/${_contacts[index].monkeyPath}")
          .exists()
          .then((exists) {
        if (!exists) {
          dbHelper
              .setMonkeyForContact(_contacts[index], null);
        }
      });
    }
    // Build contact
    return buildSingleContact(context, _contacts[index]);
  },
),
```

We were previously doing the same thing with `Image.file` and PNGs and performance was not an issue in that case, it's just more convenient for us to use SVGs since we use the same images in different locations and of course it's ideal to not manage more than one size.

If you need any more info or any more context just let me know, the entire project is open source as well.

This is the service we get the SVGs from: https://monkeys.appditto.com/?address=ban_1dqzxzi5debtkke7kqhwxjggbc5fkfo4d96r7cpak8u9gt8995mo7hhecr7u

Thanks!

**Comment by dnfield** [comment]
Opening a file isn't free, and rendering the SVG isn't either.

Does it help at all if you use `precachePicture` to load the images you'll need earlier?

**Comment by bbedward** [comment]
Ok so I added a method to precache all of the images as:

```
  /// Precache SVG images for contacts
  Future<void> _precacheSvgs() async {
    List<Contact> contacts = await dbHelper.getContacts();
    String documentsDirectory = (await getApplicationDocumentsDirectory()).path;
    contacts.forEach((c) async {
      if (c.monkeyPath != null) {
        File svgFile = File("$documentsDirectory/${c.monkeyPath}");
        if (await svgFile.exists()) {
          precachePicture(FilePicture(
            svgByteDecoderOutsideViewBox,
            svgFile
          ), context);
        }
      }
    });
  }
```

This helps quite a bit with the initial frame drops when opening the actual list, but does not make any difference on the actual scrolling performance (still seeing quite a bit of frame drops/lag when scrolling the list - especially on android and lower end iPhones, compared to the PNGs which was fast/nearly 60fps across all devices we tested)

**Comment by dnfield** [comment]
Using the `outsideViewBox` variants is not recommended as it will potentially consume more resources than you really need to.

For complicated enough SVGs, it may make sense to parse them into rasterized images instead and cache those.  Something like

```
final String rawSvg = getNetworkSvg(url);
final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, url);
final ui.Image = await svgRoot.toPicture().toImage();
// store the image on the disk
```

I do know that when I test with more complicated SVGs (like the Ghostscript Tiger, which has lots and lots of paths and groups), or if you're using an SVG that doesn't have very performant features (like `<clipPath>` elements that are defined by multiple paths), it will be expensive to draw.

I'm not sure if that helps you or not - you may already have ways to rasterize this ahead of time.  If your SVGs aren't all that large or complicated that's also a problem, but based on your other post I think they might be.

**Comment by bbedward** [comment]
Thanks for the response,

They're pretty similarly complex to ghostscript tiger I think. 

We can get rasterized images from server as PNGs, it's just less than ideal since we need a large size, medium size, small size, etc. I think that's what we'll do at least for now though.

Thanks for the work you do on this, it's really awesome!

**Comment by dnfield** [comment]
One other thought is to use a Repaint boundary around the SVG and see if that helps.
