### ISSUE TITLE
<clipPath> with a `transform` won't work.

### ISSUE THREAD

**Issue by ragasubekti** [dnfield/flutter_svg#136]
So, i'm trying to render svg to screen using as usual `SvgPicture.asset()` but it doesn't show anything or even render.

There also no error thrown at the debug console, it just doesn't render

[An example of the svg](https://gist.github.com/ragasubekti/d3e03a76ae7f60bd8bee66430ce2fe7f)

I've also tried to use `usvg` but the result still same

**Comment by dnfield** [comment]
It's the clip path.  If you remove that it will work.

Unfortunately, I'm not properly supporting clipPaths with a transform on them right now.

**Comment by ragasubekti** [comment]
Thankyou, i was so confused
