### ISSUE TITLE
how to use canvas drawImage draw xml.

### ISSUE THREAD

**Issue by TOTOROYang** [dnfield/flutter_svg#137]
AvdPicture.asset("xxx.xml") is a widget.
drawImage need a ui.Image.
what can i do.

normal image can use 
 ByteData data = await rootBundle.load("xxx.png");
    Codec codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
    FrameInfo fi = await codec.getNextFrame();
    return fi.image;

**Comment by dnfield** [comment]
```dart
final String avdString = await rootBundle.loadString('xxx.xml');
final VectorDrawable avdDrawable = await avd.fromAvdString(avdString);
final ui.Picture avdPicture = avdDrawable.toPicture(...);
final ui.Image avdImage = avdPicture.toImage(...);
```

Just note that AVD support is fairly limited at this point.  Basic drawings should work but anything with references or gradients likely won't.
