### ISSUE TITLE
Support CustomPainter Generator

### ISSUE THREAD

**Issue by Sach97** [dnfield/flutter_svg#138]
Hi Dan, thank's for this great library. Would it be possible to support a CustomPainter Generator ? I tried to generate paths of my svg with your [dart_path_parsing](https://github.com/dnfield/dart_path_parsing) package and then do something like canvas.draw(...) in my paint method but it paints something different than the original svg. Could you please give me some tips ? Maybe should I use Drawable root ? And then use DrawableStyle, DrawablePaint and DrawableViewport on every children? Main purpose of a CustomPainter would be to animate the canvas (in my case every stroke by stroke).

**Comment by dnfield** [comment]
Can you share the code that isn't working?

**Comment by Sach97** [comment]
Yeah for sure. Here is the [code](https://github.com/Sach97/flutter_kanji_demo) with my Custom Painter and the generated paths. And here [path_parsing snippet](https://gist.github.com/Sach97/f5c2a6ac81c2d71b2509ebde223f749e) I used to generate the paths.

**Comment by Sach97** [comment]
My bad it worked with the parseSvgPathData method
