### ISSUE TITLE
[Query] Caching SVG 

### ISSUE THREAD

**Issue by abhinavc** [dnfield/flutter_svg#139]
Hi, 
This is more of a (novice) query than an actual issue. I am trying to animate an SVG. And I am wondering if `flutter_svg` will re-read the file (an IO operation) everytime the image needs to change. 

For example, in the (minimal) code below, let `paddle.svg` be a simple rectangle that shrinks/expands as per some animation code (not shown).So, if I am trying to animate `Paddle`, then would the SVG file `paddle.svg` be re-read again in every call to `build`? 

If yes, then isn't that (a) expensive and (b) is there a way to cache the SVG and re-render it with just some attributes changed (like width in this case)? 

```dart
class Paddle extends StatefulWidget {
   _PaddleState createState() => _PaddleState() ;
}

class _PaddleState extends State<Paddle> {
    double width ; 

    @Override
    Widget build(BuildContext ctx) {    
         return SvgPicture.asset("assets/paddle.svg", width: width) ;
    }
} 
```

**Comment by dnfield** [comment]
It should be cached. But in general for this, it's best to measure performance of your actual code and then tune, rather than trying to preoptimize.
