### ISSUE TITLE
`display="none"` is not supported.

### ISSUE THREAD

**Issue by farhanrahmadi** [dnfield/flutter_svg#140]
![Screenshot_1553999040](https://user-images.githubusercontent.com/37819341/55283921-c19cf680-5396-11e9-8e06-4b2439ea4055.png)

image render weird on my bottom bar 

here the code [https://gist.github.com/farhanrahmadi/97780b32719c3867d55d0783ba92e28e](buttonbarError)

**Comment by dnfield** [comment]
It's a iittle hard for me to tell what's going on here - can you make sure this doesn't happen when you use some other icon instead of SVG, and can you provide some example SVG assets that are failing to render correctly?

**Comment by farhanrahmadi** [comment]
@dnfield i use it before using image png it workfine but after i user svg it like that

**Comment by dnfield** [comment]
Can you provide a full reproducible example?  Preferably paired down to the minimum code to cause this issue.

**Comment by farhanrahmadi** [comment]
@dnfield [https://gist.github.com/farhanrahmadi/440aaf93d6089d15cd996bb3c1f4080a](hope this helpfull)

**Comment by dnfield** [comment]
That gist doesn't compile and doesn't include the assets...

**Comment by farhanrahmadi** [comment]
@dnfield here my repo for inspection [https://github.com/farhanrahmadi/cariin](url)

**Comment by dnfield** [comment]
I don't have support for the `display` attribute, but your SVG has them, for example https://github.com/farhanrahmadi/cariin/blob/master/assets/bottombar/booking-active.svg?short_path=d6190e2#L8

**Comment by dnfield** [comment]
This should be fixed on master - as long as CI passes I'll publish as 0.12.1

**Comment by dnfield** [comment]
(Just note that it would probably be best to remove those hidden nodes anyway - or have your designer do so).

**Comment by dnfield** [comment]
Fixed in version 0.12.1
