### ISSUE TITLE
SVG Network Error handling?

### ISSUE THREAD

**Issue by skybur** [dnfield/flutter_svg#144]
How do I handle error when loading SVG from network? Currently I only use `SvgPicture.network`, when there is no internet connection the widget throws exception and the image won't reload even if I use `setState()`.
Thanks in advance

**Comment by Qwin** [comment]
+1

**Comment by dnfield** [comment]
I suspect there's a bug where the cache is getting a bad entry if the network is down.  I don't suppose you have a test case for this? :)

**Comment by Qwin** [comment]
Well my main problem is that the error that gets thrown cannot be caught by a try / catch as it happens asynchronously. Is there a way to catch it and then retry manually ?

**Comment by dnfield** [comment]
So `SvgPicture.network` is really just a convenience wrapper. Error handling for it is kind of tough and could probably be improved, but I strongly suspect you'd have a better time just handling the network retrieval separately and using `SvgPicture.string` on the downloaded content.

**Comment by skybur** [comment]
I forgot I made this issue. Actually I already solved this by using `precachePicture`. There I caught the exception so the widget can automatically reload when changing page/rebuilding.

**Comment by Qwin** [comment]
@dnfield Thats my current workaround sadly, it would be great to see future updates where the error can be caught using a callback handler / delegate that you pass to the SvgPicture.

**Comment by Nolence** [comment]
Couldn't figure out that `precachePicture` thing. Just in case anyone gets stuck on this, here's the way I did it

```dart
FutureBuilder(
  future: http.get(iconUrl),
  builder: (context, snapshot) {
    if (snapshot.data == null)
      return CircularProgressIndicator();

    final response = snapshot.data as http.Response;

    if (![200, 201].contains(response.statusCode) ||
        snapshot.hasError) return Placeholder();

    final fileString = response.body;

    return SvgPicture.string(fileString);
  },
),
```
