### ISSUE TITLE
Text transform translate not working

### ISSUE THREAD

**Issue by dees91** [dnfield/flutter_svg#146]
After update from `0.9.0+1` to `0.12.1` text translate stopped working. 

Here is example svg which was displayed correctly in `0.9.0+1` and letter A is missing in `0.12.1`.

[ic_assist.svg.zip](https://github.com/dnfield/flutter_svg/files/3040746/ic_assist.svg.zip)

**Comment by dnfield** [comment]
Ugh.  I messed up transform inheritence in the parsing rewrite.  Sorry about that.  I'll add a test and fix it.

**Comment by dnfield** [comment]
This should be fixed on master now - I have to regenerate some goldens which I'll try to do tomorrow and then publish it.

**Comment by dees91** [comment]
Thanks for quick reply. Good job. Looking forward for new version :)
