### ISSUE TITLE
Opacity is inherited incorrectly for overlapping shapes

### ISSUE THREAD

**Issue by ened** [dnfield/flutter_svg#147]
The attached file should render with a semi-transparent background (it does so in Chrome and 
mac quicklook), but renders with black background in `flutter_svg` 0.12.2 [startrec.svg.zip](https://github.com/dnfield/flutter_svg/files/3043930/startrec.svg.zip).

**Comment by dnfield** [comment]
It's because of the duplicated `<ellipse>` tags - flutter_svg ends up drawing two ovals at half opacity and getting full opacity.

**Comment by ened** [comment]
When I quickly scanned the SVG, I only found one declaration of opacity "0.5", though. So if it's multiple ellipses, then perhaps one of them "inherits" the opacity accidentally?

**Comment by dnfield** [comment]
It's this part here:

```svg
    <g opacity=".5">
      <ellipse clip-rule="evenodd" cx="24.1" cy="24.1" fill-rule="evenodd" rx="22.7" ry="22.7"/>
      <ellipse cx="24.1" cy="24.1" rx="22.7" ry="22.7"/>
    </g>
```

Those two ellipses are identical (except for the clip/fill rules). I end up drawing the first one and then the second one,a nd the opacities get added.  I suspect that's a bug, but a work around is to remove one of the ellipses.

**Comment by dnfield** [comment]
Pretty sure this is a bug with how I'm handling opacity inheritance.

**Comment by dnfield** [comment]
Urgh.  This is not trivial for me to fix.  I believe the spec wants me to composite everything in the group and then apply opacity.  I, on the other hand, am trying to just cascade opacity down the tree and composite everything all at once.

**Comment by dnfield** [comment]
Relevant portion of the spec:

>  Object/group opacity can be thought of conceptually as a postprocessing operation. Conceptually, after the object/group is rendered into an RGBA offscreen image, the object/group opacity setting specifies how to blend the offscreen image into the current background.

Which is not quite how I'm doing it.

**Comment by dnfield** [comment]
I believe I can fix this without destroying performance...  Just need to rework the way "group opacity" is handled a bit.

**Comment by dnfield** [comment]
Ok.  There will be some performance penalty but it's definitely going to be more correct now.  

Your SVG would still benefit from removing the duplicated shapes - but it renders correctly on master now.

Feel free to reopen if things aren't working.  I'll have a new version out soon with this.

**Comment by ened** [comment]
Thank you for the quick support!
