### ISSUE TITLE
Exclude SVG from semantics

### ISSUE THREAD

**Issue by droidery** [dnfield/flutter_svg#150]
It would be useful to be able to remove the semantics from the SVG image.

The Image API has this param, and it would be useful for Flutter SVG to have the same -- for when the SVG is decorative.

```dart
  /// Whether to exclude this image from semantics.
  ///
  /// Useful for images which do not contribute meaningful information to an
  /// application.
  final bool excludeFromSemantics;
```

**Comment by dnfield** [comment]
Fixed in master.
