### ISSUE TITLE
SVG rendering badly in release mode

### ISSUE THREAD

**Issue by danieldai** [dnfield/flutter_svg#153]
I am using flutter to make a weather app, and flutter_svg is used to render weather icons, the icons render good in debug mode, but in release mode, some icons render badly

In debug mode and some times in release mode, it renders likes this:
![OK](https://www.mianjiajia.com/static/images/right.jpg)

And in debug, sometimes, it renders likes this:
![OK](https://www.mianjiajia.com/static/images/wrong.jpg)

**Comment by danieldai** [comment]
Out put of flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 64-bit edition (version 1.33.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by dnfield** [comment]
Your app looks really nice!

Unfortunately this is a known regression up until I believe v 1.3.8 (or 1.3.9?).  Please try using the latest beta, which contains the fix.
