### ISSUE TITLE
Sometimes renders incorrect image

### ISSUE THREAD

**Issue by niusounds** [dnfield/flutter_svg#156]
At sometime, SvgPicture renders incorrect image especially after redrawing. I tested with "Toggle debug paint" feature but it will also occur at non "Toggle debug paint" redrawing.

![output](https://user-images.githubusercontent.com/1331297/56723697-705d0880-6784-11e9-987a-73ec4e1cbd74.gif)

I think it is caused some bugs in PictureRecorder or Canvas (but is not sure). I'm searching root cause...

**Comment by dnfield** [comment]
What version of flutter?

Is it still a problem on master?

**Comment by niusounds** [comment]
I'm using stable channel 1.2.1.
I found https://github.com/dnfield/flutter_svg/issues/151
Is it a bug of flutter engine?

**Comment by niusounds** [comment]
I tried with flutter 1.5.9-pre.20 (current master channel). Probably it is fixed. It is not a problem of flutter_svg library.
Thank you for your advice!

If you know, please tell me what version of flutter fix this issue.

**Comment by dnfield** [comment]
I'm not sure exactly which version, but the latest beta definitely has it.
