### ISSUE TITLE
The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.    Because test_app depends on flutter_svg >=0.13.0 which requires SDK version >=2.2.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by louia** [dnfield/flutter_svg#161]
I already have the dart 2.2 according to this post https://www.reddit.com/r/FlutterDev/comments/av23cg/google_simultaneously_releases_flutter_sdk_12_and/ehc721z?utm_source=share&utm_medium=web2x

So the plugin look at the line in pubspec.yaml
```
environment:sdk: ">=2.1.0 <3.0.0"

**Comment by louia** [comment]
how to resolve :
```
flutter channel master
flutter upgrade
```

**Comment by TopGuo** [comment]
most problem due to dart‘s version,so you only update dart sdk , by run this cmd
```
flutter channel master

```

**Comment by AdamMusa** [comment]
enter this on your terminal it will fix all the reversion problem that sdk has to meet : 
      flutter upgrade  --force
