### ISSUE TITLE
Svg World map

### ISSUE THREAD

**Issue by ahmedali91** [dnfield/flutter_svg#162]
hi ,

thanks for your effort ,

I have svg world map how can make it clickable and when user click on country get the code clicked country

**Comment by dnfield** [comment]
This library only does the rendering.  You would have to use your own gesture detector to test for that

**Comment by dnfield** [comment]
See https://github.com/dnfield/flutter_svg/issues/89 for more discussion.

**Comment by raiyan24r** [comment]
> hi ,
> 
> thanks for your effort ,
> 
> I have svg world map how can make it clickable and when user click on country get the code clicked country

Did you manage to find a workaround for this?
