### ISSUE TITLE
When radial_offset branch will be merged?

### ISSUE THREAD

**Issue by alexxgarci** [dnfield/flutter_svg#163]
Hi Dev!

I'm using this library for rendering all icons in a flutter, but nowadays we have changed all the designs and I have to support icons with a linear gradient. I don't want to use png anymore, so, any notion about when this branch will be released?

**Comment by dnfield** [comment]
Radial and linear gradients are supported.  I don't think there's anything left in that branch to merge....

**Comment by alexxgarci** [comment]
Sorry, I misread the TODO part.

**Comment by dnfield** [comment]
No worries.  There's one aspect of radial gradients not currently supported, but since I've had 0 requests for it it's pretty low on my list :)
