### ISSUE TITLE
<use> links with transforms not rendering properly

### ISSUE THREAD

**Issue by PracticalCode** [dnfield/flutter_svg#164]
As you can see in the picture below, the stars are not rendering correctly in the app... (the stars do render correctly in Chrome & Edge browsers.)  I am not sure which aspect of the SVG file may be causing this.  I included the POW/MIA svg as a working example.

![image](https://user-images.githubusercontent.com/8082820/57874875-8e47e700-77df-11e9-8e18-3b9de625234f.png)

```
##  pubspec.yaml
flutter:
  uses-material-design: true
  assets:
  - images/


//  main.dart

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

//  Note >>> the stars in the 
//  Resources >>>
//  https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg
//    ... download / save [Flag_of_the_United_States.svg] to the [images] folder
//  https://en.wikipedia.org/wiki/National_League_of_Families_POW/MIA_Flag#/media/File:United_States_POW-MIA_flag.svg
//    ... download / save [Flag_of_the_United_States.svg] to the [images] folder

final Widget svgImageWidget = new SvgPicture.asset(
    'images/Flag_of_the_United_States.svg',
    //'images/United_States_POW-MIA_flag.svg',
    semanticsLabel: 'Flag');

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('DutyHonorCountry'),
          backgroundColor: Colors.blueGrey[900],
        ),
        backgroundColor: Colors.blueGrey,
        body: Center(
          child: svgImageWidget,
        ),
      ),
    ),
  );
}
```

**Comment by dnfield** [comment]
Unfortunate.  This SVG has a lot of `<use>` links and we're getting it wrong.

**Comment by dnfield** [comment]
A few bugs here:

- Losing the fill property from parent
- Losing the transform from a referenced group/shape

**Comment by IchordeDionysos** [comment]
@dnfield I may have a similar issue to this:
The SVG of the formula does not scale the numbers in the formula properly:

How the SVG looks in Flutter:
![Latex displaying in Flutter](https://cl.ly/ace9c01af668/Screen%20Shot%202019-07-09%20at%2017.27.06.png)
How it looks in Chrome:
![Latex displaying in Chrome](https://cl.ly/2bb91735ce48/Screen%20Shot%202019-07-09%20at%2017.26.07.png)

As you can see in Flutter the numbers in the fraction should be rendered smaller, but they don't.
What I found out is that the SVG does have a `<use transform="scale(0.5)" xlink:href="#E1-MJMAIN-32">`, but does not get applied to a path with the id `E1-MJMAIN-32` further down the tree.
![Possible error cause](https://cl.ly/a2d01a9ebdd5/%255Bb1d94b4f02643304a0258a4a54246bc6%255D_Screen%252520Shot%2525202019-07-09%252520at%25252017.29.52.png)

Link to SVG:
http://latex.simpleclub.com/latex2svg?latex=%5Cfrac%7B1%7D%7B%5CBigl%28%5Csqrt%7B%5Cphi+%5Csqrt%7B5%7D%7D-%5Cphi%5CBigr%29+e%5E%7B%5Cfrac25+%5Cpi%7D%7D+%3D+1%2B%5Cfrac%7Be%5E%7B-2%5Cpi%7D%7D+%7B1%2B%5Cfrac%7Be%5E%7B-4%5Cpi%7D%7D+%7B1%2B%5Cfrac%7Be%5E%7B-6%5Cpi%7D%7D+%7B1%2B%5Cfrac%7Be%5E%7B-8%5Cpi%7D%7D+%7B1%2B%5Ccdots%7D+%7D+%7D+%7D

**Comment by phamnhuvu-dev** [comment]
@IchordeDionysos You can do the following way to make workaround:
Convert from:
```xml
<use transform="scale(0.707)" xlink:href="#E5-MJMAIN-36" x="712" y="513"></use>
```
To:
```xml
<g transform="scale(0.707)" >
  <use xlink:href="#E5-MJMAIN-36" x="712" y="513"></use>
</g>
```

**Comment by dnfield** [comment]
This was so much more confusing to fix than it should have been, but I have a fix now.
