### ISSUE TITLE
decoding svg and converting it to Uint8List returns corrupted data?

### ISSUE THREAD

**Issue by adrianmoneta** [dnfield/flutter_svg#165]
Generally I want to use take a svg string of map marker add overlay text or icon in code based on context and pass it to Marker with can take bytes in constructor. 
I have my raw svg:

```
r'''<svg height="100" width="100">
   <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg>'''

```

I try to converti ti to Uint8List:

```
Future<Uint8List> convertSvg() async {
    final pictureInfo = await svg.svgPictureStringDecoder(raw2, false, null, raw2);
    final image = await pictureInfo.picture.toImage(36, 36);
    final byteData = await image.toByteData();
    final uint8List = byteData.buffer.asUint8List();
    return uint8List;
} 
```

And then, for testing purposes, I want to show result like this:

```
Container(
        alignment: Alignment.center,
        child: bytes == null
            ? Text("Patience")
            : Image.memory(bytes),
 )
```

but I all get is this error:

> flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞══════════
> flutter: The following _Exception was thrown resolving an image codec:
> flutter: Exception: operation failed
> flutter: ═══════════════════

I tried different approaches to display result of convertSvg function.  But all i get are exceptions pointing that something is wrong with my Uint8List object.

**Comment by dnfield** [comment]
By default, `Image.toByteData` gives you raw RGBA images.

For whatever reason, `Image.memory` will not work with raw RGBA images.

You should be able to resolve this by using `final byteData = await image.toByteData(format: ImageByteFormat.png)`.
