### ISSUE TITLE
My colored SVG is rendered as black?

### ISSUE THREAD

**Issue by RegisSaffi** [dnfield/flutter_svg#166]
Hey, i have SVG images and they are colored, when i import one in my flutter app,it come in black color,while i did not set the color. what is the problem?

**Comment by MeshkaniMohammad** [comment]
Same problem observed!

**Comment by Tolga-GA** [comment]
Why can't we just see the default svg color? I can see that my svg file is being brushed with the primary color.

**Comment by AresVampire** [comment]
I have same problem

**Comment by dnfield** [comment]
Can you provide a sample SVG that demonstrates this?

**Comment by AresVampire** [comment]
[Sample.txt](https://github.com/dnfield/flutter_svg/files/3213267/Sample.txt)

This is the file. I have renamed the extension to .txt for uploading.

**Comment by dnfield** [comment]
@AresVampire your problem is using a style element which isn't supported - see #105

**Comment by toanalien** [comment]
Try this: https://github.com/dnfield/flutter_svg/issues/105#issuecomment-479724077

**Comment by thealiflab** [comment]
You can watch this answer from StackOverflow

https://stackoverflow.com/a/62748066/11681472

**Comment by agersea** [comment]
Same problem, my SVG assets render black when using SvgPicture.asset.  I do not believe they are corrupted as they display properly on my Mac and in Android Studio.

**Comment by FoolishRobo** [comment]
[flutter_svg](https://pub.dev/packages/flutter_svg) can not understand [Internal or Embedded CSS](https://www.geeksforgeeks.org/types-of-css-cascading-style-sheet/).

Hence you need to convert the internal css `<style>.a{fill:#566e83;}</style>` into inline css.

Example:-
Convert this `<path class="a" ...` to `<path style="fill:#566e83;" ...`

**Comment by daixianceng** [comment]
resolved: I use webview to display svg:

```dart
import 'package:webview_flutter/webview_flutter.dart';

Container(
  height: 100,
  width: 200,
  child: WebView(
    initialUrl: 'about:blank',
    onWebViewCreated:
        (WebViewController webViewController) async {
      String svgText =
          await rootBundle.loadString('assets/white-logo.svg');
      String fileText =
          '<html><style>html,body {background: #C2185B;padding: 0;margin: 0;} svg {width: 100vw; height: 100vh;}</style><body>' +
              svgText +
              '</body></html>';
      webViewController.loadUrl(
        Uri.dataFromString(
          fileText,
          mimeType: 'text/html',
          encoding: Encoding.getByName('utf-8'),
        ).toString(),
      );
    },
  ),
)
```

**Comment by dnfield** [comment]
Using a webview will you get you pretty complete SVG support. But it will also be pretty slow. 

It's not a bad option if you have a really special and complex SVG that you want to show in full screen mode or something. But it's not a good one for showing e.g. an icon on a button :)

**Comment by pavittarx** [comment]
If you are using the `Svgpicture.asset()` omit the second parameter `color: Colors.black`;

```dart 
  const svg = 'assets/pic.svg';

  // omit the second color parameter, and your colors will be visible.
  SvgPicture.asset(svg, 
    color: Colors.black, 
    semanticsLabel: 'My SVG Picture' 
  );

 // something  like this.
  SvgPicture.asset(svg, 
    semanticsLabel: 'My SVG Picture' 
  ); 

```

**Comment by muhammadshahidraficp** [comment]
In my case, i just re-run project, i feel after adding asset svg file will work fine only after re-run project.

**Comment by iamprawesh** [comment]
The issue is that The flutter_svg is unable to load the css written inside style tag. flutter_svg only support inline css . Write inline css instead of inside the style tag

**Comment by AndreaDellaValle** [comment]
> The issue is that The flutter_svg is unable to load the css written inside style tag. flutter_svg only support inline css . Write inline css instead of inside the style tag

This definitely solves the issue! thank you @iamprawesh

**Comment by Cyrille-Dakhlia** [comment]
> [flutter_svg](https://pub.dev/packages/flutter_svg) can not understand [Internal or Embedded CSS](https://www.geeksforgeeks.org/types-of-css-cascading-style-sheet/).
> 
> Hence you need to convert the internal css `<style>.a{fill:#566e83;}</style>` into inline css.
> 
> Example:- Convert this `<path class="a" ...` to `<path style="fill:#566e83;" ...`
> 
> You can use [freecodeformat](https://www.freecodeformat.com/svg-editor.php) to edit your svg files.

Works like a charm, thank you very much 🙏

**Comment by TidelxD** [comment]
> @AresVampire your problem is using a style element which isn't supported - see #105

Thank you ! it works

**Comment by Yonkokilasi** [comment]
> resolved: I use webview to display svg:
> 
> import 'package:webview_flutter/webview_flutter.dart';
> 
> Container(
>   height: 100,
>   width: 200,
>   child: WebView(
>     initialUrl: 'about:blank',
>     onWebViewCreated:
>         (WebViewController webViewController) async {
>       String svgText =
>           await rootBundle.loadString('assets/white-logo.svg');
>       String fileText =
>           '<html><style>html,body {background: #C2185B;padding: 0;margin: 0;} svg {width: 100vw; height: 100vh;}</style><body>' +
>               svgText +
>               '</body></html>';
>       webViewController.loadUrl(
>         Uri.dataFromString(
>           fileText,
>           mimeType: 'text/html',
>           encoding: Encoding.getByName('utf-8'),
>         ).toString(),
>       );
>     },
>   ),
> )

Thanks, this was the best options out there. Especially when you are rendering third part svg icons that you have no control over. Also for those saying it's pretty slow . The only difference I noticed was about like 1 second, but that's not much considering the trade off of having no icon or a black one
