### ISSUE TITLE
Question: How to fade in network-sourced SVG picture

### ISSUE THREAD

**Issue by vassilvk** [dnfield/flutter_svg#167]
Hello,

I'm trying to figure out what's the best (idiomatic?) way to apply an animated transition (for example [fade in transition](https://flutter.dev/docs/cookbook/animation/opacity-animation)) to an SVG widget generated by `SvgPicture.network(...)`.

I'd like to use a static (non-animated) placeholder while the SVG bits are loaded from the network, but then kick off the fade-in animation as soon as the SVG is ready to be displayed.

P.S.
Massive THANK YOU! for a great library 👍 

Cheers!

**Comment by vassilvk** [comment]
I solved this by implementing `AnimatedCrossFade` widget as an internal wrapper around the placeholder and the SVG image.

The master branch of this plug in is currently not compatible with the latest stable flutter version, which is why I forked and back-ported the change against flutter_svg 0.12.4.

https://github.com/vassilvk/flutter_svg/commit/e2c4e16bd7c7d6bec499338b796e923bb6053680

**Comment by Abdelazeem777** [comment]
I made this package that can handle the fade-out animation after loading and also it uses the same mechanism for caching images like `CacheNetworkImage`:

https://pub.dev/packages/cached_network_svg_image
