### ISSUE TITLE
Svg Rendering Issue

### ISSUE THREAD

**Issue by PankajThapaAndroid4** [dnfield/flutter_svg#168]
Hi 
How to render svg image after getting string from JsonObject using svg key

{"svg": "\u003csvg width\u003d\"350\" height\u003d\"330\" id\u003d\"chartSvg\" xmlns\u003d\"http://www.w3.org/2000/svg\"\u003e\u003cg class\u003d\"slice\"\u003e\u003crect x\u003d\"0\" y\u003d\"0\" width\u003d\"350\" height\u003d\"330\" stroke\u003d\"black\" stroke-width\u003d\"3\" fill\u003d\"none\"\u003e\u003c/rect\u003e\u003c/g\u003e\u003cg class\u003d\"slice\"\u003e\u003crect x\u003d\"10\" y\u003d\"10\" width\u003d\"330\" height\u003d\"310\" stroke\u003d\"black\" stroke-width\u003d\"1\" fill\u003d\"none\"\u003e\u003c/rect\u003e\u003c/g\u003e\u003cg class\u003d\"slice\"\u003e\u003cpath d\u003d\"M175,10L92.5,87.5L10,10\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M340,10L257.5,87.5L175,10\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M92.5,87.5L10,165L10,10\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M92.5,87.5L175,165L257.5,87.5L175,10\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M257.5,87.5L340,165L340,10\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M92.5,87.5L175,165L92.5,242.5L10,165\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M257.5,87.5L340,165L257.5,242.5L175,165\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M92.5,242.5L10,320L10,165\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M175,165L257.5,242.5L175,320L92.5,242.5\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M92.5,242.5L175,320L10,320\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003cpath d\u003d\"M257.5,242.5L340,320L175,320\" stroke\u003d\"#333333\" stroke-width\u003d\"2\" fill\u003d\"none\"\u003e\u003c/path\u003e\u003ctext font-size\u003d\"15.714285714285714px\"\u003e11\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"171.7\" y\u003d\"152.6\" style\u003d\"fill: #333333;\"\u003e7\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"92.5\" y\u003d\"72\" style\u003d\"fill: #333333;\"\u003e8\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"67.75\" y\u003d\"93.7\" style\u003d\"fill: #333333;\"\u003e9\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"158.5\" y\u003d\"169.65\" style\u003d\"fill: #333333;\"\u003e10\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"69.4\" y\u003d\"250.25\" style\u003d\"fill: #333333;\"\u003e11\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"82.6\" y\u003d\"261.1\" style\u003d\"fill: #333333;\"\u003e12\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"168.4\" y\u003d\"183.6\" style\u003d\"fill: #333333;\"\u003e1\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"249.25\" y\u003d\"261.1\" style\u003d\"fill: #333333;\"\u003e2\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"274\" y\u003d\"242.5\" style\u003d\"fill: #333333;\"\u003e3\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"186.55\" y\u003d\"169.65\" style\u003d\"fill: #333333;\"\u003e4\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"274\" y\u003d\"92.15\" style\u003d\"fill: #333333;\"\u003e5\u003c/text\u003e\u003ctext font-size\u003d\"15.714285714285714px\" x\u003d\"249.25\" y\u003d\"72\" style\u003d\"fill: #333333;\"\u003e6\u003c/text\u003e\u003ctext font-size\u003d\"23.014962147807633px\" x\u003d\"153.49251892609618\" y\u003d\"87.5\" style\u003d\"fill: #333333;\"\u003eमं\u003c/text\u003e\u003ctext font-size\u003d\"23."}

**Comment by dnfield** [comment]
You need to parse that JSON and then parse the XML out of it.  This question would probably be better suited for someone like Stackoverflow though - e.g. "Using Dart, how could I retreive the XML data from this JSON?".
