### ISSUE TITLE
support for newer versions of flutter?

### ISSUE THREAD

**Issue by NicTanghe** [dnfield/flutter_svg#171]
I get the following error.

Because flutter_svg >=0.0.2 requires the Flutter SDK and flutter_svg <0.1.0 requires SDK version >=1.19.0 <2.0.0, flutter_svg is forbidden.
So, because monokimono depends on flutter_svg any, version solving failed.

Anny chance you'l be updating for newer versions?

**Comment by dnfield** [comment]
You probably just need a dependency override somewhere...  Version 0.12.x supports up yo Flutter 1.5.8, and 0.13.x 1.6+
