### ISSUE TITLE
 EXCEPTION CAUGHT BY SVG  

### ISSUE THREAD

**Issue by smaharjan974** [dnfield/flutter_svg#172]
In debug mode its fine but in release mode its getting exception caught by svg. 
 The following assertion was thrown resolving a single-frame picture stream: Unable to load asset: assets/images/gift_1.svg
 When the exception was thrown, this was the stack:
I/flutter ( 5929): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221)
I/flutter ( 5929): <asynchronous suspension>
I/flutter ( 5929): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67)
I/flutter ( 5929): <asynchronous suspension>
I/flutter ( 5929): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162)
I/flutter ( 5929): #3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281)
I/flutter ( 5929): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162)
I/flutter ( 5929): #5      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:444)
I/flutter ( 5929): <asynchronous suspension>
I/flutter ( 5929): #6      As

**Comment by dnfield** [comment]
Sounds like the asset isn't getting included in your release bundle...

**Comment by smaharjan974** [comment]
how to solve this issue but i think in ios it is working perfectly.

**Comment by dnfield** [comment]
Aee you able to load the asset on Android just using the load asset API?

**Comment by smaharjan974** [comment]
yeah it works fine until i use this library both in debug and release mode. When i use this library its get error and i also found this error is caught by this exception " EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE " but i found it works on ios release mode.

**Comment by dnfield** [comment]
It would be helpful if you had a small project that reproduces the issue.

**Comment by dnfield** [comment]
Without more information I'm not sure what to do here.  It seems likely that your asset isn't included properly.  If you have a reproducible case, I'd be happy to see this re-opened and investigated further.

**Comment by smaharjan974** [comment]
@dnfield it is due to flutter not stable version that i am using ani some changes on assests. I change the flutter version to stable and assets and it works on both debug and release mode thanks.
