### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Pante** [dnfield/flutter_svg#180]
The [link ](https://pub.dev/documentation/flutter_svg/latest/)to the online documentation for versions >= 0.13.0 is broken. Are there any plans to fix it?

**Comment by dnfield** [comment]
It's an issue with pub right. Ow unfortunately.  It should be fixed fairly soon.  For now you can use the docs from the 0.12.x versions

**Comment by Pante** [comment]
Ah, that's a shame Thank you.
