### ISSUE TITLE
flutter pub get failed  error

### ISSUE THREAD

**Issue by racknoris** [dnfield/flutter_svg#185]
I have Flutter SDK version `1.5.4-hotfix.2`, and when I try to use: `flutter_svg: ^0.13.0+2`, I get:

`Because <app name> depends on flutter_svg >=0.13.0 which requires Flutter SDK version >=1.5.9-pre.94 <2.0.0, version solving failed.`

**Comment by dnfield** [comment]
You need 0.12.4
