### ISSUE TITLE
Not compatible with Flutter 1.8.0 - Dev Channel 

### ISSUE THREAD

**Issue by dvird** [dnfield/flutter_svg#186]
Compiler message:
file:///Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4/lib/svg.dart:158:18: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/xxx/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'picture failed to precache',

**Comment by dnfield** [comment]
Need to use 0 13.x
