### ISSUE TITLE
SVG with CSS shows black box

### ISSUE THREAD

**Issue by pjcau** [dnfield/flutter_svg#19]
Hi guys,

i want use your library to render svg file on my app. When load the svg from asset but  I saw the black image. I attach the original file, can I  help me what's wrong?
Thank a lot
J
[cat.svg.zip](https://github.com/dnfield/flutter_svg/files/2093176/cat.svg.zip)

**Comment by dnfield** [comment]
Your example uses CSS in a `<style>` element.  That's not supported at this point, and I don't really have any plans to support it soon - although your example doesn't use particularly complicated or crazy CSS, it's not trivial to support and it's possible to preprocess away.  I've attached the output of running this through svgcleaner, which renders fine.
[cat_clean.zip](https://github.com/dnfield/flutter_svg/files/2093957/cat_clean.zip)

**Comment by pjcau** [comment]
I use Adobe Illustrator to extract to svg file from eps file. So there is some configuration, can we work together so resolve it?

**Comment by dnfield** [comment]
You could try setting your styling option to "Inline styles" (which are supported by this plugin) when you export, as explained here: https://css-tricks.com/illustrator-to-svg/

Or, you can take your output and run it through `svgcleaner` (linked above - that's what I used to make a working version in cat_clean.zip), which will try to inline the styles for you and do some other optimizations to the file.

**Comment by pjcau** [comment]
I resolve, and this  it' s very great news, it's necessary to extract from Adobe IA, like Export->Export As... and in next setting page , choose Styling:Inline Style.

<img width="521" alt="screen shot 2018-06-12 at 14 37 43" src="https://user-images.githubusercontent.com/1088176/41290847-5583eed2-6e4e-11e8-9610-86818a407647.png">

**Comment by pjcau** [comment]
So we find the same solution!!!! I'm a senior developer, and with this library now it's very fast and powerfull use it for the common picture. 
Thank you

Great job

**Comment by iamarnas** [comment]
> Hi @dnfield,
> I have to display some svg images from a server, which I don't have permission to modify. If possible, could you please consider implementing this feature?
> Thank you!

I have same problem to :(
