### ISSUE TITLE
mix-blend-mode not supported

### ISSUE THREAD

**Issue by MsXam** [dnfield/flutter_svg#190]
We are currently using version 0.12.4+2 and notice that we get black rendering marks drawn over svg's that we are displaying , i.e :

![image](https://user-images.githubusercontent.com/18722796/60723322-3e59e680-9f2b-11e9-93a8-c2402b15ed62.png)

Here we can see that:
1- Ears have black shading instead of white
2- Black shading under chin instead of white
3- Two black oval shapes above top of left eye instead of white shading 
4- Shading of black is lost at bottom of circle.

We exported our SVG in AI, this was the settings we used for AI:

![image](https://user-images.githubusercontent.com/18722796/60723524-c213d300-9f2b-11e9-8b4b-b1c4a6dcd396.png)

The original AI file is also attached
[flutter_svg_example.ai.zip](https://github.com/dnfield/flutter_svg/files/3362772/flutter_svg_example.ai.zip)

**Comment by dnfield** [comment]
Can you share the.exported SVG ?

**Comment by MsXam** [comment]
Sure - try this one :

[screen_2.svg.zip](https://github.com/dnfield/flutter_svg/files/3363078/screen_2.svg.zip)

**Comment by dnfield** [comment]
Sorry, I lost track of this one. This is due to the `mix-blend-mode:screen` attributes - they're not supported right now.  It might not be too much to fix that though, will check.

**Comment by dnfield** [comment]
Actually, the `isolation` isn't supported either.

**Comment by dnfield** [comment]
In theory this shouldn't be too hard to implement, but I'd be interested in knowing if this is a must have or not - I'd also be happy to review a PR with changes to support this.

**Comment by MsXam** [comment]
Mix blend attributes allow for some great compositions between a primary object and its background, having the ability for  any images or text, borders or headings  to be able to be blended with its background simply makes an SVG image look 'wholesome' , i.e a text has not just been stuck on a background but appears to be 'part of that background' - so in answer to your question, yes  **this is definitely a must have**

**Comment by dnfield** [comment]
Fixed in v0.14.3 (which is currently undergoing CI and will be published once it passes).
