### ISSUE TITLE
Add support to Flutter SDK 1.7.8+hotfix.2

### ISSUE THREAD

**Issue by akajack** [dnfield/flutter_svg#192]
A week ago Flutter SDK version `1.7.8+hotfix.2` was created on the **beta** channel. Yesterday it was published on the **stable** channel.
It solves some problems of the 64 bit compilation (mandatory from August) as it is indicated in the reference issue: [flutter/flutter #18494](https://github.com/flutter/flutter/issues/18494#issuecomment-507782791)
However, by updating Flutter, `flutter_svg` generates a compatibility problem.
This is done by updating the file `pubspec.yaml`:

```
The current Flutter SDK version is 1.7.8+hotfix.2.
Because this_app depends on flutter_svg ^0.12.4+2 which requires Flutter SDK version >=0.7.3 <1.5.9, version solving failed.
pub get failed (1)
exit code 1
```

And this by trying to compile:

```
The current Flutter SDK version is 1.7.8+hotfix.2.                      
                                                                        
Because this_app depends on flutter_svg ^0.12.4+2 which requires Flutter SDK version >=0.7.3 <1.5.9, version solving failed.
Running "flutter pub get" in MyApp...                 
pub get failed (1)
```

Please update the package to solve these problems.
Thank you and good work ;)

**Comment by dnfield** [comment]
You need to use flutter_svg 0.13.0.
