### ISSUE TITLE
Update to latest stable release

### ISSUE THREAD

**Issue by Eddydpyl** [dnfield/flutter_svg#193]
Flutter was recently updated in its stable channel, with breaking changes for this library.

**Comment by dnfield** [comment]
Use v0.13.0 and it should work.  

I'm gii g to leave this one open because I'm getting reports of this frequently.  There was a breaking change this stable that breaks 0.12.x and lower, but 0.13.x and up will work.

**Comment by Eddydpyl** [comment]
Can confirm that v0.13.0 works as expected. Thanks!

**Comment by dnfield** [comment]
I think most people are probably past this by now - will close and re-open if people keep filing bugs about it again :)

**Comment by guilhermeagostinelli** [comment]
Not working with 1.17.0 (latest Flutter SDK release on stable channel). @dnfield Could you re-open this?

**Comment by dnfield** [comment]
That's a new bug then. Please file a new issue with instructions on how to reproduce

**Comment by guilhermeagostinelli** [comment]
Ok, here it is: #341
