### ISSUE TITLE
SvgPicture ignores hieght/width when contained.

### ISSUE THREAD

**Issue by bsutton** [dnfield/flutter_svg#196]
I'm trying to display an svg inside a box.
The problem is that the svg is always sizing itself to the size of the container rather than sizing itself based on the width/height  passed.

Compare these two examples:

In this first example the svg is rendered the expect size of 10 x 10.
```
Center(
        child: Container(
            decoration: BoxDecoration(
              color: Colors.lightBlueAccent,
            ),
            child: FittedBox(
            child: SvgPicture.asset(path,
                width: 10,
                height: 10),
            ),
    );
```

In this example, even though the size is still 10 x 10 the svg grows to fill the container.

```
Center(
        child: Container(
            decoration: BoxDecoration(
              color: Colors.lightBlueAccent,
            ),
            child: FittedBox(
            child: SvgPicture.asset(path,
                width: 10,
                height: 10),

            ),
      width: 40,
    height: 40
    );
```

Am I doing something wrong or is this a bug?

**Comment by dnfield** [comment]
I think that's what FittedBox is supposed to do in this case...

What if you just have it be a `Center` instead of a FittedBox?  Or skip the FittedBox entirely?

**Comment by bsutton** [comment]
So I just I just tried the scaledown option on the fitted box and it solved the issue.

This however seems wrong. If I've specified a width/height on the svgpicture I should reasonably expect it to be honoured.

For the record here is the working code:

```
Center(
        child: Container(
            decoration: BoxDecoration(
              color: Colors.lightBlueAccent,
            ),
            child: FittedBox(fit: BoxFit.scaleDown,
            child: SvgPicture.asset(path,
                semanticsLabel: "Flip",
                width: 20,
                height: 20),

            ),
      width: 40,
    height: 40
    );
```

**Comment by dnfield** [comment]
FittedBox scales its children.  I'd have to check what the default BoxFit is, but my guess is that it's scaleUp or something like that.

**Comment by bsutton** [comment]
So if the svg size is smaller than the defined height/width on the svgpicture then it works, but it does't work if the svg size is larger?

**Comment by dnfield** [comment]
I'm not really fully sure I understand - however, I'm pretty sure this is WAI.  If you have a good counterexample where this just doesn't work the way it should - i.e. it works differently than with a an image widget in the same scenario, we can re-open this.

**Comment by ronytesler** [comment]
```
Stack(
        children: [
          Positioned(
            bottom: 0,
            left: 0,
            child: Container(
              decoration: BoxDecoration(
                border: Border.all(
                  color: Colors.yellow,
                  width: 4.0,
                ),
              ),
              child: Image.asset(
                'images/temp.jpg',
                height: height * 0.8,
                width: width * 0.4,
              ),
...
```
If I use an svg instead of a jpg, the container (and image) size doesn't change when I change the size of the window (browser).
When I use the jpg it works as I expect.
So it does behave differently.

**Comment by Eduar2TC** [comment]
I fixed it by wrapping the image inside a sizedBox with a fixed height.
```
return Align(
      alignment: Alignment.center,
      child: SizedBox(
        height: 50,
        child: SvgPicture.asset(
          'lib/assets/man012.svg',
          height: null,
          width: personImageWidth,
          fit: BoxFit.fill,
        ),
      ),
    );
```

**Comment by maxence-futures** [comment]
@Eduar2TC Alignment makes the job, nice mate.
