### ISSUE TITLE
Can't read svg asset size

### ISSUE THREAD

**Issue by lintoncaldecott** [dnfield/flutter_svg#198]
This is my asset 

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="100px" height="100px" viewBox="0 0 100 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 56 (81588) - https://sketch.com -->
    <title>Rectangle</title>
    <desc>Created with Sketch.</desc>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect id="Rectangle" fill="#0061FF" x="0" y="0" width="100" height="100"></rect>
    </g>
</svg>
```

and I am trying to interrogate it to get the width, the assertion below fails.

```
    final mapAsset = SvgPicture.asset("assets/testBox.svg");
    assert(mapAsset.width != null);
```

Is there something I am doing wrong?

**Comment by dnfield** [comment]
You shouldn't be trying to read properties like that from a Widget in general.

If you want information like that about the SVG, you'd have to basically do what `SvgPicture` is doing under the hood - parse the SVG, create the `Drawable`, and add it to a picture.  On the `DrawableRoot`, you'll get a viewport object that tells you how big it is.  But keep in mind that parsing is meant to be async, and if you make your UI block on it you'll see performance degredation.

Why are you trying to do this?

**Comment by lintoncaldecott** [comment]
Thanks for clarifying, I thought it was a r/w property not just a write property. We will try to make a workaround for it.
