### ISSUE TITLE
Designer Guideline

### ISSUE THREAD

**Issue by amorenew** [dnfield/flutter_svg#207]
I have a suggestion to add in the readme a guideline for designers who export from Adobe Illustrator they should use the following configuration for getting the right supported format
![image](https://user-images.githubusercontent.com/2842459/62599914-91de9c00-b8fe-11e9-8fb7-4af57d5100f7.png)

**Comment by dnfield** [comment]
Thanks!

Would you consider opening a PR to update the README?

**Comment by amreniouinnovent** [comment]
@dnfield I have opened a PR for it
