### ISSUE TITLE
Colored drawing not working properly with merged DrawableStyle

### ISSUE THREAD

**Issue by brun0xon** [dnfield/flutter_svg#208]
I want to draw DrawableRoot with custom color using DrawableStyle. Either I merge style or not it always will be painted with black color. Where is the problem?
```
DrawableRoot root = await svg.fromSvgString('
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 6.1 2.762"> <g transform="matrix(1 0 0 -1 0 800)">
	<path d="M0,800h6.1v-2.762H0V800z"/> </g></svg>', 'key');

root.mergeStyle(DrawableStyle(fill: DrawablePaint(PaintingStyle.fill, color: Colors.green)));
root.draw(canvas, ColorFilter.mode(Colors.black, BlendMode.color), null);
```

**Comment by dnfield** [comment]
I think you should specify no color filter in this case...

**Comment by brun0xon** [comment]
> I think you should specify no color filter in this case...

Passing null instead of ColorFilter's instance gives no effect

**Comment by dnfield** [comment]
I would try some other blend modes.  I'ts not entirely clear to me what you're trying to achieve though.

**Comment by brun0xon** [comment]
@dnfield 
I have a black colored svg image and white colored canvas. There is situation when I need to paint green colored svg image (which is black in src). What should I do?
