### ISSUE TITLE
Two import sources

### ISSUE THREAD

**Issue by json469** [dnfield/flutter_svg#210]
Is there a reason why there are two import sources for flutter_svg?

`import 'package:flutter_svg/flutter_svg.dart'`
`import 'package:flutter_svg/svg.dart'`

**Comment by dnfield** [comment]
It depends on what you actually want to use.  `flutter_svg.dart` is likely what most people want, and contains the widget definitions.  `svg.dart` can be used if you only plan to do parsing and are willing to do a bit more work to use widgets.
