### ISSUE TITLE
Bugs found.

### ISSUE THREAD

**Issue by PauloHdOF** [dnfield/flutter_svg#211]
Error loading images the following images:

- https://www.api-football.com/public/flags/ar.svg

console error: parse invalid double "1pt";

I was able to fix it as follows:
file: numbers.dart
`double parseDouble(String maybeDouble, {bool tryParse = false}) {
  assert(tryParse != null);
  if (maybeDouble == null) {
    return null;
  }
  maybeDouble = maybeDouble.trim().replaceFirst('px', '').trim();
  -> add this line  =>      maybeDouble = maybeDouble.trim().replaceFirst('pt', '').trim();    <-

  if (tryParse) {
    return double.tryParse(maybeDouble);
  }
  return double.parse(maybeDouble);
}`

- https://www.api-football.com/public/flags/bo.svg"

console error: 
"The following StateError was thrown resolving a single-frame picture stream: Bad state: Expected to find Drawable with id url().
Have ids: ()"
I couldn't fix it

- flutter:https://www.api-football.com/public/flags/cn.svg"
console error:  "The following StateError was thrown resolving a single-frame picture stream:
 Bad state: Expected to find Drawable with id url(#c).
Have ids: (url(#a), url(#b))"
I couldn't fix it

**Comment by dnfield** [comment]
Points and pixels aren't quite the same - a proper conversion here would have to be done, right?

For bo.svg, that's strange - there are no xrefs in it, not sure why it'd be looking for one.  Do you have the full stack?

For cn.svg, also looks strange -there are no references I see there to #c.  Have these changed recently?

**Comment by PauloHdOF** [comment]
Yes, I'm a beginner in programming, so this should be as much as I can do.

**Comment by dnfield** [comment]
bo.svg has some `use` elements that refer to nothing.  That case is easy to fix.

`cn.svg` doesn't give me the same error you're seeing, I suspect that's actually from a different SVG.  However, `cn.svg` doesn't render correctly because of the `use` transform issue - which is being tracked in https://github.com/dnfield/flutter_svg/issues/164

**Comment by dnfield** [comment]
Fix for the bo.svg landed in master, we'll track cn in the other one.  The pt one should have its own bug as well if it's important to you.

**Comment by reya276** [comment]
I'm having the same issues(Error) trying to output the SVG images. I created the SVG images using [inkscape](https://inkscape.org/)
