### ISSUE TITLE
Ellipse drawn solid but fill is set to none

### ISSUE THREAD

**Issue by jamesncl** [dnfield/flutter_svg#216]
I have an SVG which isn't rendering as expected in Flutter with flutter_svg 0.14.0. Here is the SVG as it appears in chrome and Adobe Illustrator:

![svg2](https://user-images.githubusercontent.com/15979056/63342355-27d4e680-c343-11e9-8e1d-61317e885342.PNG)

This is how it's rendering in Flutter:

![svg1](https://user-images.githubusercontent.com/15979056/63342368-2e635e00-c343-11e9-8e9b-24ab8c3242d4.PNG)

I'm using the basic `SvgPicture.asset(...)` constructor with no extra arguments.

`SvgPicture.asset("assets/svg/mysvg.svg")`

Here is the SVG in question. As you can see, the ellipse looks like it has a fill type of none, so it should be rendered just as an outline. Is this a bug or am I doing something wrong?

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 23.0.3, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 145 268.2" style="enable-background:new 0 0 145 268.2;" xml:space="preserve">
<style type="text/css">
	.st0{fill:none;stroke:#000000;stroke-width:2;stroke-miterlimit:10;}
</style>
<g>
	<ellipse class="st0" cx="72.5" cy="134.1" rx="69.1" ry="128.7"/>
	<g>
		<path d="M99.5,88.3c0.6,1.2,1.2,2.6,1.8,4.2c2.8,7.8,5.2,20.6,5.2,40.6c0,5.5-0.2,11.6-0.6,18.2c-0.3,4.4,3.1,8.2,7.5,8.5
			c0.2,0,0.3,0,0.5,0c4.2,0,7.7-3.3,8-7.5c0.4-6.9,0.6-13.3,0.6-19.2c0-30.2-4.9-46.9-11.4-56.9c-3.3-5-7.1-8.2-10.7-10
			c-3.4-1.7-6.4-2.1-8.2-2.1c-0.1,0-0.3,0-0.4,0H53.2c-0.1,0-0.3,0-0.4,0c-1.8,0-4.8,0.4-8.2,2.1c-5.4,2.7-11.2,8.5-15.2,18.8
			c-4.1,10.4-6.9,25.4-6.9,48c0,5.9,0.2,12.2,0.6,19.2c0.3,4.3,3.8,7.5,8,7.5c0.2,0,0.3,0,0.5,0c4.4-0.3,7.8-4,7.5-8.5
			c-0.4-6.7-0.6-12.7-0.6-18.2c0-24.2,3.5-37.8,7-44.9v150c0,6.8,5.5,12.4,12.4,12.4c6.8,0,12.4-5.5,12.4-12.4V148h4.6v90.3
			c0,6.8,5.5,12.4,12.4,12.4c6.8,0,12.4-5.5,12.4-12.4L99.5,88.3L99.5,88.3z"/>
		<path d="M76.2,58.2C86.9,56.4,95,47.2,95,36c0-12.4-10.1-22.5-22.5-22.5C60.1,13.5,50,23.6,50,36c0,11.2,8.2,20.4,18.8,22.2
			c1.2,0.2,2.4,0.3,3.7,0.3S75,58.4,76.2,58.2z"/>
	</g>
</g>
</svg>
```

**Comment by dnfield** [comment]
The `style` tag isn't supported. Try running this through `svgcleaner` or one of the similar tools mentioned in the readme - it should resolve your issue.
