### ISSUE TITLE
Some Svg Images not rendered.

### ISSUE THREAD

**Issue by hirenvadher954** [dnfield/flutter_svg#217]
Only some images not rendered.
i.e - https://restcountries.eu/data/asm.svg

**Comment by ProgrammingLife** [comment]
Wow so simple svg.

**Comment by dnfield** [comment]
If you look at the stack trace this image produces, you'll see `invalid double value: 1pt`.

You need to change the `stroke-width` to just `1`.  This library doesn't support `pt` values.
