### ISSUE TITLE
How to use flutter_svg with Palette Generator?

### ISSUE THREAD

**Issue by ueman** [dnfield/flutter_svg#218]
I would like to use [Palette Generator](https://pub.dev/packages/palette_generator) with flutter_svg.

Currently I have the following code:
```
Future<Color> colorFromSvgString(String svgAsString) async {
  final DrawableRoot svgRoot =
      await svg.fromSvgString(svgAsString, svgAsString);
  final picture = svgRoot.toPicture();
  final image = await picture.toImage(100, 100);
  final palette = await PaletteGenerator.fromImage(image);
  return palette.dominantColor.color;
}
```
This doesn't work because ´picture.toImage(100, 100)´ does not return a rendered image. How could I obtain a rendered Image from a Picture?

**Comment by dnfield** [comment]
It should definitely return an image.  Does your SVG render otherwise?

**Comment by ueman** [comment]
It does return an Image but Palette Generator doesn't return any colors from it.

The picture documentation says about [toImage](https://api.flutter.dev/flutter/dart-ui/Picture/toImage.html) that it only renders when it gets drawn the first time.
But I don't need to draw it.

On a side note: Is this the right place to ask?

**Comment by dnfield** [comment]
I suppose you could ask on StackOverflow :)

I would see if you can verify that the image being returned draws what you expect (try painting it on a canvas with drawImage).

If that works, it seems like maybe there' ssome issue with PalletteGenerator, or the usage of it in this case.

**Comment by ueman** [comment]
For a follow up see https://stackoverflow.com/questions/57736470/how-to-get-an-ui-image-from-a-ui-picture-in-flutter/57750985#57750985

Thanks for your help though.
