### ISSUE TITLE
Implement SvgImage.file

### ISSUE THREAD

**Issue by Rockvole** [dnfield/flutter_svg#22]
I need the method SvgImage.file(File myfile)
My images are stored in a directory which is user downloaded from a zip file and unpacked. So they are not available across a network, or in the assets location.

Thanks.

**Comment by dnfield** [comment]
I think what you're looking for is [`SvgPicture.file`](https://github.com/dnfield/flutter_svg/blob/master/lib/svg.dart#L138), or maybe `SvgPicture.memory` if you're loading the file in some other way first and have the bytes in memory already.

`SvgImage` was deprecated a little ways back now, and I actually just removed that code from master today.

**Comment by Rockvole** [comment]
Ok thanks. Actually I copied the example from the README today, but it didnt show SvgPicture. I have had this page in my browser for more than a week. Perhaps it was in browser cache or something.
