### ISSUE TITLE
Image not show when have <svg> in <svg>

### ISSUE THREAD

**Issue by ridz0n3** [dnfield/flutter_svg#220]
Hi, 

May i ask, i try to render a svg image which is 
`<svg fill="none" height="2990" viewBox="0 0 2300 2990" width="2300">
...
<svg height="7249" viewBox="0 0 1200 1800" width="4832" x="-1084" y="-482">
...
</svg>
...
</svg>`

when i run the app the img show only img that size 7249x4832

these are my svg file that i used https://github.com/ridz0n3/Animation/blob/master/magCover.svg
can u help me @dnfield?

**Comment by dnfield** [comment]
Nested SVG aren't supported at this time.  https://github.com/dnfield/flutter_svg/issues/132 is tracking that.
