### ISSUE TITLE
Caching for offline use

### ISSUE THREAD

**Issue by crushman1** [dnfield/flutter_svg#221]
Whats the best way to cache the svg so that it can still be shown without internet? Is there support for such a feature?

I know i can download them all manually but im hoping you guys can give a better alternative.

**Comment by manohar-voggu** [comment]
@crushman1 using [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) works for offline usage
`var file = await DefaultCacheManager().getSingleFile(url);`
`var svg =  SvgPicture.file(file);`
