### ISSUE TITLE
Round corners don't render correctly

### ISSUE THREAD

**Issue by eriknikulski** [dnfield/flutter_svg#233]
I have a SVG that should have round corners but does not in Flutter.

Here it is in Flutter:
![image](https://user-images.githubusercontent.com/32927151/66053696-13376100-e533-11e9-8fbd-27527d071f6e.png)

Code is:
```dart
SvgPicture.asset(
    'images/square.svg',
    height: 65.0,
    width: 72.0,
    ),
```

Here it is in a Browser:
<img width="80" alt="Screenshot 2019-10-02 at 16 35 58" src="https://user-images.githubusercontent.com/32927151/66053764-306c2f80-e533-11e9-8b58-b1f2bbf2d0d8.png">

SVG source:
```
<svg fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" viewBox="0 0 350 480" xmlns="http://www.w3.org/2000/svg">
    <path d="m75.286 228.593h199.393v235.869h-199.393z" fill="#fff" stroke="#000" stroke-width="28.03"/>
</svg>
```

**Comment by dnfield** [comment]
This is probably a big with inheritance.  Can you try moving the linejoin and miterlimit to the path itself?

**Comment by eriknikulski** [comment]
This works, thank you very much.
