### ISSUE TITLE
SVG file does not render when using flutter_driver integration test

### ISSUE THREAD

**Issue by mmcdon20** [dnfield/flutter_svg#234]
I created a sample project that demonstrates this: [https://github.com/mmcdon20/svg_test](https://github.com/mmcdon20/svg_test)

For some reason an svg file I was using renders fine when running the app normally, but when you use the flutter_driver integration testing [https://flutter.dev/docs/cookbook/testing/integration/introduction](https://flutter.dev/docs/cookbook/testing/integration/introduction) the svg does not render at all. 

I found that the svg file had unnecessary nesting of <g><g></g></g> tags, and after removing the unnecessary tags, the file rendered both when running the app normally and when running in integration testing. However when I tried adding unnecessary <g> tags to other svg files I could not get them to break during integration testing, so I'm not sure what specifically causes the error.

**Comment by dnfield** [comment]
This is probably some timing issue...  Something isn't waiting long enough.  I'm not sure where the fix for it should be off the top of my head though.

**Comment by mmcdon20** [comment]
I think you may be right about it being a timing issue. I tried running the same code on another computer, and ended up getting different results. This time neither the original SVG nor the modified SVG rendered during integration tests.

**Comment by srix55** [comment]
Same issue. The svg isn't getting rendered at all while using integration_test screenshots. Not throwing any errors... it just stays there... i tried 5 minutes delays too. Nothing shown. Since I am using a future builder to get the svg from assets, it just never goes to snapshot.hasData.

**Comment by srix55** [comment]
Ok... It's just a timing issue, as you said @dnfield . The integration test needed an extra pump to render the svg. I think this issue should be closed.
