### ISSUE TITLE
Mask is not applied

### ISSUE THREAD

**Issue by liri2006** [dnfield/flutter_svg#235]
I have a svg:
```
<svg width="57" height="60" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <path id="a" d="M.075.045h13.776V11.7H.075z"/>
    <path id="c" d="M0 .086h30.726v4.56H0z"/>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <g transform="translate(8.4 48.214)">
      <mask id="b" fill="#fff">
        <use xlink:href="#a"/>
      </mask>
      <path d="M10.806 11.7H3.12A3.045 3.045 0 01.075 8.655V.045h13.776v8.61a3.045 3.045 0 01-3.045 3.045" fill="#D8D8D8" mask="url(#b)"/>
    </g>
    <path d="M0 4.86l6.055 41.335a2.414 2.414 0 002.388 2.065h13.84a2.414 2.414 0 002.388-2.065L30.726 4.86H0z" fill="#F4F3F4"/>
    <g transform="translate(0 .214)">
      <mask id="d" fill="#fff">
        <use xlink:href="#c"/>
      </mask>
      <path fill="#D8D8D8" mask="url(#d)" d="M30.726 1.595l-3.84-1.51-3.84 1.51-3.84-1.51-3.842 1.51-3.84-1.51-3.841 1.51L3.84.085 0 1.596v3.051h30.726z"/>
    </g>
    <path d="M8.475 55.284v-1.211h4.117a2.77 2.77 0 115.542 0h4.117v1.211H8.475z" fill="#F4F3F4"/>
    <path d="M22.613 30.107c0 9.24 7.49 16.73 16.729 16.73 9.239 0 16.728-7.49 16.728-16.73 0-9.239-7.49-16.729-16.728-16.729-9.24 0-16.73 7.49-16.73 16.73" fill="#FF737E" opacity=".12"/>
    <path d="M18.005 30.107c0 9.24 7.49 16.73 16.729 16.73 9.239 0 16.729-7.49 16.729-16.73 0-9.239-7.49-16.729-16.73-16.729-9.238 0-16.728 7.49-16.728 16.73" fill="#FF737E" opacity=".2"/>
    <path d="M13.397 30.107c0 9.24 7.49 16.73 16.729 16.73 9.239 0 16.73-7.49 16.73-16.73 0-9.239-7.491-16.729-16.73-16.729-9.24 0-16.729 7.49-16.729 16.73" fill="#FF737E"/>
    <path d="M29.376 30.857h-7.051a.75.75 0 110-1.5h7.051v-7.051a.75.75 0 111.5 0v7.051h7.051a.75.75 0 110 1.5h-7.051v7.051a.75.75 0 11-1.5 0v-7.05z" fill="#FFF" fill-rule="nonzero"/>
  </g>
</svg>
```
Which should be displayed like this:
![image](https://user-images.githubusercontent.com/2411723/66204112-641d9580-e6aa-11e9-97b0-5f8623ba798b.png)

But masks are not applied and it looks like this:
![image](https://user-images.githubusercontent.com/2411723/66204153-7992bf80-e6aa-11e9-867d-31681f3ed24c.png)

**Comment by dnfield** [comment]
This appears to be fixed in v0.14.4 - please comment if that's not the case.  That one specifically fixed bus where masks weren't being applied properly to groups (this is just a different manifestation of that AFAICT).

**Comment by liri2006** [comment]
Hi, thanx for taking a time to look into this issue. Unfortunately issue still persists even after upgrade to v0.14.4.

[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)

**Comment by dnfield** [comment]
I'll try again - last night it looked like it was rendering to me

**Comment by dnfield** [comment]
I'm not able to reproduce this locally anymore after 0.14.4 :(

Are you sure you're working with v0.14.4 and the SVG pasted in the first comment?  I'm testing on an Android emulator, and ran it on both master and beta on Android.

**Comment by liri2006** [comment]
Sorry, my bad, it is showing up correctly. 
Thanx a lot for all the work you've put into this lib. It is one of the most useful libs for flutter out there!
