### ISSUE TITLE
Failed assertion: line 122 pos 10: 'params.length == 6': is not true.

### ISSUE THREAD

**Issue by fengzhisheng** [dnfield/flutter_svg#237]

**Comment by fengzhisheng** [comment]
![image](https://user-images.githubusercontent.com/20789580/66726495-50bdb780-ee6c-11e9-99d8-a13125892bce.png)
![image](https://user-images.githubusercontent.com/20789580/66726587-d04b8680-ee6c-11e9-91f0-f5d5843b6f6b.png)

**Comment by dnfield** [comment]
This should have a trim on it.  You can work around it by removing the trailing space

**Comment by dnfield** [comment]
This is fixed on master now.
