### ISSUE TITLE
Find SvgPicture in a test

### ISSUE THREAD

**Issue by vanlooverenkoen** [dnfield/flutter_svg#242]
How can we find a specific svg picture in a test?

This does not work.

```
class FinderUtil {
  static Finder findSvgPicture(String assetName) {
  final finder = find.byElementPredicate((widget) {
  if (!(widget is SvgPicture)) return false;
  final svgPicture = widget as SvgPicture;
  if (!(svgPicture.pictureProvider is ExactAssetPicture)) return false;
  final assetPicture = svgPicture.pictureProvider as ExactAssetPicture;
  return assetPicture.assetName == assetName;
  });
  return finder;
  }
}
```

**Comment by dnfield** [comment]
SvgPicture isn't an Element, it's a Widget.  

There's no custom/special elements in use in this library, so this is probably not a good way to find what you're looking for in general.  You could try searching the render tree instead, but you'd really be better off just keying your widgets.

For SVG tests, you probably also just want to do some kind of golden test anyway.

**Comment by vanlooverenkoen** [comment]
I have done some golden tests before. But today I created a step-through test to make sure everything works perfectly. Sometimes a placed a GestureDetector around a svgpicture. But the GestureDetector is not unique Because there are over a dozen of GestureDetector widgets on 1 screen. Should I wrap every svgpicture with an extra widget to find that specific widget?

**Comment by dnfield** [comment]
You could give them keys to find them, but it really depends on what you're trying to test

**Comment by dnfield** [comment]
You could also find them by semantic label if you're giving them semantic labels (which you should normally).

**Comment by vanlooverenkoen** [comment]
Ah yeah oke thanks :) semantics labels it is
