### ISSUE TITLE
Drawing Animation Support

### ISSUE THREAD

**Issue by TannerYoung** [dnfield/flutter_svg#243]
Is there any support planned to animate the drawing of the svg? Something as simple as a percentage of the SVG paths to draw would allow use with an animation controller to give really nice effects.

**Comment by dnfield** [comment]
Not really.  I think it would be confusing to have animation support but not support SVG's native animation capabilities (which would basically require JavaScript and SMIL support).  But I'd be open to pull requests, or you might pursue a separate package that uses the parser etc. From this one
