### ISSUE TITLE
SvgPicture.network Adding border radius

### ISSUE THREAD

**Issue by anoop4real** [dnfield/flutter_svg#245]
Hi, 
I am using SvgPicture.network to get image from network. How can I add a border radius to it? I tried ClipRRect and also Container with BoxDecoration ... but both didnt quite work... do you have a sample?

**Comment by dnfield** [comment]
ClipRRect should definitely work.  Please update this with a reproduction and I'll reopen it - but local testing on my end shows that it works just fine, e.g.

```
ClipRRect(
        borderRadius: const BorderRadius.all(Radius.circular(500.0)),
        child: SvgPicture.string(
            '''<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
<rect x="1" y="1" width="100" height="100" fill="black" />
</svg>'''));
```

Netowrk SVG work equally well when I test it locally.
