### ISSUE TITLE
svg images Rendering issues 

### ISSUE THREAD

**Issue by undamatlamanikanta** [dnfield/flutter_svg#249]
The following UnimplementedError was thrown during paint():
UnimplementedError

User-created ancestor of the error-causing widget was:
SizedBox org-dartlang-app:///packages/flutter_svg/svg.dart:727:29

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/dart_sdk.js 3995:11    throw_
package:build_web_compilers/src/dev_compiler/dart_sdk.js 132301:17  drawPicture
package:flutter_svg/src/render_picture.dart 193:12                  paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/proxy_box.dart 2341:13                [_paintChildWithTransform]
package:flutter/src/rendering/proxy_box.dart 2355:17                paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/box.dart 2508:14                      defaultPaint
package:flutter/src/rendering/flex.dart 948:7                       paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src%5Cmaterial%5Cmaterial.dart 549:11               paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/object.dart 384:12                    pushLayer
package:flutter/src/rendering/proxy_box.dart 1755:14                paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/object.dart 384:12                    pushLayer
package:flutter/src/rendering/object.dart 456:7                     pushClipRRect
package:flutter/src/rendering/proxy_box.dart 1394:22                paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                    paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                 paint
package:flutter/src/rendering/object.dart 2211:7                    [_paintWithContext]
package:flutter/src/rendering/object.dart 135:10                    _repaintCompositedChild
package:flutter/src/rendering/object.dart 95:5                      repaintCompositedChild
package:flutter/src/rendering/object.dart 937:29                    flushPaint
package:flutter/src/rendering/binding.dart 346:19                   drawFrame
package:flutter/src/widgets/binding.dart 777:13                     drawFrame
package:flutter/src/rendering/binding.dart 283:5                    [_handlePersistentFrameCallback]
package:flutter/src%5Cscheduler%5Cbinding.dart 1043:15              [_invokeFrameCallback]
package:flutter/src%5Cscheduler%5Cbinding.dart 982:9                handleDrawFrame
package:flutter/src%5Cscheduler%5Cbinding.dart 898:5                [_handleDrawFrame]
package:build_web_compilers/src/dev_compiler/dart_sdk.js 159683:23  <fn>
package:build_web_compilers/src/dev_compiler/dart_sdk.js 42577:14   _rootRunUnary
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41888:14   runUnary
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41807:14   runUnaryGuarded
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41841:34   <fn>

The following RenderObject was being processed when the exception was fired: RenderPicture#3aa31:
creator: RawPicture ← SizedBox ← FittedBox ← SizedBox ← Semantics ← SvgPicture ← Column ←
DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#e8e79 ink renderer] ←
NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
parentData: <none> (can use size)
constraints: BoxConstraints(w=109.3, h=72.7)
size: Size(109.3, 72.7)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════

please help me as soon as possible

**Comment by dnfield** [comment]
Web is not really supported yet. See #173
