### ISSUE TITLE
Please add Recomended Export settings for Inkscape

### ISSUE THREAD

**Issue by georgikoemdzhiev** [dnfield/flutter_svg#251]
I am a Linux user and I don't have Adobe Illustrator installed, I use Inkscape. I would be great if the "README" file is updated to include exporting settings from **Inkscape** as well. Thanks

**Comment by dnfield** [comment]
I would be happy to accept a contribution on this.  Afaik the default settings are fine, except for sometimes creating def elements out of order.

**Comment by georgikoemdzhiev** [comment]
I am afraid I am not too knowledgeable in Inkscape myself. I just picked up the program and still figuring it out. I can, however, do a PR once I figure out export settings that work well

**Comment by dnfield** [comment]
I'm going to close this under the assumption that the default settings are in fact just fine :)
