### ISSUE TITLE
How about providing another optional native svg parser engine?

### ISSUE THREAD

**Issue by hanabi1224** [dnfield/flutter_svg#253]
Rust provides great [toolchain](https://github.com/kennytm/rust-ios-android) to easily build android / ios libraries, and dart provide ffi libary since version 2.6 to save MethodChannel communication to invoke native methods.

If you think this might be a good idea, I can probably help create a dart library that binds to rust [svg lib](https://crates.io/crates/svg) (parser part)

Please let me know your feedback and concerns

**Comment by dnfield** [comment]
It will not support tree shaking and won't work on some flutter platforms (web, fuchsia).  

It's also not clear what the lib would be responsible for.  Parsing? Drawing?  We can't give an ffi lib a canvas at this point.  Would it be faster?  Do you have benchmarks?

**Comment by hanabi1224** [comment]
@dnfield My idea is to have use it as a parser as an alternative to https://github.com/dnfield/dart_path_parsing  I can do some benchmark and update the thread later

**Comment by dnfield** [comment]
I had benchmarked that code against the C++ code from Skia to do it and found no meaningful difference.  I'd be happy to see  if that changes for the rust library - but it would have to be done in some optional way to make sure we can continue to support other platforms.

**Comment by dnfield** [comment]
I'm going to close this bug as not actionable.  If you want to submit a PR at some point to make this work I'd be happy to review it.
