### ISSUE TITLE
How to convert a SVG to a Uint8List?

### ISSUE THREAD

**Issue by ViniciusMesquita-O** [dnfield/flutter_svg#256]
Hi, 
I'm using the Maps API and to change the marker style I can use only PNG files or Bytes as Uint8List.
Searching in the documentation I didn't find any method to convert the Svg widget that I create to bytes... there's any way to do that? Any future implementation? 

Thank you.

**Comment by dnfield** [comment]
I believe you would want to either rasterize it to a png or just base64 encode the raw string.  Not really familiar with the maps API you mean - do you have documentation?

**Comment by ViniciusMesquita-O** [comment]
I need to use this [class](https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/BitmapDescriptor-class.html) to change the marker icon and I only have the function fromAssetImage(path/of/asset) or fromBytes(byteData)  to setup a new marker.
So, there's any way to convert the SVG to the second method?

**Comment by dnfield** [comment]
Something like:

```
import 'package:flutter_svg/flutter_svg.dart';
final String rawSvg = '''<svg viewBox="...">...</svg>''';
final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);

// If you only want the final Picture output, just use
final Picture picture = svgRoot.toPicture();
final Image image = await picture.toImage();
final ByteData data = await image.toByteData(format: ImageByteDataFormat.png);
```
