### ISSUE TITLE
SVG Inside SingleChildScrollView smooth scrolling

### ISSUE THREAD

**Issue by Raggaer** [dnfield/flutter_svg#257]
Hello!

I am using a `SingleChildScrollView` as a parent for my `SvgPicture.network` widget, to be able to scroll horizontally (since its a big SVG that I am rendering). The scrolling its not very smooth (FPS dropping), does scrolling re-render the SVG image?

```
       SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
            color: Colors.white,
            child: SvgPicture.network(
              'https://respoe.xyz/passive-tree',
              semanticsLabel: 'Passive Tree',
              width: 900.0,
              placeholderBuilder: (BuildContext context) => Container(
                  padding: const EdgeInsets.all(30.0),
                  child: const CircularProgressIndicator()),
            ),
          ),
        ),
```

Maybe I could improve something here, I set a very big width so the image is 'zoomed' and its easier to see what is going on (again, its a big image and on smaller sizes its hard to see whats going on), you can check the SVG on the URL provided, It has a lot of nodes to render but renders fine without any FPS drop.

**Comment by dnfield** [comment]
You might want to wrap the `SvgPicture.network` in a `RepaintBoundary`.

**Comment by Raggaer** [comment]
@dnfield That worked fine, thank you
