### ISSUE TITLE
Render svg in a png image

### ISSUE THREAD

**Issue by MrGian** [dnfield/flutter_svg#259]
I'm trying trying to render the svg in a png image using this code:
```
File file = File(path);
file.createSync(recursive: true);
DrawableRoot root = await svg.fromSvgString(Values.svg, Values.svg);
ui.Picture picture = root.toPicture(clipToViewBox: true);
ui.Image image = await picture.toImage(4096, 4096);
ByteData data = await image.toByteData(format: ui.ImageByteFormat.png);
final buffer = data.buffer;
file.writeAsBytesSync(buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
```

But the the output image is a 4096x4096 image with a very small rendered svg in the top left corner.
How I can make the rendered svg fill all the image?

**Comment by dnfield** [comment]
You need to pass the `size` parameter to `root.toPicture` as well.  Otherwise, it doesn't scale the canvas to that size and you end up with what you have right now.
