### ISSUE TITLE
<polyline> doesn't render correctly

### ISSUE THREAD

**Issue by Rockvole** [dnfield/flutter_svg#26]
This image does not look correct :
https://github.com/Rockvole/communikate20-kbml/blob/master/describing/images/finish.svg

It has an additional line - thanks.

**Comment by dnfield** [comment]
Ahh.  This is due to a bug in the `<polyline>` parsing - I'm forcing the path created from that to close, which I should only be doing for `<polygon>`s.

**Comment by dnfield** [comment]
Fixed in 112a92d

I'm in the middle of some text related work, if this is urgent for you I could probably do a patch release for it, let me know.  You could also try to just pull the package from that git commit

**Comment by Rockvole** [comment]
No rush, next release is good.

**Comment by dnfield** [comment]
Published in v0.5.0
