### ISSUE TITLE
Does SvgPicture.asset only support rendering a single color

### ISSUE THREAD

**Issue by zzdota** [dnfield/flutter_svg#260]
Does SvgPicture.asset only support rendering a single color?
My original image is colored, after using SvgPicture.asset, it becomes a single black;
Or my original image is a gradient color, after using SvgPicture.asset, it also becomes a single black

**Comment by dnfield** [comment]
Sounds like a bug.  Can you share the svg?

**Comment by zzdota** [comment]
My original image
[icon_svg.zip](https://github.com/dnfield/flutter_svg/files/3935915/icon_svg.zip)

The original image shows the effect as follows
![image](https://user-images.githubusercontent.com/16704305/70385178-af179a00-19c6-11ea-8888-bab339a22178.png)

code is as follows
![image](https://user-images.githubusercontent.com/16704305/70385190-e5551980-19c6-11ea-969d-f16d91b1a057.png)

Then the effect is displayed on the Android emulator as follows
![image](https://user-images.githubusercontent.com/16704305/70385198-13d2f480-19c7-11ea-9b6f-a076f3ae51f6.png)

**Comment by barak-innov** [comment]
Moreover, for me its not rendering Liniar gradient, when I export svg from
Figma.

בתאריך יום א׳, 8 בדצמ׳ 2019, 8:29, מאת zzdota ‏<notifications@github.com>:

**Comment by dnfield** [comment]
Your SVG uses a `style` element, which this library does not support (see #105)

@barak-innov - please open a new issue with a sample SVG that isn't working.
