### ISSUE TITLE
Debug baselines in SvgPicture

### ISSUE THREAD

**Issue by lazingor** [dnfield/flutter_svg#269]
Is it possible to get an `SvgPicture` to render its baseline for debugging purposes?

Background: as I understand it, svgs ultimately get rendered into a `RenderPicture` which extends `RenderBox`: see `lib/src/render_picture.dart`.
 When `debugPaintBaselinesEnabled = true;`, `RenderBox`es draw a nice green line through them to show the baseline. `SvgPicture` does not seem to do this however. Would it be possible to get this package to draw baselines as well? This would be very useful for sorting out alignment issues.

I'd be happy to try to implement if someone can point me in the right direction - I am new to Flutter. Presumably we just need to inherit the `debugPaintBaselines()` method from `RenderBox`:
https://api.flutter.dev/flutter/rendering/RenderBox/debugPaintBaselines.html

Thanks for a great package!

**Comment by lazingor** [comment]
Maybe the issue is that a baseline isn't defined. If not, that would be a handy feature to have!

**Comment by dnfield** [comment]
This is for text right?

I'm not quite clear on what it would mean for svg, but yes you'd want to override that method to achieve it

**Comment by lazingor** [comment]
Yeah that's right, it's about aligning with a text baseline. Overriding these worked -- thanks!
