### ISSUE TITLE
Expose underlying SVG properties

### ISSUE THREAD

**Issue by lazingor** [dnfield/flutter_svg#270]
Is there currently a way to access some of the attributes of the underlying SVG after it has been loaded as an `SvgPicture`? For example, can one access the width, height, viewBox and style attributes of the `<svg>` element?

**Comment by dnfield** [comment]
That would incurr extra memory usage.  

There's probably some way to do this as an optional thing, but in some cases the Drawable classes the parser produces don't map 1:1 to an svg element

**Comment by lazingor** [comment]
Thanks for the quick input. I found that adding an extra property containing `parserState.attributes` to the `_root` element in `svg` enabled me to get at the things I wanted.
