### ISSUE TITLE
Getting a bounding box from a <g>

### ISSUE THREAD

**Issue by lazingor** [dnfield/flutter_svg#272]
I saw some talk about custom rendering some `<g>` elements in an SVG, and talk about exposing IDs, in #79. I was wondering something which is presumably related: I have some `<g>` elements with an `id` attribute specified in my svg, and I would like to be able to get something like a bounding box for the elements contained within this `<g>`. Is there a way to get at this somehow? I don't mind digging into the code, but I'm struggling to find a good entry point for this.

Where in the code are the elements actually processed into coordinates?

**Comment by dnfield** [comment]
I think you're looking for the transform on DrawableGroup

**Comment by lazingor** [comment]
Thanks for that pointer. I'm still working on figuring out how it all hangs together, but a preliminary question: will the `style.transform property on the `DrawableGroup` be relative to the root `ViewBox`, or just to the group's parent (which might in turn have transforms)?

**Comment by nfjdu** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/43147143/230375177-8fd16f13-0c24-4b84-9f37-48a8f82e2a6a.png)

If I get render result like this, how could i take actual image sizes (minimal rect that fits image(bbox)), but not fitted box sizes ? Thanks
