### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by ngaurav** [dnfield/flutter_svg#275]
Right now the strokes and fills default to black.
If the constructor allows a boolean field for dark mode, then the default can have two values black and white.

Right now, I am using a temporary solution where in dark mode I just add `fill=#000000` in root `<g/>` element of SVG.

**Comment by dnfield** [comment]
This isn't really in line with the SVG spec.

It's also not clear what you would actually want here - why stop at default fill or stroke colors?  If we default them to white, for example, what do you do with all th eother colors in an SVG?

For a simple icon, assuming a transparent background, you can probably just use the `color` and `colorBlendMode` parameters to change the color of the strokes/fills.

**Comment by ngaurav** [comment]
I agree with you that use case is very limited.
Right now I am using SVG to render latex math. Most of SVGs are entirely black. But in some places I am using (red and blue) colors to focus on specific parts. Dark Mode will really help here, but I am able to achieve the same effect by manually injecting fillcolor in root.

Other colors can be inverted too similar to iOS accessibility "invert color" option.
But I guess some `colorBlendMode` does similar thing. Let me know if you are aware of the right `colorBlendMode`

**Comment by dnfield** [comment]
I don't think you can invert colors with a blend mode.

However, the invert colors on iOS should really be supported at the Flutter engine level rather than specific to this widget.

**Comment by ngaurav** [comment]
I found one satisfactory blend mode which does the job.
`color = Colors.white; colorBlendMode = BlendMode.Difference` 

This issue is resolved now.

**Comment by dnfield** [comment]
Actually if this could take the colorfilter.matrix parameter it would be easier.  That may be worth adding

**Comment by dnfield** [comment]
Although you could also just use the ColorFiltered widget to do that...

**Comment by ngaurav** [comment]
Yeah it is probably not that critical. Anyways I must admit, your response time to issues is amazing. Thank you.

**Comment by fotiDim** [comment]
I ended up doing something like that:
```
SvgPicture.asset(
  'assets/icon.svg',
  color: SchedulerBinding.instance.window.platformBrightness ==
      Brightness.dark ? Colors.white : Colors.black,
)
```

it would be nice to have something like:

```
SvgPicture.asset(
  'assets/icon.svg',
  color: Colors.black,
  darkThemeColor: Colors.white,
)
```
