### ISSUE TITLE
Clear pixellation in vector rendering in Flutter vs. Sketch (or other img editor)

### ISSUE THREAD

**Issue by shamilovtim** [dnfield/flutter_svg#284]
Here's a screen grab of an svg on Sketch:
<img width="74" alt="Screen Shot 2020-01-28 at 7 18 32 PM" src="https://user-images.githubusercontent.com/3495974/73317804-5e256480-4205-11ea-847d-3b44ae381604.png">

You can see the crisp lines on the path edges.

Here's a screen grab of that same svg displayed through flutter_svg:
<img width="27" alt="Screen Shot 2020-01-28 at 7 36 39 PM" src="https://user-images.githubusercontent.com/3495974/73317834-8745f500-4205-11ea-9bfb-6582b86be97c.png">

You can see clear pixellation on the edges of paths. Any idea what I'm doing wrong?

Here's the raw svg string:
```
<svg height="14" width="14" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd" transform="translate(-.000014)"><circle cx="7" cy="7" fill="#de9225" r="7"/><path d="m7 10.9999976c1.6562389 0 2.99998569-1.34374678 2.99998569-2.99999283s-1.34374679-4.99998808-2.99998569-4.99998808c-1.6562532 0-3 3.34374203-3 4.99998808s1.3437468 2.99999283 3 2.99999283z" fill="#fff" fill-rule="nonzero"/></g></svg>
```

**Comment by dnfield** [comment]
Are you rendering it to a raster image and scaling it somehow?

What's the Flutter code you used to produce this?

**Comment by shamilovtim** [comment]
Thanks for the fast response! 
Here's how I'm loading my svg in order to draw it on a Canvas in our fl_chart dependency. [Relevant PR.](https://github.com/imaNNeoFighT/fl_chart/pull/184)

```
Future<ui.Image> loadSvg() async {
    final String rawSvg =
        '<svg height="14" width="14" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd" transform="translate(-.000014)"><circle cx="7" cy="7" fill="#de9225" r="7"/><path d="m7 10.9999976c1.6562389 0 2.99998569-1.34374678 2.99998569-2.99999283s-1.34374679-4.99998808-2.99998569-4.99998808c-1.6562532 0-3 3.34374203-3 4.99998808s1.3437468 2.99999283 3 2.99999283z" fill="#fff" fill-rule="nonzero"/></g></svg>';

    final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);

    final ui.Picture picture = svgRoot.toPicture();
    return await picture.toImage(14, 14);
  }
```

**Comment by shamilovtim** [comment]
Is it the case where in the SVG pixels can be split but when it converts to an image a pixel can only be one color at a time?

**Comment by dnfield** [comment]
I would strongly recommend you do not make it into an image.  If you must, you should scale it up by at least the devicePixelRatio on the media query.

Why can't you just paint it on the canvas as a picture?

**Comment by dnfield** [comment]
You could apply a translate or transform first to place it

**Comment by shamilovtim** [comment]
Thanks for the tips!! I had to create a separate objective for Picture which includes both a Picture and a width and height. It's strange that Flutter doesn't offer these attributes at least optionally on the Picture object, they are highly useful. 

```dart
class SizedPicture {
  Picture picture;
  int width;
  int height;

  SizedPicture(this.picture, this.width, this.height);
}
```

Then I used that metadata to translate using save:
```dart
        if (line.pictureData != null) {
          final int imageWidth = line.pictureData.width;
          final int imageHeight = line.pictureData.height;
          final double centerX = imageWidth / 2;
          final double centerY = imageHeight / 2;
          final double xPosition = to.dx - centerX;
          final double yPosition = viewSize.height - bottomChartPadding - centerY;

          canvas.save();
          canvas.translate(xPosition, yPosition);
          canvas.drawPicture(line.pictureData.picture);
          canvas.restore();
        }
```

No pixellation!
<img width="346" alt="Screen Shot 2020-01-28 at 9 39 35 PM" src="https://user-images.githubusercontent.com/3495974/73323821-b2851000-4216-11ea-86b8-ec29ba9e90d8.png">
