### ISSUE TITLE
SVG with multiple colors

### ISSUE THREAD

**Issue by Lima21** [dnfield/flutter_svg#288]
Hi, I've a SVG that have multiple colors, it's possible to use this package and set two different colors to the same SVG?

Without color:
![image](https://user-images.githubusercontent.com/16529736/73600218-f17fd200-4544-11ea-9127-6da7415880d3.png)

After set color:
![image](https://user-images.githubusercontent.com/16529736/73600220-fe042a80-4544-11ea-8746-f5fe23541904.png)

**Comment by dnfield** [comment]
I think if you set the right color and blendmode it should work - probbably just color black, and maybe blend mode screen - you'd have to experiment a bit.

If not, you could wrap it with a ColorFilter widget, which would let you pass in a full matrix and change whatever channels you want more fine grained.

**Comment by Lima21** [comment]
Hi @dnfield 
I got this with the ColorFilter, thank you ;)
