### ISSUE TITLE
Support the <pattern> element

### ISSUE THREAD

**Issue by rahuldange09** [dnfield/flutter_svg#289]
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="273" width="298">
  <defs>
    <image id="1a54d514-63f6-47f8-a0f4-ed80dsdddsf04a" `

Are this type of images supported ?
And if how to  use them?

**Comment by dnfield** [comment]
Yes.

Please share an svg that fails to render.

**Comment by rahuldange09** [comment]
Here 
please have a look
https://easyupload.io/rcu2hb

**Comment by dnfield** [comment]
This SVG uses `<pattern>`, which is why it doesn't work.  It just so happens someone else asked me a very similar question yesterday.  I'm not sure when I'll have time to look more about this, but PRs are welcome to implement it.  Here's the relevant part of the spec and MDN:

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Patterns

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern

https://www.w3.org/TR/SVG11/pservers.html#Patterns

**Comment by dnfield** [comment]
FWIW, you can generally avoid using pattern elements in SVGs, particularly to display images, but there doesn't seem to be a good reason yet to not support this in flutter_svg.

**Comment by dnfield** [comment]
Here's an example SVG that should render correctly, pulled from MDN:
```svg
<svg viewBox="0 0 230 100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <pattern id="star" viewBox="0,0,10,10" width="10%" height="10%">
      <polygon points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"/>
    </pattern>
  </defs>

  <circle cx="50"  cy="50" r="50" fill="url(#star)"/>
  <circle cx="180" cy="50" r="40" fill="none" stroke-width="20" stroke="url(#star)"/>
</svg>
```

**Comment by rahuldange09** [comment]
> Here's an example SVG that should render correctly, pulled from MDN:
> 
> ```
> <svg viewBox="0 0 230 100" xmlns="http://www.w3.org/2000/svg">
>   <defs>
>     <pattern id="star" viewBox="0,0,10,10" width="10%" height="10%">
>       <polygon points="0,0 2,5 0,10 5,8 10,10 8,5 10,0 5,2"/>
>     </pattern>
>   </defs>
> 
>   <circle cx="50"  cy="50" r="50" fill="url(#star)"/>
>   <circle cx="180" cy="50" r="40" fill="none" stroke-width="20" stroke="url(#star)"/>
> </svg>
> ```
Oh I see.
So for now I need to convert them.

**Comment by klaes-ashford** [comment]
> FWIW, you can generally avoid using pattern elements in SVGs, particularly to display images, but there doesn't seem to be a good reason yet to not support this in flutter_svg.

@dnfield, I was trying to place an image covered to its viewbox, preserving aspect ratio. By default, it fits to the viewbox. I found this stackoverflow [link](https://stackoverflow.com/a/23241935/3150830), how to achieve the same. But since, pattern is not supported, can I achieve the same without using pattern and image tags only ?

code I am trying to render : -
```
<pattern id="a" height="100%" preserveAspectRatio="xMidYMid slice" viewBox="0 0 56 54" width="100%”>
<image viewBox="0 0 56 54" rx="2.194"  x="17" y="20" xlink:href="$base64" />
</pattern>
```

**Comment by gympro159** [comment]
I have a similar problem with svg network, so i cann't edit code of svg file. How to fix it? :(

**Comment by ali-raza-flutter** [comment]
Guys any update on this issue?

**Comment by thiagorobertodc** [comment]
same here. Probably switching to a PNG for now but would be good to have it fixed since SVG scales better.

**Comment by ali-raza-flutter** [comment]
I was only face this issue in two images in my whole project.
So I use [https://onlineconvertfree.com/complete/png-svg/](this) web site to convert those images from PNG to SVJ
Now they works perfectly and my code is also consists.

Leaving it here if some is also facing this issue and want a quick fix

**Comment by thiagorobertodc** [comment]
God bless you @ali-raza-flutter thanks a lot

**Comment by srivastavarnav** [comment]
any updates on this please?

**Comment by marcoberetta96** [comment]
any update?

**Comment by guigzp** [comment]
any news on this please?

**Comment by Pedanfer** [comment]
> I was only facing this issue in two images in my whole project.
> 
> So I use [this](https://onlineconvertfree.com/complete/png-svg/) website to convert those images from PNG to SVJ Now they work perfectly and my code is also consistent.
> 
> Leaving it here if someone is also facing this issue and want a quick fix

The problem I have with this is that the PNGs from Figma already have low quality for some reason, only the SVGs look crisp, but the problem surfaces with 30% of them so far, and moving the definitions hasn´t helped. So if I convert a blurry PNG I get a blurry SVG...

**Comment by Aryan1g** [comment]
Any Updates

**Comment by dnfield** [comment]
I'm working on a new release that will support this. Alternatively, vector_graphics supports this today.

**Comment by Navil** [comment]
Any Updates to this ?

**Comment by maheshwaran-p** [comment]
Hope this tool can help you all friends .

https://svg2widget.web.app/

wee can convert the svg file as a flutter widget by using this tool and it provides the way for  best use svg to the flutter developers . 
find out the sample project and performance metrics here .
https://github.com/maheshwaran-p/samplesvg

**Comment by phamquoctrongnta** [comment]
> @dnfield I have a similar problem with svg network, so I cann't edit code of svg file. How to fix it? :(

I have same issue...
Any update?

**Comment by sarbazx** [comment]
> Hope this tool can help you all friends .
> 
> https://svg2widget.web.app/
> 
> wee can convert the svg file as a flutter widget by using this tool and it provides the way for best use svg to the flutter developers . find out the sample project and performance metrics here . https://github.com/maheshwaran-p/samplesvg

the website does not work, it always gives widget for default candy svg, not the chosen svg

**Comment by ultrabor** [comment]
I have same issue...
Any update?
