### ISSUE TITLE
New to Flutter. How to display a network image in Flutter with cached_network_image and have an image from local imageAsset as placeholder?

### ISSUE THREAD

**Issue by R3ll36** [dnfield/flutter_svg#297]
child: Stack(
              children: <Widget>[
                ClipRRect(
                  borderRadius: BorderRadius.circular(20.0),
                  child: Image(
                    height: 200.0,
                    /* width: 280.0, */
                    width: MediaQuery.of(context).size.width * 0.80,
                    image: AssetImage(event.imagePath),
                    fit: BoxFit.cover,
                  ),
                ),
              ],
            ),

**Comment by dnfield** [comment]
This has nothing to do with this repo
