### ISSUE TITLE
svg.fromSvgString Hangs on Large Input String

### ISSUE THREAD

**Issue by cedarbob** [dnfield/flutter_svg#302]
The svg file is ~43k in size and contains image elements which reference ~12 small local png files.
[field_diagram.svg.txt](https://github.com/dnfield/flutter_svg/files/4272148/field_diagram.svg.txt)
![five_bottom](https://user-images.githubusercontent.com/30355407/75630214-b3fb7c80-5bb6-11ea-8bf8-c0c52eda1c15.png)
![five_top](https://user-images.githubusercontent.com/30355407/75630215-b4941300-5bb6-11ea-9c73-7a12229549ed.png)
![four_bottom](https://user-images.githubusercontent.com/30355407/75630216-b4941300-5bb6-11ea-904f-c6db0fda4b27.png)
![four_top](https://user-images.githubusercontent.com/30355407/75630217-b4941300-5bb6-11ea-82e1-93657fcc87f5.png)
![one_bottom](https://user-images.githubusercontent.com/30355407/75630218-b52ca980-5bb6-11ea-9197-c05d6cbe6fa4.png)
![one_top](https://user-images.githubusercontent.com/30355407/75630219-b52ca980-5bb6-11ea-9631-a0dd13bed330.png)
![three_bottom](https://user-images.githubusercontent.com/30355407/75630220-b52ca980-5bb6-11ea-9039-1f450bd8d1e9.png)
![three_top](https://user-images.githubusercontent.com/30355407/75630221-b52ca980-5bb6-11ea-891b-cb939a46c13f.png)
![two_bottom](https://user-images.githubusercontent.com/30355407/75630222-b52ca980-5bb6-11ea-8ba9-ede1a5d2eb59.png)
![two_top](https://user-images.githubusercontent.com/30355407/75630223-b5c54000-5bb6-11ea-9ebf-3092c6e9a896.png)
![zero_bottom](https://user-images.githubusercontent.com/30355407/75630224-b5c54000-5bb6-11ea-811c-2833c00b29ed.png)
![zero_top](https://user-images.githubusercontent.com/30355407/75630225-b5c54000-5bb6-11ea-8c9b-4f113e2f6382.png)

**Comment by cedarbob** [comment]
Problem appears to be with the image elements.  I'm using relative URIs (bare filenames) for the referenced images, and the images are in the same directory as the svg file.  All are in the project assets folder and I'm reading the svg file with rootBundle.loadString (all of the svg text appears to be read in).

**Comment by dnfield** [comment]
Images are expected to either be base64 encoded or network URLs right now 

https://github.com/dnfield/flutter_svg/blob/967cc5c3e89933c58b7ef140c23cc44ae294402e/lib/src/svg/parsers.dart#L212-L224

This probably isn't terribly hard to support, but it's painful to test and probably makes web support more complicated.

**Comment by dnfield** [comment]
I'm going to close this as infeasible.

Supporting local assets is really messy cross platform, and it will be slow. There are ways to preprocess your files to avoid this kind of issue.
