### ISSUE TITLE
Need an example of how to use precachePicture(...)

### ISSUE THREAD

**Issue by sharpsan** [dnfield/flutter_svg#309]
https://github.com/dnfield/flutter_svg/issues/239#issuecomment-544660440

You reference the method precachePicture() in multiple places under issues, but somehow never manage to show a single complete example.

It would be useful to see an example of how precaching SVGs would work.

**Comment by dnfield** [comment]
Isn't the comment you linked to an example?

I'd be happy to add one to the docs.  There's also an example in the tests: https://github.com/dnfield/flutter_svg/blob/a3515a3820c2f5984d13b08f78657818c82821ab/test/picture_cache_test.dart#L17
