### ISSUE TITLE
Svg won't render when color specified as 'currentColor'.

### ISSUE THREAD

**Issue by shinyford** [dnfield/flutter_svg#31]
Hi - the attached svg has been downloaded from https://feathericons.com/. It specifies the stroke as `stroke="currentColor"`, which apparently is a kind of web standard for the inherited color. (?)

If I remove both `fill` and `stroke` definitions, the svg is rendered with `fill` as whatever is passed in as the `color` field; but the stroke is neither defined nor used.

Would it be possible to get `stroke` to honour the `color` directive from the widget's config? Or (better still for me) `colors.dart` to recognise and correctly return the `currentColor` wherever it's used?

[home.svg.zip](https://github.com/dnfield/flutter_svg/files/2150917/home.svg.zip)

**Comment by dnfield** [comment]
CurrentColor isn't implemented yet.  I can look at it though

**Comment by shinyford** [comment]
Thanks - or just a way to get the `stroke` to take the `color` colour would be great.

**Comment by shinyford** [comment]
Ah! Just worked out that I can get the stroke to render and have the `color:` colorFilter applied just by changing the `stroke` attribute on the svg to a colour of an appropriate opacity. This request is therefore less urgent (for me). Many thanks!

**Comment by dnfield** [comment]
I see - currentColor was set as a top level attribute here.  Yes, in that case, you'd need to specify a color on the widget itself.

Even with that, I still have to implement `currentColor` in the parsing logic - it just hasn't been a priority yet.  I'll leave this open to track.

**Comment by harshmandan** [comment]
Is the issue solved yet?

**Comment by nietsmmar** [comment]
Not solved yet? For me this makes the plugin absolutely useless, as all the svg's I try to load over network have stroke="currentColor" :/

**Comment by basile-savouret** [comment]
@dnfield it would be great to have a workaround to pass a value to the svg `stroke` property. Currently, we need to set a static color to it.

**Comment by xepozz** [comment]
Any updates?

**Comment by dnfield** [comment]
Someone is working on this.
