### ISSUE TITLE
Keeping original color

### ISSUE THREAD

**Issue by dhust** [dnfield/flutter_svg#315]
The svg file I'm using has multiple colors, but when I add it it's black. I've tried color: null.

**Comment by dnfield** [comment]
Please include the SVG file and, ideally, how it renders in chrome vs this plugin.

**Comment by beiger** [comment]
[404.zip](https://github.com/dnfield/flutter_svg/files/4373008/404.zip)
this svg is all black

**Comment by dnfield** [comment]
@beiger - that's due to #105

**Comment by beiger** [comment]
Ok
thank you
