### ISSUE TITLE
SvgPicture.network() not passing through headers

### ISSUE THREAD

**Issue by javabada** [dnfield/flutter_svg#317]
Hey, looks like http headers aren't being passed through to the actual request.

Not sure how to unit test this however.

https://github.com/dnfield/flutter_svg/blob/35970c251899cf366084e9bb8eeea24a48b4fbe8/lib/src/picture_provider.dart#L507

**Comment by daniellampl** [comment]
The fix is still not in version 0.19.0

**Comment by dnfield** [comment]
Fixed as of v0.20.0-nullsafety.2
