### ISSUE TITLE
Could not instantiate image codec. on precacheImage

### ISSUE THREAD

**Issue by surpriso1997** [dnfield/flutter_svg#318]
here is my implementation:

        runApp(Builder(
          builder: (BuildContext context) {
            precacheImage(
              
                AssetImage('assets/images/music_background.svg'), context);

            return AppRoot();
          },
        ));

here is the error:

Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack
#0      _futurize  (dart:ui/painting.dart:4304:5)
#1      instantiateImageCodec  (dart:ui/painting.dart:1682:10)
#2      PaintingBinding.instantiateImageCodec 
package:flutter/…/painting/binding.dart:88
#3      AssetBundleImageProvider._loadAsync 
package:flutter/…/painting/image_provider.dart:487
<asynchronous suspension>

**Comment by dnfield** [comment]
You need to use precachePicture and AssetPicture

**Comment by surpriso1997** [comment]
Thanks, didn't know precahePicture fixed the error.
