### ISSUE TITLE
Large SVG won't draw, but shows in Android Studio, Inkscape, browsers, etc.

### ISSUE THREAD

**Issue by MomijiMatt** [dnfield/flutter_svg#321]
https://drive.google.com/file/d/1lt-bGwtEOrCN14i_KtGlC-lOU6bf6HtO/view?usp=sharing

This is the file I'm trying to display in the app. Other smaller SVG files do show correctly with the exact same code in Flutter, but once I try this one there is nothing.

I'm assuming that it is too big, so it's trying to scale it down, and when it scales down to fit the screen it just can't show anything because the strokes are smaller than the pixel density can handle.

I'd really appreciate any help because I need this for work. Thank you.

**Comment by dnfield** [comment]
This is due to #132 

I should probly add some meaningful error handling for this too - right now it will just fail strangely and silently.

**Comment by dnfield** [comment]
Closing this since it will now report an error - follow #132 for the underlying issue.

**Comment by MomijiMatt** [comment]
> Closing this since it will now report an error - follow #132 for the underlying issue.

Thank you for the quick response!
