### ISSUE TITLE
Exception caught by SVG: Failed to find definition for url

### ISSUE THREAD

**Issue by jorgevasquezang** [dnfield/flutter_svg#327]
I am getting the error `The following assertion was thrown in _getDefinitionPaint:
Failed to find definition for url(#pattern)` loading [this SVG ](https://github.com/dnfield/flutter_svg/files/4458950/4_2_3_1.txt)(please rename the txt to svg since that extention is not supported by github).
I read in another issue that the defs tag should be at the top, but mine are, I am not sure what else can it be.
Thanks!

**Comment by dnfield** [comment]
Duplicate of #289
