### ISSUE TITLE
depends on flutter_svg 0.17.4 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by youshutong2080** [dnfield/flutter_svg#328]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

this version of v0.17.4 unsupported flutter stable with v1.12.13+hotfix.9?

**Comment by dnfield** [comment]
You're using the wrong version of something. You may have needed a lower version of flutter_svg or a higher version of flutter.  The latest published version works with stable.
