### ISSUE TITLE
Svg icon not showing in release mode

### ISSUE THREAD

**Issue by 91priyansh** [dnfield/flutter_svg#334]
I have 3 svg icon in my flutter app. Svg icon showing perfectly in debug mode but not showing in release mode. I am loading icon from asset.

Output of flutter doctor-v
Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at E:\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • SM M305F • 3200a8924951464b • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by appycamper** [comment]
same issue here, showing up in debug but not in release. Any updates please?

**Comment by dnfield** [comment]
Please share a reproduction of this issue, including what platofrm(s) you're seeing it on.

**Comment by 91priyansh** [comment]
@sidrao2006 thanks for reply will try this solution

**Comment by dnfield** [comment]
Flut

**Comment by TxusBlack** [comment]
Still not working.

**Comment by dnfield** [comment]
Hm. I dunno what happened to my last comment there :)

@txusblack this issue never contained enough information to say what would be causing. Please feel free to open a new issue with reproduction steps.
