### ISSUE TITLE
Ability to save back into a file

### ISSUE THREAD

**Issue by zenkog** [dnfield/flutter_svg#335]
Hi in my project after I extracted Paths from SVG file using 
`svg.fromSvgString(svgString, ‘’);`
Then I need to modify one of Path using another color then I need to save the list of Paths in a File again. 

So do you have a plan / may I request your library to include writing back into SVG file?

Thank you

**Comment by dnfield** [comment]
This is not planned right now, and would be fairly complicated to implement, particularly since path objects are currently opaque in Flutter.
