### ISSUE TITLE
Filename thrown exception

### ISSUE THREAD

**Issue by JSBmanD** [dnfield/flutter_svg#338]
Steps:
1. Name your svg image "boiii" (3 i at the end)
2. Try to show your svg as widget
3. Error will be thrown:

`════════ Exception caught by SVG ═══════════════════════════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════`

Normal name "boi" is working correctly with that image.

**Comment by dnfield** [comment]
Please provide a link to a github project that reproduces this problem.

**Comment by JSBmanD** [comment]
Oh, it's working just in my project.
