### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by facundomedica** [dnfield/flutter_svg#34]
This SVG fails with the error in the title: https://www.flaticon.com/free-icon/argentina_323346

**Comment by dnfield** [comment]
Can you include your code?  I'm not seeing any errors in rendering this SVG (although I was loading it directly as a string using `SvgPicture.string` to test).

**Comment by facundomedica** [comment]
I tried one more time (in other widget) to send you the code and worked. Weird... Anyway, thanks for the quick response!

**Comment by dnfield** [comment]
Perhaps wasn't configured correctly, or had a network issue if you were trying to load it over network...

Or you just needed someone to look at it, that frequently fixes bugs ;)
