### ISSUE TITLE
How to display a specific part of an SVG Graphic

### ISSUE THREAD

**Issue by chrisDK1977** [dnfield/flutter_svg#346]
I want to put a couple of SVGs together (currently in a Stack) and than display only a part of it (sometimes even scaled) which than should be placed in Flutter as a normal widget without paddings:

![image](https://user-images.githubusercontent.com/49610365/81590736-94a17c80-93bb-11ea-8dda-04b5c8ec18eb.png)

It should be Possible to define the part which should be displayed somehow (coordinates and width like in CustomClipping-Rect, ...)
is this possible somehow... tried everything like CustomClippers, ... without the desired result...

**Comment by dnfield** [comment]
You'd want a custom clip and a translate.

But it would be much more performant to just have the parts you want as separate assets.

**Comment by chrisDK1977** [comment]
I have a complexe Avatar System (with a lot of different hair types, noeses, eyes, ... shirts, trousers, shoes... for 10 different poses... for male and female). So separate Assets would lead to 1000s of new SVG files.

When I use CustomClipper I have the problem that there is space on the left and on the right of it if I want a part in the middle (see https://stackoverflow.com/questions/61504403/flutter-clip-without-space-around-the-clipped-widget). 
Is there a solution / do you know any example?

**Comment by dnfield** [comment]
I'll reply on the StackOverflow question you linked. That's why I'm saying you also need a translate :)

**Comment by dnfield** [comment]
Answered on StackOverflow. Same caveats I mentioned there apply - these are non-trivial operations to perform. If that's just a core part of your application and you can accept a hit for that ok. But if not, you're going to be using more memory and CPU than if you just had the assets you wanted, or somehow pre-processed your SVGs into the shapes you wanted.
