### ISSUE TITLE
Jagged edges on iPhone device

### ISSUE THREAD

**Issue by itsJoKr** [dnfield/flutter_svg#349]
I've noticed that when rendering curved paths, the edges would get jagged.

![image](https://user-images.githubusercontent.com/11093480/82898476-b07b5580-9f59-11ea-80d1-62691054c66a.png) 

You can see outer circle has some hard edges. This will only happen on physical iOS devices (iOS simulator and Androids are fine). Here's the svg:

```
<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="clock_icon">
            <path d="M12,24 C18.6274,24 24,18.6274 24,12 C24,5.37258 18.6274,0 12,0 C5.37258,0 0,5.37258 0,12 C0,18.6274 5.37258,24 12,24 Z" id="Path" fill="#0080B2"></path>
            <circle id="Oval" fill="#D8D8D8" cx="11.5" cy="11.5" r="9.5"></circle>
        </g>
    </g>
</svg>
```

The circle element will not form these edges. But sometimes you need to use path for rounded shapes and cannot use circle, like

![image](https://user-images.githubusercontent.com/11093480/82899703-b7a36300-9f5b-11ea-9f94-82e79d0ae785.png)

**Comment by itsJoKr** [comment]
I realized this has nothing to do with this library and is actually fixed on dev channel. Closing it.

**Comment by kbokarius** [comment]
@itsJoKr I'm seeing the same thing. Which dev channel is this fixed on? Can you provide a link to the issue/commit please.

**Comment by itsJoKr** [comment]
@kbokarius dev channel of flutter.
`flutter channel dev` 
`flutter upgrade`
