### ISSUE TITLE
The method loadAsset isn't defined for the class svg

### ISSUE THREAD

**Issue by Salvatore-Giordano** [dnfield/flutter_svg#35]
Following the guide I can't manage to draw the svg on a canvas

**Comment by dnfield** [comment]
Sorry I missed this before - Can you show your code/pubspec?  It looks like you could be missing an import or using a stale version of the library/example.

**Comment by dnfield** [comment]
Going to close this - feel free to reopen if you're still having an issue and can produce a little more of code/pubspec/etc.

**Comment by unknownzebra** [comment]
@dnfield The following is listed on the README but doesn't seem to work.

`import 'package:flutter_svg/flutter_svg.dart';`
`final DrawableRoot svgRoot = await svg.loadAsset('assets/image.svg');`

It causes an error stating that the method "loadAsset" is not defined for the class "Svg".

**Comment by dnfield** [comment]
Ohhhh this is out of date.  Will fix.

**Comment by dnfield** [comment]
I've updated the readme with a more relevant example.  The previous version was for an older version of the code and just got out of date.
