### ISSUE TITLE
SvgPicture uses Alignment instead of AlignmentGeometry

### ISSUE THREAD

**Issue by long1eu** [dnfield/flutter_svg#350]
Right now the `alignment` parameter is marked as being of type `Alignment` instead of `AlignmentGeometry` to allow the use of AlignmentDirectional.

**Comment by long1eu** [comment]
A workaround is to resolve the alignment and the pass it to SvgPicture

`alignment.resolve(Directionality.of(context))`;

**Comment by dnfield** [comment]
Fixed in 987704606038bd864cfb4439475fed7ab356b539 which wille ventually be published as part of v0.18.1
