### ISSUE TITLE
SVG size major issue ?

### ISSUE THREAD

**Issue by EArminjon** [dnfield/flutter_svg#352]
Hello,

I try to give size to my svg and i found this issue : 

```dart
SvgPicture.network(
   "https://upload.wikimedia.org/wikipedia/commons/b/b0/Apple_Pay_logo.svg",
   fit: BoxFit.contain,
   width: 10,
   height: 100,
),
```

Height override width. Is constraints like maxWidth, maxHeight could be implemented ?

**Comment by BunnyMan1** [comment]
For constraints, you could wrap the the SVG in a `container`.

```
Container(
                margin: EdgeInsets.symmetric(horizontal: 32),
                constraints: BoxConstraints(maxHeight: 56),
                child: SvgPicture.asset(
                  LogoPath,
                  semanticsLabel: "Company Logo",
                  // Subtracting the margin on either sides
                  width: screenWidth - (32 * 2),
    ),
),
```
MaxHeight is used correctly and AspectRatio of the image is maintained too.

**Comment by dnfield** [comment]
I'm not sure what's wrong here - the code provided isn't enough to reproduce an issue,a nd it's not clear what the expected/actual behavior to me is. Please consider providing a full sample and a few more details on what isn't going as expected, and I'd be happy to reopen.
