### ISSUE TITLE
SVG renders with incorrect colors.

### ISSUE THREAD

**Issue by vasilich6107** [dnfield/flutter_svg#353]
I took this image https://gw.alipayobjects.com/zos/rmsportal/wZcnGqRDyhPOEYFcZDnb.svg

After loading into flutter app the center part and keyhole is black(while Android Studio and Chrome renders it correctly)

Screenshot:
<img width="399" alt="Screenshot 2020-05-28 at 14 59 04" src="https://user-images.githubusercontent.com/6721286/83138750-f1a76d00-a0f3-11ea-8a76-a29d22794b82.png">

**Comment by samuelgringgo** [comment]
I'm also encountered this problem. Some parts are black. 

flutter_svg: ^0.17.4

**Comment by sidhijakpat** [comment]
I have the same problem, the svg is colorfull, but shown black on flutter_svg.

in my case it due to style css on the svg, for example

```xml
<style type="text/css">
	.st0{fill:#FFFFFF;}
</style>

...

<polygon class="st0" points=" ... "/>
```

when I use inline, 

```xml
<polygon style="fill: #FFFFFF;" points=" ... "/>
```

it working fine,

maybe your problem is the same?
@samuelgringgo @vasilich6107

**Comment by vasilich6107** [comment]
@sidhijakpat thanks.
I fixed this from the first day by adjusting the svg internals)

**Comment by dnfield** [comment]
@sidhijakpat - your issue is that this library doesn't support CSS. There are no plans to do that.

@vasilich6107: your issue is because this library doesn't support filters yet - see #53

**Comment by sidhijakpat** [comment]
Hi @dnfield , 

yes no problem, 
I'm just stating the possible cause of the problem that we have face on our side.

Thank you for clarifying.
