### ISSUE TITLE
Using in bottom navigationbar

### ISSUE THREAD

**Issue by mehrdad-shokri** [dnfield/flutter_svg#357]
Hi, I intend to use this package to render custom icons in a bottom navigation. first of All each ``BottomNavigationBarItem`` requires an Icon, is there a way to use this package for that purpose?  
Also, would it handle size/color change animations?  Normal icons would smoothly animate color/size icons if a bottom tab is selected/deselected

**Comment by PiN73** [comment]
`BottomNavigationBarItem` class doesn't actually requires an `Icon`. You can pass it any `Widget`

**Comment by PiN73** [comment]
To change color when the item is selected, there are two options:

1) Pass also `activeIcon` with appropriate color to `BottomNavigationBarItem`

or

2) Pass `icon` with dynamic color:
```
icon: Builder(
  builder: (context) {
    return SvgPicture.asset(
      'my_icon.svg',
      color: IconTheme.of(context).color,
    );
  },
),
```

**Comment by dnfield** [comment]
Please consider providing a code example of what isn't working.

Currently, this doesn't appear to be a bug in this package or a feature request, and it's not very actionable. If more detail sare added I'm happy to reopen.
