### ISSUE TITLE
flutter_svg depends xml ^3.3.1

### ISSUE THREAD

**Issue by robertoalvesneto** [dnfield/flutter_svg#360]
I encountered a runtime error:
Because embrapaprototipo2 depends on flutter_svg ^0.17.4 which depends on xml ^3.3.1, xml ^3.3.1 is required.

So, because embrapaprototipo2 depends on xml ^4.1.0, version solving failed.
pub get failed (1; So, because embrapaprototipo2 depends on xml ^4.1.0, version solving failed.)

**Comment by dnfield** [comment]
Ahh I have to publish a new version. This is fixed on master
