### ISSUE TITLE
ERR: The current Flutter SDK version is 1.17.3 on pub.dev

### ISSUE THREAD

**Issue by tusharojha** [dnfield/flutter_svg#365]
Pub.dev has decreased the rating, more precisely the health because of outdated flutter SDK required. I recommend changing this because Its popularity shows several people need this flutter_svg repository including me. So, please fix it!

```dart
ERR: The current Flutter SDK version is 1.17.3.
 
 Because flutter_svg requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.
```

**Comment by enricobenedos** [comment]
I have the same error, without possibility to update `flutter_svg ` I cannot update also `xml ` library

**Comment by dnfield** [comment]
Pub.dev will catch up.  Anyone on version 1.18.0-6+ needs that version of flutter_svg. Anyone on earlier versions needs to stick with v0.17.4.

/Cc @csells - there's a lot of consternation around this, you may find it interesting

**Comment by filleduchaos** [comment]
I do understand the need for the breaking change, but the stable channel just got the 1.17 release last month (and will most likely not get any major updates for at least a couple of months more, per its quarterly release schedule). It seems a bit strange to have marked a package version that doesn't work with it as stable/the default version on Pub - in my opinion v0.18 should've been marked as `-dev`, but the chance for that's in the past. At the very least, a disclaimer/explanation at the top of the README until the stable channel is on 1.18+ would be nice.

**Comment by dnfield** [comment]
This package is used by customers who are on stable _and_ who are on dev (and beta for that matter). In particular, there are customers internally at Google using this package that need it to be compatible with what's on dev/master of Flutter.

I'm not opposed to marking a release like this as `-dev` in the future, although it's a bit of a maintenance burden to then remember to promote it (with no real changes except maybe a version constraint) to the non `-dev` postfix later.  I think a better option might be to just not publish it to pub when there are features incompatible with Flutter stable until stable has been released, and just have people who need the new change pull from git. That causes another set of headaches for users though, so I'm really not sure which is better.

These kinds of refactorings don't happen very often in Flutter, but when they do it does cause some pain. Sorry about that.

**Comment by dnfield** [comment]
I'm going to close this issue as something I can't fix - pub.dev will eventually just catch up and it will be obsolete.
