### ISSUE TITLE
Because MM_project depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by jazzbpn** [dnfield/flutter_svg#369]
Because MM_project depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.
pub get failed (1; Because MM_project depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.)
exit code 1

**Comment by dnfield** [comment]
See #368
