### ISSUE TITLE
Latest version not compatible with latest Flutter?

### ISSUE THREAD

**Issue by prsolucoes** [dnfield/flutter_svg#375]
Hi,

Im create a new project with latest flutter version and when i try put the dependency (flutter_svg: 0.18.0) i got this error:

```
pub get failed (1; Because flutter_elastic_sidebar depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.)
```

Thanks.

**Comment by jasxir** [comment]
It's actually the opposite.
The latest version of the library is not compatible with the current stable Flutter SDK.
You can use `flutter_svg: ^0.17.4`

**Comment by jasxir** [comment]
> Hi,
> 
> Im create a new project with latest flutter version and when i try put the dependency (flutter_svg: 0.18.0) i got this error:
> 
> ```
> pub get failed (1; Because flutter_elastic_sidebar depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.)
> ```
> 
> Thanks.

It's actually the opposite.
The latest version of the library targets the Flutter SDK beyond the current stable, you have to use the previous version of the library.
You can use `flutter_svg: ^0.17.4`

**Comment by sardapv** [comment]
thanks man .. @jasxir

**Comment by sardapv** [comment]
Somebody update documentation please..it lead me into this error

**Comment by dnfield** [comment]
I'm not sure what documentation to update for this. I'd be happy to review a PR that updates the readme in some sensible way, but my assumption is that the version constraints provided in pubspec.yaml should explain this.
