### ISSUE TITLE
Grainy/jagged rendering of SVG image

### ISSUE THREAD

**Issue by kbokarius** [dnfield/flutter_svg#376]
We're getting somewhat grainy image rendering for a particular set of images. Some images seem to be rendering just fine, while this set doesn't look as clean. The first screenshot shows what one of those SVGs looks like when previewed on MacOS, while the second screenshot shows the image rendered in the iOS app. We did run all of the SVGs through the SVG Cleaner tool, but that had no impact on the rendering. The SVG itself is in the .zip file. 

![Screen Shot 2020-07-07 at 8 06 40 PM](https://user-images.githubusercontent.com/9427317/86870517-65427f80-c08d-11ea-93e7-dbbfd6cf878a.png)

![Screen Shot 2020-07-07 at 8 05 46 PM](https://user-images.githubusercontent.com/9427317/86870466-4ba13800-c08d-11ea-8474-46c18cc3f0e3.png)

[white_1.svg.zip](https://github.com/dnfield/flutter_svg/files/4888200/white_1.svg.zip)

**Comment by dnfield** [comment]
This SVG is mostly just an image. The image is probably getting rendered at the wrong resolution, or is being scaled up or down, or maybe isn't getting anti-aliasing applied to it. A full reproduction would be helpful.

**Comment by kbokarius** [comment]
@dnfield what exactly do you mean by a full reproduction?

**Comment by dnfield** [comment]
I mean the complete code sample resulting in your screen shot.

Depending on what resolution you render this at and what other options are used, the rendering may come out differently.

**Comment by kbokarius** [comment]
@dnfield this is resolved. You were right in that the SVG had image data embedded in it.
