### ISSUE TITLE
Implement ImageIcon or add way to convert to image icon to support BottomNavigationBar coloring

### ISSUE THREAD

**Issue by lazylazyllama** [dnfield/flutter_svg#379]
The BottomNavigationBar applies colors to its icons only if they are Icons or ImageIcons.

So we need a way to convert a svg to a ImageIcon.

**Comment by dnfield** [comment]
Can you provide a code sample of what isn't working here? 

I don't think we can implement Icon/ImageIcon here, but there should be a way to make all of this work.

I'll be happy to re-open if more details are provided - for now closing as not actionable.
