### ISSUE TITLE
SvgPicture should expose clipBehavior

### ISSUE THREAD

**Issue by liyuqian** [dnfield/flutter_svg#384]
SvgPicture now exposes the fit parameter from FittedBox, but not clipBehavior.

The clipBehavior will be needed to properly clip the content. See https://github.com/flutter/flutter/issues/61755

Specifically, some Google apps (e.g., customer dream and customer money) use SvgPicture and they'll need the clipBehavior so we can roll the clip change into Google.

**Comment by liyuqian** [comment]
CC @dnfield

**Comment by dnfield** [comment]
Are you able to open a patch that exposes it? That should be fine.

**Comment by liyuqian** [comment]
Sure, I can write a patch. I guess that I'll also need to add some tests to this repo. Is there a CI test that I should pay attention to?

**Comment by dnfield** [comment]
You can probably add something to https://github.com/dnfield/flutter_svg/blob/master/test/widget_svg_test.dart
