### ISSUE TITLE
There is no way to use it in Flutter version 1.17.5?

### ISSUE THREAD

**Issue by CPstudy** [dnfield/flutter_svg#386]
Flutter version 1.17.5:
```The current Flutter SDK version is 1.17.5.```

Then change ```flutter_svg: ^0.17.4```:
```Because every version of flutter_test from sdk depends on xml 4.2.0 and flutter_svg >=0.13.0 <0.18.0 depends on xml ^3.3.1, flutter_test from sdk is incompatible with flutter_svg >=0.13.0 <0.18.0.```

According to https://github.com/dnfield/flutter_svg/issues/365, I will use Flutter version >= 1.18.0.
But, I want use stable version. Is there any way to use flutter_svg in 1.17.5?

**Comment by dnfield** [comment]
Upgrade to flutter_svg 0.18.x

**Comment by CPstudy** [comment]
flutter_svg 0.18.0 occur:

```
The current Flutter SDK version is 1.17.5.

Because [project_name] depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.
pub get failed (1; Because [project_name] depends on flutter_svg >=0.18.0 which requires Flutter SDK version >=1.18.0-6.0.pre <2.0.0, version solving failed.)
```

How can I solve this problem?

**Comment by dnfield** [comment]
Use flutter_svg 0.17.x with that version of flutter
