### ISSUE TITLE
SVG memory leak with PageView()

### ISSUE THREAD

**Issue by sobrienpdx** [dnfield/flutter_svg#388]
We use PageView() for swiping between cards with SVG images rendered using flutter_svg library.  If there are too many pages with SVG images, the app runs out of memory and results in a crash with no stack trace. The Flutter dev tools show no issues with memory but the Xcode debug navigator shows that with each swipe on PageView more memory is used.

Our SVGs consist of one medium resolution jpeg background image with some text on top. We can't get our SVG file size any lower without sacrificing user experience. Is there a way to do garbage collection on the SVGs that are not being currently rendered? What objects in flutter_svg are hidden memory consumers that I can do garbage collection on?

**Comment by dnfield** [comment]
SVGs automatically cache in the `PictureCache`. Until fairly recent versions of Flutter, they would not track the size of any embeded images. You may have better luck if you try on master.

If you need to evict them, you should use the eviction methods on `PictureProvider`. 

It's also generally not going to work very well to embed images at this point in an SVG. In particular, images will automatically decode at full resolution with no opportunity to scale them down. You should make sure any embedded images are the smallest possible resolution for your use case. In general, you will have a better time if you use the JPEGs outside of the SVG and just draw the SVG in a `Stack` over an `Image` widget.

**Comment by sobrienpdx** [comment]
@dnfield Thanks for the ideas. I ended up using ```PictureProvider.clearCache()``` if ```PictureProvider.cacheCount``` got too high. Works great and I don't see any performance impact unless the user scrolls backward a bunch (which my users usually won't do) and even then it's barely noticeable. Thanks for your help!

**Comment by dnfield** [comment]
Sounds like this is resolved.
