### ISSUE TITLE
Label g inside svg

### ISSUE THREAD

**Issue by IngMarFlo** [dnfield/flutter_svg#389]
Hi, i have a code that contain a label g whit a path label on it; with this structure the library fails. Can you help me?

My code is:
`<svg xmlns="http://www.w3.org/2000/svg" width="797.528" height="356.175" viewBox="0 0 797.528 356.175">
  <g id="svgGroup" stroke-linecap="round" fill-rule="evenodd" font-size="9pt" stroke="#000" stroke-width="0.25mm" fill="none" style="stroke:#000;stroke-width:0.25mm;fill:none">
    <path d="M150 0 L75 200 L225 200 Z" />
  </g>
</svg>`

**Comment by dnfield** [comment]
The error in the console should have been some help here - flutter_svg does not support `mm` or `pt` in dimensions or font sizes. And if you use a Stroke width of .25, the triangle is very very faint.
