### ISSUE TITLE
Issues with plugin after upgrading flutter

### ISSUE THREAD

**Issue by varuntribe** [dnfield/flutter_svg#398]
`../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {                          
                         ^^^^^^^^^^^^^^^^^^^                            
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {        
                                           ^^^^^^^^^^^^^^^^^^^          
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {                          
      ^                                                                 
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {        
               ^                                                        
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);                              
          ^^^^^^^^^^^^^^^^^^^                                           
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),                           
                             ^^^^^^^^^^^^^                              
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);  `

Not Sure what `flutter upgrade` did but after running that command, I can't compile the project anymore. Getting all sort of issues from the plugin :(

Is anyone else having the same issue?

**Comment by dnfield** [comment]
You need to use 0.18.0 on the latest Flutter stable.

**Comment by varuntribe** [comment]
> You need to use 0.18.0 on the latest Flutter stable.

Hi, I have 0.18.0 mentioned in pubspec.yaml but for some reason my pub cache has the older version. 

I even ran pub repair but it's still downloading 0.17.4, is there anything I can do to force it to use 0.18.0?

**Comment by varuntribe** [comment]
> You need to use 0.18.0 on the latest Flutter stable.

Okay `pub repair` worked. Thanks for lightning fast reply ha! Really appreciate it.
