### ISSUE TITLE
flutter_svg can not support flutter 1.20.0

### ISSUE THREAD

**Issue by a-href** [dnfield/flutter_svg#399]
When I upgraded my version of fluent to 1.20.0, the flutter_svg reported errors, as shown in the figure below.
Maybe the flutter_svg needs to support flutter 1.20.0

![image](https://user-images.githubusercontent.com/13159272/90233986-88f9a200-de51-11ea-824c-f1b194b28782.png)

**Comment by dnfield** [comment]
Use v0.18.0
