### ISSUE TITLE
Network  caching doesn't work

### ISSUE THREAD

**Issue by pro100svitlo** [dnfield/flutter_svg#400]
I am using `0.18.0` package version.

When I am using svg with proper internet connection - it works fine:
```dart
SvgPicture.network("someUrl.svg");
```

When I restarted app without internet connection - 
_Expected result_: the image would be shown from the cache.
_Fact result_: empty widget...

**Comment by dnfield** [comment]
I'm not quite sure what you mean by restart, but the cache definitely does not persist.

**Comment by dnfield** [comment]
Yes - but that behavior would be better to implement in a separate network caching package rather than flutter_svg.  There's plenty of implementation details that go into that that shouldn't have to be worked out here.

**Comment by rdcoder33** [comment]
> Yes - but that behavior would be better to implement in a separate network caching package rather than flutter_svg. There's plenty of implementation details that go into that that shouldn't have to be worked out here.

Yeah, but then it will be hard to use another package to cache images and `flutter_svg` to display SVG Images. I would like to request you to give [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager) a try. 

It will really nice if flutter_svg itself caches the images using flutter_cache_manager.

BTW Thanks for this amazing and only working SVG package.

**Comment by trevhud** [comment]
@dnfield any thoughts on how we might extend flutter_svg with a cache that persists?

**Comment by dnfield** [comment]
I would recommend building a package on top of flutter_svg that handles your caching needs. Network based caching gets highly application specific and has lots of knobs to turn - there's not a great reason to incorporate it into this library.

**Comment by trevhud** [comment]
Maybe we could change SvgPicture.network() to optionally take a client? That way we can pass in our own client that has interceptors or whatnot. Or maybe we could expose a Stream or Future so that users of the library can write an extension for SvgPicture that accesses it.
