### ISSUE TITLE
Color of SVG is always black

### ISSUE THREAD

**Issue by Hassanmsaid** [dnfield/flutter_svg#409]
Default color of SVG picture is always black until I change the color attribute, so how to use multi-colored SVGs with original colors?

**Comment by dnfield** [comment]
You are very likely running into #105

**Comment by Hassanmsaid** [comment]
The problem was with the SVG itself, I had to change the styling from Inline CSS to **Presentation Attributes** as mentioned in the [documentation](https://pub.dev/packages/flutter_svg)
