### ISSUE TITLE
"DiagnosticableMixin" not found

### ISSUE THREAD

**Issue by mahmud009** [dnfield/flutter_svg#413]
I'm having this error while trying to run the flutter app.

/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
/G:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'G:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 22s
Exception: Gradle task assembleDebug failed with exit code 1

My flutter version is :-
![image](https://user-images.githubusercontent.com/57699312/92158529-ddd77980-ee4d-11ea-8d15-88b068f7d498.png)

Here is my dependency list

logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.1
  html_unescape: 1.0.1+3
  provider: 4.1.3
  flutter_signin_button: 1.0.0
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.4.1
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.4+3
  validate: 1.7.0
  country_pickers: 1.3.0
  shared_preferences: 0.5.7+3
  firebase_messaging: 6.0.16
  firebase_analytics: 5.0.15
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.2+5
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.6.1+6
  flutter_range_slider: 1.4.0
  page_indicator: 0.3.0
  extended_image: 0.9.0
  intro_slider: 2.3.1
  url_launcher: 5.4.11
  firebase_core: 0.4.5
  firebase_auth: 0.16.1
  firestore_ui: 1.10.0
  flutter_webview_plugin: 0.3.11
  connectivity: 0.4.8+6
  random_string: 2.0.1
  google_maps_flutter: 0.5.28+1
  place_picker: 0.9.14
  cached_network_image: 2.2.0+1
  image_picker: 0.6.7+2
  fab_circular_menu: 1.0.0
  uuid: 2.1.0
  uni_links: 0.4.0
  flutter_staggered_grid_view: 0.3.0
  device_apps: 1.0.9
  auto_size_text: 2.1.0
  lazy_load_scrollview: 1.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: 0.10.11+1
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.5
  page_view_indicators: 1.3.1
  animated_text_kit: 2.2.0
  wave: 0.0.8
  http_auth: 0.2.9
  international_phone_input: 1.0.4
  pin_code_fields: 3.1.2
  cupertino_icons: 0.1.3
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.22+1
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: 2.1.0
  flutter_ticket_widget: 0.0.1
  custom_splash: 0.0.2
  apple_sign_in: ^0.1.0
  firebase_database: 3.1.6
  google_sign_in: 4.5.1
  event_bus: 1.1.1

**Comment by dnfield** [comment]
You need to either move to Flutter stable, or use flutter_svg 0.17.x

**Comment by mahmud009** [comment]
How can I move to flutter stable ?
I'm new in flutter.

**Comment by dnfield** [comment]
```
flutter upgrade
```

**Comment by mahmud009** [comment]
> ```
> flutter upgrade
> ```
> 
> 

Worked for me. Thanks.
