### ISSUE TITLE
Question: returning SVG as a canvas context

### ISSUE THREAD

**Issue by cassioseffrin** [dnfield/flutter_svg#420]
Hello guys, 

I am very grateful tor the efforts on this lib, It's really amazing lib. I am trying to get the SVG to work with another lib. https://pub.dev/packages/pdf.

The pdf lib has a class Shape,that can be used to render a Shape based on the context canvas. The canvas can use the same path of SVG. But as SVG can have multiples paths it's not easy to convert it.

My question is there is somehow to get the same output of Shape from flutter_svg?

Here is the Shape Class from pdf lib:
```
class Shape extends Widget {
  Shape(
    this.shape, {
    this.strokeColor,
    this.fillColor,
    this.width = 1.0,
    this.height = 1.0,
    this.fit = BoxFit.contain,
  })  : assert(width != null && width > 0.0),
        assert(height != null && height > 0.0),
        aspectRatio = height / width;

  final String shape;

  final PdfColor strokeColor;

  final PdfColor fillColor;

  final double width;

  final double height;

  final double aspectRatio;

  final BoxFit fit;

  @override
  void layout(Context context, BoxConstraints constraints,
      {bool parentUsesSize = false}) {
    final double w = constraints.hasBoundedWidth
        ? constraints.maxWidth
        : constraints.constrainWidth(width);
    final double h = constraints.hasBoundedHeight
        ? constraints.maxHeight
        : constraints.constrainHeight(height);

    final FittedSizes sizes =
        applyBoxFit(fit, PdfPoint(width, height), PdfPoint(w, h));
    box = PdfRect.fromPoints(PdfPoint.zero, sizes.destination);
  }

  @override
  void paint(Context context) {
    super.paint(context);

    final Matrix4 mat = Matrix4.identity();
    mat.translate(box.x, box.y + box.height);
    mat.scale(box.width / width, -box.height / height);
    context.canvas
      ..saveContext()
      ..setTransform(mat);

    if (fillColor != null) {
      context.canvas
        ..setFillColor(fillColor)
        ..drawShape(shape, stroke: false)
        ..fillPath();
    }

    if (strokeColor != null) {
      context.canvas
        ..setStrokeColor(strokeColor)
        ..drawShape(shape, stroke: true);
    }

    context.canvas.restoreContext();
  }
}
```

**Comment by dnfield** [comment]
I'm not really clear what you're trying to do. Why not just render the SVG to the same canvas without converting it to the Shape class?

**Comment by cassioseffrin** [comment]
Hi @dnfield ,

Here a question made in pdf library : https://github.com/DavBfr/dart_pdf/issues/289

The pdf library don't offers support for SVG, therefore the only way to do it is through they widget Shape. I don't understand so much about flutter canvas, so I have no success in make the converter. However seems like it can't be so difficult once both libraries in some way get the canvas to render the content. 

If you could give me your opinion. If this converter task will requires too much time (complex code)  I will be forced to work with ordinary pngs.
 
Thks in advance.

**Comment by dnfield** [comment]
I suspect that this would be super-nontrivial to do.

You would probably have better luck rasterizing your SVG to an image at the ppropriate resolution and just including it there as an image, which is already supported by the PDF library. 

The problem is going to be, a very simple SVG that is say just a path and a fill/stroke will be easy to handle. But as soon as you get into gradients, or transforms, or effects (which aren't even supported by this library yet), it's going to be a lot harder and some of it might not translate properly.

**Comment by cassioseffrin** [comment]
Indeed, in my real scenario I use another lib to generate svg from user touches signature, that will includes paths, circles, rects etc. So I will follow your advice and rasterise it to PNG to avoid headaches.

SVG is the holy gral of high quality graphics, but today I will surrender to my complex job. Of course all the learn I get will be used in the future.

Sorry for making a question in the issues, It's not an issue at all,  but I think it can help the community who intend to use those 2 amazing open source libs!

Thks @dnfield I have appreciated your help!
