### ISSUE TITLE
Document web support status

### ISSUE THREAD

**Issue by coupestartup** [dnfield/flutter_svg#428]
A couple of paragraphs about flutter_svg's support for the web would be helpful.

For example, the README could mention how to activate web support, what the known issues are, or what alternative approaches/packages are available.

**Comment by dnfield** [comment]
This is entirely reasonable. I'll try to get to this soon.

**Comment by bradcypert** [comment]
I'd definitely appreciate this too. I'm kinda new to Flutter, so I forgot to check for web support before installing. Started building things on top of this and suddenly my web version looked terrible xD.

Thanks for all you do @dnfield!

**Comment by franarolas** [comment]
@dnfield Any news on Flutter Web support?

**Comment by dnfield** [comment]
Right now, it's only properly supported if you use the Skia/CanvasKit backend. The HTML backend still has too many missing pieces.

**Comment by mikeesouth** [comment]
Any updates here? I was using flutter_svg 0.19.1 with flutter 1.25.x and SKIA. SVGs were rendered correctly on supported browsers. After upgrading to flutter 1.26.x (beta) and flutter_svg 0.20.0-nullsafety.2 the svgs are no longer showing on mobile browsers (tested on latest Chrome for Android and latest Safari on iPhone 12 Pro). But for desktop browsers it is working, any idea on what could be wrong?

**Comment by dnfield** [comment]
Web now has some more support for SVG as well on Flutter master.
