### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by rupamking1** [dnfield/flutter_svg#430]
The following assertion was thrown resolving a single-frame picture stream:
Unable to load asset: First/Pricing0.svg

When the exception was thrown, this was the stack
#0      PlatformAssetBundle.load 
package:flutter/…/services/asset_bundle.dart:225
<asynchronous suspension>
#1      AssetBundle.loadString 
package:flutter/…/services/asset_bundle.dart:68
#2      CachingAssetBundle.loadString.<anonymous closure> 
package:flutter/…/services/asset_bundle.dart:166
#3      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:291:23))
...
Picture provider: ExactAssetPicture(name: "First/Pricing0.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#1d168(), name: "First/Pricing0.svg", colorFilter: null)
════════════════════════════════════════════════════════════════════════════════

I checked 5 times web and android also, but still error.
please help me.

**Comment by rupamking1** [comment]
I think made for this dollar      id="$-5"    
I already tried in String.

**Comment by DevonJerothe** [comment]
make sure file is in you assets folder and declared in you pubspec.yaml.

**Comment by rupamking1** [comment]
I fixed it Thank you for answering me 😇.

**Comment by IDONTSUDO** [comment]
+++++ dont work

**Comment by rupamking1** [comment]
Its working

**Comment by Bes79** [comment]
Unable to load asset: Consortium.svg

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:224:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:27)
<asynchronous suspension>
#2      AssetBundlePictureProvider._loadAsync (package:flutter_svg/src/picture_provider.dart:462:25)
...
Picture provider: ExactAssetPicture(name: "Consortium.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#e22c9(), name: "Consortium.svg", colorFilter: null)

not working for me, please help

**Comment by Bes79** [comment]
sorry, i set wrong path

**Comment by Bes79** [comment]
must be 'assets/Consortium.svg'
