### ISSUE TITLE
SVG pictures are damaged in release mode using SKIA engine

### ISSUE THREAD

**Issue by alectogeek** [dnfield/flutter_svg#433]
As you may know, there is a shader compilation jank problem in Flutter apps. To handle this problem I had to turn off metal support in my flutter iOS project and use SKIA instead. 

Pictures look good in debug mode, but kinda damaged in release mode.
Examples:
1)
release:
![image](https://user-images.githubusercontent.com/18165303/96759518-757e3080-13d8-11eb-8002-c0344fd8f54a.png)

debug:
![image](https://user-images.githubusercontent.com/18165303/96759816-d1e15000-13d8-11eb-93b2-65cf1daa87d1.png)

2)
release:
![image](https://user-images.githubusercontent.com/18165303/96759583-8b8bf100-13d8-11eb-8d2f-70db3fb24a84.png)

debug:
![image](https://user-images.githubusercontent.com/18165303/96759937-f63d2c80-13d8-11eb-81cc-527f749ef0f5.png)

3)
release:
![image](https://user-images.githubusercontent.com/18165303/96759670-a8282900-13d8-11eb-983d-d37acff85a90.png)

debug:
![image](https://user-images.githubusercontent.com/18165303/96760045-1ec52680-13d9-11eb-98c9-58b26bc16fce.png)

**Comment by dnfield** [comment]
Running in OpenGL on macOS is no longer supported on stable Flutter. This is almost certainly a bug or regression in Skia, but at this point we're only working on fixing Metal related issues because that's all we're able to support upstream. 

See also: flutter/flutter#61045

**Comment by dnfield** [comment]
Also https://github.com/flutter/flutter/issues/60267

**Comment by alectogeek** [comment]
That is frustrating. Don't you know any workarounds regarding SVG pictures rendering?

**Comment by dnfield** [comment]
No -  in fact, you are likely to see this issue pop up in other ways unexpectedly if you continue to try to use the Open GL backend on iOS. I really get that this is frustrating though, and I'm sorry it's causing you difficulties. It may be worth weighing the value of upgrading Flutter vs. the value of a little more jank on Metal until 60267 is resolved.

**Comment by alectogeek** [comment]
Unfortunately, janks are too severe in my app. I cannot deploy to production with them. With SKIA the app works way better. 
Thank you for the information! Hope Flutter team will solve the problem asap
