### ISSUE TITLE
SVG shadow not showing in Android but showing in web

### ISSUE THREAD

**Issue by rupamking1** [dnfield/flutter_svg#439]
Please help me
SVG shadow not showing in Android but showing in web, how to fix it.

**Comment by dnfield** [comment]
Probably a duplicate of #53

**Comment by rupamking1** [comment]
please add shadow feature

**Comment by dnfield** [comment]
Feel free to thumbs up that bug - I'd like to get to it at some point, but it's a little complicated to properly support, and much easier to just "fake" it by drawing your own shadow using Flutter.

**Comment by rupamking1** [comment]
@dnfield Thanks this is a good idea. 👍

If you have free time in future please try to make SVG Shadow possible. 😇
