### ISSUE TITLE
Painting properties are not properly inherited from parent to child

### ISSUE THREAD

**Issue by wkornewald** [dnfield/flutter_svg#44]
In 0.5.1 the attached SVG is rendered correctly, but in 0.5.4 the lines are too thin.
![good-0 5 1](https://user-images.githubusercontent.com/134387/43827477-349c6522-9afa-11e8-90f9-2918bc254703.png)
![bad-0 5 4](https://user-images.githubusercontent.com/134387/43827478-34b8421a-9afa-11e8-9ee5-12f3d9d30d41.png)
[profile.zip](https://github.com/dnfield/flutter_svg/files/2269618/profile.zip)

**Comment by dnfield** [comment]
Ahh.  That release fixed a different issue where stroke and fill weren't inheriting certain properties, but now is breaking some other cases.

It's fixable.  I'll look at it today.  I'd say if 0.5.1 was working stick with it for now.

**Comment by dnfield** [comment]
I actually should have caught this - the Tiger SVG test rendered differently, but visually looked more or less OK ... oh well.  Fixing it.

**Comment by dnfield** [comment]
fixed in 7265289
