### ISSUE TITLE
I/flutter ( 1150): unhandled element filter; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#c5d67()

### ISSUE THREAD

**Issue by nolyoi** [dnfield/flutter_svg#442]
I'm getting this error in my debug console when loading an SVG. It takes a second or two to load after the initial page loads.

`I/flutter ( 1150): unhandled element filter; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#c5d67(), name: "assets/images/ski_create_profile.svg", colorFilter: null)`

The code I am running is very simple and is the following:

```
Container(
                alignment: Alignment.center,
                child: SvgPicture.asset('assets/images/ski_create_profile.svg'),
              ),
```

Anyone have some ideas on why this is taking so long to load and what exactly this error message means?

flutter_svg: ^0.19.1

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by dnfield** [comment]
This just means the `filter` element isn't supported - see #53
