### ISSUE TITLE
I'd like to make each drawable clickable and trigger an action when clicked, any guidance?

### ISSUE THREAD

**Issue by HBHXTRA** [dnfield/flutter_svg#457]
Any guidance how I could make each drawable or some of them clickable and trigger action based on that?

**Comment by HBHXTRA** [comment]
I tried a hack by making drawbacks extends custompainter but I’m blocked as I can’t clip the different elements and they ultimately stack on each other and therefore you detect only one top of the last element which is covering all the others.

Any idea how I could clip those properly to make sure each tap on the right element is detected or maybe other way to do this?

My goal is to be able to detect gesture on each element or group of elements like text and trigger actions on that

**Comment by dnfield** [comment]
This is not something I plan to support in this library. You're on the right track with just trying to use the drawable classes, and you can look at the widget implementation(s) in this library to get a sense of how to draw things correctly.
