### ISSUE TITLE
SvgPicture.network Generate UI jams

### ISSUE THREAD

**Issue by sunbx** [dnfield/flutter_svg#459]
hello
I used the SvgPicture.network method to load SVG over the network, but found that drawing SVG produced UI latches. Here's an example call you can experiment with
Of course, specify the URL of the SVG

```
SvgPicture.network(
                                            'https://avatars.dicebear.com/api/male/ak_dXusX5K7S1wgZ2N2t7PZax4ShZTmr8qr4G8div9oM9FrgTGSt.svg',
                                            fit:BoxFit.none,
                                            width: 36,
                                            height: 36,
                                            placeholderBuilder: (BuildContext context) => Container(
                                                padding: const EdgeInsets.all(30.0),
                                                child: const CircularProgressIndicator()),
                                          ),
```

**Comment by dnfield** [comment]
Does this only happen with network? If so, it'd be helpful to know what platform, but it's very likely an upstream bug in Flutter or Dart. I'm going to close this on that assumption, but if you have updates that might show otherwise I can reopen.

**Comment by sunbx** [comment]
I found this problem when I was debugging with iOS, you can use the above code, directly run the experiment, you will find that the delay is about a few seconds, I suspect it is caused by the load network is not placed in the child thread, you can have a look, thank you

**Comment by dnfield** [comment]
IOS has a bug around network connections occasionally blocking the UI. It may be resolved on master but probably not stable yet. It's a bug in dart.

**Comment by sunbx** [comment]
How can I solve it well?
Or just wait
This is the problematic video, and you can look at the phenomenon

[RPReplay_Final1606992917.MP4.zip](https://github.com/dnfield/flutter_svg/files/5635576/RPReplay_Final1606992917.MP4.zip)
