### ISSUE TITLE
skia svg

### ISSUE THREAD

**Issue by gedw99** [dnfield/flutter_svg#46]
https://github.com/google/skia/tree/master/experimental/svg/model

just thought it might be good to link here.
I was looking into the WASM skia support and found the SVG support :)

**Comment by dnfield** [comment]
Last I had checked this was incomplete - only some interfaces stubbed out, no parsing logic.  There are some C++ parsing libraries that could be used with it though.

However, the Flutter team had also decided that even if it was available at the engine level it likely wouldn't be included - there's an ongoing effort right now to reduce the binary size, and this is functionality that can be supported without adding that to Flutter's Skia build.

It'd be interesting to toy with, but the Dart path is a lot easier and doesn't have to add any unnecessary code for those who don't need it.

**Comment by gedw99** [comment]
ah good pint. I saw they trimmed the flutter size by a significant %.
Did not realise they are not exposing it.

ah well...

should close...
