### ISSUE TITLE
Feature Request: Compound Path

### ISSUE THREAD

**Issue by zenkog** [dnfield/flutter_svg#460]
I've been using this plugin and it is great! Thank you for this amazing plugin.

I have a suggestion because I need this in my app:

Can we have the way to compound paths?

Use case:
If we have an SVG that draws 3 different circles (3 different paths) like this:

![image](https://user-images.githubusercontent.com/38452853/100602967-83ac5e80-333f-11eb-98da-6463f41b5ece.png)

But we want to apply the gradient in a different way. We want the gradient to apply across all three circles as if they were one path. Like this:

![image](https://user-images.githubusercontent.com/38452853/100603244-c2421900-333f-11eb-8607-5eafb9d07dce.png)

So we need to combine (compound) the paths to become one path.
This is a feature in Adobe Illustrator (by pressing cmd+8 in mac or ctrl+8 in windows). 
I need to do this programmatically because the app downloads Artworks (as SVG files) and need to work on it in the app.

**Comment by dnfield** [comment]
I'm not really sure what you're asking for - it should be possible to create SVG(s) like you're suggesting and rendering them as you want, but that's not anything to do with this package specifically. If I'm missing something we can re-open.
