### ISSUE TITLE
feature: animated svg picture loader

### ISSUE THREAD

**Issue by nt4f04uNd** [dnfield/flutter_svg#462]
There was already similar issue, but it was closed by author #167

I would like to request a feature to have an animated switch between the placeholder and the svg itself. It could be inserted into the `SvgPicture` as properties we have in `AnimatedSwitcher`, or it could be standalone widget like `AnimatedSvgPicture`, but I doubt the latter might confuse developers.

**Comment by dnfield** [comment]
I'm not really clear on what the use case is here - it would help to provide some code that either does what you want or that isn't quite working.

I would probably lean towards having this kind of thing happen outside of this library though, rather than burying a lot more complexity related to network handling in it.

**Comment by nt4f04uNd** [comment]
@dnfield i'm talking about analogue of `FadeInImage` from flutter, but with slightly different syntax. Something like 
```dart
SvgPicuture.network(
   'someurl',
   duration: const Duration(milliseconds: 300),
   inCurve: Curves.easeOut,
   outCurve: Curves.easeIn,
   transitionBuilder: // .....
)
```
Of course I can do this without changing your library, but why not to have this to simplify the process? Feel free to close if you think this is redundant.

**Comment by dnfield** [comment]
As I said, I'm pretty hesitant to add more network related functionality to this library - it makes things that much harder to get working for web, and it's not really core to this library's functionality.

Instead, I think it would probably be better to just have a package dedicated to doing animations once network loading is done, and allow that network data to be fed into other libraries like this one (or the image widget). Does that make sense?

**Comment by nt4f04uNd** [comment]
@dnfield yep, I got you, definitely makes sense
