### ISSUE TITLE
Problem with headers for SVGPicture.network

### ISSUE THREAD

**Issue by henrikvedal** [dnfield/flutter_svg#464]
When using the header to set cookies for SVGPicture.network i get HttpException (HttpException: Could not get network asset, uri = https://....);

The code im running:
SvgPicture.network(
"${Provider.of<AuthenticationService>(context).cookieJar.host}${_hazards.symbolUrl}",
                    headers: {
                      'Accept': 'application/json',
                      'Cookie': Provider.of<AuthenticationService>(context) .cookieJar.getCookieString(),
                    },
                  ),

When checking the httpGet that it tries to run, it doesn't seem like the header is getting inserted into the request.  Currently I have wrapped SVGPicture.memory inside a future that does the GET request for me and i'm able to revive the SVG data. So there is no problem with the URL and the header.

**Comment by dnfield** [comment]
This was very recently fixed, but on a version that requires a fairly new version of flutter.  See #342
