### ISSUE TITLE
Not supported by the latest version of flutter

### ISSUE THREAD

**Issue by mulieli** [dnfield/flutter_svg#468]
![image](https://user-images.githubusercontent.com/24307960/102854577-c30d2d00-445d-11eb-9cbb-94298ea6ae3d.png)

Please update to a supported version as soon as possible

**Comment by dnfield** [comment]
You need to use an earlier version of flutter_svg. You're trying to use one that should have been marked as a pre-release but wasn't. Try the 0.18.x version.
