### ISSUE TITLE
Let the plugin pick the colour code from the SVG file.

### ISSUE THREAD

**Issue by wamaeb** [dnfield/flutter_svg#470]

**Comment by dnfield** [comment]
I'm not sure what this means. Please feel free to elaborate.

**Comment by Wamae** [comment]
@dnfield I had noticed that the plugin did not pick the colour specified in the SVG. I had to manually set the colour in in flutter.

**Comment by dnfield** [comment]
Please share an example of an SVG that is not rendering correctly.
