### ISSUE TITLE
flutter_svg  0.19.2+1  no install to flutter 1.22.5 ,

### ISSUE THREAD

**Issue by au-top** [dnfield/flutter_svg#475]
flutter_svg in  pub.dev  install page tips use flutter_svg   0.19.2+1 version   , 
but flutter_svg   0.19.2+1   is use Higher per version  , no use flutter stable  version  ,
Should I add a pair of flitters_ The installation version of stable prompt, rather than developers need to manually adjust the flutter_ Svg version, preview version is not the first choice for development .

**Comment by wesleytoshio** [comment]
same here

**Comment by Blast06** [comment]
Did you find a solution to this?

**Comment by putrautama007** [comment]
current release sdk version is 1.22.5 but flutter_svg using sdk version 1.24.0-6.0.pre 
the solution is downgrade the flutter_svg version to 0.19.0 or change to Dev Channel to upgrade to sdk version 1.24.0-6.0.pre

**Comment by au-top** [comment]
use  0.19.1

dependencies:
  flutter_svg: ^0.19.1

**Comment by Smarpit-Singh** [comment]
Use can use `flutter_svg: ^0.19.0`

**Comment by flakerimi** [comment]
using  1.22.6. doesn't work.

flutter_svg: ^0.19.2+1

**Comment by dnfield** [comment]
You need to make sure to observe the SDK constraints on the flutter_svg package -they're generally set correctly, although only using a lower bound. I know this is a source of confusion, but there's not a ton I can doa bout this (except being more vigilant about publishing packages not marked as -dev or whatever to pub).
