### ISSUE TITLE
Clear answser

### ISSUE THREAD

**Issue by rupamking1** [dnfield/flutter_svg#478]
Please tell me you want to add shadow feature in your package or not?  Pls, answer me in one word.

**Comment by dnfield** [comment]
Duplicate #53 

I've started working on this feature a couple times. The main problem is the complexity of it. The way it's written in the spec, there are many many complex and inefficient possibilities. I've tried a couple times to get it down to something that would be reasonably performant but still support common use cases. 

In all honesty, I have other work that is higher priority than this. If there was a good patch for it I would consider it, but this is going to be a relatively difficult feature to implement. I have an idea for something that could work outside of SVG that might be a bit more doable, mentioned that in the linked bug.

So in a word: yes, I do. But it's not trivial :)
