### ISSUE TITLE
Superclass has no method named 'debugFillProperties

### ISSUE THREAD

**Issue by Yoda-Man** [dnfield/flutter_svg#480]
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
 lib\main.dart
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by dnfield** [comment]
You likely need a newer version of flutter_svg.

It'd help to know the version of flutter_svg you are using and the version of flutter.

**Comment by dnfield** [comment]
Ah, I can see it's 0.17.4 from the logs there for SVG. 

It's very likely you just need to upgrade that to either 0.19 or 0.20 release, depending on which Flutter version you are on.

**Comment by Yoda-Man** [comment]
I ran the command flutter --version and got the following output

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by Yoda-Man** [comment]
I ran the command **flutter pub deps** to determine which package depends on SVG 0.17.4 and got the following output.
Is it correct to assume  should try use a different PDF viewer?

|-- pdf_viewer_jk 1.1.1
|   |-- flutter...
|   |-- flutter_advanced_networkimage 0.7.0
|   |   |-- flutter...
|   |   |-- flutter_svg 0.17.4
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   |-- path_drawing 0.4.1+1
|   |   |   |   |-- flutter...
|   |   |   |   |-- meta...
|   |   |   |   |-- path_parsing 0.1.4
|   |   |   |   |   |-- meta...
|   |   |   |   |   '-- vector_math...
|   |   |   |   '-- vector_math...
|   |   |   |-- vector_math...
|   |   |   '-- xml 3.7.0
|   |   |       |-- collection...
|   |   |       |-- convert...
|   |   |       |-- meta...
|   |   |       '-- petitparser 3.1.0
|   |   |           '-- meta...
|   |   |-- http...
|   |   |-- path...
|   |   '-- path_provider...
|   |-- flutter_cache_manager 1.4.2
|   |   |-- clock...
|   |   |-- file 5.2.1
|   |   |   |-- intl...
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- flutter...
|   |   |-- http...
|   |   |-- path...
|   |   |-- path_provider...
|   |   |-- pedantic...
|   |   |-- rxdart 0.24.1
|   |   |-- sqflite 1.3.2+1
|   |   |   |-- flutter...
|   |   |   |-- path...
|   |   |   '-- sqflite_common 1.0.2+1
|   |   |       |-- meta...
|   |   |       |-- path...
|   |   |       '-- synchronized 2.2.0+2
|   |   '-- uuid 2.2.2
|   |       |-- convert 2.1.1
|   |       |   |-- charcode...
|   |       |   '-- typed_data...
|   |       '-- crypto 2.1.5
|   |           |-- collection...
|   |           |-- convert...
|   |           '-- typed_data...
|   |-- numberpicker 1.3.0
|   |   |-- flutter...
|   |   '-- infinite_listview 1.0.1+1
|   |       '-- flutter...
|   '-- path_provider...

**Comment by Yoda-Man** [comment]
I solved the issue by using another PDF Viewer  called advance_pdf_viewer:
