### ISSUE TITLE
SVG renders in black and color attribute doesn't work

### ISSUE THREAD

**Issue by neoacevedo** [dnfield/flutter_svg#481]
Hi,

This package works good, but when I'm rendering a SVG image being in light gray color, the image is rendered in black color and when I set the attribute color to any other color, it simply doesn't work.

The original image (A pic from the phone camera):
![imagen](https://user-images.githubusercontent.com/438372/106055146-fffebc00-60ba-11eb-94c4-dce0e158ac24.png)

The rendered SVG:
![imagen](https://user-images.githubusercontent.com/438372/106055083-e8bfce80-60ba-11eb-9d17-4b03e02f8637.png)

**Comment by dnfield** [comment]
Please share a code sample that reproduces this and I will reopen.

**Comment by neoacevedo** [comment]
I had to stop debug and start it again. It seems doesn't update in Hot Reload.
