### ISSUE TITLE
some svg pics shows not normal in iOS14

### ISSUE THREAD

**Issue by XinleZhou2018** [dnfield/flutter_svg#485]
I am using flutter_svg 0.17.4

<img width="441" alt="11111111" src="https://user-images.githubusercontent.com/39542071/106873040-fd314600-670e-11eb-8036-c59eb7e00972.png">
<img width="375" alt="2222222222" src="https://user-images.githubusercontent.com/39542071/106873054-028e9080-670f-11eb-8727-b56c612f96ee.png">

you can see the 2rd pic shows not normal in ios14, but it shows normal in ios12.

**Comment by XinleZhou2018** [comment]
@dnfield  the version of flutter I am using is 1.12.13 hotfix5

**Comment by dnfield** [comment]
That's a fairly old version at this point. Can you try on the latest stable or beta?  What about master?

**Comment by dnfield** [comment]
This is almost certainly an issue with the OpenGL implmentation on that version of Flutter - I don't think this will show up in the metal versions. Going to close this as fixed upstream.
