### ISSUE TITLE
Pub.dev picture_provider.dart source != github source

### ISSUE THREAD

**Issue by giorgioborri** [dnfield/flutter_svg#492]
Hi,
a demo app used to understand flutter needed this package ,but the version downloaded from pub.dev have an issue on "picture_provider.dart" file, as reported in the attached image 
the code on github don't show the same code in that file !
the nullOk parameter give error on compiling with Flutter 1.26.0-17.5.pre

![Schermata 2021-02-19 alle 12 37 42](https://user-images.githubusercontent.com/64954086/108500310-de56b600-72af-11eb-9f02-c54a0b2253ef.png)

**Comment by dnfield** [comment]
You are likely looking at an older version from pub. Try looking at github for that tag.

**Comment by giorgioborri** [comment]
Hi
I've visited the versions page on pub.dev of this package and clicked on
download link. I've got the 0.19.2+1 version. then I checked the file from
the zip file with the same file on github and then I seen the difference.
Please try yourself


Il giorno ven 19 feb 2021 alle ore 16:26 Dan Field <notifications@github.com>
ha scritto:

**Comment by dnfield** [comment]
That should match https://github.com/dnfield/flutter_svg/blob/v0.19.2%2B1/lib/src/picture_provider.dart

**Comment by dnfield** [comment]
Closing this as resolved - you're looking at an older version than master on pub. Master currently reflects a preelase version on pub.
