### ISSUE TITLE
How to get aspect ratio before getting widget

### ISSUE THREAD

**Issue by sc00n** [dnfield/flutter_svg#496]
I am using the following code to show an SVG of a downloaded file.

```
    final Widget svg = SvgPicture.file(
      File(pathName),
        semanticsLabel: 'SVG IMAGE',
      placeholderBuilder: (BuildContext context) => Container(
          child: const CircularProgressIndicator()),
      width: width,
      height: height
    );
```

I however need to know the aspect ratio before I show the image. Is this possible? Can I for example read out the aspect ratio right after I download the file (but before I show it)?

Thanks!

**Comment by dnfield** [comment]
You can't do this using `SvgPicture` widgets, but you could do it if you just directly interact with the `DrawableRoot` class, e.g. 

```dart
    final PictureInfo info = await svg.svgPictureStringDecoder(
      await File(pathName).readAsString(),
      null,
      pathName,
    );
    print(info.size);
    final Widget widget = RawPicture(info);
```

**Comment by dnfield** [comment]
You would, of course, have to do your own implementation there of handling the asynchronicity

**Comment by sc00n** [comment]
Thanks  a lot!

After some adaptations from your code it worked: 

```
     String raw=file.readAsStringSync();
      final PictureInfo info = await svg.svgPictureStringDecoder(
        raw,
        false,
        null,
        mf.path,
      );
      Size temp=info.viewport.size;
      mf.aspectRatio=temp.width/temp.height;
```

**Comment by DarrylDJohnson** [comment]
For Flutter web, @sc00n's answer needs one slight change:

`String raw = (await HttpRequest.request(assetPath)).response;
`
This is because dart:io does not work on Flutter web. Instead dart:html must be used.

**Comment by sc00n** [comment]
With the new flutter_svg you can do it like this:

`      String rawSvg=file.readAsStringSync();
      final PictureInfo pictureInfo = await vg.loadPicture(SvgStringLoader(rawSvg), null);
      mf.aspectRatio = pictureInfo.size.width / pictureInfo.size.height;`
