### ISSUE TITLE
SVG  not rendering correctly

### ISSUE THREAD

**Issue by Auk513** [dnfield/flutter_svg#499]
flutter_svg: ^0.19.1
flutter: 1.22.6

svg: [home_default_avatar.svg.zip](https://github.com/dnfield/flutter_svg/files/6028120/home_default_avatar.svg.zip)

expected:
![image](https://user-images.githubusercontent.com/6188580/108827952-30297400-7601-11eb-93ac-47fdd4915562.png)
rendered:
![image](https://user-images.githubusercontent.com/6188580/108828023-459e9e00-7601-11eb-827f-86f78e5f09fc.png)

same thing happens on the following SVGs:
[icon_home_learning.svg.zip](https://github.com/dnfield/flutter_svg/files/6028135/icon_home_learning.svg.zip)
[icon_home_to_learn.svg.zip](https://github.com/dnfield/flutter_svg/files/6028137/icon_home_to_learn.svg.zip)
[icon_home_to_relearn.svg.zip](https://github.com/dnfield/flutter_svg/files/6028138/icon_home_to_relearn.svg.zip)

**Comment by dnfield** [comment]
This has multiple unsupported parts:

#102 
#289

**Comment by megahertzon** [comment]
close de app and restart works for me!!!
