### ISSUE TITLE
stroke-width and other attributes ignored when stroke not provided

### ISSUE THREAD

**Issue by wkornewald** [dnfield/flutter_svg#50]
In the attached image the circle is not rendered with the correct stroke width because the `parseStroke()` function returns early when stroke is not provided for the `<circle>` element (but it's already set on the `<g>` parent and thus should be inherited).

[showcase-cycle.zip](https://github.com/dnfield/flutter_svg/files/2323262/showcase-cycle.zip)

**Comment by wkornewald** [comment]
Oh I see you've already fixed it in master...

**Comment by dnfield** [comment]
I'll try to do a release for this before long.  I've been very busy with a move over the last few weeks but things will eventually settle down!
