### ISSUE TITLE
flutter 2.0

### ISSUE THREAD

**Issue by budisentosa** [dnfield/flutter_svg#504]
err on build
> Task :app:compileFlutterBuildDebug
/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^

**Comment by pansitwattana** [comment]
I upgraded pubspec.yaml flutter_svg to ^0.19.3 and it can build. I got crash on ^0.19.1

**Comment by dnfield** [comment]
Correct. You need a higher version of flutter svg
