### ISSUE TITLE
Outdate Dependency Causing Incompatible with Other Package

### ISSUE THREAD

**Issue by Ge2C** [dnfield/flutter_svg#505]
Because image >=3.0.1 depends on xml ^5.0.0 and image >=3.0.0-nullsafety.0 <3.0.1 depends on xml ^5.0.0-nullsafety.1, image >=3.0.0-nullsafety.0 requires xml ^5.0.0-nullsafety.1. 
And because flutter_svg >=0.18.1 <0.20.0-nullsafety.0 depends on xml ^4.2.0 and flutter_launcher_icons >=0.9.0 depends on image ^3.0.0-nullsafety.0, flutter_svg >=0.18.1 <0.20.0-nullsafety.0 is incompatible with flutter_launcher_icons >=0.9.0.
So, because retitest_app depends on both flutter_launcher_icons ^0.9.0 and flutter_svg ^0.19.3, version solving failed.

fluter SVG still using XML 4.2.0 that outdated not already version 5.0.0 this causing incompatibility

**Comment by thomasschwarzott** [comment]
The path_drawing dependency should also be updated, so that the package can be used with fl_chart:

Because fl_chart >=0.20.0-nullsafety1 depends on path_drawing ^0.5.0-nullsafety.0 and flutter_svg >=0.18.1 <0.20.0-nullsafety.0 depends on path_drawing ^0.4.1+1, fl_chart >=0.20.0-nullsafety1 is incompatible with flutter_svg >=0.18.1 <0.20.0-nullsafety.0.

**Comment by dnfield** [comment]
I understand that this is really frustrating, but I don't believe this is a bug in this library (or in path_drawing).

You're facing dependency resolution issues. You have two options:

- Make sure you're using a relatively recent version of flutter_svg. The errors being reported here are suggesting that you're using a relatively old version of flutter_svg with other newer packages.
- Try to find a set of dependencies that are compatible.
- use `dependency_overrides` to force compatibility. flutter_svg has had only minimal breaks between 0.19 and 0.20.
