### ISSUE TITLE
Svg not showing when Flutter for Web is built with html Web renderer

### ISSUE THREAD

**Issue by srdjan86** [dnfield/flutter_svg#509]
Hello,

I found an issue when building Flutter for Web with Web renderer set to auto ( `flutter build web` ). Accessing that website from mobile device leads to svg icons not being shown.

I think it has to do with web renderer set to html when accessing from mobile device. 

You can reproduce it locally by building web app with: `flutter run -d chrome --web-renderer html`

Version of Flutter: 2.0.1
Channel: Stable
Version of flutter_svg: 0.19.0

**Comment by dnfield** [comment]
Duplicate of #491
