### ISSUE TITLE
Support non-zero based viewBoxes (e.g. `viewBox="57 42 20 20"`)

### ISSUE THREAD

**Issue by artrmz** [dnfield/flutter_svg#51]
SVGs generated with [Gravit Designer](https://gravit.io) not rendering.

Sample SVG: 
[male.svg.zip](https://github.com/dnfield/flutter_svg/files/2332265/male.svg.zip)

**Comment by dnfield** [comment]
I don't think I'm handling this type of `viewBox` properly - I'm pretty sure the current implementation expects that the `viewBox`'s `x` and `y will be 0,0.

This is definitely a bug, but as a work around is it possible for you tell Gravit to use a 0,0 based viewBox?

**Comment by dnfield** [comment]
This isn't a very hard fix, but it probably won't come before #54, as some of the changes required for it could impact that.

**Comment by dnfield** [comment]
Fixed in e000b0f - this should end up getting published soon, but I want to figure out why Travis is having a hardtime with the goldens these days first.
