### ISSUE TITLE
Bad vertical padding

### ISSUE THREAD

**Issue by mamodo123** [dnfield/flutter_svg#516]
My code is simple: 
`Container(
                  color: Color(0xff123456),
                  child: SvgPicture.asset(Assets.IMAGE_LOGO_NAMED_SVG)),`
But it render my svg with a strange vertical border, that i'm pretty sure doens't exists in original svg

![Screenshot from 2021-03-13 09-45-49](https://user-images.githubusercontent.com/47646223/111030421-ec947f80-83e0-11eb-9fc1-cb16f1510b93.png)

![logo_semfundo_escrita](https://user-images.githubusercontent.com/47646223/111030441-0766f400-83e1-11eb-8a0f-3294062cf105.png)

**Comment by dnfield** [comment]
Please share a full reproduction, including the svg code

**Comment by mamodo123** [comment]
@dnfield 
this is my dart file:

`import 'package:erbse_instagram/resources/assets.dart' as Assets;
import 'package:erbse_instagram/resources/colors.dart' as Colors;
import 'package:erbse_instagram/resources/strings.dart' as Strings;
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.GREEN_LOGO,
          title: const Text(
            Strings.APP_NAME,
            style: TextStyle(color: Colors.LIGHT_TEXT),
          ),
        ),
        body: Padding(
          padding: const EdgeInsets.all(10),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SvgPicture.asset(Assets.IMAGE_LOGO_NAMED_SVG),
              const SizedBox(
                height: 20,
              ),
              Text(
                Strings.dica(2),
                style: TextStyle(fontSize: 23),
              ),
            ],
          ),
        ),
      ),
    );
  }
}`

and the SVG code is:

`<svg id="Camada_1" data-name="Camada 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 486.78 157.37"><path d="M.05,83.35V10.7A1.48,1.48,0,0,1,1.53,9.22H46a1.48,1.48,0,0,1,1.48,1.48V25.78A1.48,1.48,0,0,1,46,27.26H21.27V38H42.58a1.48,1.48,0,0,1,1.48,1.48V54.57a1.48,1.48,0,0,1-1.48,1.48H21.27V66.8H46a1.47,1.47,0,0,1,1.48,1.47V83.35A1.48,1.48,0,0,1,46,84.83H1.53A1.48,1.48,0,0,1,.05,83.35Z" transform="translate(-0.05)" fill="#642574"/><path d="M117.39,84.44a1.48,1.48,0,0,1-1.48,1.5H96.3a1.48,1.48,0,0,1-1.47-1.44c-.45-12.37-6.64-18.76-16.39-19.39V84.47A1.48,1.48,0,0,1,77,86H58.68a1.47,1.47,0,0,1-1.47-1.48V10.7a1.47,1.47,0,0,1,1.47-1.48h35.9C107,9.22,117,17.91,117,36.29c0,10.82-3.5,18.26-8.89,22.57C113.64,65.14,117.09,73.69,117.39,84.44ZM78.43,45a.71.71,0,0,0,.74.68H87.8c4.3,0,7.79-3.29,7.79-8.73s-3.49-8.73-7.79-8.73H79.17a.71.71,0,0,0-.74.68Z" transform="translate(-0.05)" fill="#642574"/><path d="M186.82,60.71c0,16-9.4,24.12-19.82,24.12H128.7a1.48,1.48,0,0,1-1.48-1.48V10.7a1.48,1.48,0,0,1,1.48-1.48h34.06c10.93,0,20.28,7.84,20.28,23.31,0,8.2-2.46,11.11-2.46,11.11A26.49,26.49,0,0,1,186.82,60.71ZM148.46,37.28a.74.74,0,0,0,.74.74H156a5.6,5.6,0,0,0,0-11.2H149.2a.74.74,0,0,0-.74.74Zm16.6,24.36a5.6,5.6,0,0,0-5.6-5.6H149.2a.74.74,0,0,0-.74.74v9.71a.74.74,0,0,0,.74.73h10.26A5.59,5.59,0,0,0,165.06,61.64Z" transform="translate(-0.05)" fill="#642574"/><path d="M238.66,26.5a1.45,1.45,0,0,1-1.76,1.3,77.75,77.75,0,0,0-13.81-1.72c-7.48-.13-8.47,4.66-8.47,6s.86,6.38,9.82,8.58a24.82,24.82,0,0,1,19,24.67c0,14.36-8.21,21.7-28.84,21.7a131.27,131.27,0,0,1-16-.94,1.45,1.45,0,0,1-1.27-1.6l1.41-14.72a1.48,1.48,0,0,1,1.78-1.3,70.74,70.74,0,0,0,13.36,1.71c7.49.12,8.47-4.67,8.47-6s-.86-6.38-9.82-8.59a24.85,24.85,0,0,1-19-24.67c0-14.35,11.16-21.7,28.84-21.7,6.46,0,13.46.66,16.41,1a1.47,1.47,0,0,1,1.3,1.61Z" transform="translate(-0.05)" fill="#642574"/><path d="M253.26,83.35V10.7a1.48,1.48,0,0,1,1.48-1.48h44.42a1.48,1.48,0,0,1,1.48,1.48V25.78a1.48,1.48,0,0,1-1.48,1.48H274.48V38h21.31a1.48,1.48,0,0,1,1.48,1.48V54.57a1.48,1.48,0,0,1-1.48,1.48H274.48V66.8h24.68a1.47,1.47,0,0,1,1.48,1.47V83.35a1.48,1.48,0,0,1-1.48,1.48H254.74A1.48,1.48,0,0,1,253.26,83.35Z" transform="translate(-0.05)" fill="#642574"/><circle cx="338.91" cy="92.89" r="18.52" fill="#642574"/><circle cx="378.75" cy="55.28" r="19.09" fill="#a4ca6b"/><circle cx="415.08" cy="31.84" r="13.15" fill="#a4ca6b"/><circle cx="312.63" cy="125.48" r="7.76" fill="#a4ca6b"/><path d="M383.85,121.69c27.79-17,47.8-39,71.94-65.49,13.36-14.66,23.85-27.6,31-36.82a102.11,102.11,0,0,0-37.94,2.71c-8.93,2.33-45.43,13.12-71.62,49.36-17.83,24.68-15.14,39.38-34.68,57.48A82.19,82.19,0,0,1,309,147.79,185.18,185.18,0,0,0,383.85,121.69Z" transform="translate(-0.05)" fill="#55a632"/><g opacity="0.8"><path d="M179.14,104.08a5.62,5.62,0,0,1,1.46,4.14v.65l-3.65.36v-.93a2.32,2.32,0,0,0-.5-1.63,2.11,2.11,0,0,0-2.86,0,2.37,2.37,0,0,0-.5,1.63v.32a4.18,4.18,0,0,0,.68,2.23,12.28,12.28,0,0,0,2.5,2.63,17.69,17.69,0,0,1,3.69,4,7.68,7.68,0,0,1,1.07,4v1.26a5.53,5.53,0,0,1-1.52,4.15,7.2,7.2,0,0,1-8.69,0,5.53,5.53,0,0,1-1.52-4.15v-1.68l3.65-.36v1.79c0,1.57.71,2.36,2.14,2.36s2.15-.79,2.15-2.36v-.83a4.08,4.08,0,0,0-.72-2.3A13.49,13.49,0,0,0,174,116.7a16.36,16.36,0,0,1-3.61-4,7.66,7.66,0,0,1-1-4v-.54a5.12,5.12,0,0,1,5.65-5.61A5.67,5.67,0,0,1,179.14,104.08Z" transform="translate(-0.05)" fill="#1d1d1b"/><path d="M196.82,104.2a6,6,0,0,1,1.56,4.42v2.25l-3.65.18v-2c0-1.93-.72-2.9-2.15-2.9a2,2,0,0,0-1.59.65,2.82,2.82,0,0,0-.55,1.89v13.67a2.82,2.82,0,0,0,.55,1.89,2,2,0,0,0,1.59.65c1.43,0,2.15-1,2.15-2.9v-2.79l3.65.18v3a6,6,0,0,1-1.56,4.42,6.7,6.7,0,0,1-8.64,0,6.11,6.11,0,0,1-1.53-4.44V108.62a6.11,6.11,0,0,1,1.53-4.44,6.7,6.7,0,0,1,8.64,0Z" transform="translate(-0.05)" fill="#1d1d1b"/><path d="M217.26,128h-3.79V117.09H209V128h-3.8V103H209v10.55h4.5V103h3.79Z" transform="translate(-0.05)" fill="#1d1d1b"/><path d="M235.13,104.31a6.38,6.38,0,0,1,1.63,4.63V122a6.38,6.38,0,0,1-1.63,4.63,6.78,6.78,0,0,1-9,0,6.42,6.42,0,0,1-1.62-4.63V108.94a6.42,6.42,0,0,1,1.62-4.63,6.78,6.78,0,0,1,9,0Zm-6.22,2.54a3.28,3.28,0,0,0-.59,2.13v13a3.28,3.28,0,0,0,.59,2.12,2.09,2.09,0,0,0,1.73.74,2.12,2.12,0,0,0,1.74-.74A3.34,3.34,0,0,0,233,122V109a3.34,3.34,0,0,0-.59-2.13,2.12,2.12,0,0,0-1.74-.74A2.09,2.09,0,0,0,228.91,106.85Z" transform="translate(-0.05)" fill="#1d1d1b"/><path d="M254.23,104.31a6.38,6.38,0,0,1,1.63,4.63V122a6.38,6.38,0,0,1-1.63,4.63,6.78,6.78,0,0,1-9,0,6.42,6.42,0,0,1-1.62-4.63V108.94a6.42,6.42,0,0,1,1.62-4.63,6.78,6.78,0,0,1,9,0ZM248,106.85a3.28,3.28,0,0,0-.59,2.13v13a3.28,3.28,0,0,0,.59,2.12,2.09,2.09,0,0,0,1.73.74,2.12,2.12,0,0,0,1.74-.74,3.34,3.34,0,0,0,.59-2.12V109a3.34,3.34,0,0,0-.59-2.13,2.12,2.12,0,0,0-1.74-.74A2.09,2.09,0,0,0,248,106.85Z" transform="translate(-0.05)" fill="#1d1d1b"/><path d="M266.91,124.43h6.33V128H263.12V103h3.79Z" transform="translate(-0.05)" fill="#1d1d1b"/></g><path d="M288.07,145.26l2.12-.63a91.74,91.74,0,0,0,19-8.4,11.15,11.15,0,1,1,14.4-10.67c0,.06,0,.12,0,.18.44-.39.89-.78,1.33-1.19a79.08,79.08,0,0,0,7.63-8.08,24,24,0,1,1,22-41.73c1.19-2.14,2.48-4.34,3.93-6.63a24,24,0,0,1,30.9-34.38q4.16-3.31,8.27-6.13a20.34,20.34,0,0,1,22.95-12.95A133.93,133.93,0,0,1,441.88,7a112.12,112.12,0,0,1,39.61-3.2L483,2.14A185.44,185.44,0,0,0,424,2.61C410.19,5,354,16.25,316.08,62c-25.85,31.17-20.45,50.83-49.51,73.16-18.37,14.12-38,19.68-51,22.19A312.84,312.84,0,0,0,288,145.3Z" transform="translate(-0.05)" fill="#5a8e31"/></svg>`

**Comment by dnfield** [comment]
I don't see any issues with the reproduction you're sharing - here's how it looks for me (after replacing some strings)

Not sure what's causing your extra padding but it doesn't show up here.

<img width="813" alt="Screen Shot 2021-04-06 at 5 05 54 PM" src="https://user-images.githubusercontent.com/8620741/113792263-5c550c00-96fa-11eb-8e0a-901cd29a3c0f.png">

**Comment by leonardchikenzen** [comment]
This issue is still here
