### ISSUE TITLE
text font-style="italic" does not work

### ISSUE THREAD

**Issue by softwaresinc** [dnfield/flutter_svg#517]
Most text attributes work, but not italic. This fails:
    `<text` x="20" y="35" font-style="italic"  `font-family="serif">text</text>`
but this works:
    `<text` x="20" y="35" font-weight="bold"  `font-family="serif">text</text>`

**Comment by dnfield** [comment]
Need to implement font-style attribute.

**Comment by guman24** [comment]
font-style = "italic" is still not working in SVG. Anybody here to assist in this issue ?
