### ISSUE TITLE
SVG  not rendering in mobile browser (Chrome & Safari)

### ISSUE THREAD

**Issue by imSanjaySoni** [dnfield/flutter_svg#520]
**SVG  not rendering in mobile browser (Chrome & Safari)**
I am using the latest version ( flutter_svg 0.19.3 ). it is working fine in android phone, iPhone and desktop browsers. but not working in mobile browser. please help I am trying fix since two days but I couldn't find any solution.

**Comment by krishnakumarcn** [comment]
Same issue here.

**Comment by imSanjaySoni** [comment]
> Check this out
> [#488 (comment)](https://github.com/dnfield/flutter_svg/issues/488#issuecomment-778628637)

Its worked thanks @krishnakumarcn
