### ISSUE TITLE
Tint SvgPicture after creation

### ISSUE THREAD

**Issue by qbait** [dnfield/flutter_svg#524]
I would like to build `Img` util that simplifies syntax for other developers. They can call sth like `Img.search` and asset is created.

However, sometimes there is a situation that an asset needs to be passed and tint after creation. I would like to have a syntax like `Img.search.tint(red)` then.

However, I can't see the way to tint SvgPicure after is created. Am I missing something?

Below is my pseudo code with what I would like to achieve.

```
class Img {
  static SvgPicture get close => SvgPicture.asset('assets/icons/close.svg');
  static SvgPicture get search => SvgPicture.asset('assets/icons/search.svg');
}

extension on Img {
  SvgPicture tint(Color color) {
    this.copyWith(color: color); //I would like to be able to tint SvgPicture
  }
}
```

**Comment by qbait** [comment]
Is class like that a good idea then?

```
class SvgAssets {
  static const bull = SvgAsset('bull');
  static const search = SvgAsset('search');
}

class SvgAsset {
  final String _assetName;
  final _path = 'assets/icons/';
  final _extension = '.svg';

  String get _fullPath => _path + _assetName + _extension;

  const SvgAsset(this._assetName);

  SvgPicture get bld => SvgPicture.asset(_fullPath);

  SvgPicture build({Color? color, double? width}) => SvgPicture.asset(_assetName, color: color, width: width);
}
```

And you can call it
`SvgAssets.search.bld`
or
`SvgAssets.search.build(color: red)`

**Comment by dnfield** [comment]
It's really up to you how you design your API for this :) I would try to figure out what the use cases are, and benchmark whether it's better to use the color parameter or not or try to somehow transform the assets if possible. In general, it would be faster to render without using the color parameter, especially as the SVG gets more complex.
