### ISSUE TITLE
how to migrate from flutter_icons to flutter_svg

### ISSUE THREAD

**Issue by aytunch** [dnfield/flutter_svg#527]
I have been using flutter_icons before and as of today that package is not being maintained and does not support null-safety.

I already have a long list of svg icons packed inside of a folder(json + ttf + dart files) generated automatically by the tool: https://www.fluttericon.com/

I was wondering if there was an easy way to use this package with the same data I have been using? Or do we have to add every icon to our asset folder one by one?

Thanks

**Comment by dnfield** [comment]
You have to do it one by one - flutter_icons uses icon fonts, which is pretty different from SVG.

**Comment by aytunch** [comment]
Thanks for the clarification.
I guess this package preserves the color data of svg which flutter_icons could not I believe right?

**Comment by dnfield** [comment]
Yes, among other things
