### ISSUE TITLE
Some details don't load from these images

### ISSUE THREAD

**Issue by lcandido** [dnfield/flutter_svg#534]
Hi friend, some details don't load from these attached images.

I'm using this dependency:  flutter_svg: ^0.21.0

[icons.zip](https://github.com/dnfield/flutter_svg/files/6315041/icons.zip)

[gender.zip](https://github.com/dnfield/flutter_svg/files/6315035/gender.zip)

Best regards.

**Comment by dnfield** [comment]
Both cases are #102
