### ISSUE TITLE
Flutter web: Not rendered in android devices

### ISSUE THREAD

**Issue by mbdax034** [dnfield/flutter_svg#540]
Hello team,

I m working on a web app and i try to use svg files for images.
The svg file is loaded  but not rendered (only on android devices).
ps: flutter_svg working for all platforms except web mobile

Version 
```
flutter_svg: 0.22.0
```

```
Flutter (Channel stable, 2.0.5, on Linux, locale fr_FR.UTF-8)
```

**Comment by jonasbark** [comment]
check out https://flutter.dev/docs/development/tools/web-renderers#command-line-options - you need to use canvaskit only if you want to use flutter_svg on mobile devices

**Comment by dnfield** [comment]
Flutter svg should now work with the html backend, but I don't think that's the case on stable. Can you try this on beta dev or master?

**Comment by jonasbark** [comment]
Just tried it - on beta it doesn't seem to be available yet but on dev it is.

**Comment by mbdax034** [comment]
Thanks, it work with canvaskit option

**Comment by jonbhanson** [comment]
It also worked with canvaskit for me, but the docs state that canvaskit adds about 2MB in download size, which was a dealbreaker for me.  Sad to say, but I will be using raster images until this is resolved.

**Comment by dnfield** [comment]
AFAIK, SVGs should generally render fine on HTML backend at this point - if you have a specific one that does not please share it in a new bug, although it's likely a bug upstream in the HTML backend.
