### ISSUE TITLE
Not render on Flutter Web - Mobile View

### ISSUE THREAD

**Issue by wilyanto** [dnfield/flutter_svg#542]
Having issue in rending SVG image for Mobile View (in Flutter Web). The SVG pictures are on below section, the white-squared container

![image](https://user-images.githubusercontent.com/53255602/115988260-f49c2d80-a5e2-11eb-8f02-e26192db100b.jpeg)

But it's working fine for Desktop View (in Flutter Web also)

![image](https://user-images.githubusercontent.com/53255602/115988277-0da4de80-a5e3-11eb-933b-b00db148747d.jpeg)

**Comment by dnfield** [comment]
See #173 and #491

**Comment by wilyanto** [comment]
> See #173 and #491

Thank You, works on #173 thread
