### ISSUE TITLE
SVG paths invisible in CanvasKit

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dnfield/flutter_svg#545]
### [SVG paths]

All of the **[SVG paths that can be found here][SVG paths]** are **invisible** in CanvasKit for some reason.

#### Example

```
M377 20c0-5.333 1.833-10 5.5-14S391 0 397 0c4.667 0 8.667 1.667 12 5
3.333 2.667 6.667 9 10 19 6.667 24.667 20.333 43.667 41 57 7.333 4.667 11
10.667 11 18 0 6-1 10-3 12s-6.667 5-14 9c-28.667 14.667-53.667 35.667-75 63
-1.333 1.333-3.167 3.5-5.5 6.5s-4 4.833-5 5.5c-1 .667-2.5 1.333-4.5 2s-4.333 1
-7 1c-4.667 0-9.167-1.833-13.5-5.5S337 184 337 178c0-12.667 15.667-32.333 47-59
H213l-171-1c-8.667-6-13-12.333-13-19 0-4.667 4.333-11.333 13-20h359
c-16-25.333-24-45-24-59z
```

On **mobile**, they all work fine, however, when using `flutter_svg` on web with the CanvasKit renderer, they are simply not rendered.

### Problem

It would be very beneficial for us if `flutter_svg` supported these as this would solve flutter/flutter#81615 as we would not have to use `<img>` DOM elements.  

Currently, the package uses `<img>` DOM elements with `data:image/svg+xml;utf8,$svgString`, however, Flutter using CanvasKit _completely crashes_ when doing that and including a few elements.  
Consequently, `flutter_svg` could solve the problem by rendering the SVGs on CanvasKit. However, this does not work as the paths are invisible when using `flutter_svg`.

[SVG paths]: https://github.com/simpleclub-extended/flutter_math_fork/blob/a27c5fb7153de145620a31c0b6002d1b3cc25572/lib/src/render/svg/svg_geomertry.dart#L129

**Comment by dnfield** [comment]
I'm not able to reproduce this. For example, I just tried this SVG:

```
<svg viewBox="0 0 1000 1000">
  <path d="M377 20c0-5.333 1.833-10 5.5-14S391 0 397 0c4.667 0 8.667 1.667 12 5
3.333 2.667 6.667 9 10 19 6.667 24.667 20.333 43.667 41 57 7.333 4.667 11
10.667 11 18 0 6-1 10-3 12s-6.667 5-14 9c-28.667 14.667-53.667 35.667-75 63
-1.333 1.333-3.167 3.5-5.5 6.5s-4 4.833-5 5.5c-1 .667-2.5 1.333-4.5 2s-4.333 1
-7 1c-4.667 0-9.167-1.833-13.5-5.5S337 184 337 178c0-12.667 15.667-32.333 47-59
H213l-171-1c-8.667-6-13-12.333-13-19 0-4.667 4.333-11.333 13-20h359
c-16-25.333-24-45-24-59z" />
</svg>
```

on web canvaskit and it seems to render the same as in Chrome. It also is rendering fine in HTML backend. 

Can you share a full reproduction? I'd be happy to re-open the issue if there's one I can reproduce.

**Comment by creativecreatorormaybenot** [comment]
@dnfield sure, I will follow up with examples.

**Comment by creativecreatorormaybenot** [comment]
@dnfield Trying to reproduce it, I was actually able to confirm that the isolated SVG is rendering equally on mobile and CanvasKit - just inside of the library, inside of the widget tree - it is not displaying on CanvasKit, even though the exact same code is displaying on mobile.

I will continue to investigate this. If I do not give an update, it means I found a solution that was not related to `flutter_svg` and rather some other CanvasKit behavior.

**Comment by creativecreatorormaybenot** [comment]
(the bug was: remnants of `flutter_svg` not being supported on web, causing a conditional import to return a container on web)
