### ISSUE TITLE
SVGs not showing up 

### ISSUE THREAD

**Issue by kevinApplaud** [dnfield/flutter_svg#55]
Hi,

I just started using this library and it seems such a headache. What I am trying to do, is to show a vector downloaded from internet, but I just see CircularProgressIndicator and then white screen.
```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class testPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
      body: Center(
        child:  SvgPicture.network(
          'https://upload.wikimedia.org/wikipedia/commons/6/67/Firefox_Logo%2C_2017.svg',
          placeholderBuilder: (BuildContext context) => new Container(
              padding: const EdgeInsets.all(30.0),
              child: const CircularProgressIndicator()),
        ),
      ),
    );
  }
}
```

And I am using this in my pubspec.yaml
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.5.5+1

ERROR MSG:
I/flutter (13107): unhandled element title; Picture key: NetworkPicture("https://upload.wikimedia.org/wikipedia/commons/6/67/Firefox_Logo%2C_2017.svg", headers: null, colorFilter: null)

**Comment by dnfield** [comment]
I'm pretty sure this is running into the same issue that #54 is addressing - the linked SVG uses lots of `userSpaceOnUse`, which isn't currently supported.

I'll leave this open for now, but let's try to recheck it once #54 lands.

**Comment by dnfield** [comment]
#54 resolves this - that SVG now renders correctly.  I'll probably look to add it as a golden test at some point.
