### ISSUE TITLE
Publish stable 1.x version

### ISSUE THREAD

**Issue by danilofuchs** [dnfield/flutter_svg#558]
Currently, this package only provides alpha versions, such as 0.22.0

This means every minor change (0.23.0, ...) are interpreted as breaking changes by Dart Pub.

Other dependencies might depend on a specific version of flutter_svg, so it blocks some straightforward upgrades.

I believe this package has already proven its stability and production readyness. (We've been using it extensively for 1 year without a single bug).

This is a minor incovenience when using the library for a long period. It is totally manageable, but is happens every time a new version is published.

Anyways, thank you for this amazing piece of software!

**Comment by dnfield** [comment]
Yeah it's probably time. There are more things I was hoping to get done, and I'm still likely to err on the side of caution when bumping versions (sometimes people are broken because of golden tests for example).

**Comment by dnfield** [comment]
So the two things I'd like to have before a 1.0 are:

- Out of Order defs (#102)
- Filter effects (#53)

**Comment by danilofuchs** [comment]
Nice!
I myself missed support for filters recently and had to use PNGs instead
I understand these issues are complex to solve, and I'm afraid few people are qualified enough to act on this domain. Perhaps another team member from @flutter could help push these forward?

It would be nice to break down these in smaller deliveries (create an interface for rendering filters, and implement them bit by bit) so people can help doing small PRs and we all have partial support sooner (partial support is OK before 1.0 IMO).

**Comment by dnfield** [comment]
Yeah. I have a WIP patch to support out of order defs - it's something I work on when I have cycles :) The filters might be helped by that as well. Part of my concern has been that filters, as specified, are really hard to do performantly. SVG in general isn't a great interface for performance :\

**Comment by dnfield** [comment]
This is done. I still don't have out of order defs or filters, but it's ok.
