### ISSUE TITLE
Performance issues in scrollable widgets

### ISSUE THREAD

**Issue by rs5173** [dnfield/flutter_svg#560]
After repeated investigation, it is finally found that flutter_svg will cause severe frame drop in scrollable widgets, flutter version is 2.2

**Comment by rs5173** [comment]
As the number of SvgPicture increases, frame drop will become very serious

**Comment by rs5173** [comment]
After deleting SvgPicture, it becomes smooth

**Comment by dnfield** [comment]
What if you add repaint boundaries around the SVG?

**Comment by dnfield** [comment]
It also really depends on what the SVG is. :)

**Comment by rs5173** [comment]
I don’t quite understand what "add repaint boundaries around the SVG" means. I tried to set allowDrawingOutsideViewBox to true, but it still has no effect.

**Comment by rs5173** [comment]
The SVGs I use are all small icons, such as

`<svg xmlns="http://www.w3.org/2000/svg" width="21.392" height="15.397" viewBox="0 0 21.392 15.397">
    <path id="路径_19" data-name="路径 19" d="M67.4,216h-.1a6.233,6.233,0,0,0-6.107,5.723v.006l-.048.007a4.856,4.856,0,0,0,.71,9.66H73.54a4.854,4.854,0,0,0,4.852-4.856v-.08a4.855,4.855,0,0,0-4.3-4.744l-.035,0-.008-.09a6.233,6.233,0,0,0-6.2-5.623Zm0,1.435h.452a4.8,4.8,0,0,1,4.8,4.8v.163a.717.717,0,0,0,.717.722h.176a3.421,3.421,0,0,1,0,6.842H61.852a3.421,3.421,0,0,1,0-6.842h.034a.717.717,0,0,0,.717-.717v-.167a4.8,4.8,0,0,1,4.8-4.8Z" transform="translate(-57 -216)" fill="#0c0c0c"/>
</svg>
`

**Comment by rs5173** [comment]
All svg comes from adobe xd

**Comment by dnfield** [comment]
So instead of something like `ListView(children: [SvgPicture.asset(...), SvgPicture.asset(...)]`, do `ListView(children: [RepaintBoundary(child: SvgPicture.asset(...)), RepaintBoundary(child: SvgPicture.asset(...))]`.

**Comment by rs5173** [comment]
Using RepaintBoundary did not help me much. In the end, I found a package called flutter_svg_provider. Its method is to convert SVG data into an Image at runtime. This issue was resolved.

pub:https://pub.dev/packages/flutter_svg_provider

**Comment by rs5173** [comment]
thank you for your reply!

**Comment by dnfield** [comment]
@olegyablokov please share a reproduction.
