### ISSUE TITLE
SVG width and height is ignored

### ISSUE THREAD

**Issue by Parkar99** [dnfield/flutter_svg#574]
I am not sure what the exact source of this issue is, but the SVG does have a `viewport` attribute but I am not sure how that affects it's size. Here is the code I am trying:

```dart
TextField(
  decoration: InputDecoration(
    hintText: 'Search by school name',
    prefixIcon: SvgPicture.asset(
      'assets/svgs/search.svg',
      color: Colors.grey,
      height: 1,
      width: 1,
    ),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(5),
    ),
  ),
)
```

Here is the SVG:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
    <g transform="translate(-2.638 -2.638)">
        <path class="b" stroke="#000" stroke-linecap="round"
                stroke-linejoin="round" stroke-width="1.4px" fill="none"
                d="M19.222,11.861A7.361,7.361,0,1,1,11.861,4.5,7.361,7.361,0,0,1,19.222,11.861Z" />
        <path class="b" stroke="#000" stroke-linecap="round"
                stroke-linejoin="round" stroke-width="1.4px" fill="none"
                d="M28.353,28.353l-3.378-3.378"
                transform="translate(-7.578 -7.578)" />
    </g>
</svg>
```

Here's what it looks like:

![Search field with search SVG icon](https://user-images.githubusercontent.com/50555895/125608439-c3155dfd-9fbe-4ac8-9aa0-d901b9b50329.png)

The code uses a height and width of 1 pixel to illustrate the problem better. And the above image proves that the SVG is all but 1 pixel in height and / or width.

**Comment by dnfield** [comment]
I don't think the bug is in this library - this works if you aren't tryig to use it as a `InputDecoration`'s `prefixIcon`.

**Comment by dnfield** [comment]
Yeah, I see similar behavior when using an `Image` there.

**Comment by aytunch** [comment]
The same problem is in `AppBar`s `leading` property as well. Can you recommend a workaround?

**Comment by adimshev** [comment]
Wrap into SizedBox
