### ISSUE TITLE
Error loading a particular SVG network asset.

### ISSUE THREAD

**Issue by ZiyadF296** [dnfield/flutter_svg#585]
Hello!

First of all, thank you for this incredible package that helps a lot! Unfortunately, for some assets or for some SVG assets some of the element(s) causes the widget to return an error.

For example, I have this URL which is supposed to return an SVG asset [here is the link](https://source.boringavatars.com/marble/120/$userId?colors=264653,2a9d8f,e9c46a,f4a261,e76f51).

I am using the network option of course! However I receive an error, but I was kind of expecting to receive an error anyways because that image contains a few sophisticated gradients and other effects.

The error I receive is:
```
════════ Exception caught by SVG ═══════════════════════════════════════════════
The following ProgressEvent$ object was thrown resolving a single-frame picture stream:
  [object ProgressEvent]

When the exception was thrown, this was the stack
Picture provider: NetworkPicture("https://source.boringavatars.com/marble/120/userId?square=true?colors=264653,2a9d8f,e9c46a,f4a261,e76f51", headers: null, colorFilter: null)
Picture key: NetworkPicture("https://source.boringavatars.com/marble/120/userId?square=true?colors=264653,2a9d8f,e9c46a,f4a261,e76f51", headers: null, colorFilter: null)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by dnfield** [comment]
I think this is a flutter-web issue specifically - do you get the same problem on mobile/desktop?

Going to close this since I think it's an upstream issue, but will reopen if new details emerge.

**Comment by roberto-donext** [comment]
Same here... what that mean??? This plugin doesn´t work with web????

**Comment by zanpen2000** [comment]
Same here... what that mean??? This plugin doesn´t work with web????
