### ISSUE TITLE
SVG is expanding to fill the column

### ISSUE THREAD

**Issue by giiyms** [dnfield/flutter_svg#587]
Hello,

Trying to stick an SVG in the center of the page with a loading progress underneath.
I want the SVG to scale to the width of the device but it seems to produce a container that goes the complete height of available space. 

Seems like a bug. I do not want to set the height to a fixed value, is there a trick to shrink wrap it?

![image](https://user-images.githubusercontent.com/8017509/130101265-41001a32-1e16-43a0-a8dc-3d9c0556fabf.png)

**Comment by dnfield** [comment]
Please provide a minimal and complete reproduction. If you can do so I'll re-open this, as long as it's clear that it's a bug in this library.

**Comment by giiyms** [comment]
Here is a github repo to copy with the svg in the assets folder.

https://github.com/giiyms/flutter_svg_example/tree/master

**Comment by dnfield** [comment]
I'm not clear on what the problem is - the borders you're seeing there are due to the safe area AFAICT.

**Comment by giiyms** [comment]
The loading indicator is getting pushed to the bottom. The loading indicator should be just below the image. 

The SVG is not limiting the height based on the aspect ratio. The container is expanding to fill the space.

**Comment by dnfield** [comment]
Ahh, I see, yeah. By default, it tries to make sure the image stays centered in its available space, which is usually the expected thing.  If you want it to only take up a certain amount of space, you have to specify a height or width or both. If you only specify one, aspect ratio will be maintained.
