### ISSUE TITLE
Caching SVG varieties and draw them to the canvas

### ISSUE THREAD

**Issue by FaFre** [dnfield/flutter_svg#589]
I have a lot of small SVG's, which I want to display in different sizes and colors (depending on variables). In some circumstances up to 100 SVG's can be displayed at the same time.

I was thinking about storing the SVG's as `DrawableRoot`'s. On demand I will load the `DrawableRoot`-template, customize the `DrawableStyle` and cache it after calling `.toPicture()`. 

Later I have to display the SVG. I found here two ways how that could work:

I saw there is the `RawPicture`-Widget, that takes the `Picture` wrapped inside `PictureInfo`. However, `RawPicture`is not exposed by the package, so I'm not sure if this is the preferred way then.

The other option I found it would be calling `toImage()` and cache the rendered image instead of the earlier output from `.toPicture()`. This seems to really render the image which can then be drawn to the canvas using `paintImage()`.

Maybe I'm overseeing some things here. Does someone have some input for me?

Having a good solution for that can possibly be packed into an PR to extend the API.

**Comment by dnfield** [comment]
RawPicture might be a bad widget to expose - I'm not sure it can handle picture lifecycle properly.

The library, by default, does caching - I'm not really clear on what your use case is though or what performance issue you're trying to solve.

**Comment by FaFre** [comment]
I have a `Stack` containing, let's say 100 `Positioned` icons. Around 20 times per second the `Stack` is getting rebuilt to change the coordinates of the `Positioned`. Because I'm using keys in a proper way, the SVG-Widget itself is not getting rebuilt, but the SVG has to get drawn at a new position now, since `Positioned` changed. 

I assume even the cached SVG's are actually drawn on the canvas path by path or at least in a way that is to slow for me. I suspect drawing on the canvas is causing performance issues in my case due the amount of a huge number of rebuilds. 

I used raster images using flutters default `Image`-Widget in the same scenario with a much better performance. So I plan to use the flexibility of the SVG's to customize and resize them to my needs, and rasterize them before they are getting displayed.

**Comment by dnfield** [comment]
Yeah, the SVG widget itself caches a `Picture`, but it does not rasterize anything. For your use case, you probably want to cache the rasterized version of what you're drawing for faster redraws.

It _might_ help to wrap your SVGs in a `RepaintBoundary`. If not, you'll just want to `toImage` them at some point.

**Comment by FaFre** [comment]
Amazing! `RepaintBoundary` did the job!

Thank you very much :)
