### ISSUE TITLE
Check if width or height is set by style instead of inline attribute

### ISSUE THREAD

**Issue by Sembauke** [dnfield/flutter_svg#597]
The application that I am working with is providing `width` and `height` by style with no way to change this. This results in the error that no width, height, or view box is provided.

This might be a bit out of scope for this package.

I use the flutter_html package to parse the HTML I receive from my API.

![image](https://user-images.githubusercontent.com/46919888/132652957-81d53cdc-d495-4fed-b379-dc0a654615db.png)

**Comment by dnfield** [comment]
This is a specific case of #105 

In this case, it seems like whatever is parsing that HTML should be able to resolve that style for you to actual values. But I suspect flutter_html doesn't support that because it's both super complicated and super expensive...
