### ISSUE TITLE
After upgrading to Flutter2.5, some svgs cannot be rendered normally

### ISSUE THREAD

**Issue by rs5173** [dnfield/flutter_svg#598]
svg:
`<svg id="1" data-name="1" xmlns="http://www.w3.org/2000/svg" width="14.81" height="19.715"
    viewBox="0 0 14.81 19.715">
    <path id="2" data-name="2"
        d="M411.462,239.591a9.108,9.108,0,0,0-1.639-2.261.775.775,0,0,0-.605-.29.739.739,0,0,0-.765.707.622.622,0,0,0,.093.32v.037l.053.051a7.482,7.482,0,0,1,1.443,2.042,7.784,7.784,0,0,1-1.4,8.729l-.117.14.013.01a.592.592,0,0,0-.075.288.7.7,0,0,0,.719.667.753.753,0,0,0,.373-.1l.032.025.111-.121a8.974,8.974,0,0,0,1.759-10.246"
        transform="translate(-403.493 -233.677)" />
    <path id="3" data-name="3"
        d="M199.97,449.588a1.475,1.475,0,1,0,1.474,1.475,1.477,1.477,0,0,0-1.474-1.475"
        transform="translate(-198.494 -441.205)" />
    <path id="4" data-name="4"
        d="M578.432,99.424a12.994,12.994,0,0,0-3.417-4.6l-.144-.1-.02.023a.748.748,0,0,0-1.041.686.708.708,0,0,0,.1.354l-.036.044.187.154a11.429,11.429,0,0,1,3.024,4.056c2.15,4.813.806,10.3-3.194,13.052l-.175.121.038.038a.745.745,0,0,0,.63,1.143.7.7,0,0,0,.338-.086l.015.018.128-.088c4.492-3.156,5.995-9.386,3.57-14.813"
        transform="translate(-564.774 -94.68)" />
</svg>
`

**Comment by dnfield** [comment]
I'm not able to reproduce this on the current `stable` or `master` channels. The SVG renders just the same as in Chrome for me.

Please feel free to ping with more details if there's a reproduction for this I'm missing.
