### ISSUE TITLE
precache network svg

### ISSUE THREAD

**Issue by desmeit** [dnfield/flutter_svg#624]
I can precache an asset with this:

```
Future.wait([
      precachePicture(
        ExactAssetPicture(
            SvgPicture.svgStringDecoder, 'assets/svg/test.svg'),
        null,
      ),
...
```

How is this possible with a network SVG for using with SvgPicture.network?

**Comment by dnfield** [comment]
Just use a `NetworkPicture` instead of an `ExactAssetPicture`.

**Comment by desmeit** [comment]
`The argument type 'Future<PictureInfo> Function(String, ColorFilter, String)' can't be assigned to the parameter type 'Future<PictureInfo> `

What should I use instead of SvgPicture.svgStringDecoder?

**Comment by dnfield** [comment]
You'd need SvgPicture.svgByteDecoderBuilder

**Comment by desmeit** [comment]
how can this work with flutter_svg 2.0.9?
