### ISSUE TITLE
Can I retire websafe_svg?

### ISSUE THREAD

**Issue by jpeiffer** [dnfield/flutter_svg#629]
I saw this hit 1.0.0 and is now officially supporting web.  Does this mean I can archive [websafe_svg](https://pub.dev/packages/websafe_svg) now because this supports both CanvasKit and HTML mode out of the box?

(please say yes; please say yes...). :)

**Comment by dnfield** [comment]
You are, of course, free to do either way, though I suspect your impelmentation (delegating to `Image.network`) will be more performant in some cases. I'm not entirely sure, but flutter_svg does support web.

**Comment by jacob-hutchings** [comment]
I might be doing something wrong but I am getting much better results with `websafe_svg` than flutter_svg when using `--web-renderer html`.

About 50% of the time flutter_svg renders svgs incorrectly:

<img width="55" alt="Screen Shot 2021-12-13 at 4 10 29 PM" src="https://user-images.githubusercontent.com/3528029/145904151-52e699c6-fb91-4a93-be41-febd7de36aae.png">

    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-square"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>

<img width="39" alt="Screen Shot 2021-12-13 at 4 10 22 PM" src="https://user-images.githubusercontent.com/3528029/145904171-6b6fe698-d117-478b-b631-78c727835625.png">


    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-share"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path><polyline points="16 6 12 2 8 6"></polyline><line x1="12" y1="2" x2="12" y2="15"></line></svg>

**Comment by dnfield** [comment]
I'm willing to bet that most of these are bugs in the HTML rendering backend.
