### ISSUE TITLE
How to have SvgPicture inherit the color from BottomNavigationBar? 

### ISSUE THREAD

**Issue by dennisbakhuis** [dnfield/flutter_svg#631]
Hi Dan (and other who read this),
It is probably not an issue with flutter_svg but more my understanding of Flutter (and my Google-Fu I guess) but I cannot seem to find the proper approach solving my problem. I replaced the standard Icons in a BottomNavigationBar with custom SVG files. Using flutter_svg this works like a charm, however, without any other changes these new "icons" are static and just black while the default icons somehow inherit the selected/unselected color from their parent.

Things I have thought of:
1) I could of course hard-code the colors and use two icons (icon + activeIcon) but this seems rather stupid if I want to use a global theme.
2) In the BottomNavigationBar (BNB), use a check for current active tab and use the theme.of(context).bottomnavigationbartheme.selectedColor etc.  --> for this I would have to set up this as it is not yet set up in the theme. The default BNB apparently was able to select the colors from the primarySwatch (or something related).

What would be an appropriate approach?

Thanks again for the great effort of flutter_svg!

Cheers,
Dennis

**Comment by manoharanpncity** [comment]
List<BottomNavigationBarItem> bottomNavigation(Color? activeColor) {
    return [
      BottomNavigationBarItem(
        icon: SvgPicture.asset('assets/icon/home.svg',
          height: 22.0, width: 22.0, ),
        activeIcon: SvgPicture.asset(
          'assets/icon/home.svg',
          height: 22.0,
          width: 22.0,

        ),
        title: Text(
          "Title",
          style: GoogleFonts.poppins(),
        ),
      ),
   

    ];
  }



  BottomNavigationBar(
  type: BottomNavigationBarType.fixed,

  items: bottomItems(activeColor),
  currentIndex: currentIndex,
  showSelectedLabels: true,
  backgroundColor: AppColors.backgroundColor,
  selectedLabelStyle: GoogleFonts.poppins(
  color:
  !unSelected ? AppColors.appColor : AppColors.textColor,
  ),
  selectedItemColor: AppColors.appColor,
  unselectedItemColor: AppColors.textColor,
  showUnselectedLabels: true,
  onTap: (index) {
 
  },
  );

You can use like this..Need a color or multilpe images


Thank you..!

**Comment by manoharanpncity** [comment]
List<BottomNavigationBarItem> bottomItems(Color? activeColor) {
      BottomNavigationBarItem(
  )
}
in onTap you can change the active color.
Thank you..!

**Comment by dnfield** [comment]
This would be more appropriate as a StackOverflow question rather than an issue in this repo - please consider posting there.
