### ISSUE TITLE
flutter 2.8 does not show SVG in firefox

### ISSUE THREAD

**Issue by BigGitWorld** [dnfield/flutter_svg#633]
I was using the flutter_svg package correctly and then updated my flutter to the latest version (2.8 stable channel).
Now, SVG icons are shown in the chrome not the in firefox, while I'm using ``web-renderer canvaskit``.

**Comment by dnfield** [comment]
Is this for all SVGs or only some?

**Comment by dnfield** [comment]
I'm going to close this for lack of a reproducible case, but please feel free to ping it if this is still an issue.

**Comment by BigGitWorld** [comment]
> Is this for all SVGs or only some?

No its for all SVG icons.
all svg icons shown correctly in the Chrome. but I dont know why the Firefox does not show them.
