### ISSUE TITLE
Creating a stack (composition) of svgs and show them smoothly

### ISSUE THREAD

**Issue by chrisDK1977** [dnfield/flutter_svg#638]
I have posted this questions already 1.5 years ago on stackoverflow:
https://stackoverflow.com/questions/65004045/flutter-how-to-display-composed-svg-image-correctly

The problem still exists and when creating a flutter app for web it is even worse.

Our app is using avatars the user can build out of Headshapes, Eybrows, Eyes, Hair, Noses, ... Tops, Trousers, Shoes.

The (>3000) assets are svgs and we use a stacks to display a composition of the body parts (sometimes colored) as previews from which the users can choose.

Everything is working fine but (especially) for the web the stacks are not showing every component while rendering which looks very ugly when entering the page or swichting between man/women, ... as it is showing for a short time (up to ~2 secondes) f.e. the legs but the trowsers above are not loaded.

Is there a way to get the information when all currently displayed assets are loaded and show a dummy for the composition or nothing (show all or nothing) meanwhile?

**Comment by dnfield** [comment]
This is a hard question to answer - it really depends onw hat the SVGs are doing. I would not expect 3000 SVGs stacked on top of each other to perform very well though.

**Comment by chrisDK1977** [comment]
> This is a hard question to answer - it really depends onw hat the SVGs are doing. I would not expect 3000 SVGs stacked on top of each other to perform very well though.

Hi Dan,

:-D of course there are not 3000 SVGs stacked on top of each other. There are about 3.000 SVGs **in the assests**s and we create a stack where we put about 20 of these together.
