### ISSUE TITLE
svg doesn't render correctly

### ISSUE THREAD

**Issue by SteveAlexander** [dnfield/flutter_svg#64]
Here's an export from Sketch that doesn't render as expected.

Here it is in Flutter:

![image](https://user-images.githubusercontent.com/4321921/45379451-05493200-b5f8-11e8-8966-837bd6cf3f40.png)

Code is:

```
SvgPicture.asset(
        'assets/back.svg',
        width: 24.0,
        height: 24.0
      ),
```

Here it is in Chrome:

![image](https://user-images.githubusercontent.com/4321921/45379486-1db94c80-b5f8-11e8-955b-bb456a852e3b.png)

SVG source:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="14px" height="20px" viewBox="0 0 14 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 51.2 (57519) - http://www.bohemiancoding.com/sketch -->
    <title>Path 2</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="03.-Agenda" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Speaker" transform="translate(-18.000000, -35.000000)" stroke="#2694D1" stroke-width="4">
            <polyline id="Path-2" transform="translate(30.000000, 45.000000) rotate(-45.000000) translate(-30.000000, -45.000000) " points="24 51 24 39 36 39"></polyline>
        </g>
    </g>
</svg>
```

**Comment by SteveAlexander** [comment]
If I remove the `fill="none"` from element `id="03.-Agenda"`, then I get the same thing in Chrome as I see in Flutter.

![image](https://user-images.githubusercontent.com/4321921/45380019-85bc6280-b5f9-11e8-8fbb-b5eb5efa0025.png)

So, I guess flutter_svg isn't handling `fill="none"` the same way Chrome is.

**Comment by SteveAlexander** [comment]
If I move the `fill="none"` onto the `polyline` element, then it renders as expected in Flutter.

![image](https://user-images.githubusercontent.com/4321921/45380136-e21f8200-b5f9-11e8-9962-105aecf78f35.png)

**Comment by dnfield** [comment]
Bug.  I'll look at it.
