### ISSUE TITLE
Flashy SVG after every Hero animation

### ISSUE THREAD

**Issue by rocboronat** [dnfield/flutter_svg#642]
Upgrading from 0.23.0+1 to 1.0.0 gave us flashy SVGs after every Hero animation 😢

Here's a video to see the issue in action 👇 

https://user-images.githubusercontent.com/456499/148534159-53d1b53f-71d1-4602-bbf9-2395bb46d190.mp4

Thanks for your work, team! 👍

**Comment by dnfield** [comment]
Can you share a full but minimal reproduction of this issue?

**Comment by rocboronat** [comment]
I'm going for it! 😸

**Comment by rocboronat** [comment]
Here it is! https://github.com/rocboronat/flashy-svg-example

The main class is https://raw.githubusercontent.com/rocboronat/flashy-svg-example/master/lib/main.dart

It reproduces the issue. I have to say I feared it wasn't going to, hehe...

Again, thanks for your work 😀

**Comment by dnfield** [comment]
Ok, mystery solved.

To support `em` and `ex` units (fyi @bselwe), we have to read font information from the currently valid TextStyle, i.e. `DefaultTextStyle.of(context)`. For the hero transition, we're getting put into an overlay that somehow has a different text style with a font size of 48. This invalidates the picture cache and causes redraws to happen (hence the predictable flickers for a frame at the beginning and end of the animation).

You can work around this by wrapping your SVG with a `DefaultTextStyle`, like so:

```dart
DefaultTextStyle(
  style: const TextStyle(fontSize: 14),
  child: SvgPicture.whatever(...),
),
```

And the flickering will go away. In the mean time, we can make this at least a little better by not invalidating the picture cache for pictures that do not use em/ex units (and imilarly for ones that do not use currentColor if that value changes).

**Comment by rocboronat** [comment]
Ohhh that's easy! Thanks for the support, @dnfield!

Right now that we use SVG in a lot of places of the app, would you recommend doing this patch and moving to 1.0.0 or just waiting with the old stable version 0.23.0+1 until you release a 1.x.x version that fixes it?

**Comment by dnfield** [comment]
I have a fix for this that should land soon in 1.0.2, so whether you want to work around it or not is up to you :)

**Comment by dnfield** [comment]
Published as 1.0.2

**Comment by rocboronat** [comment]
Wow, I didn't expect it to be that fast. Thank you so much, @dnfield! 🙇

**Comment by dnfield** [comment]
Just note that you _will still get the flash_ if you have an SVG that actually uses `em/ex/rem` units and the text style changes.
