### ISSUE TITLE
Add ability to create an svg `ImageProvider`

### ISSUE THREAD

**Issue by jesusrp98** [dnfield/flutter_svg#644]
Include a similar functionality to what is being offered by [`flutter_svg_provider`](https://pub.dev/packages/flutter_svg_provider), where an `ImageProvider` specially created for SVGs is provided.

**Comment by cmendes0101** [comment]
There are a couple of closed issues related to this #471 #152 #640

**Comment by dnfield** [comment]
Yes. This is not a feature I'm interested in supporting in this package.
