### ISSUE TITLE
svg incorrect group positioning

### ISSUE THREAD

**Issue by mattsellars** [dnfield/flutter_svg#648]
First off thanks for actively addressing rendering issues. This is by far the best svg renderer I've seen in flutter.

I found when rendering assets from this collection https://storage.googleapis.com/dot-crypto-metadata-api/images/unstoppabledomains.svg that the text and the oval they want to render as a border are not falling into the right places. Group elements in the svg are not placed correctly.

Here's an attached png file of the desired rendering: <img width="264" alt="Screen Shot 2022-01-14 at 9 42 19 AM" src="https://user-images.githubusercontent.com/236337/149552357-32f9e50b-a198-4ca3-8a0e-93350eece990.png">

Here's how the widget is rendering it for me: <img width="188" alt="Screen Shot 2022-01-14 at 9 43 33 AM" src="https://user-images.githubusercontent.com/236337/149552549-b34ea2d9-0f26-4ad4-a02d-7f3936502bd0.png">

Here's the source svg:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="250px" height="250px" viewBox="0 0 250 250" version="1.1">
    
    <title>unstoppabledomains</title>
    <desc>Created with Sketch.</desc>
    <g id="unstoppabledomains" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group" transform="translate(75.000000, 197.000000)">
            <rect id="Rectangle" stroke="#2FE9FF" stroke-width="2.11267614" x="0.260564052" y="0.457746731" width="100" height="34" rx="17"/>
            <text id=".crypto" font-family="OpenSans-Bold, Open Sans" font-size="16" font-weight="bold" fill="#FFFFFF">
                <tspan x="16.5847828" y="23.4577467">.CRYPTO</tspan>
            </text>
        </g>
        <g id="sign" transform="translate(56.000000, 19.000000)">
            <polygon id="Rectangle-Copy-3" fill="#2FE9FF" points="137.000268 2.12559903 137.000268 48.8887777 -2.72848394e-13 104.154352"/>
            <path d="M111.312718,-1.42108539e-14 L111.312718,80.7727631 C111.312718,104.251482 92.1448713,123.284744 68.5001341,123.284744 C44.855397,123.284744 25.6875503,104.251482 25.6875503,80.7727631 L25.6875503,46.7631786 L51.3751006,32.734225 L51.3751006,80.7727631 C51.3751006,88.9903146 58.0838469,95.6519563 66.3595049,95.6519563 C74.6351629,95.6519563 81.3439093,88.9903146 81.3439093,80.7727631 L81.3439093,16.3671125 L111.312718,-1.42108539e-14 Z" id="Path" fill="#FFFFFF"/>
        </g>
    </g>
</svg>`

**Comment by dnfield** [comment]
This looks like the text isn't getting transformed the way it should.

**Comment by dnfield** [comment]
Can't reproduce this at head anymore...
