### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by modulovalue** [dnfield/flutter_svg#649]
Hello Dan,

Just a quick question:

The xml library offers two ways to parse xml, an event based way and one that builds a tree.
I'm just curious: do you remember why you chose the event based method? Was there a technical reason that guided that choice?

**Comment by dnfield** [comment]
Memory. 

Building a DOM tree makes some things convenient but uses a lot more memory. The event based model (at least in theory) can hold a lot less in memory for the duration of parse time.
