### ISSUE TITLE
Changing the currentColor dynamically doesn't have effect

### ISSUE THREAD

**Issue by nikuz** [dnfield/flutter_svg#650]
It's necessary when switch to dark mode and back.

Let's say we have an icon:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
    <path d="M2,2V12H22V2ZM20,8H17v3H15V8H12V6h3V3h2V6h3Z"/>
    <path d="M2,12V22H22V12Zm5,6H4V16h8v2H7Z" fill="#666"/>
</svg>
```

Which in the light mode, with the `currentColor` set to `black`, looks like this:
<img width="53" alt="Screen Shot 2022-01-14 at 9 36 27 PM" src="https://user-images.githubusercontent.com/1743481/149610436-e827b853-344f-4186-b9d7-868bfa5714f7.png">

Then in the dark mode, with the `currentColor` set to `white`, it looks like this:
<img width="54" alt="Screen Shot 2022-01-14 at 9 37 05 PM" src="https://user-images.githubusercontent.com/1743481/149610446-6ff68f2f-9913-4acb-a71b-1430555b581e.png">

Providing the `currentColor` works only on the initial load of a particular asset. But later changing it dynamically doesn't have effect on already cached icons. I also can't set the color manually because it overrides all the `fill` definitions inside the asset and the result icon looks like this:
<img width="72" alt="Screen Shot 2022-01-14 at 9 33 43 PM" src="https://user-images.githubusercontent.com/1743481/149610381-ecfe1c99-65a0-475c-aae0-3fa58940ceaa.png">

I really don't see the way to show multi-color SVG icons in different brightness mode for now. 

The code says:
> The picture will be cached using the [PictureCache], incorporating any color filtering used into the key (meaning the same SVG with two different `color` arguments applied would be two cache entries).

Would it be possible adding the third argument `currentColor` into the code generating the cache key?

**Comment by dnfield** [comment]
Your SVG does not actually use `currentColor`. Can you provide a full sample that reproduces this issue?

**Comment by nikuz** [comment]
Hi @dnfield! Thank you for the fast answer! I started to create a working example, by your request, and found that I was using the outdated version of your library. Which was `0.23.0+1`. I reviewed the new version and found the next way of defining the currentColor is working fine for me:
```dart
SvgPicture.asset(
  'asset.svg',
  theme: SvgTheme(
    currentColor: isLightThemeSet ? Colors.black : Colors.white,
  ),
)
```

I'm going to close the issue. Thank you for your work!

**Comment by dnfield** [comment]
That makes sense - currentColor was only added recently :)
