### ISSUE TITLE
Text with `text-anchor="middle"` does not center multiple words correctly

### ISSUE THREAD

**Issue by Ionaru** [dnfield/flutter_svg#654]
**Description**
When a `<text>` element has the `text-anchor="middle"` attribute and the text consists of multiple words, the text will center on the first word only, not the entire element.

Single-word `<text>` elements work correctly.

**SVG code**
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200">
    <circle cx="100" cy="100" r="35" fill="none" stroke="red" />
    <text fill="black" x="100" y="100" text-anchor="middle">Test text</text>
</svg>
```

**Expected result (Chrome)**
![image](https://user-images.githubusercontent.com/3472373/150394478-6492f628-3257-4d0b-9666-d2509aabc634.png)

**Actual result (Flutter)**, ignore image size differences.
![image](https://user-images.githubusercontent.com/3472373/150394508-650e32ad-a763-4bcf-8890-23a3b52f992f.png)

**Version info**
- flutter_svg 1.0.1
- Flutter 2.8.0
- Dart 2.15.0
- Chrome 97
- Windows 10

**Additional info**

https://www.w3.org/TR/SVG/text.html#TextAnchorProperty

**Comment by dnfield** [comment]
I think this is fixed on master but not published yet.

**Comment by dnfield** [comment]
Yeah, fixed in https://github.com/dnfield/flutter_svg/pull/621, needs to be published.

**Comment by dnfield** [comment]
Publishing in v1.0.3 right now.
