### ISSUE TITLE
Error found in FirebaseCrashlytics

### ISSUE THREAD

**Issue by bounty1342** [dnfield/flutter_svg#660]
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Failed to find definition for url(#paint0_linear). Error thrown Instance of 'GI'.
#0      FirebaseCrashlytics.recordError (package:firebase_crashlytics/src/firebase_crashlytics.dart:117:55)
#1      FirebaseCrashlytics.recordError (package:firebase_crashlytics/src/firebase_crashlytics.dart:79:27)
#2      FirebaseCrashlytics.recordFlutterError (package:firebase_crashlytics/src/firebase_crashlytics.dart:136:12)
#3      FirebaseCrashlytics.recordFlutterError (package:firebase_crashlytics/src/firebase_crashlytics.dart)
#4      reportMissingDef (package:flutter_svg/src/utilities/errors.dart:5:24)
#5      _getDefinitionPaint (package:flutter_svg/src/svg/xml_parsers.dart:164:5)
#6      parseFill (package:flutter_svg/src/svg/xml_parsers.dart:267:12)
#7      parseStyle (package:flutter_svg/src/svg/xml_parsers.dart:492:11)
#8      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:924:7)
#9      SvgParserState.startElement (package:flutter_svg/src/svg/parser_state.dart:949:12)
#10     SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:850:13)
#11     SvgParser.parse (package:flutter_svg/parser.dart:27:12)
#12     Svg.fromSvgString (package:flutter_svg/svg.dart:131:12)
#13     Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:84:30)

Sorry, can't give more context.

If can't help, feel free to close it.

version :   flutter_svg: 0.23.0+1

**Comment by dnfield** [comment]
You'd need the SVG itself, but this error indicates you have an SVG that references an undfined paint. It's very likely caused by #102
