### ISSUE TITLE
Doc improvement

### ISSUE THREAD

**Issue by marcglasberg** [dnfield/flutter_svg#662]
The doc states that:

>  While I'm making every effort to avoid needlessly changing the API, it's not guarnateed to be stable yet (hence the pre-1.0.0 version). 

But version is now 1.0.3. Also, a typo in `guarnateed`.

**Comment by dnfield** [comment]
I missed this as part of the 1.0 publish. Thanks!  Should be an easy fix

**Comment by dnfield** [comment]
Fixed in d0fd7a1
