### ISSUE TITLE
Network Image via CGI

### ISSUE THREAD

**Issue by pieterbergmans** [dnfield/flutter_svg#663]
Does flutter_svg support grabbing a network image generated via CGI. I've been trying to get this to work but no image shows up.  I'm dealing with this kind of URLs:

https://pubchem.ncbi.nlm.nih.gov/image/nfpa.cgi?code=303OX

Thanks in advance.

**Comment by dnfield** [comment]
This library just uses the Dart HTTP stuff from dart:io or dart:html depending on whether you're using VM or web. CGI should just work. You may have some other issue, please feel free to file more specific ones with reproducible cases.
