### ISSUE TITLE
Jagged edges in a svg image

### ISSUE THREAD

**Issue by CaptainDario** [dnfield/flutter_svg#665]
This package seems very promising however I seem to not get it working correctly.

I am trying to load an svg image that renders fine in edge. However when I load in in Flutter it has jagged edges.
![bug_1](https://user-images.githubusercontent.com/51273483/154283761-65ad8b69-2efc-4235-bfbd-2db279f6ee5a.png)
![bug_2](https://user-images.githubusercontent.com/51273483/154283875-757f3da0-ee42-46a4-abc5-f90350ef4e10.png)

I am using this code:

``` dart
 Container(
  color: Colors.white,
  child: SvgPicture.asset(
    'assets/artwork/onboarding_1_2.svg',
    clipBehavior: Clip.antiAlias,
  ),
),
```

Is there anything I can do to get smooth edges?
Any help would be greatly appreciated.

**Comment by CaptainDario** [comment]
It was a problem with the automatically traced SVG containing too many elements

**Comment by philqc** [comment]
> It was a problem with the automatically traced SVG containing too many elements.

Could you elaborate a bit on how you fixed this problem? Thanks

**Comment by CaptainDario** [comment]
I traced a bitmap with Inkscape and it contained lots of unnecessary overlapping layers.

![Problem](https://i.imgur.com/AZndWqB.png)

After tracing it manually it was much better but still a little jagged. For now, this is okay for me though.
