### ISSUE TITLE
Part of svg stops rendering after widget rebuild

### ISSUE THREAD

**Issue by Maatteogekko** [dnfield/flutter_svg#666]
[Here](https://github.com/Maatteogekko/flutter_svg_issue) is a repo with a minimal app reproducing the issue.
This is the app on startup:
![temp](https://user-images.githubusercontent.com/54111322/154312944-f94a1383-92a9-4f40-bb22-2df35b48a167.jpg)

This is what happens after clicking on "SetState":
![temp (1)](https://user-images.githubusercontent.com/54111322/154312971-fa932641-ee8c-446e-96ad-bc4b5f8fab3a.jpg)

The first pair of assets have a group with **opacity less than 1**, while the other two have **opacity = 1**.
I am on Flutter 2.10.1 stable.

Please let me know if something else is needed to help debug this issue

**Comment by dnfield** [comment]
@flar - I strongly suspect this is related to opacity peephole optimizations. I have confirmed that this is a regression in flutter and not related to this package directly. If it helps I can try to bisect further, but I'm pretty sure I'll hit on the engine roll where the opacity peephole optimization came internal tod isplaylists. In fact, I can check before and after that commit directly.
