### ISSUE TITLE
Case sensitive attribute names?

### ISSUE THREAD

**Issue by csga5000** [dnfield/flutter_svg#67]
I just spent like an hour trying to figure out why one of my SVG's errored and not others when rendering.
Works:
```
<svg viewBox="0 0 32 32">
	<defs>
		<linearGradient id="linearGradient4688">
			<stop stop-color="#761f24" offset="0"/>
			<stop stop-color="#962025" stop-opacity="0.35" offset="0.65"/>
			<stop stop-color="#c1272d" stop-opacity="0" offset="1"/>
		</linearGradient>
		<linearGradient y2="0" x2="0" y1="1" x1="0.5" id="linearGradient4694" xlink:href="#linearGradient4688"/>
	</defs>
	<circle fill="#c1272d" stroke="#b8cfe0" stroke-width="1.5" stroke-linejoin="round" stroke-miterlimit="4" r="15.25" cy="16" cx="16"/>
	<circle fill="url(#linearGradient4694)" stroke-miterlimit="4" r="12" cx="16" cy="16"/>
</svg>
```

Doesn't:
```
<svg viewbox="0 0 32 32">
	<defs>
		<linearGradient id="linearGradient4688">
			<stop stop-color="#761f24" offset="0"/>
			<stop stop-color="#962025" stop-opacity="0.35" offset="0.65"/>
			<stop stop-color="#c1272d" stop-opacity="0" offset="1"/>
		</linearGradient>
		<linearGradient y2="0" x2="0" y1="1" x1="0.5" id="linearGradient4694" xlink:href="#linearGradient4688"/>
	</defs>
	<circle fill="#c1272d" stroke="#b8cfe0" stroke-width="1.5" stroke-linejoin="round" stroke-miterlimit="4" r="15.25" cy="16" cx="16"/>
	<circle fill="url(#linearGradient4694)" stroke-miterlimit="4" r="12" cx="16" cy="16"/>
</svg>
```

Cause of the error:
`svg.dart:51` result of `svgRoot.toPicture` is `null` (so later assertion `pic != null` fails).

It shouldn't crash just because of casing on the viewbox should it?

**Comment by dnfield** [comment]
The implementation as is right now needs to have either a `viewBox`, a `width`, or a `height`.  And `viewBox` is case sensitive (XML is case sensitive, unlike HTML, and SVG follows the XML spec).  

It would probably be good to throw a better error though in this case.

**Comment by dnfield** [comment]
Added better error and test in bec0a13

If you think something else might be helpful here, feel free to comment/reopen the issue

**Comment by csga5000** [comment]
Thanks @dnfield!  Fantastic!  I thought even if we decided it had to be case sensitive a more graceful failure would be in order, so I'm happy to hear you did that.  Appreciate your fast assistance!
