### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_svg/flutter_svg.dart'.

### ISSUE THREAD

**Issue by FrazeColder** [dnfield/flutter_svg#673]
## Bug report

I have now recreated my problem with a new project to exclude that there is any problem with my package. When installing a fresh flutter project and adding `flutter_svg` my IDE tells me `Target of URI doesn't exist: 'package:flutter_svg/flutter_svg.dart'.` and when reloading the flutter app with `r` in the bash I get the following error:

```
lib/main.dart:2:8: Error: Error when reading
'/usr/local/Caskroom/flutter/2.10.0/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-1.0.3/lib/flutter_svg.dart': No such file or directory
import 'package:flutter_svg/flutter_svg.dart';
```

How can this be? What I am doing wrong here? I have pushed my project to github so you can see run the app as well as see the problem. Here you can find the repository: https://github.com/FrazeColder/svg_debug.

### Steps to reproduce

1. `flutter create projectname`
2. `flutter pub add flutter_svg`
3. `flutter pub get`
4. `flutter run`
5. add `import 'package:flutter_svg/flutter_svg.dart';` to the `main.dart` file.
6. Press `R` to hot reload the app

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.2
svg_debug 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- petitparser 4.4.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- xml 5.3.1 [collection meta petitparser]
```

</details>

---

**Comment by dnfield** [comment]
Perhaps your pub cache is corrupted. It should be safe to remove the whole directory and restart.  This is a bug in pub if anything though.

**Comment by FrazeColder** [comment]
@dnfield thanks for your answer. But what do you mean by "remove the whole directory and restart"?

Delete my project? Delete just the Dart SDK folder? etc.

**Comment by dnfield** [comment]
The .pub-cache folder

**Comment by mrshatner** [comment]
What is The .pub-cache folder? Where can I find it?

**Comment by Icetagchuan** [comment]
`Target of URI doesn't exist:`  
I get this problem after I use `flutter pub add ...`, then run again ` flutter packages get` , it is solved.

**Comment by iliosana** [comment]
For me, the following worked:

1. flutter clean
2. flutter packages get
3. closing and reopening Visual Studio Code
