### ISSUE TITLE
Support xlink:href for defs

### ISSUE THREAD

**Issue by csga5000** [dnfield/flutter_svg#68]
Here's the SVG:
```
<svg viewBox="0 0 32 32">
	<defs>
		<linearGradient id="linearGradient4688">
			<stop stop-color="#761f24" offset="0"/>
			<stop stop-color="#962025" stop-opacity="0.35" offset="0.65"/>
			<stop stop-color="#c1272d" stop-opacity="0" offset="1"/>
		</linearGradient>
		<linearGradient y2="0" x2="0" y1="1" x1="0.5" id="linearGradient4694" xlink:href="#linearGradient4688"/>
	</defs>
	<circle fill="#c1272d" stroke="#b8cfe0" stroke-width="1.5" stroke-linejoin="round" stroke-miterlimit="4" r="15.25" cy="16" cx="16"/>
	<circle fill="url(#linearGradient4694)" stroke-miterlimit="4" r="12" cx="16" cy="16"/>
</svg>
```

Renders fine in chrome with a red angled linear gradient in the center part caused by the inner circle.

In my app, the inner circle is plain white.  Any idea why?

**Comment by dnfield** [comment]
I don't have support for these kind of composed references for `defs` - really, the only thing you can reference right now is a gradient or a clipRect :(

**Comment by dnfield** [comment]
Renamed this issue and will leave open to track/guage interest.

**Comment by csga5000** [comment]
But regardless, is a gradient like I'm wanting (linear inside a cirlce) possible and I just need to change my svg's xml, or are you saying that's not supported?

**Comment by csga5000** [comment]
So it does work if I remove the xlink:
```
<svg viewBox="0 0 32 32">
	<defs>
		<linearGradient y2="0" x2="0" y1="1" x1="0.5" id="linearGradient4688">
			<stop stop-color="#761f24" offset="0"/>
			<stop stop-color="#962025" stop-opacity="0.35" offset="0.65"/>
			<stop stop-color="#c1272d" stop-opacity="0" offset="1"/>
		</linearGradient>
	</defs>
	<circle fill="#c1272d" stroke="#b8cfe0" stroke-width="1.5" stroke-linejoin="round" stroke-miterlimit="4" r="15.25" cy="16" cx="16"/>
	<circle fill="url(#linearGradient4688)" stroke-miterlimit="4" r="12" cx="16" cy="16"/>
</svg>
```

Still not super great w/ SVG's but this works.

Perhaps I just am not noticing a difference rendering the other SVG through your library that may well be manifesting.

**Comment by dnfield** [comment]
It looks like neither is working to my eyes - it's just that your second example it's less obvious because of the size of the paths.

Your first SVG could be refactored like this, and it will work fine:

```svg
<svg viewBox="0 0 32 32">
	<defs>
		<linearGradient id="linearGradient4688">
			<stop stop-color="#761f24" offset="0"/>
			<stop stop-color="#962025" stop-opacity="0.35" offset="0.65"/>
			<stop stop-color="#c1272d" stop-opacity="0" offset="1"/>
		</linearGradient>
      <linearGradient y2="0" x2="0" y1="1" x1="0.5" id="linearGradient4694">
        <stop stop-color="#761f24" offset="0"/>
        <stop stop-color="#962025" stop-opacity="0.35" offset="0.65"/>
        <stop stop-color="#c1272d" stop-opacity="0" offset="1"/>
      </linearGradient>
	</defs>
	<circle fill="#c1272d" stroke="#b8cfe0" stroke-width="1.5" stroke-linejoin="round" stroke-miterlimit="4" r="15.25" cy="16" cx="16"/>
	<circle fill="url(#linearGradient4694)" stroke-miterlimit="4" r="12" cx="16" cy="16"/>
</svg>
```

In fact, you could remove the `linearGradient id="linearGradient4688"` altogether.  

Your second one could also be refactored similarly.

Basically, the `xlink:href` attribute is saying "use the stops defined in the gradient over there for me". It's a nice way to keep the SVG a little smaller and more composable.  It's not impossible to support, but it hasn't been high on my list because it's not terribly difficult to work around.

**Comment by dnfield** [comment]
Implemented in dd44ee7

Still needs: 
- [ ] documentation
- [ ] decision about whether this really should be a breaking change
- [ ] clean up of paint server stuff - I don't think some of the types are used anymore

**Comment by dnfield** [comment]
I'd appreciate any feedback on whether this is really fixing the problem for all your SVGs - I added a couple tests that pass, but suspect I might be missing something for some more complicated cases.

**Comment by dnfield** [comment]
This should be working as of v0.10.1

Going to open another issue for out of order def support, which Inkscape seems to also like to do.
