### ISSUE TITLE
color parameter gets ignored in Firefox but it works in Android, iOS and Chrome

### ISSUE THREAD

**Issue by jcblancomartinez** [dnfield/flutter_svg#687]
Hi,

My code is as follows:

`SvgPicture.asset('assets/icons/home.svg',
              width: 28.toR,
              height: 28.toR,
              color: Colors.blueAccent)`
![This](https://user-images.githubusercontent.com/1192455/159950212-0ba3ddb7-d1b5-4e3f-86e9-2c7f26c307b2.svg) is the SVG file,![this](https://user-images.githubusercontent.com/1192455/159949892-c2b6ef62-1ecf-4bf8-9c39-4ac206546f76.png) is the screenshot from Chrome (Version 98.0.4758.102 (Official Build) (64-bit) on Ubuntu) and ![this](https://user-images.githubusercontent.com/1192455/159949959-c386b8aa-9d1e-4ca9-ba32-fb68becccbf9.png) is the screenshot from Firefox (98.0.1 (64-bit) on Ubuntu).

Thanks.

**Comment by dnfield** [comment]
This is a bug upstream in flutter.

**Comment by dnfield** [comment]
Are you using canvaskit or html backend?

**Comment by dnfield** [comment]
It's veyr likely that HTML backend on Firefox is not supporting `ColorFilterLayer` correctly.

**Comment by dnfield** [comment]
Yes, or see if you can use the `currentColor` on the `theme` property if they're simple enough, or avoid the HTML backend on Firefox :)

**Comment by jcblancomartinez** [comment]
Great. Would you mind creating the issue to Flutter and paste it here. I don't have the required evidence to prove the issue is in Flutter itself.

Thanks.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/100700

**Comment by jcblancomartinez** [comment]
Thank you so much.
