### ISSUE TITLE
Stroke width rendered incorrectly

### ISSUE THREAD

**Issue by wkornewald** [dnfield/flutter_svg#69]
The following image doesn't look right when rendered with flutter_svg:
[showcase-cycle.zip](https://github.com/dnfield/flutter_svg/files/2422745/showcase-cycle.zip)

**Comment by dnfield** [comment]
Hmm.  I'm incorrectly assuming that if `stroke` is not specified on an element, I can ignore any other `stroke*` properties.  I think this might be the same problem as with #62

**Comment by dnfield** [comment]
Should be fixed in 1d42460 which will be published as 0.6.1 - can you verify first?

**Comment by wkornewald** [comment]
Thanks a lot. Looks good now.
