### ISSUE TITLE
Render svg error

### ISSUE THREAD

**Issue by guchengxi1994** [dnfield/flutter_svg#690]
I have a svg file here
![_test_svg](https://user-images.githubusercontent.com/33513462/161424388-674c056c-bbc0-4037-b6be-c3c0c7d82a51.svg)
, but it rendered wrong.

In this file ,line 28, it has a ```mask``` tag， if i remove this tag , it rendered fine.

![image](https://user-images.githubusercontent.com/33513462/161424559-49de2e33-6546-4c1a-83f9-a58e478f0687.png)

**Comment by dnfield** [comment]
Which part is rendering wrong?

I would definitely remove the mask if you can since they degrade performance significantly. But on the main branch of flutter_svg this appears to render the same as in Chrome...

**Comment by guchengxi1994** [comment]
I am not familiar with svgs, but if files have mask tags , the image will be a white box.
![image](https://user-images.githubusercontent.com/33513462/161502737-a5618372-c74a-4da1-86f4-1b58904d2822.png)
![image](https://user-images.githubusercontent.com/33513462/161502906-28bbc6af-587a-4d64-831c-a03bb0331ddf.png)
once I remove the mask tag, it rendered fine,
![image](https://user-images.githubusercontent.com/33513462/161503026-e69499fd-3a35-4075-93c0-fa28780bb788.png)
![image](https://user-images.githubusercontent.com/33513462/161503154-6ec6924e-0604-44c7-b887-9fceb8fa81e2.png)
I dont know why so I open this issue.

**Comment by dnfield** [comment]
Ah! You didn't mention that you're trying this on Flutter Web. If you're using the HTML backend it probably has bugs.

**Comment by guchengxi1994** [comment]
Ok, I will try it on mobiles , thanks a lot.
