### ISSUE TITLE
SVG image button with transparent parts

### ISSUE THREAD

**Issue by okhomin** [dnfield/flutter_svg#693]
Hi! Thank you so much for the library!
The button has rounded angles and it handles my clicks if I click on transparent areas.
Is it possible to make it unclickable on the transparent areas?

`TextButton(
          style: defaultButtonStyle,
          child: SvgPicture.asset(
            scanQRButtonAsset,
            height: MediaQuery.of(context).size.height * qrButtonsScale,
          ),
          onPressed: () => {print('camera')},
        ),`

https://user-images.githubusercontent.com/37224169/162563360-488b42c5-c60e-4573-8c55-05ca1c4b5eb1.mov

**Comment by dnfield** [comment]
You'd need to make the button have the same shape, similar to how the FAB buttons work.

**Comment by okhomin** [comment]
> You'd need to make the button have the same shape, similar to how the FAB buttons work.

Could you tell me more about this, please? Maybe you have an example?

**Comment by dnfield** [comment]
The FloatingActionButton in the Flutter SDK is an example of how to make a round button.

**Comment by dnfield** [comment]
I believe if you use IconButton it will also be round by default.

**Comment by okhomin** [comment]
![image](https://user-images.githubusercontent.com/37224169/162591989-609b5ff0-c67c-4b14-9616-df51ae16c9e4.png)
I have a button like this. And I want to make the transparent area unclickable.

**Comment by dnfield** [comment]
See https://stackoverflow.com/questions/64534487/how-to-make-a-custom-button-shape-in-flutter

I don't expect to make this library support that kind of use case, it gets pretty complicated to handle generically

**Comment by okhomin** [comment]
Ok. Thank you for the help
