### ISSUE TITLE
How to change stoke ?

### ISSUE THREAD

**Issue by Vedsaga** [dnfield/flutter_svg#694]
```svg
<svg width="372" height="1" viewBox="0 0 372 1" fill="none" xmlns="http://www.w3.org/2000/svg">
<line x1="0.5" y1="0.5" x2="371.5" y2="0.5" stroke="#9D9D9D" stroke-linecap="round" stroke-width="1"  stroke-dasharray="5 5"/>
</svg>
```

I have this code...
```dart
SvgPicture.asset("assets/icons/svgs/add.svg",color: green, height: 21,width: 21)
```

 currently I could change the `height ` & `width` I was wondering similarly if I could change the `stroke` dynamically... just by passing`stroke` argument ? 
Is it possible to do this?

**Comment by dnfield** [comment]
No, but you can use the color property.

**Comment by Vedsaga** [comment]
> No, but you can use the color property.

Could this be considered future feature to be added?
