### ISSUE TITLE
Unable to get the color property in tests

### ISSUE THREAD

**Issue by muhammadmateen027** [dnfield/flutter_svg#696]
I'm trying to write a test case to detect the color for an image asset but I can't get the property of color for `SvgPicture.asset()` in test case:

Here is the widget that I used with `color` property:
```dart
SvgPicture.asset(
      'assets/icons/trending_icon.svg',
      key: const Key('icon_trending'),
      width: 15,
      color: foregroundColor,
),
```

When I try to get the property of `color`, it's not there: 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/24449076/163949299-cf8a7913-73df-49e6-9c31-374ef36c4347.png">

**Additionally**, I tried `theme` property, but it is not changing the color on runtime:
```dart
// This is not changing the color on runtime
theme: SvgTheme(
    currentColor: foregroundColor,
),
```
Package version: `flutter_svg: ^1.0.3`
Flutter version:
```dart
Flutter 2.13.0-0.1.pre • channel unknown • unknown source
Framework • revision 13a2fb10b8 (6 days ago) • 2022-04-12 15:34:25 -0500
Engine • revision 499984f99c
Tools • Dart 2.17.0 (build 2.17.0-266.1.beta) • DevTools 2.12.1
```

**Comment by muhammadmateen027** [comment]
Found solution, add this function privately in your test class: 
```dart
ColorFilter _getColorFilter(Color? color, BlendMode colorBlendMode) =>
      color == null ? null : ColorFilter.mode(color, colorBlendMode);
```

and test should expect `color` like: 
```dart
expect(widget.colorFilter, _getColorFilter(Colors.black));
```

**Comment by dnfield** [comment]
Yes, the color property does not exist on the widget.
