### ISSUE TITLE
Support for configurable color styles

### ISSUE THREAD

**Issue by gmaggio** [dnfield/flutter_svg#70]
I wonder if you can make it so that we can change individual colors via a parameter. For example, if in the SVG file it has `style` like below:

```
<style type="text/css">
	.color1{fill:#333333;}
	.color2{fill:#33CCCC;}
	.color3{fill:#DFDFDF;}
</style>
```

...then I could maybe do something like this: 

```
new SvgPicture.asset(
  assetName,
  style: {
    color1: #111111,
    color2: #eeeeee,
    color1: #aaee22,
  },
);
```

This way we don't have to have multiple SVG files of the same image but with different color variations.

**Comment by dnfield** [comment]
At one point I was considering this but leaned against it for a few reasons.

1. I have no plans to support inheritable `<style>` elements.  CSS rules are complex, and implementing them both correctly and performantly is non-trivial.  
2. I already support applying a color filter, which is probably more like what you want anyway.  It doesn't give you quite as much control over individual colors independently of one another, but it should give you the opportunity to apply a color overall to an image.  This could be improved further by upstream support for color matrix filters, which I'd like to see happen in Flutter.
