### ISSUE TITLE
Override color of DrawableRoot

### ISSUE THREAD

**Issue by FaFre** [dnfield/flutter_svg#703]
I decode my SVG's using `fromSvgBytes`. Here we can control the color via the `SvgTheme` color property.

Is it possible to paint the resulting `DrawableRoot` on the canvas using `draw()` in another color? 

I tried to construct a new `DrawableRoot` from the original one, overriding the `color` property, with the desired one. But it doesn't seem to have any effect.

**Comment by dnfield** [comment]
DrawableRoot is going away.

You can do things like applying a color filter in a saveLayer call though.
