### ISSUE TITLE
Svg rendering is messed up in Flutter 3

### ISSUE THREAD

**Issue by maboumra** [dnfield/flutter_svg#709]
Pictures were ok in flutter version 2.10.5. After changing flutter to 3.0.0 flutter_svg is rendering all pictures messed up. In Android at least.

**Comment by dnfield** [comment]
Please share an example of a now broken SVG

**Comment by maboumra** [comment]
I was trying to get an example to show you. After upgrading again to flutter 3 everything was ok. I am sorry but I really don't know what happened :(
