### ISSUE TITLE
Not compatible with connectivity_plus

### ISSUE THREAD

**Issue by zakblacki** [dnfield/flutter_svg#715]
> Because flutter_svg >=1.1.0 depends on xml ^6.0.1 and dbus >=0.2.0 depends on xml ^5.0.0, flutter_svg >=1.1.0 is incompatible with dbus >=0.2.0.
> And because nm 0.5.0 depends on dbus ^0.7.0 and no versions of nm match >0.5.0 <0.6.0, flutter_svg >=1.1.0 is incompatible with nm ^0.5.0.
> And because connectivity_plus_linux 1.3.0 depends on nm ^0.5.0 and no versions of connectivity_plus_linux match >1.3.0 <2.0.0, flutter_svg >=1.1.0 is incompatible with connectivity_plus_linux ^1.3.0.
> And because connectivity_plus 2.3.0 depends on connectivity_plus_linux ^1.3.0 and no versions of connectivity_plus match >2.3.0 <3.0.0, flutter_svg >=1.1.0 is incompatible with connectivity_plus ^2.3.0.
> So, because project depends on both connectivity_plus ^2.3.0 and flutter_svg ^1.1.0, version solving failed.

**Comment by dnfield** [comment]
That is not a bug with this package. You'll need to either use compatible dependencies or use dependency_overrides if you're sure that thee packages can work together. Before that I'd try using flutter_svg 1.0.x.
