### ISSUE TITLE
Error: The getter 'vidya_nawait' isn't defined

### ISSUE THREAD

**Issue by tusharbhambere** [dnfield/flutter_svg#717]
: Error: Expected ';' after this.
package:flutter_svg/src/picture_provider.dart:546
    final String data = vidya_nawait
                        ^^^^^^^^^^^^
: Error: The getter 'vidya_nawait' isn't defined for the class 'AssetBundlePictureProvider'.
package:flutter_svg/src/picture_provider.dart:546

- 'AssetBundlePictureProvider' is from 'package:flutter_svg/src/picture_provider.dart' ('../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-1.1.0/lib/src/picture_provider.dart').
package:flutter_svg/src/picture_provider.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'vidya_nawait'.
    final String data = vidya_nawait
                        ^^^^^^^^^^^^

**Comment by dnfield** [comment]
You have syntax errors in your project.

**Comment by tusharbhambere** [comment]
no syntax error few Hours ago app is working suddenly flutter_svg package giving this error

../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-1.1.0/lib/src/picture_provider.dart:546:25: Error: Expected ';' after this.
    final String data = vidya_nawaitz
                        ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-1.1.0/lib/src/picture_provider.dart:546:25: Error: The getter 'vidya_nawaitz' isn't defined for the class 'AssetBundlePictureProvider'.
 - 'AssetBundlePictureProvider' is from 'package:flutter_svg/src/picture_provider.dart' ('../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-1.1.0/lib/src/picture_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'vidya_nawaitz'.
    final String data = vidya_nawaitz
                        ^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/home/tbhambere/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/tbhambere/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

**Comment by dnfield** [comment]
Yes... you have edited your local pub cache, perhaps by accident. It is corrupted now. You would be best off blowing it away an letting pub refill it.
