### ISSUE TITLE
Sometimes a critical error occurs when trying to display an image

### ISSUE THREAD

**Issue by Darkos-den** [dnfield/flutter_svg#719]
SvgPicture.asset("assets/ic_image.svg")

I usually use such a widget to draw graphics in an application. In most cases, everything works fine, but sometimes a crash occurs, which I personally cannot reproduce, but reports are constantly received in the crash.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: Invalid image data. Error thrown Instance of 'ErrorDescription'.
       at .instantiateImageCodec(.java)

**Comment by dnfield** [comment]
This doesn't have a reproduction and seems ot be rooted in code not related to this package. Closing as inactionable - please share a reproducible test case to reopen.
