### ISSUE TITLE
Support <image> with base64 content

### ISSUE THREAD

**Issue by tudor07** [dnfield/flutter_svg#72]
Can you add support for this ?

`<image fill="none" height="162" width="192" xlink:href="data:image/png;base64,...image content.../>`

**Comment by dnfield** [comment]
This shouldn't be super difficult at a basic level, although in my experience raster images within SVGs tend to cause problems - you can no longer safely scale the image without loss of quality.

I'll try some experiments on it...

**Comment by dnfield** [comment]
Do you have any meaningful samples that could be used for this?

**Comment by tudor07** [comment]
Not really, I guess you can use any base64 converter to create same samples.

**Comment by dnfield** [comment]
Fiddling with this a little bit. The hardest part is deciding where to resolve the image, which must be done asynchronously - even if it's presented as base64 data, there's still a need to asynchronously instantiate it into an image codec that Flutter can use.

Off the top of my head, the options seem to either make the image resolution process happen as a pass during the async part of building the widget, or to make the parsing itself be async (which is a bigger change, but would avoid requiring two passes of the data).

**Comment by dnfield** [comment]
Implemented in acc192cdb
