### ISSUE TITLE
Unsupported operation: NaN - Unable to display Svg

### ISSUE THREAD

**Issue by ac-arconomy** [dnfield/flutter_svg#726]
I am attempting to render an Svg retreived from GraphViz and I receive the error below. I have attached the SVG file that is causing the issue. Please can you assist.

```
======== Exception caught by scheduler library =====================================================
The following UnsupportedError was thrown during a scheduler callback:
Unsupported operation: NaN

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 80:5             toInt]
dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 90:34            floor]
lib/_engine/engine/html/picture.dart 715:40                                   _computePixelDensity
lib/_engine/engine/html/picture.dart 135:15                                   recomputeTransformAndClip
lib/_engine/engine/html/surface.dart 559:5                                    preroll
lib/_engine/engine/html/picture.dart 120:11                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/scene_builder.dart 534:23                             <fn>
lib/_engine/engine/profiler.dart 34:18                                        timeAction
lib/_engine/engine/html/scene_builder.dart 529:5                              build
packages/flutter/src/rendering/layer.dart 943:35                              buildScene
packages/flutter/src/rendering/view.dart 228:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 508:18                            drawFrame
packages/flutter/src/widgets/binding.dart 892:13                              drawFrame
packages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame
lib/_engine/engine/initialization.dart 194:45                                 <fn>
====================================================================================================
```
![rule_graph](https://user-images.githubusercontent.com/24886887/176095876-bb79a12c-a6ca-4b5a-afb4-08282e3b9a1d.svg)

**Comment by ac-arconomy** [comment]
Code used to display the Svg is as follows;

SvgPicture.asset("assets/images/rule_graph.svg");

**Comment by dnfield** [comment]
I'm unable to reproduce this - I think it's probably a bug in the HTML rendering backend for web though. 

I'm using a relatively recent revision of Flutter and the latest of flutter_svg on github (which I still have to publish to pub - I'll try to do that today).

If you're able to come up with a consistent reproduction please feel free to comment.

**Comment by ac-arconomy** [comment]
Hi Dan - thanks for looking into this. I have upgraded to the latest flutter version and flutter_svg version.

Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (3 weeks ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2

flutter_svg: ^1.1.1

I still get the issue consistently when attempting to render to the image using;
SvgPicture.asset("assets/images/rule_graph.svg");

I also get a new issue (Error: XmlParserException: name expected at 4:236) when trying to parse the file as string using the SvgParser?

final SvgParser parser = SvgParser();
parser.parse(svgString, warningsAsErrors: true);

Do you have any other suggestions I might be able to try?

======== Exception caught by scheduler library =====================================================
The following UnsupportedError was thrown during a scheduler callback:
Unsupported operation: NaN

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 80:5             toInt]
dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 90:34            floor]
lib/_engine/engine/html/picture.dart 715:40                                   _computePixelDensity
lib/_engine/engine/html/picture.dart 135:15                                   recomputeTransformAndClip
lib/_engine/engine/html/surface.dart 559:5                                    preroll
lib/_engine/engine/html/picture.dart 120:11                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/surface.dart 645:18                                   preroll
lib/_engine/engine/html/scene_builder.dart 534:23                             <fn>
lib/_engine/engine/profiler.dart 34:18                                        timeAction
lib/_engine/engine/html/scene_builder.dart 529:5                              build
packages/flutter/src/rendering/layer.dart 943:35                              buildScene
packages/flutter/src/rendering/view.dart 228:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 508:18                            drawFrame
packages/flutter/src/widgets/binding.dart 892:13                              drawFrame
packages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame
lib/_engine/engine/initialization.dart 194:45                                 <fn>
====================================================================================================
Error: XmlParserException: name expected at 4:236
    at Object.throw_ [as throw] (http://localhost:3001/dart_sdk.js:5080:11)
    at iterator.XmlEventIterator.new.moveNext (http://localhost:3001/packages/xml/src/xml_events/streams/with_parent.dart.lib.js:1994:21)
    at parser_state.SvgParserState.new._readSubtree (http://localhost:3001/packages/flutter_svg/src/svg/parsers.dart.lib.js:5738:37)
    at _readSubtree.next (<anonymous>)
    at parser_state.SvgParserState.new.parse (http://localhost:3001/packages/flutter_svg/src/svg/parsers.dart.lib.js:5773:18)
    at parse.next (<anonymous>)
    at runBody (http://localhost:3001/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:3001/dart_sdk.js:40691:7)
    at parser_state.SvgParserState.new.parse (http://localhost:3001/packages/flutter_svg/src/svg/parsers.dart.lib.js:5770:20)
    at parse (http://localhost:3001/packages/flutter_svg/src/svg/parsers.dart.lib.js:6455:28)
    at parse.next (<anonymous>)
    at runBody (http://localhost:3001/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:3001/dart_sdk.js:40691:7)
    at parser$.SvgParser.new.parse (http://localhost:3001/packages/flutter_svg/src/svg/parsers.dart.lib.js:6453:20)
    at rules_provider.RulesProvider.new.getRuleGraph (http://localhost:3001/packages/arconomy/data/providers/rules_provider.dart.lib.js:75:20)
    at getRuleGraph.next (<anonymous>)
    at http://localhost:3001/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:3001/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:3001/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:3001/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:3001/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:3001/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:3001/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:3001/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:3001/dart_sdk.js:40784:13)
    at http://localhost:3001/dart_sdk.js:36261:9

======== Exception caught by scheduler library =====================================================
The following PersistedSurfaceException was thrown during a scheduler callback:
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
lib/_engine/engine/html/surface.dart 180:3                                    debugAssertSurfaceState
lib/_engine/engine/html/scene_builder.dart 294:14                             addRetained
packages/flutter/src/rendering/layer.dart 543:14                              [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1106:12                             addChildrenToScene
packages/flutter/src/rendering/layer.dart 1681:5                              addToScene
packages/flutter/src/rendering/layer.dart 938:5                               buildScene
packages/flutter/src/rendering/view.dart 228:30                               compositeFrame
packages/flutter/src/rendering/binding.dart 508:18                            drawFrame
packages/flutter/src/widgets/binding.dart 892:13                              drawFrame
packages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame
lib/_engine/engine/initialization.dart 194:45                                 <fn>
====================================================================================================








![rule_graph](https://user-images.githubusercontent.com/24886887/176322357-a7a0553a-e354-4251-9432-645107bfd9e6.svg)

**Comment by dnfield** [comment]
I do not, sorry. Maybe create a full project that reproduces this?

**Comment by ac-arconomy** [comment]
Hi Dan - I have built a new project with just the image and it works!??! It must be something to do with how the SvgPicture is wrapped in the project.

Do you recognise the Parser issue?

Thanks for your time.
