### ISSUE TITLE
请支持渐变色属性

### ISSUE THREAD

**Issue by peter100u** [dnfield/flutter_svg#732]
请支持渐变色属性，这个属性特别的重要，在绘制大图片的时候，是必要的， 请问您有计划对渐变色的支持吗

**Comment by dnfield** [comment]
Based on Google translate, this is asking for gradient color support.

Gradient colors are supported. Please share an SVG that fails to render properly.

**Comment by peter100u** [comment]
<linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(255,0,0);stop-opacity:1" />
    </linearGradient>

**Comment by peter100u** [comment]
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.dev/svgjs" viewBox="0 0 1920 1080" class="overflow-hidden rounded-md drop-shadow-lg transition duration-300 w-85screen rotate-90" style="overflow: hidden; height: 85vh;"><rect width="1920" height="1080" fill="#22194d"></rect><g clip-path="url(&quot;#SvgjsClipPath1042&quot;)"><g transform="matrix(1.15,0,0,1.15,-141.0026796340942,-81)"><path d="M0,-1080C-1.6404404403304322,-984.7827393895407,-10.185330475693709,-690.8243345838822,-9.842642641982593,-508.6964363372439C-9.499954808271477,-326.56853809060556,7.064843314847096,-165.15793578376065,2.0561270022666918,12.76738947983003C-2.952589310313712,190.6927147434207,-41.8221248598478,386.8823086777161,-39.89494051746502,558.8555152443002C-37.967756175082236,730.8287218108844,7.8952577826101304,863.095617298973,13.61923305656336,1044.606628879335C19.34320833051659,1226.1176404596968,-3.281216697651748,1462.0226895396943,-5.551088873745641,1647.9215847264718C-7.820961049839534,1833.8204799132493,-0.9251814789576068,2074.653597454412,0,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1038&quot;)"></path><path d="M480,-1080C474.70533995438075,-948.9969302488389,447.89091022057477,-572.6912454862033,448.2320397262846,-293.98158149303345C448.5731692319944,-15.271917499863548,485.6273192279484,312.1544730878265,482.0467770342591,592.2579839590193C478.46623484056977,872.361494830212,427.0899160698584,1125.349147727293,426.7487865641486,1386.6394837341231C426.40765705843876,1647.9298197409532,471.1247977606914,2031.106580622354,480,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1039&quot;)"></path><path d="M960,-1080C953.6089850253909,-975.9943485405694,926.0955982734667,-681.9169755637016,921.6539101523454,-455.9660912434161C917.212222031224,-230.0152069231306,917.7391390794776,55.62537440161563,933.3498712732716,275.705305921713C948.9606034670655,495.7852374418103,1002.9244726296847,651.4782433991828,1015.318303315109,864.513497877168C1027.7121340005333,1077.5487523551533,1016.9325726050023,1338.0024157691523,1007.7128553858174,1553.9168327896243C998.4931381666325,1769.8312498100963,967.9521425643029,2058.9861387982705,960,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1040&quot;)"></path><path d="M1440,-1080C1450.10648952239,-961.6711977872628,1508.4951150698373,-580.9586050769185,1500.63893713434,-370.02718672357685C1492.7827591988428,-159.0957683702352,1404.1737521640248,-25.213261090796294,1392.8629323870168,185.58851012004996C1381.5521126100089,396.3902813308962,1432.6020982047426,676.7107981264419,1432.7740184722916,894.7834405415008C1432.9459387398406,1112.8560829565597,1392.690123737693,1283.1549380339866,1393.8944539923111,1494.0243646104032C1395.0987842469292,1704.8937911868197,1432.3157423320517,2049.0040607684004,1440,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1041&quot;)"></path></g></g><defs><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1038"><stop stop-color="#22194d" offset="0"></stop><stop stop-color="#19194d" offset="0"></stop></linearGradient><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1039"><stop stop-color="#4734a1" offset="0"></stop><stop stop-color="#3534a1" offset="0.25"></stop></linearGradient><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1040"><stop stop-color="#8372d1" offset="0"></stop><stop stop-color="#7372d1" offset="0.5"></stop></linearGradient><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1041"><stop stop-color="#ccc6ec" offset="0"></stop><stop stop-color="#c6c6ec" offset="0.75"></stop></linearGradient><clipPath id="SvgjsClipPath1042"><rect width="1920" height="1080"></rect></clipPath></defs></svg>

**Comment by peter100u** [comment]
> Based on Google translate, this is asking for gradient color support.
> 
> Gradient colors are supported. Please share an SVG that fails to render properly.

<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.dev/svgjs" viewBox="0 0 1920 1080" class="overflow-hidden rounded-md drop-shadow-lg transition duration-300 w-85screen rotate-90" style="overflow: hidden; height: 85vh;"><rect width="1920" height="1080" fill="#22194d"></rect><g clip-path="url(&quot;#SvgjsClipPath1042&quot;)"><g transform="matrix(1.15,0,0,1.15,-141.0026796340942,-81)"><path d="M0,-1080C-1.6404404403304322,-984.7827393895407,-10.185330475693709,-690.8243345838822,-9.842642641982593,-508.6964363372439C-9.499954808271477,-326.56853809060556,7.064843314847096,-165.15793578376065,2.0561270022666918,12.76738947983003C-2.952589310313712,190.6927147434207,-41.8221248598478,386.8823086777161,-39.89494051746502,558.8555152443002C-37.967756175082236,730.8287218108844,7.8952577826101304,863.095617298973,13.61923305656336,1044.606628879335C19.34320833051659,1226.1176404596968,-3.281216697651748,1462.0226895396943,-5.551088873745641,1647.9215847264718C-7.820961049839534,1833.8204799132493,-0.9251814789576068,2074.653597454412,0,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1038&quot;)"></path><path d="M480,-1080C474.70533995438075,-948.9969302488389,447.89091022057477,-572.6912454862033,448.2320397262846,-293.98158149303345C448.5731692319944,-15.271917499863548,485.6273192279484,312.1544730878265,482.0467770342591,592.2579839590193C478.46623484056977,872.361494830212,427.0899160698584,1125.349147727293,426.7487865641486,1386.6394837341231C426.40765705843876,1647.9298197409532,471.1247977606914,2031.106580622354,480,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1039&quot;)"></path><path d="M960,-1080C953.6089850253909,-975.9943485405694,926.0955982734667,-681.9169755637016,921.6539101523454,-455.9660912434161C917.212222031224,-230.0152069231306,917.7391390794776,55.62537440161563,933.3498712732716,275.705305921713C948.9606034670655,495.7852374418103,1002.9244726296847,651.4782433991828,1015.318303315109,864.513497877168C1027.7121340005333,1077.5487523551533,1016.9325726050023,1338.0024157691523,1007.7128553858174,1553.9168327896243C998.4931381666325,1769.8312498100963,967.9521425643029,2058.9861387982705,960,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1040&quot;)"></path><path d="M1440,-1080C1450.10648952239,-961.6711977872628,1508.4951150698373,-580.9586050769185,1500.63893713434,-370.02718672357685C1492.7827591988428,-159.0957683702352,1404.1737521640248,-25.213261090796294,1392.8629323870168,185.58851012004996C1381.5521126100089,396.3902813308962,1432.6020982047426,676.7107981264419,1432.7740184722916,894.7834405415008C1432.9459387398406,1112.8560829565597,1392.690123737693,1283.1549380339866,1393.8944539923111,1494.0243646104032C1395.0987842469292,1704.8937911868197,1432.3157423320517,2049.0040607684004,1440,2160L 1920 2160 L 1920 -1080 Z" fill="url(&quot;#SvgjsLinearGradient1041&quot;)"></path></g></g><defs><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1038"><stop stop-color="#22194d" offset="0"></stop><stop stop-color="#19194d" offset="0"></stop></linearGradient><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1039"><stop stop-color="#4734a1" offset="0"></stop><stop stop-color="#3534a1" offset="0.25"></stop></linearGradient><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1040"><stop stop-color="#8372d1" offset="0"></stop><stop stop-color="#7372d1" offset="0.5"></stop></linearGradient><linearGradient x1="0.1" y1="0" x2="0" y2="1" id="SvgjsLinearGradient1041"><stop stop-color="#ccc6ec" offset="0"></stop><stop stop-color="#c6c6ec" offset="0.75"></stop></linearGradient><clipPath id="SvgjsClipPath1042"><rect width="1920" height="1080"></rect></clipPath></defs></svg>

**Comment by matrixccp** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg width="242px" height="130px" viewBox="0 0 242 130" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>4</title>
    <defs>
        <linearGradient x1="100%" y1="35.5713408%" x2="5.6907739%" y2="64.4286592%" id="linearGradient-1">
            <stop stop-color="#429EA7" stop-opacity="0.596563593" offset="0%"></stop>
            <stop stop-color="#254849" stop-opacity="0.634997815" offset="32.6026014%"></stop>
            <stop stop-color="#202327" offset="100%"></stop>
        </linearGradient>
        <rect id="path-2" x="0" y="0" width="242" height="130" rx="12"></rect>
        <filter x="-10.3%" y="-19.2%" width="124.0%" height="144.6%" filterUnits="objectBoundingBox" id="filter-3">
            <feMorphology radius="3" operator="erode" in="SourceAlpha" result="shadowSpreadOuter1"></feMorphology>
            <feOffset dx="4" dy="4" in="shadowSpreadOuter1" result="shadowOffsetOuter1"></feOffset>
            <feGaussianBlur stdDeviation="12" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur>
            <feComposite in="shadowBlurOuter1" in2="SourceAlpha" operator="out" result="shadowBlurOuter1"></feComposite>
            <feColorMatrix values="0 0 0 0 0.120187953   0 0 0 0 0.120187953   0 0 0 0 0.120187953  0 0 0 0.5 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix>
        </filter>
    </defs>
    <g id="语音房间" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="切图3" transform="translate(-492.000000, -406.000000)">
            <g id="4" transform="translate(492.000000, 406.000000)">
                <g id="矩形">
                    <use fill="black" fill-opacity="1" filter="url(#filter-3)" xlink:href="#path-2"></use>
                    <use fill-opacity="0.5" fill="url(#linearGradient-1)" fill-rule="evenodd" xlink:href="#path-2"></use>
                </g>
                <g id="编组-12" transform="translate(86.000000, 0.000000)" fill="#FFFFFF" opacity="0.199869792">
                    <polygon id="矩形" points="0 0 70 0 64 17 6 17"></polygon>
                </g>
            </g>
        </g>
    </g>
</svg>
