### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by shinayser** [dnfield/flutter_svg#735]
Hello!!!

I am developing an app that uses `SvgPicture.network` but I'm having a hard time trying to properly write some widget tests.

Anyone gots any advice?

**Comment by shinayser** [comment]
Wold like to share a way of testing that I've found:

just add `HttpOverrides.global = null;` to your `setUpAll` of your tests.

**Comment by MuTe33** [comment]
By default, no network calls are allowed in tests. You can overwrite this behaviour like this:

```dart
HttpOverrides.global = _EnableHttpOverrides();

class _EnableHttpOverrides extends HttpOverrides {}
```

**Comment by Momy93** [comment]
I had the same issue, leaving my [solution](https://github.com/dnfield/flutter_svg/issues/676#issuecomment-1199631939) here in case it helps you too.

**Comment by ikbendewilliam** [comment]
@shinayser What you can do instead is have a switch to see if you are in a test and simply render a Container instead. 
```dart
if (Platform.environment.containsKey('FLUTTER_TEST')) { 
return Container(color: Colors.red);
} 
return SvgPicture.network(...
```

Or as mentioned above, enable the network calls

**Comment by dnfield** [comment]
Do not write unit tests that actually fetch from the network, they will be flaky :)

**Comment by dnfield** [comment]
(Instead, mock out the HTTP client and just provide some asset)

**Comment by hosseinzare1** [comment]
Check out this new package: [network_media_mock](https://pub.dev/packages/network_media_mock)

[Detailed answer](https://github.com/flutter/flutter/issues/158705#issuecomment-2568882541)
