### ISSUE TITLE
must I set color ?

### ISSUE THREAD

**Issue by YDJSZY** [dnfield/flutter_svg#74]
I just show default color. but if I did't set color and it will show black color

**Comment by dnfield** [comment]
I'm not sure I understand the question...

**Comment by YDJSZY** [comment]
@dnfield I has a svg and it has default color, so I don't need to set the color.but now it show black color if I don't set the color

**Comment by dnfield** [comment]
Can you share the SVG and the Dart code you're using to render it?  And what your expected results are vs. actual?

**Comment by facundomedica** [comment]
I think what OP is saying is that he has an SVG that is already colored and he wants to keep that color without having to specify it, but if he doesn't specify the color, the result image will end up colored black.

**Comment by dnfield** [comment]
That definitely sounds like a bug, but it'd be very helpful to me to know how to reproduce it.

**Comment by ctrysbita** [comment]
#### Origin SVG output by Adobe AI
![svg_in_image_viewer](https://user-images.githubusercontent.com/8357481/47955120-10a05480-dfce-11e8-822d-d53f1616128d.png)
#### SVG rendered by flutter_svg
![svg_in_flutter](https://user-images.githubusercontent.com/8357481/47955119-10a05480-dfce-11e8-9328-17bc724940bf.png)

Well, maybe I have the same problem. The origin svg file is attached and rename to *.txt
[svg_origin.svg.txt](https://github.com/dnfield/flutter_svg/files/2545169/svg_origin.svg.txt)

**Comment by dnfield** [comment]
@ctrysbita the linked SVG has a few unsupported features:

1. Styles are specified in a `<style>` element and then referenced by `@class` attributes.  I don't plan to support that.  You could work around this by moving the style declarations inline to your shape/path elements.
2. `<image>` tag.  https://github.com/dnfield/flutter_svg/issues/72 is tracking that, it's currently unsupported but should be possible.  That said, I'd generally recommend against it if at all possible - raster images in SVG is asking for trouble.

@YDJSZY - if you have a sample, we could see if it's really the same issue or not.

**Comment by YDJSZY** [comment]
this is my code:
`new SvgPicture.asset(
                  'images/wallet-logo.svg',
                  width: 116.0,
                  height: 131.0,
                )`
now, I don't set any color, run command 'flutter run' and then some warning:

I/flutter ( 8198): ══╡ EXCEPTION CAUGHT BY SVG
╞═══════════════════════════════════════════════════════════════════════
I/flutter ( 8198): The following UnimplementedError was thrown in parseSvgElement:
I/flutter ( 8198): The <style> element is not implemented in this library.
I/flutter ( 8198):
I/flutter ( 8198): Style elements are not supported by this library and the requested SVG may not render as
intended.
I/flutter ( 8198): If possible, ensure the SVG uses inline styles and/or attributes (which are supported),
or use a
I/flutter ( 8198): preprocessing utility such as svgcleaner to inline the styles for you.
I/flutter ( 8198):
I/flutter ( 8198): Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#a703c(), name:
I/flutter ( 8198): "images/wallet-logo.svg", colorFilter: null)
I/flutter ( 8198):
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8198): unhandled element style; Picture key: AssetBundlePictureKey(bundle:
PlatformAssetBundle#a703c(), name: "images/wallet-logo.svg", colorFilter: null)
I/flutter ( 8198): unhandled element title; Picture key: AssetBundlePictureKey(bundle:
PlatformAssetBundle#a703c(), name: "images/wallet-logo.svg", colorFilter: null)

The svg show black color. this isn't what I want. my svg has default color and it look like yellow.
In a word,I don't want to set any color, I hope It look like default. thanks!

**Comment by ctrysbita** [comment]
@dnfield Thanks. If the inline style works well, I will try to convert my file.

**Comment by dnfield** [comment]
@ydjszy same thing, style elements aren't supported.  Styles must be inline.

**Comment by dnfield** [comment]
Closing this - the style part is a won't fix for now, and the image part has #72 tracking it already

**Comment by nourasharawy** [comment]
add color  parameter to SvgPicture.asset
