### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Almis90** [dnfield/flutter_svg#742]
SVG:

~~~
<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45"><g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 10c10.5 1 16.5 8 16 29H15c0-9 10-6.5 8-21" fill="#000"/><path d="M24 18c.38 2.91-5.55 7.37-8 9-3 2-2.82 4.34-5 4-1.042-.94 1.41-3.04 0-3-1 0 .19 1.23-1 2-1 0-4.003 1-4-4 0-2 6-12 6-12s1.89-1.9 2-3.5c-.73-.994-.5-2-.5-3 1-1 3 2.5 3 2.5h2s.78-1.992 2.5-3c1 0 1 3 1 3" fill="#000"/><path d="M9.5 25.5a.5.5 0 1 1-1 0 .5.5 0 1 1 1 0zm5.433-9.75a.5 1.5 30 1 1-.866-.5.5 1.5 30 1 1 .866.5z" fill="#ececec" stroke="#ececec"/><path d="M24.55 10.4l-.45 1.45.5.15c3.15 1 5.65 2.49 7.9 6.75S35.75 29.06 35.25 39l-.05.5h2.25l.05-.5c.5-10.06-.88-16.85-3.25-21.34-2.37-4.49-5.79-6.64-9.19-7.16l-.51-.1z" fill="#ececec" stroke="none"/></g></svg>
~~~

Expected result:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/7188683/182455572-34c93eac-bb57-41cf-a5c3-55826d16e10c.png">

Actual result:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/7188683/182456139-4a984cb0-79c2-47d2-a6fe-2aa841b96d53.png">

**Comment by dnfield** [comment]
Which platform?

**Comment by Almis90** [comment]
Tried on web, macos and iOS and it has same result.

**Comment by dnfield** [comment]
This is a bug in the path parsing library. Specifically, it's not handling concatenated arc commands well right now. This is a smaller reproduction

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
  <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" transform="scale(4)">
    <path d="M5.5 5.5a.5 1.5 30 1 1-.866-.5.5 1.5 30 1 1 .866.5z" fill="black" stroke="black" />
  </g>
</svg>
```

**Comment by dnfield** [comment]
Ahh it's not even just back to back arcs, the decomposition math is wrong for the arcs in here.

**Comment by dnfield** [comment]
path_parsing is failing to convert degrees to radians when doing a matrix rotation operation. Ugh. How did this ever work.

**Comment by dnfield** [comment]
I have a fix for this and I'm very curious how many golden image tests it breaks in google.

**Comment by Almis90** [comment]
> I have a fix for this and I'm very curious how many golden image tests it breaks in google.

**Comment by Almis90** [comment]
Closed by mistake, just wanted to leave comment

**Comment by dnfield** [comment]
No, sorry - this package is used internally at Google by a large number of golden image tests. Fixing this could potentially change them if people accepted this mistake. Luckily, it looks like not many of the tests internal to Google use this feature :)

I'll be publishing a fix for this soon.

**Comment by dnfield** [comment]
(In other words - this is a real bug, but it's been around since I created this package so some people might be depending on the incorrect behavior, which is sad)

**Comment by Almis90** [comment]
Just tested, works great!

**Comment by dnfield** [comment]
For future me:the reason this wasn't caught sooner is because most usages that were ever seriously tested were circular (or roughly circular) arc commands, where the rotation didn't make a difference.
