### ISSUE TITLE
Unable to display SVGs with <g><image(base64)>

### ISSUE THREAD

**Issue by AlexV525** [dnfield/flutter_svg#749]
The preview is entirely empty.

Source SVG: https://qbc6i-daaaa-aaaah-qcywq-cai.raw.ic0.app/?tokenid=lrmer-zqkor-uwiaa-aaaaa-b4awf-uaqca-aaavk-q

**Comment by dnfield** [comment]
Pretty sure the bug here is that flutter_svg is expecting there to be `width`/`height` attributes, which aren't necessarily required by the spec.
