### ISSUE TITLE
SVGs with entirely contained cutouts do not render the cutout

### ISSUE THREAD

**Issue by sdxv** [dnfield/flutter_svg#75]
Firstly I apologize as I don't think I have the proper terminology to address the issue with the correct term, however I think I can still clearly communicate the issue.

Image reference of the issue:
https://imgur.com/a/QqKvLcK

As you can see in the first image on the imgur link, there is an svg that is comprised of 5 ovals. There is one oval that is the main shape, and then four ovals that have been subtracted from the main oval to create cutouts. with the exception of the bottom left oval all cutout ovals have been ignored in the rendered image. The bottom left oval overlaps the edge of the main oval and thus becomes a part of the shape outline. The others are wholly contained within (is compound path the correct term for this?).

I have attached the file which is just a quick test I made, but have seen the same issue in other files as well.
[test.svg.txt](https://github.com/dnfield/flutter_svg/files/2545257/test.svg.txt)

Thanks for looking!

**Comment by dnfield** [comment]
Looks like `fillrule` isn't getting inherited properly.  I've seen issues related to this.  

As a temporary work around, you can move the `fillrule` style portion down to the affected element.

**Comment by dnfield** [comment]
Should bef ixed in the latest commit - if you can take a look, I'll publish it shortly in 0.6.4

**Comment by dnfield** [comment]
(Fixed in dc5bce8 that is)

**Comment by dnfield** [comment]
Closing this for now - let me know if 0.6.3 didn't actually fix this (feel free to reopen or open a new issue).

**Comment by sdxv** [comment]
Thank you! Works perfectly.
