### ISSUE TITLE
SVG doesn't render correctly

### ISSUE THREAD

**Issue by seanharding** [dnfield/flutter_svg#753]
The attached SVG does not render correctly in flutter_svg. I'm not intimately familiar with the SVG format, but it appears that most or all of the gradients are rendering as white. This is with flutter_svg 1.1.4 and Flutter 3.0.5. Screenshot is from iOS.

**Correct Rendering**
<img width="100" alt="Screen Shot 2022-08-23 at 20 55 12" src="https://user-images.githubusercontent.com/2908560/186300781-65a229cc-a883-43da-8ade-e236bc7365ef.png">

**flutter_svg rendering**
<img width="69" alt="Screen Shot 2022-08-23 at 20 55 19" src="https://user-images.githubusercontent.com/2908560/186300786-ea127597-3987-4f2e-900a-539f80aab020.png">

**SVG File**

![coffee_cup](https://user-images.githubusercontent.com/2908560/186300769-e7379dc8-3054-465b-9b8d-469086afd605.svg)

**Comment by dnfield** [comment]
#102 - although if I open this SVG in a new tab it also doesn't render correctly...

This should render fine in package:vector_graphics.
