### ISSUE TITLE
svg on macOS High Sierra  10.13.6 (17G65) does not render correctly

### ISSUE THREAD

**Issue by gaodeng** [dnfield/flutter_svg#757]
svg on macOS High Sierra 10.13.6 (17G65)  does not render correctly, some svg is broken, some svg does not show anything.
But strangely enough it renders perfectly fine on macOS monterey 12.4.

## macOS High Sierra 10.13.6 (17G65) does not render 
<img width="999" alt="Screen Shot 2022-08-27 at 3 35 34 PM" src="https://user-images.githubusercontent.com/1118249/187055369-4bdc3c70-4b8b-4157-92f7-341a0b613471.png">

## macOS monterey 12.4
<img width="992" alt="Screen Shot 2022-08-28 at 10 07 11" src="https://user-images.githubusercontent.com/1118249/187055372-96164604-1b1a-4011-8e82-249036bf5e83.png">

## Here are the svg files
[urban.zip](https://github.com/dnfield/flutter_svg/files/9439015/urban.zip)

**Comment by dnfield** [comment]
Flutter has dropped support for 10.13.

This is, in all likelihood, an issue with the GL backend. But that backend is now gone. Closing this as infeasible.

**Comment by dnfield** [comment]
(Part of why Flutter is dropping support fo 10.13 is that supporting the GL backend on macOS is really hard because Apple has lots of bugs in its GL implementation and has dropped support for GL based tooling, so it's super hard to fix stuff if it goes wrong)
