### ISSUE TITLE
SVG disappears in iOS PWA

### ISSUE THREAD

**Issue by bukunmialuko** [dnfield/flutter_svg#760]
SVG disappears in iOS PWA app.

Icons:
![ic_copy](https://user-images.githubusercontent.com/28612861/187623331-4bf58139-90a1-486e-b3ce-33862d33aa1e.svg)

![ic_time](https://user-images.githubusercontent.com/28612861/187623385-010a9c53-b33c-4b87-ad87-64dfb12d0271.svg)

Example.

https://user-images.githubusercontent.com/28612861/187623247-6fb55256-b08c-40b1-b4a5-4f69888ed959.mp4

**Comment by dnfield** [comment]
I need a reproduction to be able to work on this. But it's probably a bug in the HTML backend engine implementation.

**Comment by dnfield** [comment]
Closing this, if ther'es a small reproduction please add and let's reopen.
