### ISSUE TITLE
flutter: Bad state: Could not parse "null" as a color.

### ISSUE THREAD

**Issue by simanlx** [dnfield/flutter_svg#764]
lutter: ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
flutter: The following StateError was thrown resolving a single-frame picture stream:
flutter: Bad state: Could not parse "null" as a color.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      SvgParserState.parseColor (package:flutter_svg/src/svg/parser_state.dart:1799:5)
flutter: #1      SvgParserState.parseStroke (package:flutter_svg/src/svg/parser_state.dart:1357:21)
flutter: #2      SvgParserState.parseStyle (package:flutter_svg/src/svg/parser_state.dart:1621:15)
flutter: #3      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:955:7)
flutter: #4      SvgParserState.startElement (package:flutter_svg/src/svg/parser_state.dart:985:12)
flutter: #5      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:881:13)
flutter: <asynchronous suspension>
flutter: #6      SvgParser.parse (package:flutter_svg/parser.dart:27:12)
flutter: <asynchronous suspension>
flutter: #7      Svg.fromSvgString (package:flutter_svg/svg.dart:139:12)
flutter: <asynchronous suspension>
flutter: #8      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:90:34)
flutter: <asynchronous suspension>
flutter:
flutter: Picture provider: ExactAssetPicture(name: "assets/images/BottomBar/txl_1.svg", bundle: null,
flutter:   colorFilter: null)
flutter: Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#d1fa3(), name:
flutter:   "assets/images/BottomBar/txl_1.svg", colorFilter: null, theme: SvgTheme(currentColor:
flutter:   Color(0xff000000), fontSize: 15.0, xHeight: 7.5))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: getUnhandledGroupApplicationCount-----------0}
[log] ** "SplashLogic" onDelete() called, isError [false]
[log] ** "SplashLogic" deleted from memory, isError [false]
flutter: Another exception was thrown: Bad state: Could not parse "null" as a color.

**Comment by simanlx** [comment]
Positioned(
                top: 6.h,
                child:item.shuxing==1?SvgPicture.asset(
                  i == index ? item.selectedImgRes : item.unselectedImgRes,
                  width: item.imgWidth,
                  height: item.imgHeight,

                )
                    :
                Image.asset(
                  i == index ? item.selectedImgRes : item.unselectedImgRes,
                  width: item.imgWidth,
                  height: item.imgHeight,
                ),
              ),

**Comment by sanket-vekariya** [comment]
Facing the same issue.. Any updates?

**Comment by dnfield** [comment]
`null` is not a valid color.

I think I can probably relax the check here though - browsers are more permissive and just default to black in this case.
