### ISSUE TITLE
Artifacts/pixelated iOS rendering compared to Android

### ISSUE THREAD

**Issue by miquelbeltran** [dnfield/flutter_svg#769]
We noticed that SVGs are looking slightly different on our iOS builds than our Android builds.

These two screenshots show the difference: (from uncompressed PNGs, images not scaled) 

![svg_android_ios](https://user-images.githubusercontent.com/2494376/189057623-a3056950-f7b1-4896-ba0b-bb6e4864895e.png)

The Android one is made with a Pixel 5, the iOS one is made with an iPhone 12 Mini.

Here is the "eye" SVG:

```
<svg width="37" height="23" viewBox="0 0 37 23" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M18.5022 0C4.625 0 0 11.5 0 11.5C0 11.5 4.625 23 18.5 23C32.375 23 37 11.5 37 11.5C37 11.5 32.3772 0 18.5022 0ZM18.5022 20.7C8.40377 20.7 3.87127 13.943 2.56254 11.5C3.87633 9.0505 8.40883 2.3 18.5022 2.3C28.5984 2.3 33.1287 9.05481 34.4396 11.5C33.1244 13.9495 28.5919 20.7 18.5022 20.7Z" fill="#495057"/>
<path d="M18.5022 11.5001V4.6001C14.6685 4.6001 11.5625 7.68929 11.5625 11.5001C11.5625 15.3109 14.6685 18.4001 18.5 18.4001C22.3294 18.4001 25.4375 15.3109 25.4375 11.5001C25.4375 9.59325 24.6585 7.86825 23.4025 6.62194L18.5022 11.5001Z" fill="#495057"/>
</svg>
```

The builds have been generated on CI, with the Flutter version 3.3.1

flutter_svg version is 1.1.4

Any hints on how to improve the SVG rendering on iOS are welcome.

**Comment by dnfield** [comment]
Likely due to bugs related to https://github.com/flutter/flutter/issues/111231

**Comment by miquelbeltran** [comment]
Thanks for the hint! Likely indeed, as I think this issue started appearing soon after adopting 3.3.0 (at least there were no complaints until then)

**Comment by miquelbeltran** [comment]
Just to confirm, the issue seems to be gone since Flutter 3.3.2
