### ISSUE TITLE
Flutter 3.3.0

### ISSUE THREAD

**Issue by kirill-21** [dnfield/flutter_svg#770]
After update:
![image](https://user-images.githubusercontent.com/63228361/189084272-3cfc2701-ba61-4b47-a4c3-93e085e0c015.png)

Before update:
![image](https://user-images.githubusercontent.com/63228361/189084333-f3fd76c6-fae9-4997-b22e-9d81ae8dab4a.png)

```
SvgPicture.asset(
  'resources/icons/minimize.svg',
  color: Colors.white,
  height: 7.0,
),
```
Icon:
![minimize](https://user-images.githubusercontent.com/63228361/189084817-b11bd294-fce8-46bb-b601-e49b55ca33f7.svg)

If i change size from 7.0 to 8.0 the issue will disappear, what is it?

**Comment by maitycyrus** [comment]
Since Flutter 3.3.0 I recognized glitches on certain more "complex" SVGs iPhone 12. They happen like every 2-5 minutes and just for 1-2 frames.

**Comment by dnfield** [comment]
This is almost certainly a bug in Flutter, probably the one about raster caching - see e.g. https://github.com/flutter/flutter/issues/111231 for the CP request that should fix this.
