### ISSUE TITLE
What is the reason why some image url cannot be loaded?

### ISSUE THREAD

**Issue by wds1181977** [dnfield/flutter_svg#778]
https://openseauserdata.com/files/ce05bcf17232f70ac6706b9600331430.svg 
Many urls like this cannot be opened，but the browser can be opened. 

dependencies:
  flutter_svg: ^1.1.5

`SvgPicture.network(
  'https://openseauserdata.com/files/ce05bcf17232f70ac6706b9600331430.svg',
  placeholderBuilder: (BuildContext context) => Container(
      padding: const EdgeInsets.all(30.0),
      child: const CircularProgressIndicator()),
);`

`[✓] Flutter (Channel unknown, 3.0.3, on macOS 11.6 20G165 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.3 at /Users/yolo/Library/flutter
    • Upstream repository unknown
    • Framework revision 676cefaaff (3 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yolo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/yolo/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • ds的iPhone (mobile) • 00008110-001679243632801E • ios            • iOS 15.7
      19H12
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS
      11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                    • web-javascript • Google
      Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available`

**Comment by dnfield** [comment]
The error message you got should have explained this - see #105
