### ISSUE TITLE
SvgPicture.asset Color Property Not Working with Impeller Enabled

### ISSUE THREAD

**Issue by cliftonlabrum** [dnfield/flutter_svg#781]
I'm on **Flutter 3.3.3** and I decided on a whim to try turning on Impeller. I added this to the `Info.plist` file of my iOS app:
```
<key>FLTEnableImpeller</key>
<true/>
```
Without making any other changes, I built my app and all the SVG icons in my app that use the `color` property no longer use that color. They default to whatever is hard-coded in the SVG file itself.

```
SvgPicture.asset(
  'assets/images/file.svg',
  color: Color(0xFFFFFFFF), //<-- No longer working;
  width: width,
  height: height,
  fit: BoxFit.scaleDown,
)
```
And here's the SVG file I reference:
```
<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="omitted for simplicity..." fill="#888C96"/>
</svg>
```
I only see the `#888C96` color and not the `#FFFFFF` that I use to override the `color` property with.

I'm testing this on an iPhone device running iOS 16.0.2. Is there anyone else seeing this? Is there something I need to do differently?

**Comment by dnfield** [comment]
This is an issue with impeller, probably something where the color filter source isn't getting applied correctly. Does this reproduce with just any path?

**Comment by dnfield** [comment]
Almost certainly https://github.com/flutter/flutter/issues/110672
