### ISSUE TITLE
Does not render some default stock icons without further optimisation

### ISSUE THREAD

**Issue by tigtms** [dnfield/flutter_svg#783]
When working with an SVG string within Flutter web (rendering as HTML), taking [this example](https://icon-sets.iconify.design/bi/chat-left-dots/) from Bootstrap icons, it renders incorrectly without further optimisation.

The icon string had to be fed through SVGCleaner utility with its output then pasted into https://www.svgviewer.dev/, and then optimised.

I wrote a quick test which can be accessed at this [sandbox](https://svgsandbox.web.app).

**Comment by dnfield** [comment]
I'm not able to reproduce this.

I used this SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" preserveAspectRatio="xMidYMid meet"
    viewBox="0 0 16 16">
    <g fill="currentColor">
        <path
            d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
        <path d="M5 6a1 1 0 1 1-2 0a1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0a1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0a1 1 0 0 1 2 0z" />
    </g>
</svg>
```

On or near Flutter ToT and flutter_svg ToT. It looks the same in desktop, Chrome CanvasKit, and Chrome HTML.

**Comment by dnfield** [comment]
If you can share a project that reproduces this let me know - I can definitely see the issues in your link but it's not clear to me where the bug might be.

**Comment by dnfield** [comment]
oh!

This is something weird with save layers in HTML. If I add a `color` to the SVG it renders badly on HTML.

**Comment by dnfield** [comment]
Remove the `color` parameter from your `SvgPicture` constructors.

Color filtering on the HTML backend in general sometimes just doesn't work and fails in strange ways.
