### ISSUE TITLE
Big svgs don't render in golden tests

### ISSUE THREAD

**Issue by ValentinVignal** [dnfield/flutter_svg#786]
I have a simple test:

```dart
await tester.pumpWidget(
  SvgPicture.asset(
    'assets/my-svg.svg',
  )
);

await expectLater(find.byType(SvgPicture)), matchesGoldenFile('my_golden_file.png'));
```

When the SVG is big enough (I guess more that 50KB), the golden image doesn't display the SVG.

I suppose this is because the load of the asset is done in an isolate.

https://github.com/flutter/flutter/blob/aab696c236e3dbd231deb5b6067d2125c72a546f/packages/flutter/lib/src/services/asset_bundle.dart#L82-L95 :

```dart
    // 50 KB of data should take 2-3 ms to parse on a Moto G4, and about 400 μs
    // on a Pixel 4.
    if (data.lengthInBytes < 50 * 1024) {
      return utf8.decode(data.buffer.asUint8List());
    }
    // For strings larger than 50 KB, run the computation in an isolate to
    // avoid causing main thread jank.
    return compute(_utf8decode, data, debugLabel: 'UTF8 decode for "$key"');
```

What would you recommend me to do to be able to see the SVG in the golden?

**Comment by dnfield** [comment]
There's a fair amount of complexity around this that isn't related to this package, but it should get better after #782 

I'm going to close this for now though, since fixing it there is sort of an unintentional side effect.
