### ISSUE TITLE
Icon bug when rendering with html

### ISSUE THREAD

**Issue by gabriel-cervantes** [dnfield/flutter_svg#787]
flutter_svg: ^1.1.5
Flutter: 3.3.4

> ### HTML
![image](https://user-images.githubusercontent.com/77002762/195619415-4bc96422-4257-4800-88ca-e08f6beac7a7.png)

---

> ### Canvas
![image](https://user-images.githubusercontent.com/77002762/195619746-a2b9c3f2-e617-4cb4-ad2f-f48d38433dbb.png)

![image](https://user-images.githubusercontent.com/77002762/195624463-382300a4-695e-465b-91d9-a3128d037d21.png)

**Comment by dnfield** [comment]
the HTML backend has bugs in its `saveLayer` implementation, which is how `color` is applied.
