### ISSUE TITLE
Section of image is not being rendered

### ISSUE THREAD

**Issue by s15-coder** [dnfield/flutter_svg#791]
I have this svg which renders partially, the "x" in the image is not being shown:
PDTA: The background in the screenshot is applied with a flutter color, no problem there.

How it looks rendered in flutter:
![image](https://user-images.githubusercontent.com/57452504/196855219-6e2741a4-e46a-4be2-85f0-19472bb5b2fc.png)

How it is:
![blacklisted_kyc (1)](https://user-images.githubusercontent.com/57452504/196854361-d5d08dd4-ad71-4a24-9f60-ba5b3157df37.svg)

**Comment by FeodorFitsner** [comment]
Try updating `flutter_svg` to the latest 1.1.6. This is how its being rendered for me in Flutter with 1.1.6:

![image](https://user-images.githubusercontent.com/5041459/198400083-764124f4-a1c6-42dc-b5bb-dedd1c3b952d.png)

**Comment by dnfield** [comment]
I believe this is fixed in the latest release, please ping this back if that's not the case.
