### ISSUE TITLE
[FR] copyWith support for SvgPicture

### ISSUE THREAD

**Issue by EnesKaraosman** [dnfield/flutter_svg#800]

**Comment by dnfield** [comment]
What does this mean?

**Comment by EnesKaraosman** [comment]
Is it possible to override let’s say color of an svg before rendering.
Imagine I’m getting the svg from 3rd party dependency

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Dan Field ***@***.***>
Gönderildi: Sunday, October 30, 2022 8:51:33 AM
Kime: dnfield/flutter_svg ***@***.***>
Bilgi: Enes Karaosman ***@***.***>; Author ***@***.***>
Konu: Re: [dnfield/flutter_svg] [FR] copyWith support for SvgPicture (Issue #800)


What does this mean?

**Comment by dnfield** [comment]
No, you'd have to do those transformations yourself on the XML, and I don't think that will ever be supported by this package. However, some color mapping support will be added in #782

**Comment by NikolayKantur** [comment]
any updates for this features?

i want to use it like

final SvgPicture icon;

icon.copyWith(width: 20, height: 20, color: Colors.red); ----- something like that
