### ISSUE TITLE
Circles are not rendered on flutter web

### ISSUE THREAD

**Issue by santiagos01** [dnfield/flutter_svg#801]
Expected (with https://www.svgviewer.dev/):
<img src="https://user-images.githubusercontent.com/113275441/199544772-81a47ae3-e588-4a2b-8e52-4cc13ba5bb2b.png" width=100>

Actual (with `flutter_svg`):
<img src="https://user-images.githubusercontent.com/113275441/199544670-f1ea88ef-38f6-4da3-bb44-9b6d1f0e1647.png" width=100>

Svg file:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300" shape-rendering="geometricPrecision" text-rendering="geometricPrecision">
  <path d="M4.263 150c0-80.44 65.21-145.65 145.65-145.65S295.561 69.56 295.561 150s-65.21 145.65-145.65 145.65S4.262 230.44 4.262 150Z" fill="#323232"/>
  <g fill="#fff" stroke-width="0">
    <rect width="9.442" height="33.379" rx="3" ry="3" transform="matrix(1.37574 -.79429 .188668 1.53577 60.752 102.702)"/>
    <rect width="9.442" height="33.379" rx="3" ry="3" transform="matrix(1.37574 .79429 -.188668 1.53577 226.194 95.202)"/>
    <circle transform="rotate(-1.106 4910.273 -12168.09) scale(1.07329)" r="17.47"/>
    <circle transform="rotate(-1.106 4792.566 -3245.096) scale(1.07329)" r="17.47"/>
  </g>
</svg>
```

**Comment by dnfield** [comment]
CanvasKit or HTML?

**Comment by dnfield** [comment]
Looks like these aren't getting rendered on any platform :) Probably a bug in the circle handling code and/or transform handling.

**Comment by dnfield** [comment]
Sorry for the delay, you can work around this temporarily by using a less complicated matrix (i.e. remove the `scale(1.07329)`) if that's visually acceptable. Otherwise you'll have to wait for the fix to roll through.
