### ISSUE TITLE
Async SvgPicture constructors

### ISSUE THREAD

**Issue by nanokatze** [dnfield/flutter_svg#804]
My program puts an SvgPicture inside an InteractiveWidget and InteractiveWidget transforms SvgPicture's placeholder, which is not desirable. Given that Flutter has FutureBuilder, if SvgPicture had async constructors (as in, static methods that construct SvgPicture objects), one could just pass Future<SvgPicture> into the future parameter of FutureBuilder, and manage placeholders by themselves.

This potentially would also let flutter_svg somewhat shrink in terms of LOC, if sync constructors were reimplemented in terms of async ones + FutureBuilder.

**Comment by dnfield** [comment]
There's no such thing as an async constructor in Dart.

You can interact with the picture provider yourself, although that's about to go away. Otherwise you could interact with `vg.loadPicture` in the upcoming release.

**Comment by nanokatze** [comment]
By "async constructor" I really meant just async static method on SvgPicture that would construct objects of that type. It's clarified in the original issue message too.

I tried to use picture provider directly in some way, but I didn't find out how one would wait for it to "load" the data externally, IIRC the necessary method was marked protected.

Regardless, thank you for the answer, looking forward to the upcoming release and seeing if that addresses my wants :-)
