### ISSUE TITLE
precachePicture only work in en locale

### ISSUE THREAD

**Issue by Nolomon** [dnfield/flutter_svg#810]
In splash screen I await the caching future using:
precachePicture(
                          NetworkPicture(
                              SvgPicture.svgByteDecoderBuilder, imageUrl),
                          context,
);
Then, the app navigates to a different screen which has the SvgPicture.network() widget.
When app is in "en" English locale all fine; the SVG is cached, but when it's in "ar" Arabic locale the SVG will still reload as if not cached.

I have checked some PictureConfiguration parameters to see if any differs between the Splash and Home screens, like (asset bundle, locale, text direction) but they're all equal.

**Comment by dnfield** [comment]
The cache uses the locale as part of the key in case you mean to have different assets per locale

**Comment by Nolomon** [comment]
Thanks for the replay, the locale isn't changing during the experiment, it is the same start to finish. But if it was in English cache work, if it's in Arabic it doesn't. Could it be that I need to specify viewBox?
