### ISSUE TITLE
<text> element is not rendering.

### ISSUE THREAD

**Issue by aadi-github** [dnfield/flutter_svg#814]
Hi, I am loading an SVG that contains a TEXT element which is not rendering, other than that all the paths are rendered properly.
Below is the actual image ...
![AC Motor](https://user-images.githubusercontent.com/89453528/204284954-b9394183-66e2-4720-b0af-a9e33ce26f06.svg)

![image](https://user-images.githubusercontent.com/89453528/204285574-431c91fc-8284-4355-8740-a4dd22a0944a.png)In the above image, "M" will not get shown but the shape is there.

Below is the SVG created by the steps mentioned on the page for Adobe Illustrator still, no luck "M" gets vanished completely.

![ac_motor2](https://user-images.githubusercontent.com/89453528/204283581-64ae1b6d-824e-4afe-8fb0-1f564aedb788.svg)

Please let me know what can be done. Below is the output I am getting by doing both above mentioned.
![image](https://user-images.githubusercontent.com/89453528/204286237-3ce7eb09-07cd-4cba-ba32-3adfc2e83490.png)

**Comment by jonahwilliams** [comment]
On the latest vector_graphics based backend this appears to be working as expected.

![204284954-b9394183-66e2-4720-b0af-a9e33ce26f06](https://user-images.githubusercontent.com/8975114/204977558-d700147e-6e34-4f20-89cc-8b8004e2956b.svg)

Leaving this open as this has not been released yet

**Comment by dnfield** [comment]
Confirmed this works with the latest release.

Note that the actual SVG you linked to has a bunch of other unsupported stuff like foreign elements and a `switch` element, which is part of the SVG2 specification and not (yet?) implemented by this library.
