### ISSUE TITLE
attribute opacity at svg level is ignored?

### ISSUE THREAD

**Issue by revever** [dnfield/flutter_svg#825]
Firstly many thanks for this nice library.

However, for the svg below, the opacity at svg level is not rendered:
`<svg viewBox="0 0 100 100" opacity="0.1" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40" fill="green" /></svg>`

Under debug, I see that the opacity is correctly parsed as groupOpacity in DrawableRoot. Is this a bug or not-supported feature? Thanks for your help.

**Comment by dnfield** [comment]
I can reproduce this on master. This probably isn't a hard fix but I'm not quite sure when I'll get to it rightnow.

**Comment by revever** [comment]
> I can reproduce this on master. This probably isn't a hard fix but I'm not quite sure when I'll get to it rightnow.

Glad to hear that there will be a fix. For the moment, my workaround is to programmatically move the opacity into an additional group just under the DrawableRoot, something like:
`<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <g opacity="0.1">
	<circle cx="50" cy="50" r="40" fill="green" />
  </g>
</svg>`

**Comment by dnfield** [comment]
This has been fixed in the latest release.
