### ISSUE TITLE
Unable to load asset, when filename has accent

### ISSUE THREAD

**Issue by ebadta81** [dnfield/flutter_svg#826]
Hello,

i have a simple ```SvgPicture.asset("media/cikkcsoport/$cikkcsoportkod.svg")``` in my code, and if the ```$cikkcsoportkod``` has accented value, flutter cannot load the asset.

I use ```flutter_svg: ^1.1.6```

**It works with unaccented filenames**, only the accented ones drop error messages like:

```
════════ Exception caught by SVG ═══════════════════════════════════════════════
The following assertion was thrown resolving a single-frame picture stream:
Unable to load asset: media/cikkcsoport/AÍ.svg

When the exception was thrown, this was the stack
#0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:258
<asynchronous suspension>
#1      AssetBundle.loadString
package:flutter/…/services/asset_bundle.dart:83
<asynchronous suspension>
#2      AssetBundlePictureProvider._loadAsync
package:flutter_svg/src/picture_provider.dart:546
<asynchronous suspension>
Picture provider: ExactAssetPicture(name: "media/cikkcsoport/AÍ.svg", bundle: null, colorFilter: null)
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#17a4a(), name: "media/cikkcsoport/AÍ.svg", colorFilter: null, theme: SvgTheme(currentColor: Color(0xff000000), fontSize: 14.0, xHeight: 7.0))
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Unable to load asset: media/cikkcsoport/AÓ.svg
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Unable to load asset: media/cikkcsoport/AÁ.svg
════════════════════════════════════════════════════════════════════════════════
```

How can I resolve this problem?

**Comment by dnfield** [comment]
Are you able to load this asset using just `rootBundle.loadString`?

Are you sure you have spelled it correctly, using exactly the same characters/codepoints?

**Comment by ebadta81** [comment]
Yes, I put the ```final res = rootBundle.loadString("media/cikkcsoport/AÓ.svg");``` test code in my main fn, and it is running without error.

I am sure, I spelled it correctly. Copy - pasting from the error message i get 
```
$ ls media/cikkcsoport/AÓ.svg
media/cikkcsoport/AÓ.svg
```

**Comment by dnfield** [comment]
It would probably help to have a full reproduction. I also suspect this is some platform-specific issue and related to Flutter or the tool rather than flutter_svg.

**Comment by ebadta81** [comment]
I suspect the same

**Comment by jonahwilliams** [comment]
Note that there is a related issue we've seen where the unicode representation of the file is actually different from the unicode representation of the string you've typed out. This can be verified by checking the raw bytes of the file path and comparing to the raw bytes of the string you've typed.

**Comment by jonahwilliams** [comment]
(This is specific to the flutter tooling and not a flutter_svg issue though)

**Comment by ebadta81** [comment]
I can confirm, it is some argument at creating the flutter project.

Now I created a new flutter project from VSCode, and copy the relevant files to it.

Now I can open all my svg-s.

**Comment by dnfield** [comment]
I'm going to close this issue - @jonahwilliams may know of an upstream issue that's relevant, or feel free to open one with details about your version of flutter, what platform(s) are affected, and a sample project if possible in flutter/flutter.
