### ISSUE TITLE
Migration guide for `color` is deprecated.

### ISSUE THREAD

**Issue by eli1stark** [dnfield/flutter_svg#828]
In the version 2 of `flutter_svg` the `color` argument is deprecated, what to use instead? `ColorFilter`, if so, which one?

Three of them visually look the same:
`ColorFilter.mode(color, BlendMode.srcIn)`
`ColorFilter.mode(color, BlendMode.modulate)`
`ColorFilter.mode(color, BlendMode.srcATop)`

**Comment by dnfield** [comment]
Thanks, updated the readme. Use srcIn for the example.

**Comment by dnfield** [comment]
The reason I did this is that Flutter has added more advanced color filtering possibilities since this library was written, e.g. to do matrix based filters.
