### ISSUE TITLE
`fill` is ignored in when copying a path

### ISSUE THREAD

**Issue by pento** [dnfield/flutter_svg#832]
## Bug Description

I ran into this bug whilst testing version 2.0.0-dev.2, it's a change in behaviour from 1.1.6.

It appears that `<use xlink:href='#somepath'/>` no longer copies the `fill` attribute from the source path.

The same behaviour also occurs if I use `vector_graphics_compiler` to pre-compile the SVG.

## Test Case

This example SVG demonstrates the bug, as shown in the screenshots below.

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" height="24" width="24" id="sun">
    <g>
        <g transform="" style=""><g xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="sun">
        <circle style="fill:#ffd54f" id="sphere" cx="12" cy="12" r="5"/>

        <path d="M 12,2                L 14.5,5.5                A 7,7 0 0,0 9.5,5.5                Z" id="sunbeam" fill="#ffd54f"/>

        <use transform="rotate(60,12,12)" xlink:href="#sunbeam"/>
        <use transform="rotate(120,12,12)" xlink:href="#sunbeam"/>
        <use transform="rotate(180,12,12)" xlink:href="#sunbeam"/>
        <use transform="rotate(240,12,12)" xlink:href="#sunbeam"/>
        <use transform="rotate(300,12,12)" xlink:href="#sunbeam"/>
    </g></g>
    </g>
</svg>
```

## Screenshots

<table>
<tr>
	<td>Version 1.1.6
	<td>Version 2.0.0-dev.2
<tr>
	<td align="center"><img width="80" alt="Screenshot of a stylised Sun icon, with a yellow center, and yellow triangle sunbeams coming off it." src="https://user-images.githubusercontent.com/352291/214963793-8acf1196-3387-4403-905c-1c84bc5763ef.png">
	<td align="center"><img width="80" alt="Screenshot of the same Sun icon, with a yellow center, but with one yellow triangle sunbeam coming off it, the other sunbeams are black." src="https://user-images.githubusercontent.com/352291/214963811-5d61df5c-c413-4e4d-ac17-45757ae53be2.png">
</table>

**Comment by dnfield** [comment]
Yup, this is a regression. Fix shouldn't be hard.
