### ISSUE TITLE
currentColor usage

### ISSUE THREAD

**Issue by kirill-21** [dnfield/flutter_svg#836]
![image](https://user-images.githubusercontent.com/63228361/216436089-5a1a5746-ada7-4cc6-a840-49a3efc146f9.png)

How do i specify the color for SvgTheme widget if it does not understand the Color class?

**Comment by dnfield** [comment]
You need to import `Color` from `package:vector_graphics`. That should probably be re-exported from package:flutter_svg though... which will cause conflicts potentially. argh.

**Comment by kirill-21** [comment]
> You need to import `Color` from `package:vector_graphics`. That should probably be re-exported from package:flutter_svg though... which will cause conflicts potentially. argh.

Maybe  it will be easier to rename it or create a converted inside SvgTheme class which will automatically convert flutter's color to vector's one?

**Comment by MarcAnProv** [comment]
> You need to import `Color` from `package:vector_graphics`. That should probably be re-exported from package:flutter_svg though... which will cause conflicts potentially. argh.

Could you please provide an example, I'm not sure what you mean exactly.

**Comment by kirill-21** [comment]
> > You need to import `Color` from `package:vector_graphics`. That should probably be re-exported from package:flutter_svg though... which will cause conflicts potentially. argh.
> 
> Could you please provide an example, I'm not sure what you mean exactly.

i think he says that you need to import this package and use hide Color on material.dart import so that they do not conflict.

**Comment by glin94** [comment]
<img width="536" alt="Снимок экрана 2023-02-10 в 15 40 48" src="https://user-images.githubusercontent.com/34025626/218094913-407a170a-ffe7-4ae6-8c55-d4d0ecaffc6f.png">

or

<img width="627" alt="Снимок экрана 2023-02-10 в 15 42 48" src="https://user-images.githubusercontent.com/34025626/218095216-67d2bbbf-d073-4a7d-b523-d3be6e1ee585.png">
<img width="448" alt="Снимок экрана 2023-02-10 в 15 45 05" src="https://user-images.githubusercontent.com/34025626/218095680-e8c4088e-3c3d-42e8-8600-c0f3743681bc.png">

**Comment by glin94** [comment]
> > You need to import `Color` from `package:vector_graphics`. That should probably be re-exported from package:flutter_svg though... which will cause conflicts potentially. argh.
> 
> Could you please provide an example, I'm not sure what you mean exactly.

<img width="555" alt="Снимок экрана 2023-02-10 в 15 48 09" src="https://user-images.githubusercontent.com/34025626/218096345-ed2c37e9-9c7c-477e-99b7-19c82356e22d.png">


or
<img width="555" alt="Снимок экрана 2023-02-10 в 15 47 28" src="https://user-images.githubusercontent.com/34025626/218096131-c2df5049-2bb9-4bdd-a90e-b01ed84c4256.png">
 and
<img width="467" alt="Снимок экрана 2023-02-10 в 15 48 43" src="https://user-images.githubusercontent.com/34025626/218096370-a02ae622-ca9e-412e-8c30-eee72494af7c.png">

**Comment by jonahwilliams** [comment]
Let's fix this so it goes through an int conversion
