### ISSUE TITLE
I am seeing a significant performance regression on 2.0.0

### ISSUE THREAD

**Issue by mariopepe** [dnfield/flutter_svg#837]
I have no `precachePicture` in place, nor anything else.

And still I am seeing a significant performance degradation after upgrading to 2.0.0 (i.e. it is happening for the first time ever that I load a page, and only after some milliseconds, the svg pop-appears, causing a unpleasant effect)

Downgrading to 1.1.6 for the time being

**Comment by dnfield** [comment]
This only seems to happen in debug mode (see thread here: https://github.com/dnfield/flutter_svg/issues/809, specifically towards the end).

It seems like Flutter is just slower in debug mode at spawning isoaltes and getting results from them.

**Comment by dnfield** [comment]
Also, there is `vg.precachePicture` available.

**Comment by Tokenizer94** [comment]
Wow. after upgrading to version 2, Images take like 3 seconds to load! Why?
If it's because of the debug mode, Then why versions below 2 don't have this problem?

**Comment by mariopepe** [comment]
> Wow. after upgrading to version 2, Images take like 3 seconds to load! Why?
> If it's because of the debug mode, Then why versions below 2 don't have this problem?

Exactly, this is a very good question.

**Comment by dnfield** [comment]
Version 2 uses isolates to avoid blocking the ui thread during decode.  This means less jank/long frames, but slower load times in debug mode.

**Comment by jonahwilliams** [comment]
I think until we figure out why the isolate computation is slow in debug, we should run on the main thread in and only use isolates for profile/release

 its not super obvious that the long decode times will go away in profile/rlease mode and I can't really fault anyone for being concerned. You would see more blocking UI thread work but I suspect that would get drowned out in general debug mode jank.

**Comment by behzodfaiziev** [comment]
@mariopepe  I also faced performance issue in debug mode. However, as @dnfield said in release there shouldn't be any issue. I tried and I confirm no issue in release mode

**Comment by Dohmanlechx** [comment]
> I think until we figure out why the isolate computation is slow in debug, we should run on the main thread in and only use isolates for profile/release
> 
> its not super obvious that the long decode times will go away in profile/rlease mode and I can't really fault anyone for being concerned. You would see more blocking UI thread work but I suspect that would get drowned out in general debug mode jank.

I agree with you. It's not fun for us developers to work on something that seems broken, and we have to explain this to every new developer and QA tester.

**Comment by dnfield** [comment]
I'm talking with the Dart team about this.

It seems like in JIT mode spawning off this many isolates ends up running the compiler in parallel for basically the same code. It's also just possible that JIT isn't as fast as AOT for some of these cases.

One option that I'm not a huge fan of is to just not use isolates in debug mode. I'm not a huge fan of that, but it's already something we do for tests because unit testing anything spawning isolates with flutter_test is kind of a nightmare.

**Comment by Tanthus** [comment]
Is there a way to globally turn off the isolate and run the compiling in the main thread?

**Comment by dnfield** [comment]
> Is there a way to globally turn off the isolate and run the compiling in the main thread?

Not currently.

**Comment by subzero911** [comment]
Same here with SVG images, they are loaded very slooowly.

**Comment by Tanthus** [comment]
This seems to work fine now in 2.0.1 in both release and debug mode.

**Comment by dnfield** [comment]
Yeah, 2.0.1 has removed isolate parsing for debug mode.

**Comment by Dohmanlechx** [comment]
Thanks, @dnfield for your work.
