### ISSUE TITLE
Images not loading from package in version 2.0.0

### ISSUE THREAD

**Issue by nekomaruh** [dnfield/flutter_svg#839]
I have been implementing the widget like this in a custom package.

<img width="245" alt="Screen Shot 2023-02-03 at 01 27 48" src="https://user-images.githubusercontent.com/42304227/216512534-5cee6575-ac54-4834-8f3b-92eb8bd8bed0.png">

But then when calling the module widget, i got this error. (It was working fine with version 1.1.6).

<img width="768" alt="Screen Shot 2023-02-03 at 01 30 04" src="https://user-images.githubusercontent.com/42304227/216512793-c21c1b61-d37f-4890-8db8-6c78bf5dce8c.png">

**Comment by dnfield** [comment]
Yeah, this is a bug that will be fixed shortly.

**Comment by dnfield** [comment]
Fixed by https://github.com/dnfield/flutter_svg/pull/838, published as 2.0.0+1
