### ISSUE TITLE
Svg icons are delayed

### ISSUE THREAD

**Issue by Demirzekk** [dnfield/flutter_svg#840]
My assets svg icons are delayed loading. 
 flutter_svg: ^2.0.0+1
if I use ^1.1.6, there is no delayed

**Comment by levi956** [comment]
Same!!!!! 
Almost pushed into production.

**Comment by Dohmanlechx** [comment]
Same, but the reason might be that I removed the `precachePicture` function as it no longer existed and I don't understand how to replace them. Created issue: https://github.com/dnfield/flutter_svg/issues/841

**Comment by appinteractive** [comment]
Also saw that loading, looks horrible. I did not remove anything, just upgraded and my app was loading like web in the 90`s

**Comment by appinteractive** [comment]
okay seems like that issue only exists in debug mode, did not validate it till now. #809

**Comment by blue492** [comment]
same issue here
flutter_svg: ^2.0.0+1
flutter: 3.7.1

**Comment by Dohmanlechx** [comment]
> okay seems like that issue only exists in debug mode, did not validate it till now. #809

Just tried in profile mode, and yeah it was instantaneous, but for the big main logo it can be a biiiiit delayed. Just if I had a way to precache or await until the app loaded the SVG.

But for small icons, yes instantaneous. This should be documented tho, if it isn't already.

**Comment by dnfield** [comment]
Duplicate of #837
