### ISSUE TITLE
AssetBytesLoader can't be assigned to Parameter PictureProvider<dynamic, dynamic>

### ISSUE THREAD

**Issue by buehler** [dnfield/flutter_svg#844]
Hi there!

While using the flutter svg package, I tried to use prebuilt binary svgs to ensure fast performance :-)
When I tried to use the described way:

```dart

import 'package:flutter_svg/flutter_svg.dart';
import 'package:vector_graphics/vector_graphics.dart';

final Widget svg = SvgPicture(
  const AssetBytesLoader('assets/foo.svg.vec')
);
```

I came across the following issue:
```
A loader that retrieves bytes from an [AssetBundle].

See [AssetBytesLoader].

The argument type 'AssetBytesLoader' can't be assigned to the parameter type 'PictureProvider<dynamic, dynamic>'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)
```

It seems not possible to use asset bytes loader as picture provider anymore (as stated in the docs).

Did I do something wrong?

Regards

**Comment by dnfield** [comment]
In that case, just use the `VectorGraphic` API directly from package:vector_graphics.

**Comment by buehler** [comment]
Oh nice, thank you. This means, no need for "flutter-svg"?

**Comment by dnfield** [comment]
Right
