### ISSUE TITLE
Filling All Available Spaces Regardless of SVG File Content

### ISSUE THREAD

**Issue by bahricanyesil** [dnfield/flutter_svg#846]
I have two different SVG files and I'm trying to fill the all available spaces for both without changing the code of the SVG files. Here are the two screenshots that show the differences:
SVG 1 - NOT EXPECTED RESULT
- It does not take the whole available space and puts some spacing. As I mentioned, I want to solve this problem without being able to change the SVG file content.
SVG 2 - EXPECTED RESULT
- It takes the whole space as expected.

<img width="684" alt="Screen Shot 2023-02-08 at 11 01 17" src="https://user-images.githubusercontent.com/60237280/217469559-2e98ac48-2ed3-4afc-b6f4-5ab147a2e395.png">

Here're the contents of the SVG files
SVG 1 - UNEXPECTED Result:
https://bitholla.s3.ap-northeast-2.amazonaws.com/icon/USDT-hollaex-asset-01.svg 

SVG 2 - EXPECTED Result:
https://bitholla.s3.ap-northeast-2.amazonaws.com/icon/MATIC-hollaex-asset-01.svg

What is the reason for this problem and how can I overcome this without changing the content of the SVG file?

**Comment by dnfield** [comment]
Please provide the Dart code that isn't working. Your SVGs provided appear to render correctly in my own test application.

**Comment by bahricanyesil** [comment]
Sure, here are the corresponding code pieces:

```
Column(
          children: <Widget>[
            Container(
              height: 200,
              width: 200,
              color: Colors.red,
              child: SvgPicture.network(
                'https://bitholla.s3.ap-northeast-2.amazonaws.com/icon/USDT-hollaex-asset-01.svg',
                color: Colors.white,
              ),
            ),
            Container(
              height: 200,
              width: 200,
              color: Colors.purple,
              child: SvgPicture.network(
                'https://bitholla.s3.ap-northeast-2.amazonaws.com/icon/MATIC-hollaex-asset-01.svg',
                color: Colors.white,
              ),
            ),
          ],
        )
```

Note that I want an equal size of SVG files regardless of their internal paddings.

**Comment by bahricanyesil** [comment]
> Please provide the Dart code that isn't working. Your SVGs provided appear to render correctly in my own test application.

Sure, here are the corresponding code pieces:

```
Column(
          children: <Widget>[
            Container(
              height: 200,
              width: 200,
              color: Colors.red,
              child: SvgPicture.network(
                'https://bitholla.s3.ap-northeast-2.amazonaws.com/icon/USDT-hollaex-asset-01.svg',
                color: Colors.white,
              ),
            ),
            Container(
              height: 200,
              width: 200,
              color: Colors.purple,
              child: SvgPicture.network(
                'https://bitholla.s3.ap-northeast-2.amazonaws.com/icon/MATIC-hollaex-asset-01.svg',
                color: Colors.white,
              ),
            ),
          ],
        )
```

Note that I want an equal size of SVG files regardless of their internal paddings.

**Comment by dnfield** [comment]
Please provide a full sample I can run :)

**Comment by bahricanyesil** [comment]
@dnfield, As I mentioned in my previous comments, I want to ignore internal padding which is not affected by the `color` parameter in the SVG file.

**Comment by bahricanyesil** [comment]
> Right - to do that, you'd need to update your SVG to not claim to be as large as it's claiming to be, or to center the actual drawn content.
> 
> It would be posssible at runtime to figure out the bounds of the actual drawn content, but it's not trivial or cheap to do that and I really wouldn't recommend it. It's much saner to just have your SVG provide a better value in the `viewBox` attribute.
> 
> I'm going to close this as not planned, since it looks like everything is WAI from flutter_svg's point of view.

Thanks for quick responses and explanations.
