### ISSUE TITLE
Error on v2. working well on 1.1.6

### ISSUE THREAD

**Issue by sartajroshan** [dnfield/flutter_svg#848]
Unhandled Exception: Unsupported operation: Cannot forward opacity through a savelayer node

Unsupported operation: Cannot forward opacity through a mask node

**Comment by dnfield** [comment]
@jonahwilliams this is related to the opacity peepholing optimization. Instead of throwing could we just bail?

**Comment by jonahwilliams** [comment]
Yes, but the thrown error isn't the problem. That indicates we decided to forward the opacity even though the node says it doesn't support it. Need the original SVG, should be easy to fix.

**Comment by dnfield** [comment]
@sartajroshan can you share the svg?

**Comment by sartajroshan** [comment]
![discount_bg](https://user-images.githubusercontent.com/36073299/217995560-c03d1aad-5507-4545-9688-3e167a974fe1.svg)


> @sartajroshan can you share the svg?

**Comment by dnfield** [comment]
@jonahwilliams it looks like the visitor tries to do the optimization when it encounters a saveLayer node in some cases, but then when it actually has to process the saveLayer it throws?

**Comment by sartajroshan** [comment]
![cashback_bg](https://user-images.githubusercontent.com/36073299/218524413-8087346e-342a-4ccf-a7ec-e4248eeeb81a.svg)
![gift_bg](https://user-images.githubusercontent.com/36073299/218524442-77b72a12-7b8f-4ce3-9d60-a5dc58cb86da.svg)

Same issue with these files

**Comment by dnfield** [comment]
@sartajroshan are you still having this issue if you use the latest vector_graphics publication?

I foolishly just published a new flutter_svg and forgot to update the vector_graphics constraint, but if you do a `pub upgrade` I think it should still get you the latest one.

**Comment by sartajroshan** [comment]
> @sartajroshan are you still having this issue if you use the latest vector_graphics publication?
> 
> I foolishly just published a new flutter_svg and forgot to update the vector_graphics constraint, but if you do a `pub upgrade` I think it should still get you the latest one.

I manually edited the file with the fix. Then the svg file i shared with you first worked correctly. But these two svg files still not rendering

**Comment by sartajroshan** [comment]
> > @sartajroshan are you still having this issue if you use the latest vector_graphics publication?
> > I foolishly just published a new flutter_svg and forgot to update the vector_graphics constraint, but if you do a `pub upgrade` I think it should still get you the latest one.
> 
> I manually edited the file with the fix. Then the svg file i shared with you first worked correctly. But these two svg files still not rendering

Showing error

Unsupported operation: Cannot forward opacity through a mask node
