### ISSUE TITLE
SVG is filled with black, but if opened manually, it is not filled.

### ISSUE THREAD

**Issue by DIKGONZA** [dnfield/flutter_svg#850]
SVG is filled with black, but if opened manually, it is not filled.

**that's how it is on google**
![Captura de pantalla 2023-02-10 a la(s) 4 34 13](https://user-images.githubusercontent.com/25334145/218056275-17314a42-9e8f-4b5d-84b5-c80b8741e2d0.png)

**This is how it is representing it.**
![IMG_020B8D84A948-1](https://user-images.githubusercontent.com/25334145/218056916-8f6001b7-c34f-4333-bb8f-c3c73d7a93ad.jpeg)

**Comment by dnfield** [comment]
Please share the SVG that is failing.

**Comment by DIKGONZA** [comment]
Hi Daniel, [this is the svg](https://firebasestorage.googleapis.com/v0/b/maskoteando-co.appspot.com/o/icon_person_check.svg?alt=media&token=1b9ba7d6-ac46-43af-82a3-c3444ed4070b)
