### ISSUE TITLE
Flutter SVG | Compare Asset Testing

### ISSUE THREAD

**Issue by felipecastrosales** [dnfield/flutter_svg#852]
Hi! 

Before the version `2.0.0`, I had this test that worked fine and made the assertion I wanted. 

```dart
final findAsset = find.byWidgetPredicate(
  (widget) =>
      widget is SvgPicture &&
      (widget.pictureProvider as ExactAssetPicture)
              .assetName
              .compareTo('assets/flutter.svg') ==
          0,
);

expect(findAsset, findsOneWidget);
```

**However**, after `2.0.0` this testis invalid because there were internal change in the package, e.g:
- pictureProvider: 
`The getter 'pictureProvider' isn't defined for the type 'SvgPicture'.
Try importing the library that defines 'pictureProvider', correcting the name to the name of an existing getter, or defining a getter or field named 'pictureProvider'.`
- ExactAssetPicture: 
`The name 'ExactAssetPicture' isn't a type, so it can't be used in an 'as' expression.
Try changing the name to the name of an existing type, or creating a type with the name 'ExactAssetPicture'.`

I would be like to know which is the best option to follow, with the new version of the package. 

I also made a **Minimal Reproducible Example**: 

- https://github.com/felipecastrosales/svg_mre

**Comment by felipecastrosales** [comment]
I found a solution for this. 

Just do it this way: 

```dart
final findAsset = find.byWidgetPredicate(
  (widget) =>
      widget is SvgPicture &&
      (widget.bytesLoader as SvgAssetLoader) // Here! 
              .assetName
              .compareTo('assets/flutter.svg') ==
          0,
);
```

Is this an interesting approach? I believe so. I'll leave the issue open as I'm open to feedback and if there's something better to be done here. And I also made the commit.

**Comment by dnfield** [comment]
Yes, this is the correct way to fix this issue.

**Comment by felipecastrosales** [comment]
Ok, @dnfield. Thanks for answer. :)

**Comment by dkbast** [comment]
This would be great as part of a migration guide - btw there are still references to the picture provider in the code documentation.
