### ISSUE TITLE
using colorFilter filled svg image wih stroke border , cannot fill the image with color with provided stroke border.

### ISSUE THREAD

**Issue by amer-zk** [dnfield/flutter_svg#857]
original SVG Photo of this code : 
SvgPicture.network(url!);

<img width="82" alt="image" src="https://user-images.githubusercontent.com/39316144/218342516-bb101947-4a9a-4eb7-a24f-02e2ddbcd670.png">

but when I provide colorFilter by this code : 
SvgPicture.network(url!, colorFilter: ColorFilter.mode(color!, BlendMode.srcIn));

<img width="80" alt="image" src="https://user-images.githubusercontent.com/39316144/218342509-e5cbff6e-a142-48d7-bc66-b043c24687ec.png">

i need to fill the image with color but woth stroke color , how to achive this :
<img width="232" alt="image" src="https://user-images.githubusercontent.com/39316144/218342626-77d4aa7e-3a0f-4a45-b4e7-c23a0191f712.png">

svg file : 
![Icon ionic-logo-game-controller-b](https://user-images.githubusercontent.com/39316144/218342690-62eb31b8-5bf3-4d55-b357-cda806142530.svg)

**Comment by dnfield** [comment]
Blend mode based color filters won't work for this (unless I'm just forgetting some trick with one of them, which is possible).

A color matrix based filter would work. The color you're going for appears to be `rgba(206, 183, 230, 1)`. Divide those values by 255 to get this color filter matrix:

```dart
                    colorFilter: const ColorFilter.matrix(<double>[
                        .807, 0, 0, 0, 0, //
                        0, .717, 0, 0, 0,
                        0, 0, .901, 0, 0,
                        0, 0, 0, 1, 0,
                      ]),
```

And it looks like what you want.

You could alternatively use a color mapper, like

```dart
class _MyColorMapper extends ColorMapper {
  @override
  Color substitute(
      String? id, String elementName, String attributeName, Color color) {
    if (color.value == Colors.white.value) {
      return const Color.fromARGB(255, 203, 183, 255);
    }
    return color;
  }
}
```

which will do the change at parse time and require less processing resources at render time.

**Comment by amer-zk** [comment]
@dnfield The first matrix works perfectly , but would you please describe matrix elements ? why there is 1 in the last row ?
 
BTW , i couldn't use ColorMapper you mentioned,my editor couldn't find ColorMapper class, could you define which import must i use for that?

Thank you.  😃 💙

**Comment by dnfield** [comment]
https://docs.rainmeter.net/tips/colormatrix-guide/ is a pretty good explanation of color matrices.
