### ISSUE TITLE
Unsupported operation: Cannot forward opacity through a mask node

### ISSUE THREAD

**Issue by sartajroshan** [dnfield/flutter_svg#862]
Showing error

Unsupported operation: Cannot forward opacity through a mask node

              ![cashback_bg](https://user-images.githubusercontent.com/36073299/218524413-8087346e-342a-4ccf-a7ec-e4248eeeb81a.svg)
![gift_bg](https://user-images.githubusercontent.com/36073299/218524442-77b72a12-7b8f-4ce3-9d60-a5dc58cb86da.svg)

Same issue with these files

_Originally posted by @sartajroshan in https://github.com/dnfield/flutter_svg/issues/848#issuecomment-1428319843_

**Comment by dnfield** [comment]
The component causing this issue has been deleted for now, next release will not have this issue.
