### ISSUE TITLE
Irregular rendering of several SVGs.

### ISSUE THREAD

**Issue by psyirius** [dnfield/flutter_svg#864]
![image](https://user-images.githubusercontent.com/99079175/219067296-b31e4f53-3b04-44fc-bb17-c939c14f9978.png)

Svg Source: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/bzrfeed.svg

![image](https://user-images.githubusercontent.com/99079175/219071598-eef9319b-fc0c-4205-b7fd-6815ba8c8fe0.png)

Svg Source: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/svg.svg

**Comment by dnfield** [comment]
I think these are two seprate bugs, and unfortunately the first one might be harder to fix in the 2.0.1 code which might be optimizing too aggressively in this case.

**Comment by dnfield** [comment]
This will be released shortly.
