### ISSUE TITLE
Set `currentColor` to black by default

### ISSUE THREAD

**Issue by adil192** [dnfield/flutter_svg#869]
Following https://github.com/adil192/saber/issues/383...

The user was having an issue with an SVG that used `currentColor`:

<img src="https://user-images.githubusercontent.com/21128619/220474643-a9d49a93-d766-43c1-b9db-95c6417d55ae.png" width=300 alt="SVG with music staffs">

In Firefox and Nautilus (the file manager on PopOS), the SVG is rendered with black lines (as pictured) but `flutter_svg` sets `currentColor` to transparent which makes the lines invisible.

**Comment by dnfield** [comment]
Please share the SVG and relevant code...

**Comment by adil192** [comment]
The fix for the linked issue was https://github.com/adil192/saber/commit/82aa60e0c805cbbb1a28007b60529d8c9b10446f
```dart
return SvgPicture.string(
  // ...
  theme: SvgTheme(
    currentColor: imageBrightness == Brightness.light
        ? Colors.black
        : Colors.white,
  ),
);
```

This is the SVG uploaded by the user
![blank-v1](https://user-images.githubusercontent.com/21128619/220475990-3830491f-bd4e-41c6-b865-5f3bc6502080.svg)

**Comment by dnfield** [comment]
Ahhh, it looks like the parser isn't handling the case where the stroke is set to currentColor bu thte fill is unspecified.
