### ISSUE TITLE
The transform attribute of the text tag was parsed incorrectly.

### ISSUE THREAD

**Issue by superbor** [dnfield/flutter_svg#872]
This is the correct display effect of svg

![image](https://user-images.githubusercontent.com/11262955/221808770-e23607cf-9841-467b-9516-5be5b9f326d6.png)

This is the display effect of using the flutter_svg library

![WechatIMG66](https://user-images.githubusercontent.com/11262955/221808291-061a7e14-7ee4-4fb6-ad6f-358c17ea1f39.jpeg)

这是svg文件

![customer_ic_ing](https://user-images.githubusercontent.com/11262955/221809756-f38e6a3e-db98-4730-9a93-1c5e939e7303.svg)

**Comment by dnfield** [comment]
I just so happen to be working on some other bugs related to text that I think would fix most of this.
