### ISSUE TITLE
SvgTheme does not apply the color

### ISSUE THREAD

**Issue by dongorias** [dnfield/flutter_svg#874]
I have declared SvgTheme with the currentColor but I see that on compilation the colour does not change.

` SvgPicture.asset(
             icon,
            theme: SvgTheme(
                currentColor:
                    isActif ? $appColors.accent1 : $appColors.greyStrong),
          ),`

Does anyone have any idea what I missed?

**Comment by dnfield** [comment]
Does your svg actually use `currentColor` in it? Please share an SVG that fails with this and I'll reopen.

**Comment by SilkeSiip** [comment]
I have the same problem.

**Comment by bhavin-concetto** [comment]
@dnfield  how can we determine if the SVG uses currentColor or not?
