### ISSUE TITLE
[Samsung/ iOS- in background] Exception: Invalid image data

### ISSUE THREAD

**Issue by Ewelina96** [dnfield/flutter_svg#875]
After running the app with flutter_svg 2.0.0 (or higher) on Samsung devices I get error 'Invalid image data'- error doesn't exist on lower than 2.0.0 version and on other Android devices, on iOS it happens after returning from background mode

**Comment by dnfield** [comment]
Please share an SVG that reproduces this problem.

**Comment by dnfield** [comment]
And/or a sample app with steps to reproduce the issue.

**Comment by dnfield** [comment]
Feel free to re-open if you can share a failing asset.
