### ISSUE TITLE
After upgrading the flutter sdk and flutter_svg version, there is a problem that the image position is distorted.

### ISSUE THREAD

**Issue by jiseungjun** [dnfield/flutter_svg#878]
After upgrading the flutter sdk and flutter_svg version, there is a problem that the image position is distorted.

`
flutter_svg: 2.0.2

[✓] Flutter (Channel stable, 3.7.6, on macOS 13.0.1 22A400 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
`

![icon_guide_help](https://user-images.githubusercontent.com/13620639/223876542-8d14a8a5-ab5c-4190-a1a7-639b8d42e990.svg)
![goal_step_03_black](https://user-images.githubusercontent.com/13620639/223876552-89bdf855-8bff-400b-80a7-66fa79f88466.svg)
![goal_step_2_white](https://user-images.githubusercontent.com/13620639/223876555-17dc7b52-6dee-410b-ab86-9f4d555818dd.svg)
![goal_step_01](https://user-images.githubusercontent.com/13620639/223876557-b5ec7f7e-046b-4b0b-afd7-555bff1845d1.svg)

**Comment by dnfield** [comment]
I recently fixed a bunch of things in text - try running `flutter pub upgrade`.  However, the whitespace handling isn't quite right here.

**Comment by dnfield** [comment]
Ok, adjusted the whitespace handling a little more to fix this case and the other ones I had been looking at. Please try running `flutter pub upgrade` and see if that picks up the latest vector_graphics_compiler version for you.

**Comment by jiseungjun** [comment]
perfect thank you
