### ISSUE TITLE
SVG asset not rendering, only white box

### ISSUE THREAD

**Issue by ermirshabani1** [dnfield/flutter_svg#884]
I'm using flutter 3.7.7 with flutter_svg 2.0.3, when i try to render an svg from assets it loads only a white box, but with network url it renders correctly. When using version 1.1.6 everything works ok, except some svg's that keeps throwing this exception 'Another exception was thrown: UnimplementedError: The <style> element is not implemented in this library.'

![image](https://user-images.githubusercontent.com/110819389/225058035-1cd18beb-8243-483d-9187-4e257b1becec.png)

**Comment by dnfield** [comment]
Please share the SVG.

It sounds like you're using `warningsAsErrors: true` somewhere.

**Comment by ermirshabani1** [comment]
> 

Example this one as an asset.
https://svgshare.com/i/r83.svg

**Comment by dnfield** [comment]
That SVG is basically just a wrapper for an image. You would be a lot better off just using the image directly.

That said this shouldn't fail to render.

**Comment by dnfield** [comment]
The MIME type reported by the SVG is off. I guess the browser accepts it though. Simple fix.

**Comment by dnfield** [comment]
You can work around this by changing the `img/png` to `image/png` in that file.
