### ISSUE TITLE
The argument type 'Clip?' can't be assigned to the parameter type 'Clip' because 'Clip?' is nullable and 'Clip' isn't.

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [dnfield/flutter_svg#887]
Getting the following error after upgrading to Flutter 3.7.7:

`lib/core/gen/assets.gen.dart:253:21: Error: The argument type 'Clip?' can't be assigned to the parameter type 'Clip' because 'Clip?' is nullable and 'Clip' isn't.`

![image](https://user-images.githubusercontent.com/4954611/225521233-7f28666a-bb1a-4cf8-881a-e8108217db48.jpeg)

```
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (8 days ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1
```

```
#pubspec.yaml
...
flutter_svg: ^2.0.2
```

**Comment by dnfield** [comment]
You probably are actually using flutter_svg 2.0.3, which made `clipBehavior` non-null. Your generated assets will need to specify a clip behavior or not specify null for it.

**Comment by dnfield** [comment]
That said, I think it's probably fine to make `clipBehavior` nullable again if it's really disruptive... Let me knwo.

**Comment by dnfield** [comment]
Either change this line:

```
clipBehavior: clipBehavior, // Error: The argument type 'Clip?' can't be assigned to the parameter type 'Clip' because 'Clip?' is nullable and 'Clip' isn't.
```

to 
```dart
clipBehavior: clipBehavior ?? Clip.hardEdge
```

or this line:

```
 @deprecated Clip? clipBehavior,
```

to

```
Clip clipBehavior = Clip.hardEdge
```

This is compatible with both 2.0.2 and 2.0.3.

**Comment by Petri-Oosthuizen** [comment]
I did not write this code. It was generated when I ran 
```
flutter pub run build_runner build --delete-conflicting-outputs 
```
