### ISSUE TITLE
SvgParser.loadFromString.<fn> error in Firebase Crashlytics

### ISSUE THREAD

**Issue by vtisnado** [dnfield/flutter_svg#892]
I tried updating the library to the latest version, but still getting the following error:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'Match' in type cast
       at SvgParser.loadFromString.<fn>(parser.dart:77)
       at Iterable.forEach(dart:core)
       at SvgParser.loadFromString(parser.dart:63)
       at SvgParser.loadFromFile(parser.dart:124)
```
The SVG assets displays fine, but don't know what fires the error.
Does anyone has seen this before?

**Comment by dnfield** [comment]
What version of flutter_svg?

I don't recognize those functions as anything from this library. Closing until clarification can be added.
