### ISSUE TITLE
When Impeller enabled SVG is clipped when rotated 90°

### ISSUE THREAD

**Issue by eli1stark** [dnfield/flutter_svg#895]
Works fine when Impeller is disabled.

flutter: 3.7.8
flutter_svg: 2.0.4

Code sample:
```dart
ColoredBox(
  color: Colors.white,
  child: Transform.rotate(
    angle: (math.pi) * 1,
    child: SvgPicture.asset(
      'path-to-svg',
      width: 100,
      height: 100,
      colorFilter: const ColorFilter.mode(
        Colors.black,
        BlendMode.srcIn,
      ),
    ),
  ),
),
```

SVG used:
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 19L12 5" stroke="#FBFBFC" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M5 12L12 19L19 12" stroke="#FBFBFC" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

When rotated:
<img width="109" alt="Screenshot 2023-03-27 at 8 06 43 AM" src="https://user-images.githubusercontent.com/57593530/227981955-a3d66690-3325-447f-b6f1-a54924c9f8a4.png">

When not rotated:
<img width="110" alt="Screenshot 2023-03-27 at 8 06 57 AM" src="https://user-images.githubusercontent.com/57593530/227982017-065edb19-544a-4ab6-b4be-68a1b1ecd619.png">

Original SVG:
<img width="110" alt="Screenshot 2023-03-27 at 8 08 52 AM" src="https://user-images.githubusercontent.com/57593530/227982568-c994bde7-0a55-42f5-99d4-8b57acd42882.png">

You can also see how corners are not rounded compared to the original SVG.

Corners are rounded when using Skia.

**Comment by dnfield** [comment]
This doesn't seem to reproduce on a recent commit of Flutter, so I think it's been fixed upstream.

**Comment by eli1stark** [comment]
@dnfield Still reproducible for me on:
stable: 3.7.9
beta: 3.9.0-0.2.pre
master: 3.9.0-20.0.pre.51 (ad7e2f7b78247408b1d2c4fde591d5924695e779)

**Comment by dnfield** [comment]
Can you provide a github project that reproduces this?

**Comment by eli1stark** [comment]
@dnfield https://github.com/eli1stark/svg_example

**Comment by dnfield** [comment]
Great, I can see the problem now thanks
