### ISSUE TITLE
Rendering errors, distorted SVGs, since flutter 1.1.1

### ISSUE THREAD

**Issue by mploigt** [dnfield/flutter_svg#90]
Since flutter version 1.1.1 my svg icons behave very strangely (see: https://youtu.be/xqpA_xjGK5g).
I'm using flutter_svg 0.7.0+1 and have cleaned my svgs so they don't contain width and height attributes. With flutter version 1.0.0 everything is fine.

**Comment by mploigt** [comment]
I also opened up a flutter issue: https://github.com/flutter/flutter/issues/25458

**Comment by dnfield** [comment]
Thanks for that.  I suspect this is a flutter issue right now, but will keep this open to track.

**Comment by dnfield** [comment]
This was fixed upstream in https://github.com/flutter/flutter/pull/25529
