### ISSUE TITLE
Cache ignores ColorMapper differences.

### ISSUE THREAD

**Issue by abigotado** [dnfield/flutter_svg#901]
I am converting SVG picture to BitmapDescriptor for Google Maps. But I have found it impossible to change color of the created icons dynamically. I can change colors using `ColorMapper` when first time creating my icon from SVG. But if I try to create another icon from the same SVG with other colors - it doesn't work. ColorMapper change colors only once per asset.

Is there any way to change color dynamically every time I need?

Some pieces of code:

Converter of SVG:
```dart
/// Utility for converting SVG.
class SvgConverter {
  /// Converts SVG to [BitmapDescriptor].
  static Future<BitmapDescriptor> getBitmapDescriptorFromSvgAsset(
    final String assetName, {
    final Size size = const Size(32, 32),
    final ColorMapper? colorMapper,
  }) async {
    final PictureInfo pictureInfo = await vg.loadPicture(
      SvgAssetLoader(assetName, colorMapper: colorMapper),
      null,
    );

    final double devicePixelRatio = ui.window.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();

    final double scaleFactor = min(
      width / pictureInfo.size.width,
      height / pictureInfo.size.height,
    );

    final ui.PictureRecorder recorder = ui.PictureRecorder();

    ui.Canvas(recorder)
      ..scale(scaleFactor)
      ..drawPicture(pictureInfo.picture);

    final ui.Picture rasterPicture = recorder.endRecording();

    final ui.Image image = rasterPicture.toImageSync(width, height);
    final ByteData bytes =
        (await image.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
  }
}
```

ColorMapper:
```dart
/// Default color mapper for inverting icon's colors.
const SvgColorMapper defaultColorMapper = SvgColorMapper(
  mainColor: Color(0xFF3581B8),
  oldMainColor: Colors.white,
  secondaryColor: Colors.white,
  oldSecondaryColor: Color(0xFF3581B8),
);
```

These way I always get non-colored icon (original SVG - both from `footballIcon` and `footballIconDark`):
```dart
footballIcon = await SvgConverter.getBitmapDescriptorFromSvgAsset(
        'assets/icons/map_icons/football.svg',
);
footballIconDark = await SvgConverter.getBitmapDescriptorFromSvgAsset(
        'assets/icons/map_icons/football.svg',
        colorMapper: defaultColorMapper);
```

result: 
<img width="102" alt="Снимок экрана 2023-04-07 в 16 48 29" src="https://user-images.githubusercontent.com/82471392/230668547-831c0e99-15df-46a4-bfe5-f441affa5ffd.png">

If I change the sequence - I will always get colored one (with mapper - both from `footballIcon` and `footballIconDark`):
```dart
footballIconDark = await SvgConverter.getBitmapDescriptorFromSvgAsset(
        'assets/icons/map_icons/football.svg',
        colorMapper: defaultColorMapper);
footballIcon = await SvgConverter.getBitmapDescriptorFromSvgAsset(
        'assets/icons/map_icons/football.svg',
);
```

result: 
<img width="93" alt="Снимок экрана 2023-04-07 в 16 50 02" src="https://user-images.githubusercontent.com/82471392/230668759-917d5ca3-0400-48ca-bbb1-e7210999e68d.png">

And no way to change colors once more for this asset.

**Comment by dnfield** [comment]
This is a caching bug. The cache needs to take the `ColorMapper` into account. Right now it's not.
