### ISSUE TITLE
Conform to containing shape

### ISSUE THREAD

**Issue by richchurcher** [dnfield/flutter_svg#903]
I feel like I already know the answer here, but just on the off chance: is there any way to get an `SvgPicture` to conform to a container with rounded edges, e.g.
```
  InkWell(
    customBorder: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(20),
    ),
    onTap: () {},
    child: SvgPicture.asset(
      "assets/images/foo.svg",
      fit: BoxFit.contain,
    ),
  )
```

**Comment by dnfield** [comment]
You need to clip to make that happen. See the documentation on InkWell

**Comment by richchurcher** [comment]
Thankyou!

**Comment by richchurcher** [comment]
Just dropping the solution here, for any other Flutter neophytes:
```dart
  ClipRRect(
    borderRadius: BorderRadius.circular(20),
    child: Material(
      child: InkWell(
        onTap: () {},
        child: SvgPicture.asset(
          "assets/images/native_birds.svg",
        ),
      ),
    ),
  ),
```
Note the extra `R` in `ClipRRect`, that threw me for a minute or two.

If you don't wrap in `Material`, it will still work but when tapped, the sharp corners will show up again.
