### ISSUE TITLE
main.dart not found in Readme

### ISSUE THREAD

**Issue by Rest00rer** [dnfield/flutter_svg#907]
![image](https://user-images.githubusercontent.com/100043389/232974360-d94a0ac0-b090-4813-a5ce-43e21c19aacf.png)
![image](https://user-images.githubusercontent.com/100043389/232974506-f9c448ff-21b7-4454-99ef-6a8bda55c793.png)

**Comment by dnfield** [comment]
Fixed this on master by. ... deleting the line.

Most pub packages don't link to the sample code anyway. It's kind of hard to keep this from going stale and link to the right spot on GitHub.
