### ISSUE TITLE
Prefer usvg to svgcleaner

### ISSUE THREAD

**Issue by RazrFalcon** [dnfield/flutter_svg#91]
Thanks for advertising the `svgcleaner`, but the project is kinda staled at the moment. You should prefer [`usvg`](https://github.com/RazrFalcon/resvg/tree/master/usvg). It was designed specifically for your task.

The CLI version can be found [here](https://github.com/RazrFalcon/resvg/tree/master/tools/usvg). 

It doesn't have a prebuild binaries for now or even a GUI. But it's way better than svgcleaner in SVG simplifying.

**Comment by dnfield** [comment]
Thanks for the heads up.  I'll update my readme for that.  And thanks for your contributions to SVG rendering and simplification!

**Comment by dnfield** [comment]
Docs/error messaging updated in e4977a4
