### ISSUE TITLE
Corrupted images on iOS PWA (safari)

### ISSUE THREAD

**Issue by hasanm08** [dnfield/flutter_svg#913]
![image](https://user-images.githubusercontent.com/39486543/234566136-d84c8c44-36fd-4066-920d-50fc1819dcf5.png)
Flutter 3.7.11 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f72efea43c (2 weeks ago) • 2023-04-11 11:57:21 -0700
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

flutter_svg: 2.0.4

**Comment by dnfield** [comment]
Please share the SVG that fails.

**Comment by dnfield** [comment]
Please share a full reproduction - I suspect again that you're using a color filtering parameter and trying to do this with the HTML backend,w hich just doesn't work.

**Comment by dnfield** [comment]
(Going to close this on the assumption it's a bug in the HTML renderer, please feel free to reopen if you have a reproduction showing otherwise)
