### ISSUE TITLE
flutter_svg throwing an error ( external static Never _throw(Object error, StackTrace stackTrace); )

### ISSUE THREAD

**Issue by ramithKS** [dnfield/flutter_svg#915]
Following is the official code given by flutter_svg on example tab of their tab ([https://pub.dev/packages/flutter_svg/example][1] ) :

when I'm trying run this it's the throwing the exception like this :

> external static Never _throw(Object error, StackTrace stackTrace);

[![enter image description here][2]][2]

----------

**page.dart**

    import 'package:flutter/material.dart';
    import 'package:flutter_svg/flutter_svg.dart';
    
    const List<String> _assetNames = <String>[
      // 'assets/notfound.svg', // uncomment to test an asset that doesn't exist.
      'assets/custom_emojis/angry.svg',
      'assets/custom_emojis/cool.svg',
      'assets/custom_emojis/cute_cry.svg',
    ];
    
    /// Assets treated as "icons" - using a color filter to render differently.
    const List<String> iconNames = <String>[
      'assets/custom_emojis/angry.svg',
      'assets/custom_emojis/cool.svg',
      'assets/custom_emojis/cute_cry.svg',
    ];
    
    /// Assets to test network access.
    const List<String> uriNames = <String>[
      'http://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg',
      'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg',
      'https://upload.wikimedia.org/wikipedia/commons/b/b4/Chess_ndd45.svg',
    ];
    
    class PageThree extends StatefulWidget {
      const PageThree({Key? key, required this.title}) : super(key: key);
      final String title;
    
      @override
      _PageThreeState createState() => _PageThreeState();
    }
    
    class _PageThreeState extends State<PageThree> {
      final List<Widget> _painters = <Widget>[];
      late double _dimension;
    
      @override
      void initState() {
        super.initState();
        _dimension = 203.0;
        for (String assetName in _assetNames) {
          _painters.add(
            SvgPicture.asset(
              assetName,
              package: "packageName",
            ),
          );
        }
    
        for (int i = 0; i < iconNames.length; i++) {
          _painters.add(
            Directionality(
              textDirection: TextDirection.ltr,
              child: SvgPicture.asset(
                iconNames[i],
                colorFilter: ColorFilter.mode(
                  Colors.blueGrey[(i + 1) * 100] ?? Colors.blueGrey,
                  BlendMode.srcIn,
                ),
                matchTextDirection: true,
              ),
            ),
          );
        }
    
        for (String uriName in uriNames) {
          _painters.add(
            SvgPicture.network(
              uriName,
              placeholderBuilder: (BuildContext context) => Container(
                padding: const EdgeInsets.all(30.0),
                child: const CircularProgressIndicator(),
              ),
            ),
          );
        }
        // Shows an example of an SVG image that will fetch a raster image from a URL.
        _painters.add(SvgPicture.string('''<svg viewBox="0 0 200 200"
      xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <image xlink:href="https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png" height="200" width="200"/>
    </svg>'''));
      }
    
      @override
      Widget build(BuildContext context) {
        if (_dimension > MediaQuery.of(context).size.width - 10.0) {
          _dimension = MediaQuery.of(context).size.width - 10.0;
        }
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Column(children: <Widget>[
            Slider(
              min: 5.0,
              max: MediaQuery.of(context).size.width - 10.0,
              value: _dimension,
              onChanged: (double val) {
                setState(() => _dimension = val);
              },
            ),
            Expanded(
              child: GridView.extent(
                // shrinkWrap: true,
                maxCrossAxisExtent: _dimension,
                padding: const EdgeInsets.all(4.0),
                mainAxisSpacing: 4.0,
                crossAxisSpacing: 4.0,
                children: _painters.toList(),
              ),
            ),
          ]),
        );
      }
    }

  [1]: https://pub.dev/packages/flutter_svg/example
  [2]: https://i.stack.imgur.com/CNCqc.jpg

**Comment by dnfield** [comment]
This will be fixed the next time I published - I've moved the `simple` example whichi s self contained to `example/main.dart`.
