### ISSUE TITLE
DrawableRoot was removed from the package

### ISSUE THREAD

**Issue by narritt** [dnfield/flutter_svg#916]
I updated the package to version 2.0.5 and found that some functionality was removed. Code from ReadMe example no longer works when I want to render the SVG to some other canvas.

```dart
final String rawSvg = '''<svg viewBox="...">...</svg>''';
final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);
```

I got an error "Undefined class 'DrawableRoot'" and "The method 'fromSvgString' isn't defined for the type 'Svg'."
How can this functionality be kept in the current version? At least how can I obtain a Picture from dart:ui object from SVG now?

Thank you for your work and your answer!

**Comment by dnfield** [comment]
That is correct. See this part of the readme:

```dart
import 'package:flutter_svg/flutter_svg.dart';
final String rawSvg = '''<svg ...>...</svg>''';
final PictureInfo pictureInfo = await vg.loadPicture(SvgStringLoader(rawSvg), null);

// You can draw the picture to a canvas:
canvas.drawPicture(pictureInfo.picture);

// Or convert the picture to a an image:
final ui.Image image = pictureInfo.picture.toImage(...);

pictureInfo.picture.dispose();
```

**Comment by HasanShaddadKangaroo** [comment]
@dnfield 

Any idea on how i can change the color of the picture now?

I used to do this:


`    final DrawableRoot svgRoot = await svg.fromSvgString(rawSvg, rawSvg);
    final Picture picture = svgRoot.toPicture(
      size: this.widget.size,
      colorFilter: this.widget.colorFilter,
    ); 
    return picture.toImage(
      this.widget.spacing.width.toInt(),
      this.widget.spacing.height.toInt(),
    );
    `
    But now i'm migrating to use PictureInfo and cant seem to change the color.

**Comment by aantoine** [comment]
@HasanShaddadKangaroo did you manage to solve how to set the color filter without the DrawableRoot?

**Comment by aantoine** [comment]
I managed to solve this by using what was discussed in #858 as starting point.

Basically you can draw an Image into a Canvas using a Paint with a colorFilter, and use a PictureRecorder to get the desire Image back

```dart
import 'package:flutter_svg/flutter_svg.dart';
import 'dart:ui' as ui;

static Future<ui.Image> getImageFromSvg(String path, double width, double height, {ColorFilter? colorFilter}) async {
    String data = await rootBundle.loadString(path);

    // Get the properly scaled image
    final SvgStringLoader svgStringLoader = SvgStringLoader(data);
    final PictureInfo pictureInfo = await vg.loadPicture(svgStringLoader, null);
    final ui.Picture picture = pictureInfo.picture;
    ui.PictureRecorder recorder = ui.PictureRecorder();
    ui.Canvas canvas = Canvas(recorder, Rect.fromPoints(Offset.zero, Offset(width, height)));
    canvas.scale(width / pictureInfo.size.width, height / pictureInfo.size.height);
    canvas.drawPicture(picture);
    final ui.Image colorlessImage = await recorder.endRecording().toImage(width.ceil(), height.ceil());
    pictureInfo.picture.dispose();

    if (colorFilter == null) {
      return colorlessImage;
    }
    
    // Apply color filter if necessary
    recorder = ui.PictureRecorder();
    canvas = Canvas(recorder, Rect.fromPoints(Offset.zero, Offset(width, height)));
    Paint paint = new Paint();
    paint.colorFilter = colorFilter;

    ui.Size inputSize = ui.Size(imgByteData.width.toDouble(), imgByteData.height.toDouble());
    final FittedSizes fittedSizes = applyBoxFit(BoxFit.contain, inputSize, inputSize);
    final ui.Size sourceSize = fittedSizes.source;
    final Rect sourceRect = Alignment.center.inscribe(sourceSize, Offset.zero & inputSize);
    var rect = Rect.fromPoints(Offset(0.0, 0.0),
        Offset(imgByteData.width.toDouble(), imgByteData.height.toDouble()));

    canvas.drawImageRect(imgByteData, sourceRect, rect, paint);
    final ui.Image image = await recorder.endRecording().toImage(width.ceil(), height.ceil());
    return image;
  }
```

Not an elegant solution, but it gets the work done

**Comment by queirozmat** [comment]
@aantoine It worked very well for me, both to modify the size and change the color, thank you very much for posting this solution. 😁

**Comment by ahmetveysels** [comment]
i cant import imgByteData. How i can ?

**Comment by ahmetveysels** [comment]
How can I use gradient color. @aantoine

**Comment by aantoine** [comment]
> How can I use gradient color. @aantoine

Hi! Im just a user of this package so I dont really know how to help you. You should open a new issue and ask the developers

**Comment by ahmetveysels** [comment]
I did that. I published a package as SVGProvider. [avs_svg_provider](https://pub.dev/packages/avs_svg_provider)
Thanks. @aantoine

**Comment by belalSoliman** [comment]
The method 'toPicture' isn't defined for the type 'PictureInfo'.
Try correcting the name to the name of an existing method, or defining a method named 'toPicture'.
final ui.Picture picture =
        svgDrawableRoot.toPicture(size: const Size(100, 100));
