### ISSUE TITLE
Svg Image not showing but allocate it's space.

### ISSUE THREAD

**Issue by sabikrahat** [dnfield/flutter_svg#925]
I'm using the latest flutter_svg package. In some SVG images, it fails to render the image, but it still allocates space for it. There are no errors displayed in the console. I have uploaded the SVG image and screenshot below.

SVG Image: 
![subscribe-test](https://github.com/dnfield/flutter_svg/assets/49031412/534ec191-4386-415c-b87f-617bb5e2397d)

sample output:
![error](https://github.com/dnfield/flutter_svg/assets/49031412/b2f986e3-77af-42b2-a671-cc99473dd241)

**Comment by dnfield** [comment]
...github won't even let me view the source of that image. But this is probably a case of #820

**Comment by sabikrahat** [comment]
yeah, #820 problems seem similar to me. Any solution or suggestion? @dnfield

**Comment by dnfield** [comment]
Closing as a duplicate. I don't know when I'll get a chance to work on that issue but I'm willing to review prs. It's unfortunately not a trivial fix.

**Comment by dnfield** [comment]
(and your svg example is mainly just a base64 encoded image, just use the image directly :)
