### ISSUE TITLE
matchTextDirection not working

### ISSUE THREAD

**Issue by araafat3** [dnfield/flutter_svg#926]
matchTextDirection not working from version 2.0.0 till version 2.0.6

**Comment by dnfield** [comment]
Yes, I think this got missed in the rewrite for VG. It should not be hard to add back but I'm not going to be able to work on it right this minute either.

**Comment by MostafaSolimanMO** [comment]
Do you have any intention to do it in the immediate future?

**Comment by dnfield** [comment]
Sorry, I keep losing track of this. IT's not hard to add back I just need to find time to do it. You basically would copy the old code from flutter_svg that did this to vector_graphics

**Comment by dnfield** [comment]
Fixed in v2.0.7
