### ISSUE TITLE
flutter_svg losing quality when I set color

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [dnfield/flutter_svg#928]
flutter_svg is losing quality when I want to set a color!

this is an example:
SvgPicture.asset(
 assets/images/no_notifications.svg,
 colorFilter: ColorFilter.mode(
 Colors.white,
 BlendMode.srcIn,
 ),
),

flutter_svg: 2.0.6,
Flutter 3.10.2 
Tools • Dart 3.0.2 • DevTools 2.23.1

**Comment by dnfield** [comment]
Dupe of #927
