### ISSUE TITLE
Rendering issues on Impeller depending on svg width

### ISSUE THREAD

**Issue by chrisgblr** [dnfield/flutter_svg#938]
I have rendering issues with Impeller.
Depending on the width of the svg and the screen size, sometimes the rendering breaks.

Widget setup:
```
Stack(
    fit: StackFit.expand,
    children: [
      SvgPicture.asset(
        'assets/shapes/grey.svg',
        fit: BoxFit.fitWidth,
        alignment: Alignment.topCenter,
      ),
      Container(color: Colors.red.withOpacity(.5)),
    ],
)
```

On my iPhone SE I get the following result:
Working svg:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 100">
    <rect fill="#000000" width="200" height="100"/>
</svg>
```

<img width="300" alt="Screenshot 2023-06-09 at 13 12 15" src="https://github.com/dnfield/flutter_svg/assets/6814605/0daa1eb4-3b6a-45f6-a9da-a346ce578aa4">

Svg with changed width resulting in rendering issues. The content outside of the svg isn't rendered anymore:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 375 200">
    <rect fill="#000000" width="375" height="200"/>
</svg>
```

<img width="300" alt="Screenshot 2023-06-09 at 13 13 07" src="https://github.com/dnfield/flutter_svg/assets/6814605/483da4a7-ddde-40fc-95df-d82f4d39cb7a">

**Comment by amankr** [comment]
I am also facing similar issue on impeller.   I am using following svg.

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 12L20 12M4 12L10 6M4 12L10 18" stroke="black" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

```

My Widget Setup 
```
Scaffold(
  body: Column(
   crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Container(
        color: Colors.amber,
        child: SvgPicture.asset(
          "assets/arrow_left.svg",
          // height: 25,
        ),
      ),
      Text(
        "Hello",
        style: TextStyle(fontSize: 36),
      ),
    ],
  ));
```

In above setup, The Text **"Hello"** is not visisble.
However, The text **"Hello"**,  appears back for any of the following case
- removing `crossAxisAlignment` of column
- using svg size bigger than what is defined in `<svg>` element. 

![sim-resize](https://github.com/dnfield/flutter_svg/assets/2175623/7f9b808a-3107-4a94-927d-3354f46ceb54)

**Comment by dnfield** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/130084
