### ISSUE TITLE
add possibility to render SVG to PNG in dart vm or AOT i.e. for use in backend

### ISSUE THREAD

**Issue by insinfo** [dnfield/flutter_svg#941]
add possibility to render SVG to PNG in dart vm or AOT i.e. for use in backend

**Comment by dnfield** [comment]
This is not really a suitable feature require for this repo. 

If you want to use dart:ui in a CLI based app, you can sort of make it work via `flutter test`. If that's not good enough, you can try to find or open a feature request in the flutter/flutter repo, although I don't think this would be very high priority for the team at this point. 

There are probably better options for rendering SVG to images in a backend, e.g. using headless Chrome or resvg.
