### ISSUE TITLE
Failed host lookup

### ISSUE THREAD

**Issue by fakhravari** [dnfield/flutter_svg#947]
use flutter_svg: ^2.0.6

SvgPicture.network(
                 'http://www.digikala.com/statics/img/svg/digi.svg',
                  width: 60,
                )

Exception has occurred.
SocketException (SocketException: Failed host lookup: 'www.digikala.com' (OS Error: No address associated with hostname, errno = 7))

**Comment by dnfield** [comment]
This is a networking issue not related to this library

**Comment by fakhravari** [comment]
Well, this link is healthy
It uses an https address to load photos, there are problems with Allow-Origin access.
How can these errors be completely released at the debug and publish level?
I use this item
  HttpOverrides.global = MyHttpOverrides();پ

**Comment by dnfield** [comment]
This is not a bug in this repo AFAICT.
