### ISSUE TITLE
Color not changing after colorFilter upgrade

### ISSUE THREAD

**Issue by roxana1506** [dnfield/flutter_svg#954]
I used the asset method for changing the color exactly like it says in the docs but nothing is working. The svg's color does not overwrite, it only displays the 'fill' color from its code, if it is not present it'll display black and if its value is 'null' it will not display at all. Neither the color nor the colorFilter property works anymore. Tried on many svgs.

Tried from version 2.0.0 to 2.0.7 (present)

**Comment by gabrielokura** [comment]
Try `const ColorFilter.mode(Colors.red, BlendMode.srcIn),` or `ColorFilter.mode(
                  Colors.red, BlendMode.dstIn),`

**Comment by dnfield** [comment]
This bug is not actionable as-is. Please file a complete and small reproduction (e.g. using `SvgPicture.string`) and I'd be happy to take a look/reopen.
