### ISSUE TITLE
Migration question to 2.x.x

### ISSUE THREAD

**Issue by samleecampspot** [dnfield/flutter_svg#969]
I was wondering if anyone has any ideas on the equivalent for this code?

```
final drawable = svg.definitions.getDrawable('url(#${someId})', nullOk: true) as DrawableShape?;
```

the `svg` variable was a `DrawableRoot`.

I need to draw on top of certain components on the SVG image, but not sure how to do the same with DrawableRoot being removed.  Any help is appreciated!

**Comment by dnfield** [comment]
That's not possible anymore. It'd probably be possible to make the compiler do something like this, but that API is gone because supporting it makes things really hard to optimize.
