### ISSUE TITLE
SVG load slowly

### ISSUE THREAD

**Issue by Guo2299** [dnfield/flutter_svg#977]
version：flutter_svg: ^2.0.7

When I use SvgPicture.asset to load a local svg image, it will be displayed after a delay of 2 to 3 seconds. How should I solve it? I need help

**Comment by jayce888** [comment]
What should I do? The project will be launched tomorrow, /(ㄒoㄒ)/~~

**Comment by dnfield** [comment]
Please provide a reproduction of this.
