### ISSUE TITLE
Invalid Binary - The following binaries in your app contains prohibited instructions

### ISSUE THREAD

**Issue by j-q-in-berlin** [dnfield/flutter_svg#981]
When I added flutter_svg to my project I got this error from App Store Connect:

```
We identified one or more issues with a recent delivery for your app, "xxxxxxxx" 1.0.0 (4). Please correct the following issues, then upload again. 
ITMS-90755: Invalid Binary - The following binaries in your app contains prohibited instructions: Runner.app/Frameworks/App.framework/App. Remove the instructions from the binaries, rebuild and resubmit. 

```

If I remove the flutter_svg library, this error goes away. 

Any ideas on how to fix this? 
Thanks in advance! :)

**Comment by dnfield** [comment]
This wouldn't be a flutter_svg bug. 

Try updating Xcode and make sure you are not submitting a debug version of your application to the store - trying to do that could cause this error.

**Comment by j-q-in-berlin** [comment]
This is not the case. We tried updating Xcode and we are not submitting a debug version. 
We tried multiple builds using the same version of Xcode and the same build settings and the only thing that works is removing the flutter_svg package. Also on our CI/CD pipeline we get the same result.

**Comment by dnfield** [comment]
If you figure out a reproducible way to make this happen please file a flutter bug for it. Or if you ever get a more detailed message about what illegal instruction is being used.
