### ISSUE TITLE
Issues with transparency when export SVG from Figma

### ISSUE THREAD

**Issue by akadatsky** [dnfield/flutter_svg#988]
I have a set of images in Figma editor, which I use in mobile app, but some icons have wrong color - some transparency on mobile device.
For example, I have a heart icon from Figma:
```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <mask id="mask0_1211_10005" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="1" y="1" width="22" height="22">
    <path d="M12 23C7.97916 19.3202 1 13.2392 1 7.16C1 3.7104 3.662 1 7.05 1C8.964 1 10.8016 1.99331 12.0006 3.42691C13.1996 1.99331 15.036 1 16.95 1C20.338 1 23 3.7104 23 7.16C23 13.229 16.0299 19.3401 12 23Z" fill="#00A1F1"/>
  </mask>
  <g mask="url(#mask0_1211_10005)">
    <path d="M12 22C7.97916 18.3202 1 13.2392 1 7.16C1 3.7104 3.662 1 7.05 1C8.964 1 10.8016 1.99331 12.0006 3.42691C13.1996 1.99331 15.036 1 16.95 1C20.338 1 23 3.7104 23 7.16C23 13.229 16.0299 18.3401 12 22Z" fill="#FFCC00"/>
    <path d="M8 13C1.5 13 -0.166667 6.66667 -0.5 3.5L2 -7L27 -9.5C28.1667 -4 29.8 7.5 27 7.5C19.5 7.5 16 13 8 13Z" fill="url(#paint0_linear_1211_10005)"/>
  </g>
  <defs>
    <linearGradient id="paint0_linear_1211_10005" x1="24.342" y1="9.89145" x2="8.86262" y2="-10.0914" gradientUnits="userSpaceOnUse">
      <stop stop-color="#008CEC"/>
      <stop offset="1" stop-color="#00B0F3"/>
    </linearGradient>
  </defs>
</svg>
```

In svgviewer and Figma it looks ok:
<img width="310" alt="Screenshot 2023-09-20 at 09 45 37" src="https://github.com/dnfield/flutter_svg/assets/2796990/8266a1e1-cf4a-410a-bc44-c381f57af23a">

But in mobile device it looks wrong:

```
      Container(
        color: Colors.white,
        child: Center(
          child: SvgPicture.asset(
            'images/heart.svg',
            width: 100,
            height: 100,
          ),
        ),
      ),
```
<img width="268" alt="Screenshot 2023-09-20 at 09 50 45" src="https://github.com/dnfield/flutter_svg/assets/2796990/cc76f8d2-eca2-48f5-b2f3-2e1632ed5068">

Any suggestions why it happens and how to fix it?

**Comment by hieplee2997** [comment]
There seems to be a syntax error in the svg file when exporting from figma. In figma, the <defs> tag can be at the end of the file, but with this library the <defs> tag must be placed first. You can edit the content of the svg file by placing the <defs> tag at the top of the file, right below the <svg> tag.

**Comment by akadatsky** [comment]
@hieplee2997 which tag? defs?
I believe there is no syntax error in the SVG file cause other SVG viewers show it ok. 
I tried put the defs tag first, but it does not help.

**Comment by vaifathuy** [comment]
I also experienced the same issue. My icon does not look white.
<img width="108" alt="Screenshot 2023-09-25 at 12 48 48 AM" src="https://github.com/dnfield/flutter_svg/assets/39383537/4de419f7-1d86-4812-a987-f00306574ec7">

**Comment by vaifathuy** [comment]
I also experienced the same issue. My icon does not look white.
Look at these two forward-arrow-head icons below.

<img width="120" alt="Screenshot 2023-09-25 at 12 55 36 AM" src="https://github.com/dnfield/flutter_svg/assets/39383537/445a6f3a-4085-4ecc-87ac-8acbaec1672d">

**Comment by akadatsky** [comment]
@vaifathuy could you provide SVG code?

**Comment by vaifathuy** [comment]
> @vaifathuy could you provide SVG code?

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_6807_17039" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24">
<rect width="24" height="24" fill="#004FEC"/>
</mask>
<g mask="url(#mask0_6807_17039)">
<path d="M9.3464 18.2721C9.20753 18.2721 9.06866 18.2209 8.95902 18.1113C8.74706 17.8993 8.74706 17.5485 8.95902 17.3365L13.7245 12.5711C14.0753 12.2202 14.0753 11.6501 13.7245 11.2993L8.95902 6.53382C8.74706 6.32186 8.74706 5.97103 8.95902 5.75907C9.17098 5.54711 9.52181 5.54711 9.73377 5.75907L14.4993 10.5245C14.872 10.8973 15.084 11.4016 15.084 11.9352C15.084 12.4687 14.8793 12.9731 14.4993 13.3458L9.73377 18.1113C9.62414 18.2136 9.48527 18.2721 9.3464 18.2721Z" fill="#A9AAAC"/>
```
</g>
</svg>

**Comment by dnfield** [comment]
> There seems to be a syntax error in the svg file when exporting from figma. In figma, the tag can be at the end of the file, but with this library the tag must be placed first. You can edit the content of the svg file by placing the tag at the top of the file, right below the tag.

That's been fixed.

I think the problem here is `userSpaceOnUse` for the mask.

**Comment by dnfield** [comment]
Ah, no, this is https://github.com/dnfield/flutter_svg/issues/886

`mask-type:alpha` doesn't work with this library at the moment. Open to PRs if someone has a good idea to fix it :)

**Comment by sikandernoori** [comment]
@dnfield I see this issue as completed, was the fix implemented ?
