### ISSUE TITLE
Maximum call stack size exceeded with specific SVG file

### ISSUE THREAD

**Issue by katherineqian** [dnfield/flutter_svg#997]
This specific SVG file causes what appears to be an infinite looping error whenever we attempt to render it, which in some instances can even lead to the project freezing. Rendering this SVG on other websites like https://www.svgviewer.dev/ works as expected.

The console message is: `Uncaught RangeError: Maximum call stack size exceeded`

![social_facebook](https://github.com/dnfield/flutter_svg/assets/21981137/4502570a-535b-4c81-9e96-d5e084bdffce)

**Comment by dnfield** [comment]
The SVG is not valid XML since it's re-using the `id` name.

But I'm pretty sure the bad behavior here is handled by browsers by just only accepting the _first_ time an ID is set.
