### ISSUE TITLE
Invalid Double

### ISSUE THREAD

**Issue by anmol1905** [dnfield/flutter_svg#998]
Most of my SVG files contains numbers like this
                 transform="translate(9.9194053e-6,6.5505504e-4)"
                 
It gives no error on flutter_svg 1.0.0 but the latest versions throws FormatException: Invalid double error

**Comment by gorkovv** [comment]
I have the same thing:
FormatException: Invalid double
5.7957124e

**Comment by skreborn** [comment]
It looks like https://github.com/dnfield/vector_graphics/pull/208 introduced the issue, as it didn't account for numbers like `9.9194053e-6`, so it will probably have to be fixed in [`vector_graphics_compiler`](https://github.com/dnfield/vector_graphics/tree/main/packages/vector_graphics_compiler).
